### ISSUE TITLE
提一个问题吧

### ISSUE THREAD

**Issue by zxbloved** [renzifeng/ZFPlayer#1]
提一个问题吧。简单的都能使用。但是如果把Device Orientation的 Landscape left 和Landscaoe right 取消勾选。这种情况下，旋转全屏是不支持的。这个要是能优化就好了

**Comment by renzifeng** [comment]
如果工程中 Landscape left 和Landscaoe right不勾选，这个是无法旋转的。

**Comment by renzifeng** [comment]
你看一下mainViewController，里边只有视频播放这个页面是支持转屏的，其他页面只支持竖屏。工程中勾选Device Orientation的 Landscape left 和Landscaoe right也是没事的。

**Comment by renzifeng** [comment]
你看一下mainViewController，里边只有视频播放这个页面是支持转屏的，其他页面只支持竖屏。工程中勾选Device Orientation的 Landscape left 和Landscaoe right也是没事的。
