### ISSUE TITLE
竖屏资源时：资源正在加载时，点击全屏进入，资源播放时，点击返回按钮出现黑屏卡死

### ISSUE THREAD

**Issue by dbbdsz** [renzifeng/ZFPlayer#1002]
@@@@@@@@资源正在加载时，点击全屏进入，此时全屏为横向的全屏状态。等资源加载完全开始播放时，此时点击返回按钮，屏幕出现黑屏，无任何画面，且卡死 @renzifeng

**Comment by dbbdsz** [comment]
@smileAllYears @renzifeng @victorchee @BB9z

**Comment by dbbdsz** [comment]
????

**Comment by dbbdsz** [comment]
大佬 你有没遇见呢 @renzifeng

**Comment by dbbdsz** [comment]
大佬  可在 @renzifeng

**Comment by scyios** [comment]
解决了啊 我也遇到了同样的问题 @dbbdsz

**Comment by lixiongjian** [comment]
@scyios 大佬怎么解决的, 麻烦留言下, 谢谢

**Comment by ProgZXC** [comment]
怎么解决的 帮帮忙 大佬们 @lixiongjian @scyios @BB9z

**Comment by ProgZXC** [comment]
暂时改成了不加载完成 禁止手势
