### ISSUE TITLE
3.3.3版本使用会出现很多警告，求解决

### ISSUE THREAD

**Issue by hupfei** [renzifeng/ZFPlayer#1003]
ld: warning: instance method 'playingIndexPath' in category from /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o) overrides method from class in /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o)
ld: warning: instance method 'containerViewTag' in category from /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o) overrides method from class in /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o)
ld: warning: instance method 'scrollView' in category from /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o) overrides method from class in /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o)
ld: warning: instance method 'setPlayingIndexPath:' in category from /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o) overrides method from class in /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o)
ld: warning: instance method 'setContainerViewTag:' in category from /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o) overrides method from class in /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o)
ld: warning: instance method 'setScrollView:' in category from /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o) overrides method from class in /Users/xxx/Library/Developer/Xcode/DerivedData/YYeTs-hgagjpolswpaefgxdlyvbxlblyoy/Build/Products/Debug-iphoneos/ZFPlayer/libZFPlayer.a(ZFPlayerController.o)

**Comment by laurivers** [comment]
+1

**Comment by GeekLee609** [comment]
尝试在pod引入库的时候忽略警告，即
pod 'ZFPlayer', '~> 1.0.2',:inhibit_warnings => true

**Comment by hupfei** [comment]
> 尝试在pod引入库的时候忽略警告，即
> pod 'ZFPlayer', '~> 1.0.2',:inhibit_warnings => true

早试过，无用

**Comment by GeekLee609** [comment]
> > 尝试在pod引入库的时候忽略警告，即
> > pod 'ZFPlayer', '~> 1.0.2',:inhibit_warnings => true
> 
> 早试过，无用

好的，我看看

**Comment by GeekLee609** [comment]
> > 尝试在pod引入库的时候忽略警告，即
> > pod 'ZFPlayer', '~> 1.0.2',:inhibit_warnings => true
> 
> 早试过，无用

下个版本解决

**Comment by Jayxiang** [comment]
导入 ijk 会有这个警告：warning: /Users/growingio/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/DAJUKX4ZWJGL/Foundation-3DFYNEBRQSXST.pcm: No such file or directory    而且 growingio 还不是本地用户
