### ISSUE TITLE
3.3.2和3.3.3打包出现Undefined symbols for architecture armv7错误

### ISSUE THREAD

**Issue by Homin818** [renzifeng/ZFPlayer#1006]
Undefined symbols for architecture armv7:
  "_ff_isom_write_avcc", referenced from:
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_avcodec_decode_video2", referenced from:
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_copy_packet", referenced from:
      _videotoolbox_async_decode_frame in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _videotoolbox_sync_decode_frame in IJKMediaFramework(IJKVideoToolBoxSync.o)
  "_av_fifo_drain", referenced from:
      _async_read_internal in IJKMediaFramework(ijkasync.o)
  "_av_application_on_async_statistic", referenced from:
      _call_inject_statistic in IJKMediaFramework(ijkasync.o)
  "_av_fifo_reset", referenced from:
      _async_buffer_task in IJKMediaFramework(ijkasync.o)
  "_ffurl_open_whitelist", referenced from:
      _async_open in IJKMediaFramework(ijkasync.o)
      _ijkurlhook_reconnect in IJKMediaFramework(ijkurlhook.o)
      _ijklongurl_open in IJKMediaFramework(ijklongurl.o)
      _ijksegment_open in IJKMediaFramework(ijksegment.o)
      _ijkio_ffio_open in IJKMediaFramework(ijkioffio.o)

**Comment by demoker** [comment]
@renzifeng  希望博主还是可以发布一个支持armv7指令集的ijkFramework，就苹果设备的退休率，目前还是有好多人在使用旧设备

**Comment by GeekLee609** [comment]
> @renzifeng 希望博主还是可以发布一个支持armv7指令集的ijkFramework，就苹果设备的退休率，目前还是有好多人在使用旧设备

已经修复了，请下载更新0.1.5版本的IJKFramework

**Comment by 11101b** [comment]
请问是怎么解决的，我自己编译的ijk也碰到这个问题
