### ISSUE TITLE
我升级到3.3.3报这个错误___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by mingtiandemeng** [renzifeng/ZFPlayer#1009]
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _read_key in IJKMediaFramework(ffmpeg.o)
      _RAND_poll in IJKMediaFramework(rand_unix.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by GeekLee609** [comment]
这个不属于ZFPlayer的问题，可能与Xcode版本有关系，参考[https://github.com/curl/curl/issues/5210](url)
