### ISSUE TITLE
pod最新版本的播放有问题

### ISSUE THREAD

**Issue by tyleroub** [renzifeng/ZFPlayer#1014]
1.pod ZFPlayer获取最新版本后，设置播放完一个视频后stop，等视频播放完自己停止后，再次点击播放，进度条直接就跑到结束的位置了，导致不能再次播放
2.无论新旧版本都存在一个问题，视频加载未完成，即播放器等待指示器正在转，还没有开始播放的时候，push或者present一个ViewController，然后能听见视频播放的声音，相当元上个页面的视频没有暂停

**Comment by GeekLee609** [comment]
1、尝试过视频播放完后之后调用 stop ，并未复现该问题，即
 self.player.playerDidToEnd = ^(id  _Nonnull asset) {
        @strongify(self)
        [self.player stop];
  };，你那边是怎么调用 stop 的

2、当前加载视频的控制器其生命周期方法中是否调用了
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    self.player.viewControllerDisappear = NO;
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    self.player.viewControllerDisappear = YES;
}

**Comment by tyleroub** [comment]
问题2.手速要快，普通样式，点击开始播放，几乎同时再点击右上角的push，进入下个页面，能听到视频播放的声音，willAppear和willDisappear里对应设置了NO和YES
问题1.我这里百分百复现，修改原demo的podfile以下内容
target 'ZFPlayer_Example' do
    pod 'FDFullscreenPopGesture'
    pod 'MJRefresh'
    pod 'ZFPlayer'
    pod 'ZFPlayer/Core'
    pod 'ZFPlayer/ControlView'
    pod 'ZFPlayer/AVPlayer'
#    pod 'ZFPlayer/ijkplayer'
    pod 'ZFPlayer/KSYMediaPlayer'
end
然后pod update
屏蔽ijkplayer的相关import
跑起来进入普通样式，拖动进度条到快结束，结束后播放停止，然后点击重新播放，肯定复现

**Comment by heliang219** [comment]
同上 我也遇到了你说的这个bug 我把demo中的普通样式的代码控制器放入自己的项目中 运行就出现了播放完再次点击播放进度条直接就跑到结束的位置，导致不能再次播放这个bug

**Comment by lovederh** [comment]
我遇到调用[self.player shutdown]; 
[self.player stop];
都不起作用。
