### ISSUE TITLE
关于- (void)seekToTime:(NSTimeInterval)time completionHandler:(void (^ __nullable)(BOOL finished))completionHandler;方法的回调问题

### ISSUE THREAD

**Issue by chenghaoweilai** [renzifeng/ZFPlayer#1015]
有些时候- (void)seekToTime:(NSTimeInterval)time completionHandler:(void (^ __nullable)(BOOL finished))completionHandler;这个方法的回调没有被触发  用的xcode11  sdk 3.3.3

**Comment by GeekLee609** [comment]
哪种情况下会出现？demo上的视频么

**Comment by GeekLee609** [comment]
@chenghaoweilai

**Comment by kklwg** [comment]
我也是这样。 不走回调。

 @weakify(self)
        [self.videoPlayer.player seekToTime:[currentTime integerValue] completionHandler:^(BOOL finished) {
            @strongify(self)
            if(finished){
                [HudUtil showSuccess:@"回到上次播放的位置" toView:self.videoPlayer.view]; //不回调到这里？
            }
        }];

**Comment by kklwg** [comment]
- (void)seekToTime:(NSTimeInterval)time completionHandler:(void (^ __nullable)(BOOL finished))completionHandler {
    if (self.totalTime > 0) {
        [_player.currentItem cancelPendingSeeks];
        int32_t timeScale = _player.currentItem.asset.duration. timescale;
        CMTime seekTime = CMTimeMakeWithSeconds(time, timeScale);
        [_player seekToTime:seekTime toleranceBefore:kCMTimeZero toleranceAfter:kCMTimeZero completionHandler:completionHandler];
    } else {
        self.seekTime = time;
    }
}
走的是else里面的方法。 self.totalTime = 0;

然后再通过KVO
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSKeyValueChangeKey,id> *)change context:(void *)context {

}

 if (self.seekTime) {
                    if (self.shouldAutoPlay) [self.player pause];
                    @zf_weakify(self)
                    [self seekToTime:self.seekTime completionHandler:^(BOOL finished) {
                        @zf_strongify(self)
                        if (finished) {
                            if (self.shouldAutoPlay) [self play];
                        }
                    }];
                    self.seekTime = 0;
}
这样就没有回调了。
