### ISSUE TITLE
页面卡死

### ISSUE THREAD

**Issue by CherishSmile** [renzifeng/ZFPlayer#1016]
当视频正在加载的过程中，切换到另一个视频，或者页面销毁，都会导致应用卡死

**Comment by Jvaeyhcd** [comment]
同样存在相同的问题

**Comment by GeekLee609** [comment]
怎么复现出这个问题？本地尝试过，没有复现这个问题呢 @Jvaeyhcd @CherishSmile

**Comment by CherishSmile** [comment]
也不是每次都复现，偶尔有时会直接卡死，点什么都不起作用。只能杀掉重进。

**Comment by GeekLee609** [comment]
> 也不是每次都复现，偶尔有时会直接卡死，点什么都不起作用。只能杀掉重进。

用的是 ZFAVPlayerManager 这个么？

**Comment by CherishSmile** [comment]
是的

**Comment by GeekLee609** [comment]
> 是的

好的，下个版本尝试优化一下这个点，到时候再观察一下

**Comment by kwzcoder** [comment]
> 当视频正在加载的过程中，切换到另一个视频，或者页面销毁，都会导致应用卡死

同样出现了这个问题,  麻烦问下当时怎么解决的
