### ISSUE TITLE
iOS12下开启控制器旋转就会奔溃

### ISSUE THREAD

**Issue by xiangchangming** [renzifeng/ZFPlayer#1017]
- (void)setFullScreen:(BOOL)fullScreen {
    _fullScreen = fullScreen;
    [[UIWindow zf_currentViewController] setNeedsStatusBarAppearanceUpdate];
    [UIViewController attemptRotationToDeviceOrientation];
}

error：Thread 1: Exception: "Supported orientations has no common orientation with the application, and [UINavigationController shouldAutorotate] is returning YES"

**Comment by GeekLee609** [comment]
> * (void)setFullScreen:(BOOL)fullScreen {
>   _fullScreen = fullScreen;
>   [[UIWindow zf_currentViewController] setNeedsStatusBarAppearanceUpdate];
>   [UIViewController attemptRotationToDeviceOrientation];
>   }
> 
> error：Thread 1: Exception: "Supported orientations has no common orientation with the application, and [UINavigationController shouldAutorotate] is returning YES"

你的应用支持横屏了么？

**Comment by xiangchangming** [comment]
支持横屏了，而且我用的是你们的demo源码发现也会奔溃

**Comment by GeekLee609** [comment]
> 支持横屏了，而且我用的是你们的demo源码发现也会奔溃

能说下具体是在demo中的哪个场景下？复现路径麻烦说一下，我看看

**Comment by xiangchangming** [comment]
iOS12系统下，键盘旋转还有旋转类型里面开启控制器旋转后，旋转手机就会奔溃

**Comment by objectZhang** [comment]
我找到这个问题了，问题在于获取 UIWindow 的时候，在ios13以下，会创建一个新的 UIWindow，
`- (UIWindow *)customWindow {
    if (!_customWindow) {
        if (@available(iOS 13.0, *)) {
            UIWindowScene *windowScene = nil;
            for (UIScene *scene in [UIApplication sharedApplication].connectedScenes) {
                if (scene.activationState == UISceneActivationStateForegroundActive) {
                    windowScene = (UIWindowScene *)scene;
                }
                if (!windowScene && [UIApplication sharedApplication].connectedScenes.count == 1) {
                    windowScene = (UIWindowScene *)scene;
                }
            }
            if (windowScene) {
                _customWindow = [[UIWindow alloc] initWithWindowScene:windowScene];
            } else {
                _customWindow = [[UIWindow alloc] initWithFrame:CGRectZero];
            }
        } else {
            _customWindow = [[UIWindow alloc] initWithFrame:CGRectZero];
        }
    }
    return _customWindow;
}`

**Comment by huangxianyu** [comment]
![image](https://user-images.githubusercontent.com/20720740/87842455-30c99180-c8df-11ea-9151-cd770a2b0740.png)
这个默认值导致的, 直接把YES改为NO.

**Comment by xiangchangming** [comment]
这样的话当你拿手机的方向不是垂直的时候 点击全屏还是奔溃

**Comment by xiangchangming** [comment]
- (void)setFullScreen:(BOOL)fullScreen {
    _fullScreen = fullScreen;
    [[UIWindow zf_currentViewController] setNeedsStatusBarAppearanceUpdate];
断点指向这里
    [UIViewController attemptRotationToDeviceOrientation];
}

**Comment by xiangchangming** [comment]
前提是开启控制器旋转

**Comment by githubhuxian** [comment]
> 我遇到了一个相似的问题，如果视频是竖向的，那么在iOS12和iOS13下都可以进行全屏播放。
> 唯独横向视频，在iOS12的设备上全屏就会出错。
> 最后通过增加以下代码才解决：
> AppDelegate：
> var allowOrentitaionRotation: Bool = false
> func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
> if self.allowOrentitaionRotation {
> return UIInterfaceOrientationMask.allButUpsideDown
> }
> return UIInterfaceOrientationMask.portrait
> }
> 
> 播放视频界面：
> player.orientationWillChange = { (player: ZFPlayerController, isFullScreen: Bool) -> Void in
> let delegate = UIApplication.shared.delegate as! AppDelegate
> delegate.allowOrentitaionRotation = isFullScreen
> self.setNeedsStatusBarAppearanceUpdate()
> }

这个方法可行，亲测。
我也是遇到了点击全屏就闪退的问题。
