### ISSUE TITLE
在没有URL可以加载的时候，ZFPlayerControlView不会正常显示

### ISSUE THREAD

**Issue by HongWeiChen** [renzifeng/ZFPlayer#1018]
RT

假设没有URL的情况下，ZFPlayerController不会正常显示ZFPlayerControlView，无法退出。

查看了具体代码是在 **setCurrentPlayerManager:(id<ZFPlayerMediaPlayback>)currentPlayerManager** 中有个 **_currentPlayerManager.view.hidden = YES** 的问题导致ZFPlayerControlView不会显示。

**Comment by GeekLee609** [comment]
> ZFPlayerControlView

如果视频的URL为空的话，的确不会显示 ZFPlayerControlView，逻辑上没有问题

**Comment by HongWeiChen** [comment]
@GeekLee609 感觉应该可以改成hidden默认不隐藏，但是可以提供一个属性变量用于控制是否在URL为空时候不显示，因为有时候会直接使用ZFPlayerController作为页面的显示，然后在上面进行操作（例如添加自己的按钮），返回键使用的也是ZFPlayerControlView上的，如果ZFPlayerControlView直接不显示会连退出都没有

**Comment by JianWenXie** [comment]
这个问题最后怎么解决的？我也遇到同样相关问题
