### ISSUE TITLE
竖屏资源时：资源正在加载时，点击全屏进入，资源播放时，点击返回按钮出现黑屏卡死

### ISSUE THREAD

**Issue by dbbdsz** [renzifeng/ZFPlayer#1020]
竖屏资源播放，资源正在加载时（无画面），点击全屏进入，此时全屏为横向的全屏状态。等资源加载完全开始播放时（画质出现），此时点击返回按钮，屏幕出现黑屏，无任何画面，且卡死 @ 
![2080ACE8A7A7773F0C4541ACEF67A757](https://user-images.githubusercontent.com/15864085/87640437-4e7ce680-c779-11ea-86c9-6ff31fb7fc3a.jpg)
![E0FB3A299AAF6EE34F73ED8B58475B35](https://user-images.githubusercontent.com/15864085/87640452-52a90400-c779-11ea-8298-b45bcd73b1fe.png)
    @@@@![2F9C6379FC0946B5146332F250DE0441](https://user-images.githubusercontent.com/15864085/87640458-53da3100-c779-11ea-8606-aef2299b161c.png)

**Comment by dbbdsz** [comment]
*** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [ZFFullViewController shouldAutorotate] is returning YES'

**Comment by GeekLee609** [comment]
> ZFFullViewController

你用的是哪个版本的？ZFFullViewController 最新版中没有

**Comment by dbbdsz** [comment]
最新的   s.version          = '3.3.4'  ，http://104.233.240.207:57899/testdata/392B3B579529F84F/111A617AFD872E3D//480p/480p.m3u8
这个是竖版资源，可测试下

**Comment by dbbdsz** [comment]
@GeekLee609

**Comment by f2yu** [comment]
我也遇到了这个问题，横屏时层级变成了这样
<img width="473" alt="截屏2021-03-09 下午12 01 45" src="https://user-images.githubusercontent.com/10491688/110416804-49392700-80cf-11eb-84be-7107ae41aa82.png">

**Comment by myOneGit** [comment]
解决了吗
