### ISSUE TITLE
ijk播放问题

### ISSUE THREAD

**Issue by daoxingwudao** [renzifeng/ZFPlayer#1021]
ijk播放有些视频。会出现画面旋转90度的情况

**Comment by GeekLee609** [comment]
你用的ijk是哪个版本的？另外ZFPlayer只是将ijk打包成了framework进行引用依赖，因此对于ijk内部的处理只能做一些力所能及的事

**Comment by daoxingwudao** [comment]
pod 'IJKMediaFramework','0.1.3'

**Comment by GeekLee609** [comment]
> pod 'IJKMediaFramework','0.1.3'

最新的 0.1.5 试试看

**Comment by daoxingwudao** [comment]
应该是ijk的问题 简书 https://www.jianshu.com/p/72c257d09efd

**Comment by daoxingwudao** [comment]
最新的 0.1.5  视频还是会会出现画面旋转90度的情况

**Comment by GoKnow** [comment]
@daoxingwudao 问题解决了吗

**Comment by zht415** [comment]
> https://www.jianshu.com/p/72c257d09efd



> 最新的 0.1.5 视频还是会会出现画面旋转90度的情况

请问最后如何解决的？
