### ISSUE TITLE
升级到4.0后 项目中出现了很多bug 怎么解决

### ISSUE THREAD

**Issue by heliang219** [renzifeng/ZFPlayer#1035]
用3.3.3都没出现这些奇怪的bug，升级到4.0后出现好多bug，怎么解决，大侠你这样改动让我基于正常的项目升级后都用不了啊，你咋不兼容下老版本啊。
例如：
1.第一次小窗出现的时候 不是小窗 而是和cell一样大 第二次就没事了。
2.进入详情页旋转全屏 能把我在cell里旋转的视频播放出来。

**Comment by heliang219** [comment]
3.ZFIJKPlayerManager播放完后执行replay会无限加载 重新播放不了
![b57be9ff-0482-45f7-876d-5c96bae1dc5f](https://user-images.githubusercontent.com/795426/89383853-ce222380-d72f-11ea-84ca-fd6ffceb06fb.jpg)

**Comment by heliang219** [comment]
我说的第二个bug问题大侠貌似你解决了 但是没有更新podspec

**Comment by renzifeng** [comment]
第一个问题是怎么回事？

**Comment by heliang219** [comment]
&nbsp;发个操作视频 给大神看下哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "renzifeng/ZFPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 上午9:26
收件人:&nbsp;"renzifeng/ZFPlayer"<ZFPlayer@noreply.github.com&gt;;
抄送:&nbsp;"天地缘龙"<heliang219@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [renzifeng/ZFPlayer] 升级到4.0后 项目中出现了很多bug 怎么解决 (#1035)





 
第一个问题是怎么回事？

**Comment by heliang219** [comment]
邮件不知道大侠你收到没 我在这发个 视频在压缩包里
[6857679638077800448.MP4.zip](https://github.com/renzifeng/ZFPlayer/files/5032099/6857679638077800448.MP4.zip)

**Comment by renzifeng** [comment]
4.x的改动确实有点大，4.x初期版本可能会有一些bug，我会尽快修复到稳定，要是想稳定版，可以先用3.3.3。

你说的第一条我试了，么有复现出来，具体你对照demo的代码，看看有什么不同吗

**Comment by heliang219** [comment]
4.0.1 我更新了后 播放到最后怎么就黑的一闪 黑屏了 之前都没这个问题啊

**Comment by renzifeng** [comment]
这个你得详细描述一下复现步骤，或者提供demo，我好定位问题

**Comment by heliang219** [comment]
大侠 你还是还原成之前的 在 IJKMPMovieFinishReasonPlaybackEnded之后加上
 [self.timer invalidate];
            self.timer = nil;这两句 我的第三个bug我在外部修算了

**Comment by renzifeng** [comment]
本来那就是写错了，我肯定要改的。你要是想自己维护就fork一份自己维护吧

**Comment by heliang219** [comment]
好吧 谢谢了

**Comment by Jayxiang** [comment]
关于第三个我这会崩溃到 moviePlayBackStateDidChange
