### ISSUE TITLE
替换了项目中的ZFDouYinControlView  无法滑动了  该怎么排查下？

### ISSUE THREAD

**Issue by liubang0909** [renzifeng/ZFPlayer#1036]

**Comment by liubang0909** [comment]
用的最新版本里面的 ZFDouYinControlView  看迁移说明貌似是解决了闪烁问题。。  替换了之后  发现无法滑动了

**Comment by liubang0909** [comment]
闪烁的原因能说下？

**Comment by liubang0909** [comment]
很神奇 demo里面的 ZFDouYinControlView  没有实现 - (BOOL)gestureTriggerCondition:(ZFPlayerGestureControl *)gestureControl
                    gestureType:(ZFPlayerGestureType)gestureType
              gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer
                          touch:(UITouch *)touch   这个方法  手势竟然也响应

**Comment by liubang0909** [comment]
[self.player.currentPlayerManager.view.coverImageView setImageWithURLString:coverUrl placeholder:placeholder]; 按照这个写了 移除了以前添加的view  还是会闪一下

**Comment by renzifeng** [comment]
不能滑动我猜是手势冲突了，闪一下问题应该解决了呢 你那还是闪可能coverUrl有问题吧？

**Comment by liubang0909** [comment]
用的demo里面json文件。。 coverUrl有问题的话从哪看？ 闪了一下的黑色的是哪一块啊大神

**Comment by liubang0909** [comment]
以前的话  是先展示一张cover图   播放的时候  移除掉。。  现在是啥原理啊。。

**Comment by liubang0909** [comment]
我看demo里面是不闪烁的。。 到底是哪块没设置啊。。怎么调试这个  头疼

**Comment by renzifeng** [comment]
现在是在playerView中默认加了个CoverImageView，会设置播放器未初始化之前会显示这个，我猜测你说的黑色问题，是你playerManager中设置playerView背景颜色为黑色了吧？

**Comment by liubang0909** [comment]
<img width="815" alt="截屏2020-08-06 下午4 11 01" src="https://user-images.githubusercontent.com/12213692/89507684-6e934900-d7ff-11ea-9c18-e4b419c88e2d.png">
大哥。。还真是这个问题。。定义的ZFPlayerPresentView继承了ZFPlayerView下。。又看了下demo 继承的是uiview  谢谢大神指点 🙏

**Comment by zhuozhuo** [comment]
@renzifeng @liubang0909 您好，抖音界面里面的横屏后不能滑动的问题解决了么？
