### ISSUE TITLE
可以增加倍速播放吗

### ISSUE THREAD

**Issue by Joejin-0222** [renzifeng/ZFPlayer#1037]

**Comment by renzifeng** [comment]
倍速播放是一直有的功能 `player.currentPlayerManager.rate`

**Comment by Joejin-0222** [comment]
非常感谢回复
看到这个了，但是没有UI，自己添加了一个 但是不是很好用。




在2020年08月06日 14:38，紫枫 写道：

倍速播放是一直有的功能 player.currentPlayerManager.rate
