### ISSUE TITLE
播放器页面播放视频，退出播放页面到B页面，然后切到后台，等一段时间之后打开app，视频在B页面播放了

### ISSUE THREAD

**Issue by npzlxph0415** [renzifeng/ZFPlayer#1038]

**Comment by renzifeng** [comment]
一定要设置self.player.viewControllerDisappear

**Comment by npzlxph0415** [comment]
你的ZFNormalViewController就有这个问题，你在ZFNormalViewController点击右上角push然后退到后台，再返回视频就是在播放

**Comment by Lucifer0103** [comment]
同问, 怎么解决?

**Comment by npzlxph0415** [comment]
> 同问, 怎么解决?
我改了两个地方 ZFPlayerController.m 里面前台退后后台的时候self.currentPlayerManager.shouldAutoPlay = NO;，然后后台回前台时不自动播放self.pauseByEvent = YES; 暂时这么处理的

**Comment by zhangxiongwen** [comment]
已发现问题原因所在：https://github.com/renzifeng/ZFPlayer/issues/1083
