### ISSUE TITLE
播放结束后向后滑动，“重播”按钮不会消失，(楼主的Demo)

### ISSUE THREAD

**Issue by mrhyh** [renzifeng/ZFPlayer#104]
视频会继续播放，但是“重播”按钮不会消失。原因是：视频播放结束后，向后滑动(后退)时，项目仍然会调用以下方法，但是只会调用一次.
/** 播放完了 */
- (void)zf_playerPlayEnd
{
    self.backgroundColor  = RGBA(0, 0, 0, .6);
    self.repeatBtn.hidden = NO;
    // 延迟隐藏controlView
    [self hideControlView];
}

我追溯了这个方法，是通过通知执行的，但是我却没有找到发布通知的地方，望楼主查看解答以下,先谢谢了。

**Comment by renzifeng** [comment]
谢谢，你提的bug我已经修复啦
