### ISSUE TITLE
自定义播放控制层添加UISlider不能滑动，我用demo的自定义控制层可以

### ISSUE THREAD

**Issue by D-james** [renzifeng/ZFPlayer#1040]
版本3.3.3，iOS 13，自定义播放控制层添加UISlider不能滑动，我用demo的自定义控制层slider可以滑动，不知道我哪里姿势不对

**Comment by renzifeng** [comment]
你要参考 `shouldResponseGestureWithPoint:withGestureType:touch:`的代码
