### ISSUE TITLE
4.0版本的ZFNormalViewController在iPhone11上点击全屏播放，然后退到后台，再切回APP 导航栏上移错位

### ISSUE THREAD

**Issue by HZYDZT** [renzifeng/ZFPlayer#1041]

**Comment by HZYDZT** [comment]
..

**Comment by HYZ666** [comment]
我也发现了你说的问题，真实感觉非常苦恼！

**Comment by renzifeng** [comment]
这个问题很早就出现了，还没解决方案

**Comment by HZYDZT** [comment]
> 这个问题很早就出现了，还没解决方案

没有其他的解决方案吗

**Comment by HYZ666** [comment]
横屏退到后台，再次进入前台，当前控制器的安全区与发生了变化，是否先改成进入后台后，将当前的页面退出全屏，这样就不会出现上移的问题了，我感觉退出全屏的解决方式比当前导航栏上移的问题好一些。

**Comment by DkSuperMan** [comment]
我也遇到了

**Comment by dagundejuzi** [comment]
用内嵌webView播放视频也是同样的问题，但是......版本3.3.2中，设置forceDeviceOrientation=YES，就不会有这个问题。 @renzifeng

**Comment by f2yu** [comment]
> 横屏退到后台，再次进入前台，当前控制器的安全区与发生了变化，是否先改成进入后台后，将当前的页面退出全屏，这样就不会出现上移的问题了，我感觉退出全屏的解决方式比当前导航栏上移的问题好一些。

这样改了的话，反复试几次，切换到全屏会黑屏并且什么都点不了，通过方向感应切到竖屏的话，显示正常，但是无法响应手势，估计zf里面操作window这块逻辑有点问题

**Comment by bidm** [comment]
遇到了

**Comment by NSDeveloper** [comment]
我也遇到了 左滑返回后tableView上的cell都向右偏移了
