### ISSUE TITLE
播放过程中 调用系统相机如何保持播放器的声音？ 以及关闭系统相机后，播放器的声音没有了 只有画面

### ISSUE THREAD

**Issue by Elbays-Zhang** [renzifeng/ZFPlayer#1046]
作者您好，有两个问题希望可以得到解答。
1、请问在播放过程中 ，如果我打开相机，如何能够让播放器的声音一直保持？（此时继续播放中）  我发现偶尔会出现保持的情况  不过大部分时间播放器都是会被静音。
2、在播放过程中，打开相机后，返回到播放页面（此时播放器仍然在继续播放），这时播放器没有声音了，我尝试设置player以及player.currentPlayerManager 的volume 以及muted 都无法恢复声音。请问这个应该如何解决呢？

**Comment by renzifeng** [comment]
AVAudioSession相关API应该有你想要的

**Comment by Elbays-Zhang** [comment]
了解了 谢谢~
