### ISSUE TITLE
抖音个人主页(ZFCollectionViewListController) 跳转到 抖音列表(ZFDouYinViewController) 自动加载更多(MJRefreshAutoNormalFooter)问题

### ISSUE THREAD

**Issue by Lucifer0103** [renzifeng/ZFPlayer#1047]
抖音个人主页(ZFCollectionViewListController) 跳转到 抖音列表(ZFDouYinViewController) 
添加 自动加载更多(MJRefreshAutoNormalFooter)功能. 导致抖音列表页(ZFDouYinViewController) , 界面向上串一部分, 从而引发视频播放源错乱. 请问如何解决在ZFDouYinViewController 中 添加MJRefreshAutoNormalFooter的问题 ?

**Comment by yanngxinlei** [comment]
你这个问题怎么解决的，可以交流一下吗
