### ISSUE TITLE
#import <ZFPlayer/ZFPlayerConst.h> 

### ISSUE THREAD

**Issue by iOSyifeng** [renzifeng/ZFPlayer#1049]
#import <ZFPlayer/ZFPlayerConst.h> 这个文件 缺少 我看了下 在 core里面是缺少这个文件的 最新版没上传上去?

**Comment by applekwork** [comment]
遇到同样的问题
![image](https://user-images.githubusercontent.com/24840225/90624920-5386f700-e24b-11ea-8d1d-8dbe00742d4a.png)

**Comment by iOSyifeng** [comment]
作者处理一下啊  demo都跑不起来

**Comment by guishendaye** [comment]
遇到同样的问题.   还有ZFPlayerView文件也不一样
