### ISSUE TITLE
大佬怎么快进到某一毫秒呢??

### ISSUE THREAD

**Issue by Buliceli** [renzifeng/ZFPlayer#1056]
[_player seekToTime:seekTime toleranceBefore:kCMTimeZero toleranceAfter:kCMTimeZero completionHandler:completionHandler];
这么写好像只能精准的定位到某一秒 怎么快进到某一毫秒呢

**Comment by renzifeng** [comment]
这块我在新版要做修改,改成这样吧
```objc
        int32_t timeScale = _player.currentItem.asset.duration.timescale;
        CMTime seekTime = CMTimeMakeWithSeconds(time, timeScale);
        [_player seekToTime:seekTime toleranceBefore:kCMTimeZero toleranceAfter:kCMTimeZero completionHandler:completionHandler];
```

**Comment by likai89** [comment]
我改成这样子 可以了
- (void)seekToTime:(NSTimeInterval)time completionHandler:(void (^ __nullable)(BOOL finished))completionHandler {
    if (self.totalTime > 0) {
//       CMTime seekTime = CMTimeMake(time, 1);
        CMTime seekTime = CMTimeMake(time*1000, 1000);
        [_player seekToTime:seekTime toleranceBefore:kCMTimeZero toleranceAfter:kCMTimeZero completionHandler:completionHandler];
    } else {
        self.seekTime = time;
    }
}
