### ISSUE TITLE
帅哥，咨询一个播放的问题？

### ISSUE THREAD

**Issue by mrhyh** [renzifeng/ZFPlayer#106]
我录制的视频，在系统相册中播放就是全屏（播放界面是始终横屏）铺满的的。用楼主的三方库播放，视频部分就是竖着的,屏幕还是横着的。

或者说，我录制了一个视频，在相册中播放是默认横屏、全屏的，用楼主的三方库播放时，视频就变成竖屏的了(屏幕仍然是横着的)。
  如果可以的话，希望能留下一个QQ号。

**Comment by renzifeng** [comment]
加我qq群，群里可以找到我，在readme里
