### ISSUE TITLE
seek 不准确的问题

### ISSUE THREAD

**Issue by JinJieGu** [renzifeng/ZFPlayer#1061]
使用seekToTime发现不准确问题。

举个例子：
我想seek到12.716，但是seek后，打印当前时间，发现为12.0，如下图：

![20200826164820](https://user-images.githubusercontent.com/11242805/91284719-ddd8d900-e7be-11ea-94c5-a6b1e5d57e19.jpg)

提了一个PR修复后可以精准seek到12.716，如图：

![20200826165003](https://user-images.githubusercontent.com/11242805/91284708-db767f00-e7be-11ea-90a6-6b9bd0d2ff1c.jpg)

**Comment by puyang0521** [comment]
您好，请问seekToTime不准确的问题，您是如何解决的？
