### ISSUE TITLE
视频方向不正确

### ISSUE THREAD

**Issue by Homin818** [renzifeng/ZFPlayer#1068]
列表中播放视频，使用ZFIJKPlayerManager播放时，视频方向不正确，ZFAVPlayerManager 正确，请问如何旋转ZFIJKPlayerManager的视频内容？

**Comment by GoKnow** [comment]
问题解决没有

**Comment by yuansirios** [comment]
这个问题解决了没有，同问

**Comment by Arya-Wang** [comment]
请问解决没有呢。部分视频有这个问题

**Comment by Arya-Wang** [comment]
已经解决了，参考github上ijkplaer库里面的解决方法

**Comment by Arya-Wang** [comment]
已经解决了，参考github上ijkplayer库里面的解决方法

**Comment by Nododo** [comment]
> 已经解决了，参考github上ijkplayer库里面的解决方法

https://www.jianshu.com/p/48035f64c36d 

方便更多人看到
