### ISSUE TITLE
播放中按home键进入后台.等待一段时间之后回到APP.有可能画面一直是黑屏

### ISSUE THREAD

**Issue by MonkeyHZT** [renzifeng/ZFPlayer#107]
如题.如果此时进行旋转则会正常显示.有声音无图像

**Comment by MonkeyHZT** [comment]
demo中也存在这个问题

**Comment by MonkeyHZT** [comment]
坐等后续

**Comment by MonkeyHZT** [comment]
坐等后续

**Comment by renzifeng** [comment]
我针对这个优化了一下，希望你有时间帮着测一下

**Comment by MonkeyHZT** [comment]
能说下具体的原因吗.因为我已经把您的项目修改了一些东西揉进自己的项目了.不太好更新

**Comment by renzifeng** [comment]
改动较大一些，你要是不想更新的话，就把ZFPlayerView里的`setState:`里self.layer.contents生成的黑色图片图片代码去掉，然后把`self.playerLayer.backgroundColor = [UIColor blackColor].CGColor;`

**Comment by MonkeyHZT** [comment]
十分感谢.如果后续发现bug我会及时向您反馈

**Comment by MonkeyHZT** [comment]
不过这样改的话还是会出现有声音没图像的情况

**Comment by renzifeng** [comment]
那你帮我测一下  demo有问题吗，

**Comment by MonkeyHZT** [comment]
demo有图片没声音的情况没复现...我看下我的具体代码吧.因为我看你更新的代码里边貌似只是优化了一个占位图.没有找到其他控制播放/暂停时图像的相关处理

**Comment by renzifeng** [comment]
是的 主要是改你提的bug了

**Comment by renzifeng** [comment]
再次改了一下，`self.playerLayer.backgroundColor = [UIColor blackColor].CGColor`去掉改为`self.viewr.backgroundColor = [UIColor blackColor]`，这样应该没问题了吧

**Comment by shengxiaolei** [comment]
改了后 画面没填充~

**Comment by renzifeng** [comment]
@shengxiaolei 没测出来啊
