### ISSUE TITLE
抖音主页样式，我点第一个视频，播放的是第二个，点第二个，播放的是第三个，是什么原因

### ISSUE THREAD

**Issue by xuhuaping** [renzifeng/ZFPlayer#1076]

**Comment by jiangyongchang126** [comment]
确实有这个问题，需要在scrollView的代理方法里面判断NSIndexPath
    NSInteger row = (NSInteger)scrollView.contentOffset.y / SCREEN_HEIGHT;
    self.currentIndexPath = [NSIndexPath indexPathForRow:row inSection:0];
