### ISSUE TITLE
双击home健，然后切换回前台导航栏上移导致界面错乱

### ISSUE THREAD

**Issue by wphehe** [renzifeng/ZFPlayer#1080]
作者您好，在使用ZFPlayer中，双击home健，然后切换回前台导航栏上移导致界面错乱，希望作者解决一下这个bug

**Comment by fortitude1990** [comment]
还没找到具体解决方案，是因为隐藏状态栏造成的，因为用了RTRootNavigationController了，解决起来有点麻烦；如果没用的话，可以重写navigationController的viewWillLayoutSubviews来修改navigationBar的frame


- (void)viewWillLayoutSubviews{
    [super viewWillLayoutSubviews];
    /// 视频播放会隐藏状态栏，状态栏隐藏后，navigationBar会自动上移到屏幕顶部，view的frame也会重新调整，为了避免出现跳动的现象，view的frame修复成原有参数值
    self.view.frame = CGRectMake(0, kTopHeight, kScreenWidth, kScreenHeight - kTopHeight);
}

**Comment by junedeyu** [comment]
我也遇到了这个问题，导航栏和tabbar 都乱了
