### ISSUE TITLE
seekToTime之后，立刻暂停播放

### ISSUE THREAD

**Issue by yanqiangS** [renzifeng/ZFPlayer#1081]
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/16951446/93039176-67225380-f679-11ea-8ce3-d5e8d99f6cdf.png">

你好，我这有个需求，需要在seekToTime后，立刻暂停播放。在这个回调里，调用暂停后，播放器仍然在seekTo成功后，继续播放，这是什么原因呢？

**Comment by InsectQY** [comment]
怎么解决的
