### ISSUE TITLE
暂停播放视频，app到后台，再到前台会自动播放，原因是demo中代码跟仓库中的代码不一样！！！

### ISSUE THREAD

**Issue by zhangxiongwen** [renzifeng/ZFPlayer#1083]
被这个问题困扰了很久，发现demo中并没有有这个问题，但是通过pod下来的代码就有问题，找了很久发现了问题的所在！
原因是 demo中代码跟仓库中的代码不一样！！
具体是ZFAVPlayerManager中386行，pod中的代码少了一个判断
![image](https://user-images.githubusercontent.com/21216840/93062273-512b8780-f6a7-11ea-9f4b-4296c8792b25.png)
![image](https://user-images.githubusercontent.com/21216840/93062355-6a343880-f6a7-11ea-9a6c-fa5ff0e6fd60.png)

**Comment by guishendaye** [comment]
我被后台切换前台有声音这个问题困扰很很久

**Comment by xuanInitial** [comment]
感谢   建议作者更新一下pod

**Comment by WSWshallwe** [comment]
感谢 点赞

**Comment by wangyuchaogeek** [comment]
感谢,遇到相同问题.
