### ISSUE TITLE
大佬们，竖向滚动抖音视频，请求下一页数据 collectionView  reloadData 后，最后一个视频只有声音，没有画面。

### ISSUE THREAD

**Issue by Jackie-Lee-Mr** [renzifeng/ZFPlayer#1086]
求解决方法

**Comment by xiangchangming** [comment]
reloaddata 下边加上这个 [self.player addPlayerViewToCell];

**Comment by jiangyongchang126** [comment]
各位大佬，这个问题解决了吗？ 还是不行呀

**Comment by jiangyongchang126** [comment]
在reloadData后面加下面的就可以了，      
  [self.collectionView layoutIfNeeded];
刷新的时候[self.collectionView cellForItemAtIndexPath:self.currentIndexPath]获取的对象cell为nil导致的
