### ISSUE TITLE
Crash：Application tried to present modally an active controller 

### ISSUE THREAD

**Issue by fortitude1990** [renzifeng/ZFPlayer#1088]
1、类：ZFPresentTransition
     方法：presentAnimation
     语句：[transitionContext completeTransition:YES] 
     造成crash：Application tried to present modally an active controller 
2、类：ZFOrientationObserver
      方法：enterPortraitFullScreen: animated: completion:
      语句:       [[UIWindow zf_currentViewController] presentViewController:self.portraitViewController animated:animated completion:^{
            if (completion) completion();
        }];
     造成crash：Application tried to present modally an active controller

**Comment by ChenZachary** [comment]
请问解决了吗 我竖屏的时候也是这个bug

**Comment by fortitude1990** [comment]
> 请问解决了吗 我竖屏的时候也是这个bug

解决了

**Comment by fortitude1990** [comment]
> 请问解决了吗 我竖屏的时候也是这个bug

时间太久了，具体解决方案忘记了，你可以尝试添加以下判断逻辑

 /// 视频未播放的情况下，由于视频的portraitFullScreenMode全屏填充，会有一个跳动的感觉
        if (self.player.currentPlayerManager.isPlaying && (self.player.currentPlayerManager.loadState == ZFPlayerLoadStatePlayable || self.player.currentPlayerManager.loadState == ZFPlayerLoadStatePlaythroughOK)) {
            if (!self.player.orientationObserver.isFullScreen) {
                [self.player enterPortraitFullScreen:YES animated:YES];
            }
        }else{
           if (!self.player.orientationObserver.isFullScreen) {
               /// 视频未准备完成的时候 presentationSize == CGSizeZero，当视频准备完毕后presentationSize会改为播放尺寸，在presentationSize值变动的过程中，会产生跳动的感觉
               self.player.orientationObserver.presentationSize = CGSizeMake(contentModel.videoMetaDataDto.width, contentModel.videoMetaDataDto.height);
               [self.player enterPortraitFullScreen:YES animated:YES];
           }
        }

**Comment by fortitude1990** [comment]
> 请问解决了吗 我竖屏的时候也是这个bug

你也可以尝试更新到最新版本，最近版本没发现这个问题
