### ISSUE TITLE
进入播放视频后，会影响SVProgressHUD的位置

### ISSUE THREAD

**Issue by xiaozhouboy** [renzifeng/ZFPlayer#1090]
最新版本4.0.1
全屏播放会影响SVProgressHUD的位置，从全屏播放页面出来后SVProgressHUD就跑到上面了，而且调节亮度和音量的ZFVolumeBrightnessView的位置也没有居中

**Comment by xiaozhouboy** [comment]
[
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-18 at 14 19 24](https://user-images.githubusercontent.com/15812647/93563385-5c89f600-f9ba-11ea-88cb-7f92e4a1dacc.png)
](url)

**Comment by Jacksom** [comment]
在全屏播放页面viewWillDisappear中 设置两次设备方向就好了
    [[UIDevice currentDevice] setValue:@(UIInterfaceOrientationLandscapeRight)
                                forKey:@"orientation"];
    [[UIDevice currentDevice] setValue:@(UIInterfaceOrientationPortrait)
                                forKey:@"orientation"];
