### ISSUE TITLE
ZFPlayerView 的 presentationSize 错误，造成在ZFPlayerScalingModeAspectFit下闪动

### ISSUE THREAD

**Issue by JockerLUO** [renzifeng/ZFPlayer#1124]
在 ZFPlayerView 中有
- (CGSize)presentationSize {
    if (CGSizeEqualToSize(_presentationSize, CGSizeZero)) {
        _presentationSize = self.frame.size;
    }
    return _presentationSize;
}
当停止视频时会把presentationSize设置为CGSizeZero，播放视频重新添加到view中，在layoutSubviews方法做布局，
如果在停止后，调用presentationSize，presentationSize值是前一个视频的presentationSize， 
播放新的视频还未获取到正确的presentationSize，
此时添加到view中，再调用layoutSubviews方法，会获取到一个错误的presentationSize，
设置scalingMode  为 ZFPlayerScalingModeAspectFit会出现布局错误，
视频会闪一下。
建议移除 - (CGSize)presentationSize 方法，或者优化

**Comment by SummerHF** [comment]
@JockerLUO 请问这个问题你是怎么修复的啊 这个问题很普遍 列表播放的时候

**Comment by JockerLUO** [comment]
把 ZFPlayerView 中的 presentationSize 懒加载注释掉就行

**Comment by SummerHF** [comment]
@JockerLUO 好的 我试试 谢谢哈

**Comment by SummerHF** [comment]
@JockerLUO 这就相当于把它隐藏了 不是太完美 权益之际吧 我的思路是每次播放之前把它置为CGSizeZero
