### ISSUE TITLE
iOS10上点重播按钮播放视频经常性黑屏

### ISSUE THREAD

**Issue by Stylist-H** [renzifeng/ZFPlayer#113]

**Comment by renzifeng** [comment]
这里我修改过，请更新代码在看看

**Comment by Stylist-H** [comment]
是更新在master上吗？我pod了最新的2.0.2有这个问题。

**Comment by renzifeng** [comment]
你先看一下demo有木有问题，我没测出来重播视频经常性黑屏呀。

**Comment by Stylist-H** [comment]
2.0.2的demo有此问题，如图哈
![simulator screen shot 2016 11 9 10 46 58](https://cloud.githubusercontent.com/assets/23349293/20125683/fb1a4534-a669-11e6-9fac-27cfd5bddeb7.png)

**Comment by Stylist-H** [comment]
要等它自己播放完成，再去点重播，就出现了，快进播放完成的不会出现。

**Comment by renzifeng** [comment]
这个我今天改了一下，还没更新pod，你先测测，没问题我就更新一版

**Comment by kkangkaik** [comment]
同样出现ios10 点击重播视频不播放 用的2.0.2

**Comment by renzifeng** [comment]
我马上更新 2.0.3，稍等

**Comment by kkangkaik** [comment]
多谢🙏
