### ISSUE TITLE
[4.0.1，iPhone X系列，iOS 13以上]横屏模式，退到后台再返回，tableview布局会垮掉

### ISSUE THREAD

**Issue by f2yu** [renzifeng/ZFPlayer#1163]
demo就能复现，普通样式--播放--切换成横屏--退到后台--返回前台--切换成竖屏--返回，能直接看到demo的tableview布局垮掉

**Comment by f2yu** [comment]
排查了一下，系统为iOS 14，机型为iPhone 12，估计是系统对safearea的处理问题，导致如果切换window，退到后台，对导致原来的window中vc的view回去到的safearea不对，从而导致如果试用安全区域方式或者tableView的insetsContentViewsToSafeArea为true时，布局混乱。。。所以目前切window的方式要慎用。。。

**Comment by f2yu** [comment]
退到后台前调整转向的方式问题很大，这种方式会导致黑屏、界面无法点击的情况出现，对于x以上的机型，导致横屏时用户不便于切换应用，正解是避免使用safeArea，这个调整性极大。作者的处理方式比较巧妙，通过切换window的方式来规避对项目自身的影响，比如类似抖音那样的交互比较不错，但是iOS 13及以上对safeArea的处理会有问题，比较无解。

**Comment by iosForLyc** [comment]
有解决办法吗，这个问题好像很久了

**Comment by f2yu** [comment]
> 有解决办法吗，这个问题好像很久了

暂时的规避方式是禁止UITableView使用safeArea，但这种方式lndicator依然会显示异常，得把这个也隐藏掉，另外UICollectionView分页偏移会有点小问题，不过影响不大

**Comment by f2yu** [comment]
#1132

**Comment by Dengfulei** [comment]
问题依然存在的
