### ISSUE TITLE
3.0升级的4.0，全屏后点击无法显示控制层，相当于假死

### ISSUE THREAD

**Issue by yukifeng** [renzifeng/ZFPlayer#1169]
自定义的manager和controlerview 不过基本上是复制的zf自带的controlview只是多加了几个需要的显示用的UI空间  请问有什么排查方案吗？

**Comment by renzifeng** [comment]
看一下层级结构横屏的控制器是否显示，应该是转屏的问题

**Comment by wwx1991** [comment]
> 自定义的manager和controlerview 不过基本上是复制的zf自带的controlview只是多加了几个需要的显示用的UI空间 请问有什么排查方案吗？

俺也一样，请问你解决了吗？

**Comment by yongshideweiyi** [comment]
> > 自定义的manager和controlerview 不过基本上是复制的zf自带的controlview只是多加了几个需要的显示用的UI空间 请问有什么排查方案吗？
> 
> 俺也一样，请问你解决了吗？

请问各位解决这个问题了么，我也遇到同样的问题，播放失败，控制层无论如何显示不了

**Comment by wdq123550** [comment]
> > > 自定义的manager和controlerview 不过基本上是复制的zf自带的controlview只是多加了几个需要的显示用的UI空间 请问有什么排查方案吗？
> > 
> > 
> > 俺也一样，请问你解决了吗？
> 
> 请问各位解决这个问题了么，我也遇到同样的问题，播放失败，控制层无论如何显示不了

一样的问题

**Comment by ymjmaster** [comment]
> 看一下层级结构横屏的控制器是否显示，应该是转屏的问题

什么方案解决的啊大佬？

**Comment by ymjmaster** [comment]
> > 看一下层级结构横屏的控制器是否显示，应该是转屏的问题
> 
> 什么方案解决的啊大佬？

我这问题解决了，根本原因是supportedInterfaceOrientationsForWindow方法中横竖屏的返回值不对。

**Comment by wwx1991** [comment]
> > > 看一下层级结构横屏的控制器是否显示，应该是转屏的问题
> > 
> > 
> > 什么方案解决的啊大佬？
> 
> 我这问题解决了，根本原因是supportedInterfaceOrientationsForWindow方法中横竖屏的返回值不对。

那是怎么解决的？分享一下

**Comment by HenryBog** [comment]
> > > > 看一下层级结构横屏的控制器是否显示，应该是转屏的问题
> > > 
> > > 
> > > 什么方案解决的啊大佬？
> > 
> > 
> > 我这问题解决了，根本原因是supportedInterfaceOrientationsForWindow方法中横竖屏的返回值不对。
> 
> 那是怎么解决的？分享一下
AppDelegate 添加方法

- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
    return UIInterfaceOrientationMaskAllButUpsideDown;
}
