### ISSUE TITLE
希望能自定义界面

### ISSUE THREAD

**Issue by dragonsun7** [renzifeng/ZFPlayer#121]
我们有一个项目很想用ZFPlayer，但是ZFPlayer的界面和我们的设计有点不一致，例如：我们希望开始和暂停按钮在屏幕的中间，希望顶部能有返回、分享、收藏等功能按钮。虽然也能自己修改，但是这会导致以后更新有麻烦。作者看看能不能扩展一下这部分，谢谢！

**Comment by renzifeng** [comment]
现在就是可以完整的自定义控制层controlView，功能层都在playerView里

**Comment by dragonsun7** [comment]
你现在这个代码结构，如果要实现界面自定义，需要修改ZFPlayerControlView，以后没法用CocoaPod更新了
