### ISSUE TITLE
iOS 15下竖屏全屏问题

### ISSUE THREAD

**Issue by yangmh108** [renzifeng/ZFPlayer#1255]
我直接全屏播放，之前这么写，竖屏横屏播放都可以，现在iOS15会黑屏播放不了视频
if (self.orientation == 2) {
        //竖屏
        [self.player enterPortraitFullScreen:YES animated:YES];
    }else{
        //横屏
        self.player.orientationObserver.supportInterfaceOrientation = ZFInterfaceOrientationMaskLandscape;
        [self.player rotateToOrientation:UIInterfaceOrientationLandscapeRight animated:NO completion:nil];
    }

**Comment by baiyidjp** [comment]
你好，你这个怎么解决的？

**Comment by baiyidjp** [comment]
竖屏播放返回时会展示一个黑屏的小播放页面，还不能播放视频，你有碰到这个吗
