### ISSUE TITLE
回到前台UIApplicationDidBecomeActiveNotification

### ISSUE THREAD

**Issue by TDGYL** [renzifeng/ZFPlayer#1289]
你好，我想让app回到前台时候不自动播放怎么写呢
（场景，因为我们app有segment切换，切换到其他界面就不能播放，但是目前退出后台再返回前天就自动播放了，但是我当前的segment不在播放界面）

**Comment by renzifeng** [comment]
设置`viewControllerDisappear`为`true`

**Comment by TDGYL** [comment]
你好呀 我设置true了 切换到其他页面了  然后我退出到后台  然后再返回前台  这时候不应该播放的  但是它会播放了   这是偶现的    然后我swizzle了bufferingSomeSecond这个方法，满足需求了


| |
顾宜林
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年02月22日 ***@***.***> 写道：

设置viewControllerDisappear为true

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
