### ISSUE TITLE
横屏状态切出app再返回导航栏偏移错位，用的demo跑模拟器这个问题必现，我真机也有这个问题

### ISSUE THREAD

**Issue by dongzhenggang123** [renzifeng/ZFPlayer#1317]
https://user-images.githubusercontent.com/13194532/177744162-ca7ce0c9-62f1-4314-b23c-141e0bd592fa.mp4

**Comment by KeWangKW** [comment]
[UIViewController+ZFPlayerFixSafeArea.m.zip](https://github.com/renzifeng/ZFPlayer/files/9335401/UIViewController%2BZFPlayerFixSafeArea.m.zip)

**Comment by dongzhenggang123** [comment]
> 

试了下，确实可以。谢谢啦！
