### ISSUE TITLE
嗯。。。且看vcr吧，只是记录一下，可能后续版本搞好了，也可能后续只能看你们强大的分析力了

### ISSUE THREAD

**Issue by emiyajin** [renzifeng/ZFPlayer#1323]
https://user-images.githubusercontent.com/20593326/179160952-af25503d-f632-4335-830e-6ecf630eff06.mp4

**Comment by emiyajin** [comment]
出现的问题跟 #1132 一样，只能说期待哪个厉害的程序员来解决这个问题了吧，不知道我这是上下求索的决心，还是自己无法解惑而最终的无奈

**Comment by emiyajin** [comment]
上面的问题编号里
那个分类文件无法解决导航栏自定义的，且是uitabarcontroller + navcontroller + viewcontroller这个架构的

**Comment by emiyajin** [comment]
我翻了一下issue，其中#1248说到了这个分类的弊端，至于用不用，如何解决，这个就看大家集思广益了

**Comment by emiyajin** [comment]
我翻了一下issue，其中 #1248 说到了这个分类的弊端，至于用不用，如何解决，这个就看大家集思广益了

**Comment by renzifeng** [comment]
4.1.0也解决了这个问题
