### ISSUE TITLE
全屏播放->锁屏->退出全屏.导航栏错乱

### ISSUE THREAD

**Issue by zhou963215** [renzifeng/ZFPlayer#1330]
全屏播放->锁屏->退出全屏.导航栏错乱

**Comment by KeWangKW** [comment]
[UIViewController+ZFPlayerFixSafeArea.m.zip](https://github.com/renzifeng/ZFPlayer/files/9335400/UIViewController%2BZFPlayerFixSafeArea.m.zip)

从别的回答里找到的解决办法，.m文件拖到项目里就行了

**Comment by renzifeng** [comment]
4.1.0解决
