### ISSUE TITLE
reloadData后只有声音，没画面或者说只显示封面。

### ISSUE THREAD

**Issue by w83144378** [renzifeng/ZFPlayer#1332]
这个问题从19年到现在还是没解决。。

**Comment by w83144378** [comment]
//            [self.view setNeedsLayout];
//            [self.view layoutIfNeeded];
//            [self.player addPlayerViewToCell];

这样能暂时解决问题。

**Comment by emiyajin** [comment]
啊这~~~~我都不知道你写在哪个位置写了这三个方法，我这边解决的比较暴力，就是把tableview reloadData写两遍

**Comment by emiyajin** [comment]
你这个办法，我在请求完毕，reloadData里倒是试了，是解决了有画无声的问题，但是不知为啥有个控件交互像失效了一般，就是UISlider，我是写在Cell上的，直接就无效了
