### ISSUE TITLE
 iOS 16 下播放器横屏异常

### ISSUE THREAD

**Issue by Leonard1379** [renzifeng/ZFPlayer#1333]
如题

**Comment by Liaoworking** [comment]
同样的问题

**Comment by Liaoworking** [comment]
我的解决方案是
`- (void)interfaceOrientation:(UIInterfaceOrientation)orientation {
  if (@available(iOS 16.0, *)) {
      NSArray *array = [[[UIApplication sharedApplication] connectedScenes] allObjects];
      if (array.count > 0) {
        UIWindowScene *ws = (UIWindowScene *)array[0];
        
        UIInterfaceOrientationMask currentOrientation = UIInterfaceOrientationMaskLandscapeRight;
        if (orientation == UIInterfaceOrientationPortrait) {
          currentOrientation = UIInterfaceOrientationMaskPortrait;
        }
        
        [ws requestGeometryUpdateWithPreferences: [[UIWindowSceneGeometryPreferencesIOS alloc]initWithInterfaceOrientations: currentOrientation] errorHandler:^(NSError * _Nonnull error) {
          NSLog(@"屏幕旋转失败了：%@", error);
        }];
      // 下面的这行代码默认不加 如果起不到旋转的作用就加上  以实际项目为准  
      // 其中 [GetCurrentVCTool currentViewController] 的作用是获取到当前屏幕正在显示的VC
      // [[GetCurrentVCTool currentViewController] setNeedsUpdateOfSupportedInterfaceOrientations];
      }
    }else{
      
      if ([[UIDevice currentDevice] respondsToSelector:@selector(setOrientation:)]) {
        SEL selector = NSSelectorFromString(@"setOrientation:");
        NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:[UIDevice instanceMethodSignatureForSelector:selector]];
        [invocation setSelector:selector];
        [invocation setTarget:[UIDevice currentDevice]];
        int val = (int)orientation;
        [invocation setArgument:&val atIndex:2];
        [invocation invoke];
      }
    }
}`

**Comment by xnxy** [comment]
https://xnxy.github.io/2022/08/19/%E5%85%B3%E4%BA%8EiOS%20&%20iPadOS%2016%20beta%206%E7%9B%B8%E5%85%B3API%E5%BA%9F%E5%BC%83/

跟iOS16旋转屏幕方法废弃有关吗？

**Comment by Leonard1379** [comment]
> https://xnxy.github.io/2022/08/19/%E5%85%B3%E4%BA%8EiOS%20&%20iPadOS%2016%20beta%206%E7%9B%B8%E5%85%B3API%E5%BA%9F%E5%BC%83/
> 
> 跟iOS16旋转屏幕方法废弃有关吗？

就是这个原因，但是说废弃不准确，用setValue:ForKey的方式来修改属性本来就是不允许的，只是之前这么设置还能用，iOS 16直接让他不生效了

**Comment by zhangjia940126** [comment]
我也参考了https://www.jianshu.com/p/399846e50264 这个，可是还是找不到转屏放心，有人解决不，可以贴一下代码吗，非常感谢

**Comment by coderWeil** [comment]
这个有解决的吗，APP播放功能全屏都不行了，急需更新

**Comment by cartmanguo** [comment]
同问，尝试改了下代码还是没有对

**Comment by HDLSmile** [comment]
一样的问题

**Comment by qwerOC** [comment]
> 



> 因为现有的解决方案的API只有Xcode14里才有。Xcode13需要使用 NSSelectorFromString 来解决。 我参考这篇文章解决的这个问题： https://www.jianshu.com/p/399846e50264

方便贴一下修改zfplayer代码的位置和文件么

**Comment by Liaoworking** [comment]
> > 因为现有的解决方案的API只有Xcode14里才有。Xcode13需要使用 NSSelectorFromString 来解决。 我参考这篇文章解决的这个问题： https://www.jianshu.com/p/399846e50264
> 
> 方便贴一下修改zfplayer代码的位置和文件么


//  ZFOrentationObserver.h

`
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

/// Full screen mode
typedef NS_ENUM(NSUInteger, ZFFullScreenMode) {
    ZFFullScreenModeAutomatic,  // Determine full screen mode automatically
    ZFFullScreenModeLandscape,  // Landscape full screen mode
    ZFFullScreenModePortrait    // Portrait full screen Model
};

/// Full screen mode on the view
typedef NS_ENUM(NSUInteger, ZFRotateType) {
    ZFRotateTypeNormal,         // Normal
    ZFRotateTypeCell,           // Cell
    ZFRotateTypeCellOther       // Cell mode add to other view
};

/**
 Rotation of support direction
 */
typedef NS_OPTIONS(NSUInteger, ZFInterfaceOrientationMask) {
    ZFInterfaceOrientationMaskPortrait = (1 << 0),
    ZFInterfaceOrientationMaskLandscapeLeft = (1 << 1),
    ZFInterfaceOrientationMaskLandscapeRight = (1 << 2),
    ZFInterfaceOrientationMaskPortraitUpsideDown = (1 << 3),
    ZFInterfaceOrientationMaskLandscape = (ZFInterfaceOrientationMaskLandscapeLeft | ZFInterfaceOrientationMaskLandscapeRight),
    ZFInterfaceOrientationMaskAll = (ZFInterfaceOrientationMaskPortrait | ZFInterfaceOrientationMaskLandscapeLeft | ZFInterfaceOrientationMaskLandscapeRight | ZFInterfaceOrientationMaskPortraitUpsideDown),
    ZFInterfaceOrientationMaskAllButUpsideDown = (ZFInterfaceOrientationMaskPortrait | ZFInterfaceOrientationMaskLandscapeLeft | ZFInterfaceOrientationMaskLandscapeRight),
};

@interface ZFOrientationObserver : NSObject

- (void)updateRotateView:(UIView *)rotateView
           containerView:(UIView *)containerView;

/// list play
- (void)cellModelRotateView:(UIView *)rotateView
           rotateViewAtCell:(UIView *)cell
              playerViewTag:(NSInteger)playerViewTag;

/// cell other view rotation
- (void)cellOtherModelRotateView:(UIView *)rotateView
                   containerView:(UIView *)containerView;

/// Container view of a full screen state player.
@property (nonatomic, strong, nullable) UIView *fullScreenContainerView;

/// Container view of a small screen state player.
@property (nonatomic, weak) UIView *containerView;

/// If the full screen.
@property (nonatomic, readonly, getter=isFullScreen) BOOL fullScreen;

/// Use device orientation, default NO.
@property (nonatomic, assign) BOOL forceDeviceOrientation;

/// Lock screen orientation
@property (nonatomic, getter=isLockedScreen) BOOL lockedScreen;

/// The block invoked When player will rotate.
@property (nonatomic, copy, nullable) void(^orientationWillChange)(ZFOrientationObserver *observer, BOOL isFullScreen);

/// The block invoked when player rotated.
@property (nonatomic, copy, nullable) void(^orientationDidChanged)(ZFOrientationObserver *observer, BOOL isFullScreen);

/// Full screen mode, the default landscape into full screen
@property (nonatomic) ZFFullScreenMode fullScreenMode;

/// rotate duration, default is 0.30
@property (nonatomic) float duration;

/// The statusbar hidden.
@property (nonatomic, getter=isStatusBarHidden) BOOL statusBarHidden;

/// The current orientation of the player.
/// Default is UIInterfaceOrientationPortrait.
@property (nonatomic, readonly) UIInterfaceOrientation currentOrientation;

/// Whether allow the video orientation rotate.
/// default is YES.
@property (nonatomic) BOOL allowOrentitaionRotation;

/// The support Interface Orientation,default is ZFInterfaceOrientationMaskAllButUpsideDown
@property (nonatomic, assign) ZFInterfaceOrientationMask supportInterfaceOrientation;

/// Add the device orientation observer.
- (void)addDeviceOrientationObserver;

/// Remove the device orientation observer.
- (void)removeDeviceOrientationObserver;

/// Enter the fullScreen while the ZFFullScreenMode is ZFFullScreenModeLandscape.
- (void)enterLandscapeFullScreen:(UIInterfaceOrientation)orientation animated:(BOOL)animated;

/// Enter the fullScreen while the ZFFullScreenMode is ZFFullScreenModePortrait.
- (void)enterPortraitFullScreen:(BOOL)fullScreen animated:(BOOL)animated;

- (void)exitFullScreenWithAnimated:(BOOL)animated;

+ (void)rotateScreenIniOS16WithOrientationMask:(UIInterfaceOrientationMask)orientationMask andWindowScene:(UIWindowScene *)windowScene andNeedUpdateUserInterface:(BOOL)needUpdateUserInterface API_AVAILABLE(ios(13.0));

@end

NS_ASSUME_NONNULL_END





`

**Comment by Liaoworking** [comment]
//  ZFOrentationObserver.m 代码如下

#import "ZFOrientationObserver.h"
#import "ZFPlayer.h"
#import "gymbo-Swift.h"
#define SysVersion [[UIDevice currentDevice] systemVersion].floatValue

@interface UIWindow (CurrentViewController)

/*!
 @method currentViewController
 @return Returns the topViewController in stack of topMostController.
 */
+ (UIViewController*)zf_currentViewController;

@end

@implementation UIWindow (CurrentViewController)

+ (UIViewController*)zf_currentViewController; {
  UIWindow *window = [[UIApplication sharedApplication].delegate window];
  UIViewController *topViewController = [window rootViewController];
  while (true) {
    if (topViewController.presentedViewController) {
      topViewController = topViewController.presentedViewController;
    } else if ([topViewController isKindOfClass:[UINavigationController class]] && [(UINavigationController*)topViewController topViewController]) {
      topViewController = [(UINavigationController *)topViewController topViewController];
    } else if ([topViewController isKindOfClass:[UITabBarController class]]) {
      UITabBarController *tab = (UITabBarController *)topViewController;
      topViewController = tab.selectedViewController;
    } else {
      break;
    }
  }
  return topViewController;
}

@end

@interface ZFOrientationObserver ()

@property (nonatomic, weak) UIView *view;

@property (nonatomic, assign, getter=isFullScreen) BOOL fullScreen;

@property (nonatomic, strong) UIView *cell;

@property (nonatomic, assign) NSInteger playerViewTag;

@property (nonatomic, assign) ZFRotateType roateType;

@property (nonatomic, strong) UIView *blackView;

@end

@implementation ZFOrientationObserver

- (instancetype)init {
  self = [super init];
  if (self) {
    _duration = 0.30;
    _fullScreenMode = ZFFullScreenModeLandscape;
    _supportInterfaceOrientation = ZFInterfaceOrientationMaskAllButUpsideDown;
    _allowOrentitaionRotation = YES;
    _roateType = ZFRotateTypeNormal;
  }
  return self;
}

- (void)updateRotateView:(UIView *)rotateView
           containerView:(UIView *)containerView {
  self.view = rotateView;
  self.containerView = containerView;
}

- (void)cellModelRotateView:(UIView *)rotateView rotateViewAtCell:(UIView *)cell playerViewTag:(NSInteger)playerViewTag {
  self.roateType = ZFRotateTypeCell;
  self.view = rotateView;
  self.cell = cell;
  self.playerViewTag = playerViewTag;
}

- (void)cellOtherModelRotateView:(UIView *)rotateView containerView:(UIView *)containerView {
  self.roateType = ZFRotateTypeCellOther;
  self.view = rotateView;
  self.containerView = containerView;
}

- (void)dealloc {
  [self removeDeviceOrientationObserver];
  [self.blackView removeFromSuperview];
}

- (void)addDeviceOrientationObserver {
  if (![UIDevice currentDevice].generatesDeviceOrientationNotifications) {
    [[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];
  }
  [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(handleDeviceOrientationChange) name:UIDeviceOrientationDidChangeNotification object:nil];
}

- (void)removeDeviceOrientationObserver {
  if (![UIDevice currentDevice].generatesDeviceOrientationNotifications) {
    [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];
  }
  [[NSNotificationCenter defaultCenter] removeObserver:self name:UIDeviceOrientationDidChangeNotification object:nil];
}

- (void)handleDeviceOrientationChange {
  if (self.fullScreenMode == ZFFullScreenModePortrait || !self.allowOrentitaionRotation) return;
  if (UIDeviceOrientationIsValidInterfaceOrientation([UIDevice currentDevice].orientation)) {
    _currentOrientation = (UIInterfaceOrientation)[UIDevice currentDevice].orientation;
  } else {
    _currentOrientation = UIInterfaceOrientationUnknown;
    return;
  }
  
  UIInterfaceOrientation currentOrientation = [UIApplication sharedApplication].statusBarOrientation;
  // Determine that if the current direction is the same as the direction you want to rotate, do nothing
  if (_currentOrientation == currentOrientation && ![self isNeedAdaptiveiOS8Rotation] && !self.forceDeviceOrientation) return;
  
  switch (_currentOrientation) {
    case UIInterfaceOrientationPortrait: {
      if ([self isSupportedPortrait]) {
        [self enterLandscapeFullScreen:UIInterfaceOrientationPortrait animated:YES];
      }
    }
      break;
    case UIInterfaceOrientationLandscapeLeft: {
      if ([self isSupportedLandscapeLeft]) {
        [self enterLandscapeFullScreen:UIInterfaceOrientationLandscapeLeft animated:YES];
      }
    }
      break;
    case UIInterfaceOrientationLandscapeRight: {
      if ([self isSupportedLandscapeRight]) {
        [self enterLandscapeFullScreen:UIInterfaceOrientationLandscapeRight animated:YES];
      }
    }
      break;
    default: break;
  }
}

- (void)enterLandscapeFullScreen:(UIInterfaceOrientation)orientation animated:(BOOL)animated {
  if (self.fullScreenMode == ZFFullScreenModePortrait) return;
  _currentOrientation = orientation;
  UIView *superview = nil;
  CGRect frame;
  if ([self isNeedAdaptiveiOS8Rotation] || self.forceDeviceOrientation) {
    if (UIInterfaceOrientationIsLandscape(orientation)) {
      if (self.fullScreen) return;
      superview = self.fullScreenContainerView;
      self.fullScreen = YES;
      self.view.frame = self.containerView.frame;
    } else {
      if (!self.fullScreen) return;
      if (self.roateType == ZFRotateTypeCell) superview = [self.cell viewWithTag:self.playerViewTag];
      else superview = self.containerView;
      self.fullScreen = NO;
      if (self.blackView.superview != nil) [self.blackView removeFromSuperview];
      self.view.frame = superview.bounds;
    }
    if (self.orientationWillChange) self.orientationWillChange(self, self.isFullScreen);
    
    [superview addSubview:self.view];
    
    [self interfaceOrientation:orientation];
    
    if (animated) {
      [UIView animateWithDuration:self.duration animations:^{
        self.view.frame = superview.bounds;
        [self.view layoutIfNeeded];
      } completion:^(BOOL finished) {
        if (self.fullScreen) {
          [superview insertSubview:self.blackView belowSubview:self.view];
          self.blackView.frame = superview.bounds;
        }
        if (self.orientationDidChanged) self.orientationDidChanged(self, self.isFullScreen);
      }];
    } else {
      self.view.frame = superview.bounds;
      [self.view layoutIfNeeded];
      if (self.fullScreen) {
        [superview insertSubview:self.blackView belowSubview:self.view];
        self.blackView.frame = superview.bounds;
      }
      if (self.orientationDidChanged) self.orientationDidChanged(self, self.isFullScreen);
    }
    return;
  }
  
  if (UIInterfaceOrientationIsLandscape(orientation)) {
    superview = self.fullScreenContainerView;
    if (!self.isFullScreen) { /// It's not set from the other side of the screen to this side
      self.view.frame = [self.view convertRect:self.view.frame toView:superview];
    }
    self.fullScreen = YES;
    /// 先加到window上，效果更好一些
    [superview addSubview:_view];
  } else {
    if (self.roateType == ZFRotateTypeCell) superview = [self.cell viewWithTag:self.playerViewTag];
    else superview = self.containerView;
    self.fullScreen = NO;
    if (self.blackView.superview != nil) [self.blackView removeFromSuperview];
  }
  frame = [superview convertRect:superview.bounds toView:self.fullScreenContainerView];
  
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
  [UIApplication sharedApplication].statusBarOrientation = orientation;
#pragma clang diagnostic pop
  
  /// 处理8.0系统键盘
  if (SysVersion >= 8.0 && SysVersion < 9.0) {
    NSInteger windowCount = [[[UIApplication sharedApplication] windows] count];
    if(windowCount > 1) {
      UIWindow *keyboardWindow = [[[UIApplication sharedApplication] windows] objectAtIndex:(windowCount-1)];
      if (UIInterfaceOrientationIsLandscape(orientation)) {
        keyboardWindow.bounds = CGRectMake(0, 0, MAX(ZFPlayerScreenHeight, ZFPlayerScreenWidth), MIN(ZFPlayerScreenHeight, ZFPlayerScreenWidth));
      } else {
        keyboardWindow.bounds = CGRectMake(0, 0, MIN(ZFPlayerScreenHeight, ZFPlayerScreenWidth), MAX(ZFPlayerScreenHeight, ZFPlayerScreenWidth));
      }
      keyboardWindow.transform = [self getTransformRotationAngle:orientation];
    }
  }
  
  if (self.orientationWillChange) self.orientationWillChange(self, self.isFullScreen);
  if (animated) {
    [UIView animateWithDuration:self.duration animations:^{
      self.view.transform = [self getTransformRotationAngle:orientation];
      [UIView animateWithDuration:self.duration animations:^{
        self.view.frame = frame;
        [self.view layoutIfNeeded];
      }];
    } completion:^(BOOL finished) {
      [superview addSubview:self.view];
      self.view.frame = superview.bounds;
      if (self.fullScreen) {
        [superview insertSubview:self.blackView belowSubview:self.view];
        self.blackView.frame = superview.bounds;
      }
      if (self.orientationDidChanged) self.orientationDidChanged(self, self.isFullScreen);
    }];
  } else {
    self.view.transform = [self getTransformRotationAngle:orientation];
    [superview addSubview:self.view];
    self.view.frame = superview.bounds;
    [self.view layoutIfNeeded];
    if (self.fullScreen) {
      [superview insertSubview:self.blackView belowSubview:self.view];
      self.blackView.frame = superview.bounds;
    }
    if (self.orientationDidChanged) self.orientationDidChanged(self, self.isFullScreen);
  }
}

- (void)interfaceOrientation:(UIInterfaceOrientation)orientation {
  if (@available(iOS 16.0, *)) {
      NSArray *array = [[[UIApplication sharedApplication] connectedScenes] allObjects];
      if (array.count > 0) {
        UIWindowScene *ws = (UIWindowScene *)array[0];

        UIInterfaceOrientationMask currentOrientation = UIInterfaceOrientationMaskLandscapeRight;
        if (orientation == UIInterfaceOrientationPortrait) {
          currentOrientation = UIInterfaceOrientationMaskPortrait;
        }
        [ZFOrientationObserver rotateScreenIniOS16WithOrientationMask:currentOrientation andWindowScene:ws andNeedUpdateUserInterface:YES];
      }
    }else{
      
      if ([[UIDevice currentDevice] respondsToSelector:@selector(setOrientation:)]) {
        SEL selector = NSSelectorFromString(@"setOrientation:");
        NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:[UIDevice instanceMethodSignatureForSelector:selector]];
        [invocation setSelector:selector];
        [invocation setTarget:[UIDevice currentDevice]];
        int val = (int)orientation;
        [invocation setArgument:&val atIndex:2];
        [invocation invoke];
      }
    }
}

+ (void)rotateScreenIniOS16WithOrientationMask:(UIInterfaceOrientationMask)orientationMask andWindowScene:(UIWindowScene *)windowScene andNeedUpdateUserInterface:(BOOL)needUpdateUserInterface
API_AVAILABLE(ios(13.0)){
  @try {

    if (needUpdateUserInterface) {
      // 防止appDelegate supportedInterfaceOrientationsForWindow方法不调用
      UIViewController *vc = [GetCurrentVCTool currentViewController];
      SEL selUpdateSupportedMethod = NSSelectorFromString(@"setNeedsUpdateOfSupportedInterfaceOrientations");
      if ([vc respondsToSelector:selUpdateSupportedMethod]) {
          (((void (*)(id, SEL))[vc methodForSelector:selUpdateSupportedMethod])(vc, selUpdateSupportedMethod));
      }
    }
     
     NSArray *array = [[[UIApplication sharedApplication] connectedScenes] allObjects];
     UIWindowScene *ws = (UIWindowScene *)array.firstObject;
     Class GeometryPreferences = NSClassFromString(@"UIWindowSceneGeometryPreferencesIOS");
     id geometryPreferences = [[GeometryPreferences alloc] init];
     [geometryPreferences setValue:@(orientationMask) forKey:@"interfaceOrientations"];
     SEL selGeometryUpdateMethod = NSSelectorFromString(@"requestGeometryUpdateWithPreferences:errorHandler:");
     void (^ErrorBlock)(NSError *error) = ^(NSError *error){
           NSLog(@"iOS 16 转屏Error: %@",error);
     };
     if ([ws respondsToSelector:selGeometryUpdateMethod]) {
         (((void (*)(id, SEL,id,id))[ws methodForSelector:selGeometryUpdateMethod])(ws, selGeometryUpdateMethod,geometryPreferences,ErrorBlock));
     }

  } @catch (NSException *exception) {
    NSLog(@"*****************************华丽分割线**************************");
    NSLog(@"%@",exception);
  } @finally {

  }
  
  
}

- (BOOL)isNeedAdaptiveiOS8Rotation {
  NSArray<NSString *> *versionStrArr = [[UIDevice currentDevice].systemVersion componentsSeparatedByString:@"."];
  int firstVer = [[versionStrArr objectAtIndex:0] intValue];
  int secondVer = [[versionStrArr objectAtIndex:1] intValue];
  if (firstVer == 8) {
    if (secondVer >= 1 && secondVer <= 3) {
      return YES;
    }
  }
  return NO;
}

/// Gets the rotation Angle of the transformation.
- (CGAffineTransform)getTransformRotationAngle:(UIInterfaceOrientation)orientation {
  if (orientation == UIInterfaceOrientationPortrait) {
    return CGAffineTransformIdentity;
  } else if (orientation == UIInterfaceOrientationLandscapeLeft){
    return CGAffineTransformMakeRotation(-M_PI_2);
  } else if(orientation == UIInterfaceOrientationLandscapeRight){
    return CGAffineTransformMakeRotation(M_PI_2);
  }
  return CGAffineTransformIdentity;
}

- (void)enterPortraitFullScreen:(BOOL)fullScreen animated:(BOOL)animated {
  if (self.fullScreenMode == ZFFullScreenModeLandscape) return;
  UIView *superview = nil;
  if (fullScreen) {
    superview = self.fullScreenContainerView;
    self.view.frame = [self.view convertRect:self.view.frame toView:superview];
    [superview addSubview:self.view];
    self.fullScreen = YES;
  } else {
    if (self.roateType == ZFRotateTypeCell) {
      superview = [self.cell viewWithTag:self.playerViewTag];
    } else {
      superview = self.containerView;
    }
    self.fullScreen = NO;
  }
  if (self.orientationWillChange) self.orientationWillChange(self, self.isFullScreen);
  CGRect frame = [superview convertRect:superview.bounds toView:self.fullScreenContainerView];
  if (animated) {
    [UIView animateWithDuration:self.duration animations:^{
      self.view.frame = frame;
      [self.view layoutIfNeeded];
    } completion:^(BOOL finished) {
      [superview addSubview:self.view];
      self.view.frame = superview.bounds;
      if (self.orientationDidChanged) self.orientationDidChanged(self, self.isFullScreen);
    }];
  } else {
    [superview addSubview:self.view];
    self.view.frame = superview.bounds;
    [self.view layoutIfNeeded];
    if (self.orientationDidChanged) self.orientationDidChanged(self, self.isFullScreen);
  }
}

- (void)exitFullScreenWithAnimated:(BOOL)animated {
  if (self.fullScreenMode == ZFFullScreenModeLandscape) {
    [self enterLandscapeFullScreen:UIInterfaceOrientationPortrait animated:animated];
  } else if (self.fullScreenMode == ZFFullScreenModePortrait) {
    [self enterPortraitFullScreen:NO animated:animated];
  }
}

/// 是否支持 Portrait
- (BOOL)isSupportedPortrait {
  return self.supportInterfaceOrientation & ZFInterfaceOrientationMaskPortrait;
}

/// 是否支持 LandscapeLeft
- (BOOL)isSupportedLandscapeLeft {
  return self.supportInterfaceOrientation & ZFInterfaceOrientationMaskLandscapeLeft;
}

/// 是否支持 LandscapeRight
- (BOOL)isSupportedLandscapeRight {
  return self.supportInterfaceOrientation & ZFInterfaceOrientationMaskLandscapeRight;
}

- (UIView *)blackView {
  if (!_blackView) {
    _blackView = [UIView new];
    _blackView.backgroundColor = [UIColor blackColor];
  }
  return _blackView;
}

#pragma mark - setter

- (void)setLockedScreen:(BOOL)lockedScreen {
  _lockedScreen = lockedScreen;
  if (lockedScreen) {
    [self removeDeviceOrientationObserver];
  } else {
    [self addDeviceOrientationObserver];
  }
}

- (UIView *)fullScreenContainerView {
  if (!_fullScreenContainerView) {
    _fullScreenContainerView = [UIApplication sharedApplication].keyWindow;
  }
  return _fullScreenContainerView;
}

- (void)setFullScreen:(BOOL)fullScreen {
  _fullScreen = fullScreen;
  [[UIWindow zf_currentViewController] setNeedsStatusBarAppearanceUpdate];
}

- (void)setStatusBarHidden:(BOOL)statusBarHidden {
  _statusBarHidden = statusBarHidden;
  [[UIWindow zf_currentViewController] setNeedsStatusBarAppearanceUpdate];
}

@end

**Comment by Liaoworking** [comment]
> > 因为现有的解决方案的API只有Xcode14里才有。Xcode13需要使用 NSSelectorFromString 来解决。 我参考这篇文章解决的这个问题： https://www.jianshu.com/p/399846e50264
> 
> 方便贴一下修改zfplayer代码的位置和文件么

https://gist.github.com/Liaoworking/3e0dbc2ee235a95e813c7e180caa1557  这个是修改的文件代码
已上线平稳运行一个星期， github没有消息提醒 有问题可以通过邮件联系。
