### ISSUE TITLE
我总是在这里闪退，但是也不知道什么原因，

### ISSUE THREAD

**Issue by lilin87788** [renzifeng/ZFPlayer#1340]
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/1483811/190545838-5277fc27-e0ed-4b8c-a504-98554f7d56f1.png">

<img width="2030" alt="image" src="https://user-images.githubusercontent.com/1483811/190545768-98130ee5-5df7-4521-ab04-39de9f5bac7b.png">
另外想请问下作者有没有开发swift版本的计划，谢谢大佬

**Comment by renzifeng** [comment]
有swift计划呀，无奈作者没时间，这几年很少写OC代码了，一直在写swift早就有计划了
