### ISSUE TITLE
iOS16 默认横屏问题

### ISSUE THREAD

**Issue by Zhangcong-0721** [renzifeng/ZFPlayer#1345]
![image](https://user-images.githubusercontent.com/80212063/191177365-af1ffd9d-d1a4-499d-b441-39a7867a9b6e.png)
demo里Appdelegate这样设置  全屏页面进去没显示视频window 麻烦看一下

**Comment by renzifeng** [comment]
fix

**Comment by Zhangcong-0721** [comment]
4.1.1没发到pod吗

**Comment by renzifeng** [comment]
今天发
