### ISSUE TITLE
更新了4.1.0之后，手机横屏状态下打开app,整个app无法点击，返回手势也失效

### ISSUE THREAD

**Issue by rockerkekex** [renzifeng/ZFPlayer#1347]
先操作打开一个视频，然后全屏，退出全屏，然后在横屏状态下打开app，app整个页面都无法点击了。此时横屏手机，视屏可以横屏，手势也恢复正常。
这种情况只在iOS16中出现，iOS15是正常的。

**Comment by renzifeng** [comment]
参考这个 https://github.com/renzifeng/ZFPlayer/wiki/%E8%BD%AC%E5%B1%8F%E9%80%82%E9%85%8D

**Comment by rockerkekex** [comment]
> 

完全copy这个写的，而且只会在iOS16中会出现

**Comment by renzifeng** [comment]
你用4.1.1试试，我改过这里

**Comment by hongshao361** [comment]
> 你用4.1.1试试，我改过这里

4.1.1也不行
先操作打开一个视频，然后全屏，退出全屏--->正常
先手机横屏，视频全屏，然后将手机竖屏，视频缩小-->界面卡死

**Comment by rockerkekex** [comment]
> 你用4.1.1试试，我改过这里

已经更新了，还是同样的问题

**Comment by renzifeng** [comment]
麻烦加群，找我沟通一下吧，我不太清楚具体流程

**Comment by CJL92** [comment]
我也遇到这个问题了，查看层级问题，是因为退出全屏后，ZFLandScapeControlView 始终都存在在Window上方，导致页面无法点击，我给设置hidden的，目前看是没有效果的，Xcode 13.4.1 ，iOS 16.0.2 上遇到的

**Comment by renzifeng** [comment]
遇到这个问题麻烦更新4.1.2试试

**Comment by CJL92** [comment]
上午用4.1.1，下午更新了4.1.2也存在这个问题

**Comment by renzifeng** [comment]
> 上午用4.1.1，下午更新了4.1.2也存在这个问题

这个case我不太清楚怎么复现，麻烦加群找我反馈一下具体步骤吧

**Comment by SummerOO** [comment]
怎么加群 我现在也有这个问题

**Comment by JackMayx** [comment]
在16.0上使用CocoaDebug也会导致ZFLandScapeControlView 始终都存在在Window上方，不过这个不算问题。
