### ISSUE TITLE
更新4.1.1之后，Xcode13，iOS16.0无法横屏

### ISSUE THREAD

**Issue by hongshao361** [renzifeng/ZFPlayer#1350]
触发横屏事件，发现
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 160000
            _landscapeRotationManager = [[ZFLandscapeRotationManager_iOS16 alloc] init];
#endif
未执行，_landscapeRotationManager没有创建对象，一直为nil

**Comment by hongshao361** [comment]
xcode14正常

**Comment by hongshao361** [comment]
![31AB0CDB69F9CB3FDF732D92929769CE](https://user-images.githubusercontent.com/38657410/192239354-0706995b-ba22-42f5-ab6a-43f1de19ac3e.jpg)

**Comment by renzifeng** [comment]
fix 4.1.2
