### ISSUE TITLE
ZFOrientationObserver的currentOrientation属性没了吗？

### ISSUE THREAD

**Issue by YoungXKing** [renzifeng/ZFPlayer#1351]
ZFLandscapeRotationManager未写在ZFOrientationObserver中，请问如何获取当前横屏是left还是right呢？之前是直接在代理回调中用的observer的currentOrientation属性

**Comment by renzifeng** [comment]
这个就是获取的设备的interfaceOrientation，我还是加回来吧

**Comment by zhou963215** [comment]
> 

什么时候能发新版.
