### ISSUE TITLE
ZFPortraitControlView中topToolView高度没有适配刘海屏

### ISSUE THREAD

**Issue by huangfangkai** [renzifeng/ZFPlayer#1352]
min_h = 40 ;
    self.topToolView.frame = CGRectMake(min_x, min_y, min_w, min_h);

**Comment by renzifeng** [comment]
这个是竖屏的控制层UI，哪里需要适配刘海

**Comment by huangfangkai** [comment]
我这问题，我这player竖屏也是从statebar开始的，想改下topToolView的高度发现外面改不行

**Comment by renzifeng** [comment]
你可以fork一份控制层代码，自己维护UI

**Comment by huangfangkai** [comment]
恩，我现在就是这个搞的，谢谢大佬
