### ISSUE TITLE
为什么新版pod下来之后 没有ZFAVPlayerManager文件了？

### ISSUE THREAD

**Issue by zhenguanqing** [renzifeng/ZFPlayer#1368]
创建一个ZFPlayerController需要的currentPlayerManager类，现在要自己自定义生成吗？

**Comment by michaelzhong168** [comment]
pod 'ZFPlayer/AVPlayer', '~> 4.0'
#import <ZFPlayer/ZFAVPlayerManager.h>

**Comment by zj381652512** [comment]
#pod 'ZFPlayer', :path => '../'
    
    
    pod 'ZFPlayer/Core',          '~> 4.1.4'
    pod 'ZFPlayer/ControlView',   '~> 4.1.4'
    pod 'ZFPlayer/AVPlayer',      '~> 4.1.4'
    pod 'ZFPlayer/ijkplayer',     '~> 4.1.4'
