### ISSUE TITLE
边下边播、秒播 KTVHTTPCache  ，遇到一个问题

### ISSUE THREAD

**Issue by KeWangKW** [renzifeng/ZFPlayer#1426]
https://github.com/renzifeng/ZFPlayer/assets/24774145/f44e64fb-506a-439e-af2f-482d8fbb23bd

经常播放不出来，这个情况下播放状态已经变成正在播放了

我个人这边在一秒后判断没有播放进度回调，就去重新执行播放暂时解决
![50e26cadd505f154eff98d1bb9960eee](https://github.com/renzifeng/ZFPlayer/assets/24774145/6364e1af-6a25-445b-8f15-b295ec2eb823)

**Comment by x554960766** [comment]
同样遇到这个问题

**Comment by x554960766** [comment]
换成ijk的播放器 好像解决这个问题了

**Comment by zht415** [comment]
请问解决了吗？

**Comment by x554960766** [comment]
> 请问解决了吗？

avplayer 换成 ijk后没有问题

**Comment by zht415** [comment]
> > 请问解决了吗？
> 
> avplayer 换成 ijk后没有问题

你使用ijk都正常播放吗？我把demo换成ijk播放里出现过一次崩溃

**Comment by zht415** [comment]
> 换成ijk的播放器 好像解决这个问题了

我之前跑demo 换成ijk崩溃过一次 就没使用ijk    使用ijk 你运行demo没有出现过崩溃吗
