### ISSUE TITLE
IOS有控制条隐藏的小问题

### ISSUE THREAD

**Issue by wuxianzhao** [renzifeng/ZFPlayer#144]
我在10.2的系统中运行，视频播放的时候点击视频隐藏进度条，但是马上会自动显示回来，测试了下好像跟视频缓冲有关系，如果视频下载完了，就不会有这个问题，如果视频没下载完，就会有这个问题，请大神帮忙看下有没有这个问题，非常感谢！

**Comment by LiuDeng** [comment]
+10086 一直被这个问题困扰

**Comment by QiuDaniel** [comment]
有相同问题

**Comment by QiuDaniel** [comment]
将ZFPlayerView.m中play方法里的[self.controlView zf_playerCancelAutoFadeOutControlView]和[self.controlView zf_playerShowControlView]注销掉就能解决这个问题，有没有引入其他问题暂时还不知道。

**Comment by xyxdasnjss** [comment]
遇到了同样的问题，用楼上的方法解决

**Comment by renzifeng** [comment]
这个问题解决了呢
