### ISSUE TITLE
在播放直播视频时有ERROR产生

### ISSUE THREAD

**Issue by sidetlw** [renzifeng/ZFPlayer#15]
在播放m3u8直播流时有error产生，http://dlhls.cdn.zhanqi.tv/zqlive/34338_PVMT5.m3u8
如下：
Player[6595:4610568] 15:04:38.163 ERROR:    849: AudioQueue: request to trim 4294708576 + 0 = 4294708576 frames from buffer containing 21504 frames

**Comment by renzifeng** [comment]
对直播功能还没支持，我试了一下这个视频是能播放的。

**Comment by sidetlw** [comment]
avplayer 默认是支持的

**Comment by renzifeng** [comment]
比如滑动快进快退，slider那些我都没处理。

**Comment by sidetlw** [comment]
哦 这没关系 直播时应该直接隐藏 你觉得呢
