### ISSUE TITLE
The stupid UINavigationController+ZFPlayerRotation category make it crashed with recursive call.

### ISSUE THREAD

**Issue by xingheng** [renzifeng/ZFPlayer#150]
The two categories' design is stupid, seriously. Please check the following references to get details.

* http://stackoverflow.com/a/5272612/1677041
* http://stackoverflow.com/a/14259595/1677041

For our case, this issue makes our product crashed when presenting a UIAlertController object, it causes a recursive call between method `shouldAutorotate` and `supportedInterfaceOrientations`. 

YES, the UINavigationController is used in inner UIKit, the category will affect its inner logic of UIKit as the Objective-C language is ***dynamic***.

I didn't dig it into so much, but inheriting and/or KVO(not KVC) on UINavigaionController are the prefer choice.

**Comment by xingheng** [comment]
Resolved with [this](http://stackoverflow.com/a/32010520/1677041).

**Comment by renzifeng** [comment]
thank you ,I will fix this bug
