### ISSUE TITLE
支持切换播放源吗

### ISSUE THREAD

**Issue by wfs498121294** [renzifeng/ZFPlayer#152]
支持切换播放源吗

**Comment by Quanhua-Guan** [comment]
可以这样设置多个分辨率
`playerModel.resolutionDic = @{@"高清" : self.hdVideoURL, @"标清" : self.sdVideoURL};`
可以参考在cell中播放的例子. (非cell播放时有bug, ZFPlayerView.videoArray是空的,   导致切换后播放一个nil的地址.... @renzifeng )
