### ISSUE TITLE
ios8.2使用有个大bug

### ISSUE THREAD

**Issue by kindle1994** [renzifeng/ZFPlayer#153]
在你的demo里你点击cell播放然后全屏，屏幕右边的点击事件是失效的

**Comment by tianpengtao** [comment]
我也发现8.x上有这个问题，正在找原因

**Comment by GWesley** [comment]
搞定了没？ 同志们

**Comment by GWesley** [comment]
不要使用 [[UIApplication sharedApplication] setStatusBarOrientation:orientation animated:NO]; 这个接口 在iOS8上会出问题

**Comment by tianpengtao** [comment]
应该使用哪个呢？

**Comment by kklwg** [comment]
遇到了同样的问题。iOS  8.1.2 全屏后右边屏幕的点击失效 。。求解答

**Comment by xushuduo** [comment]
http://blog.csdn.net/jeffasd/article/details/74930895
使用这个方法解决了🙄
