### ISSUE TITLE
为什么要 ASIHttrequest 做视频下载功能！ 

### ISSUE THREAD

**Issue by TzyTman** [renzifeng/ZFPlayer#158]
ASI 都好多年没有更新了。而且下载的时候还存在一些问题。为什么不使用NSSessionAPI 做下载功能？

**Comment by cooliean** [comment]
我也想问，看到了这个我一下就觉得下了几个档次，一下子号不放心，那个下载。功能就少了一大截了。

**Comment by Mag1cPanda** [comment]
我也想问，如果有时间的话，希望作者可以用NSURLSession改写一下。
