### ISSUE TITLE
关于cell播放中的状态下点击cell进入详情控制器并在详情控制器播放视频的问题

### ISSUE THREAD

**Issue by shanyuqin** [renzifeng/ZFPlayer#159]
想问下zfplayer能不能实现在cell中处于播放状态，然后点击cell进入详情控制器，在详情控制器中也有一个playerview需要播放当前点击的视频，能否通过赋值将cell中的playerView传给详情控制器中playerView，这样就不需要在push到下一个控制器后还需要重新创建一个playerView，类似于今日头条。我尝试了进行赋值，并没有成功，在详情控制器上会存在两个playerView。希望作者有时间可以给些指点。谢谢

**Comment by sushushu** [comment]
我也有同样的需求,请问怎么能做到?
