### ISSUE TITLE
列表视频界面的bug

### ISSUE THREAD

**Issue by jkpang** [renzifeng/ZFPlayer#16]
1.连续点击播放三个视频,会崩溃;
2.点击第一个视频,再点击第二个视频,cell会出现复用的问题;
3.点击一个视频,移动tableView,如果不关闭窗口的缩略视频,点击播放其它视频时,缩略视频会消失,cell也会出现复用问题

**Comment by renzifeng** [comment]
修复了一下，看看还有bug吗

**Comment by jkpang** [comment]
暂时没有了,有的话继续issue你,Good job!

**Comment by renzifeng** [comment]
ok

**Comment by hqwsun** [comment]
你好，我在你的demo中的ZFTableViewController， tableviewcell上面使用，全屏后两个多个手势滑动屏幕然后关闭，再打开会用视频和屏幕都有问题
