### ISSUE TITLE
刚刚开始播放视频时，这时controlView是显示的，但我希望立即将其隐藏。

### ISSUE THREAD

**Issue by milksimple** [renzifeng/ZFPlayer#165]
刚刚开始播放视频时，这时controlView是显示的，但我希望立即将其隐藏。于是我下意识的tap一下屏幕，此时controlView隐藏了，但却立刻又显示回来了。只有等待3秒左右，再去tap屏幕，controllView才会正常隐藏。我觉得问题应该是出在：手动触碰屏幕，没有抵消controlView的自动隐藏动作。

**Comment by Rachel829** [comment]
播放不调用 zf_playerShowControlView  并且 bottomImageView 和topImageView 初始化时设置 alpha=0

**Comment by renzifeng** [comment]
好了，我一会改一下这个问题，好多人提到了。
