### ISSUE TITLE
横屏全屏播放时提示框为竖屏

### ISSUE THREAD

**Issue by UncleShen** [renzifeng/ZFPlayer#167]
横屏全屏播放时，点击下载后崩溃的bug大神已经解了，但点击下载后弹出的提示框为竖屏显示风格

**Comment by TheLittleBoy** [comment]
因为它并是不真正的屏幕旋转，只是修改了PlayerView的transform，还有状态栏方向。

**Comment by wwx1991** [comment]
解决了吗兄弟?我发现全屏状态下调节亮度的弹框扔为竖屏显示风格
