### ISSUE TITLE
is This player Supports RTMP?

### ISSUE THREAD

**Issue by bintu1234** [renzifeng/ZFPlayer#17]
HI I am working with the RTMP i found this Library but is this support the rtmp or not. please help me

**Comment by renzifeng** [comment]
This is based on the AVPlayer, does not support the RTMP, RTMP kxmovie can reference

**Comment by bintu1234** [comment]
@renzifeng  Thank you can you please give me any suggestions for RTMP Player. Because I am struck  here from long time. and Thanks for the Replay

**Comment by renzifeng** [comment]
https://github.com/kolyvan/kxmovie

**Comment by bintu1234** [comment]
@renzifeng  Thanks i will try
