### ISSUE TITLE
播放界面 点击“下一页”旋转屏幕播放器会显示出来

### ISSUE THREAD

**Issue by shengxiaolei** [renzifeng/ZFPlayer#171]
播放界面 点击“下一页”旋转屏幕播放器会显示出来

在播放界面push到另外一个界面如何禁止播放器旋屏

貌似旋屏播放器是加载在window层的所以还是会显示出来

这个问题如何解决呢？

**Comment by liuhy412484577** [comment]
解决了吗？

**Comment by liuhy412484577** [comment]
@shengxiaolei

**Comment by shengxiaolei** [comment]
@liuhy412484577 新版本已经解决了呀

**Comment by shengxiaolei** [comment]
@liuhy412484577 self.playerView.playerPushedOrPresented = YES;
