### ISSUE TITLE
最近收到苹果的警告邮件，说是用到了热更新。如何解决 是不是下载的代码用到了呢？

### ISSUE THREAD

**Issue by EnMingHuang** [renzifeng/ZFPlayer#172]

**Comment by EnMingHuang** [comment]
The code referenced in our initial rejection message includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. The Objective-C methods respondsToSelector: and performSelector: are still supported and allowed. For example, they can be used to check OS compatibilty before using a selector. However, you should only pass selectors to these methods, which are specified at compile time. If you think you are using static selectors, it’s possible a third-party framework you’ve added to your app is not in compliance.

Please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above before submitting the next update for your app for review.

**Comment by ZClee128** [comment]
这个可以把播放时间进度的方法暴露出来用吗

**Comment by renzifeng** [comment]
并没有用的热更新，使用了runtime的一些代码，苹果这是误判啊，具体解决方案请在等等

**Comment by SegmentControl** [comment]
@renzifeng 请问现在runtime这个问题是否会影响应用上架？谢谢~~~

**Comment by DogTwoChen** [comment]
请问这个问题是否解决了
