### ISSUE TITLE
难道就我一个人发现播放的时候上部分有黑影在挡着吗？

### ISSUE THREAD

**Issue by hongzhewudi** [renzifeng/ZFPlayer#175]
![screen shot 2017-03-14 at 4 27 50 pm](https://cloud.githubusercontent.com/assets/9473584/23891861/3dab6ac4-08d3-11e7-902b-ab712b22502e.png)
播放视频的时候上面部分有黑影，这个是怎么回事？

**Comment by Quanhua-Guan** [comment]
#176 这个不是问题.
