### ISSUE TITLE
设置竖屏时偶现crash，需要添加判断，详见代码

### ISSUE THREAD

**Issue by zhichaojianer** [renzifeng/ZFPlayer#177]
/**
 *  player添加到fatherView上
 */
- (void)addPlayerToFatherView:(UIView *)view {
    // 备注：这里应该添加判断，因为view有可能为空，当view为空时[view addSubview:self];会crash
    if (view != nil) {
        [self removeFromSuperview];
        [view addSubview:self];
    }
    
    [self mas_remakeConstraints:^(MASConstraintMaker *make) {
        make.edges.mas_offset(UIEdgeInsetsZero);
    }];
}

**Comment by hongzhewudi** [comment]
请问播放的时候出现的上下阴影可以去掉吗？

**Comment by hongzhewudi** [comment]
![screen shot 2017-03-14 at 4 30 07 pm](https://cloud.githubusercontent.com/assets/9473584/23892616/49f1958a-08d6-11e7-8f0f-2ef9e9895689.png)

**Comment by renzifeng** [comment]
好，谢谢

**Comment by renzifeng** [comment]
@hongzhewudi 可以去掉，那是个imageView
