### ISSUE TITLE
难道只有我一个人有这个强迫症吗？开始播放后，想立刻隐藏controlView，但是刚开始播放后并不能立刻隐藏controlView，这不算bug吗？

### ISSUE THREAD

**Issue by milksimple** [renzifeng/ZFPlayer#179]
难道只有我一个人有这个强迫症吗？开始播放后，想立刻隐藏controlView，但是刚开始播放后并不能立刻隐藏controlView，这不算bug吗？

**Comment by renzifeng** [comment]
这个问题，我稍后改一下

**Comment by milksimple** [comment]
我本来想自己改，但试了半天，没有找到为什么不能立刻隐藏的原因，明明你已经调用了zf_playerCancelAutoFadeOutControlView方法，不明白。

**Comment by QiuDaniel** [comment]
有相同的疑问。。。

**Comment by SegmentControl** [comment]
感觉是zf_playerShowControlView这个方法在开始的时候一直被调用，导致隐藏的view再次被显示出来
