### ISSUE TITLE
关于在cell中获取网络视频的缩略图，比如获取网络视频的第一帧，不知道你还有什么好办法，望指教！

### ISSUE THREAD

**Issue by Brances** [renzifeng/ZFPlayer#186]
#pragma mark - 尝试异步获取视频缩略图
-(void)asynGetViedoThumb:(NSURL *)videoURL cell:(DDFollowMainViewCell *)cell{
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
               AVURLAsset *asset = [[AVURLAsset alloc] initWithURL:videoURL options:nil];
               NSParameterAssert(asset);
               AVAssetImageGenerator *assetImageGenerator =[[AVAssetImageGenerator alloc] initWithAsset:asset];
               assetImageGenerator.appliesPreferredTrackTransform = YES;
               assetImageGenerator.apertureMode = AVAssetImageGeneratorApertureModeEncodedPixels;
        
              CGImageRef thumbnailImageRef = NULL;
              CFTimeInterval thumbnailImageTime = 0.0;
              NSError *thumbnailImageGenerationError = nil;
            thumbnailImageRef = [assetImageGenerator 
       copyCGImageAtTime:CMTimeMake(thumbnailImageTime, 600)actualTime:NULL error:&thumbnailImageGenerationError];
        
          UIImage *thumbnailImage = nil;
        
          if(!thumbnailImageRef){
            NSLog(@"thumbnailImageGenerationError 错误 %@",thumbnailImageGenerationError);
        }
        thumbnailImage = thumbnailImageRef ? [[UIImage alloc]initWithCGImage: thumbnailImageRef] : nil;
        
        //return thumbnailImage;
        dispatch_async(dispatch_get_main_queue(), ^{
            //回调或者说是通知主线程刷新，
            cell.followMediaView.layout.model.videoThumb = thumbnailImage;
            cell.followMediaView.picView.image = cell.followMediaView.layout.model.videoThumb;
        });
        
    });
    
}
这是我搜索的代码，稍微改了一点点。
然后我-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath;数据源方法中每次去判断有无获取到缩略图，然后再去调用上面这个方法，不知道这样有什么弊端没~  望指教。

**Comment by RenSihao** [comment]
哇！居然在这里抓到你！ @Brances 这个问题最简单的办法就是让你们后台返回视频url的同时返回你一张缩略图~~~

**Comment by Brances** [comment]
@RenSihao  哈哈  ，猿粪 ！话说我的博客都没更新了~   后台哥哥比较懒    一般都会说这个app端可以解决~
不过我用这用异步获取缩略图不会卡顿，暂时我就用用这个方法啦，以后发现好办法的再来修改~
