### ISSUE TITLE
Demo里的ZFPlayer和pod版本里的ZFPlayer代码部分差异

### ISSUE THREAD

**Issue by RenSihao** [renzifeng/ZFPlayer#188]
我发现Demo里的ZFPlayer有一些类增加了一些属性和方法，但是pod出来的ZFPlayer就没有，感觉在做定制的时候不太方便

**Comment by whatsbug** [comment]
我也发现了

**Comment by xiaojua** [comment]
对的，我也是pod出来的和Demo的不一样，并且pod出的ZFDownload和Demo  里面的也不一样，少属性
