### ISSUE TITLE
老版本视频播放的时候，慢慢滑动返回的时候视频出现卡顿, 怎么修改不会出现这个问题

### ISSUE THREAD

**Issue by IPOSDai** [renzifeng/ZFPlayer#191]
视频播放的时候，慢慢滑动返回的时候视频出现卡顿，声音还是正常播放，滑动过程中是卡顿的，当我停止滑动的时候，视频一下跳到当前播放的画面。我使用了老版本，新的已经没有这个问题，想在原来的版本上解决滑动返回卡顿，需要增加些什么

**Comment by daishuyi** [comment]
我使用的是老版本的，搞忘了更新。我想问问，如果在原来的版本上解决滑动返回不卡顿主要修改什么地方。能有个指导吗？因为我们在你视频上增加了一些按钮。

**Comment by renzifeng** [comment]
使用 reademe中的ZFNavigationController
