### ISSUE TITLE
不知道为什么播放不了视频，系统是iOS 10.2.1 

### ISSUE THREAD

**Issue by Coolzhou** [renzifeng/ZFPlayer#194]
直接下的Demo在真机上跑的，播放不了 例如  http://wvideo.spriteapp.cn/video/2016/0328/56f8ec01d9bfe_wpd.mp4  然后在模拟器上的话，都是加载失败

**Comment by Quanhua-Guan** [comment]
有可能是不支持http导致的, 相关plist属性 NSAppTransportSecurity

**Comment by Sky0372Lsk** [comment]
http://www.jianshu.com/p/7a62e44c75f7 参考一下吧
