### ISSUE TITLE
ZFDownload里面的ZFFileModel类里少了属性

### ISSUE THREAD

**Issue by xiaojua** [renzifeng/ZFPlayer#195]
pod出ZFDownload里面的ZFFileModel类里少了属性，比如speed

**Comment by KONGFANJI** [comment]
我也遇到这个问题，作者看一下呗

**Comment by zengqingf** [comment]
同样遇到这个问题，伤心啊 @renzifeng 作者看一下吧

**Comment by zengqingf** [comment]
我自己在podfile中这样用的
` pod 'ZFDownload', :git => 'https://github.com/zengqingf/ZFDownload.git', :branch => 'master'`
建议出现此问题的同学可以fork作者的仓库，然后同样的方式使用，目前作者的仓库是1.0.3，但是pod仓库搜出来的最新的还是1.0.2的，更新也无用，猜测可能是1.0.3没有推到pod仓库中
