### ISSUE TITLE
请问如何设置可以保持竖着全屏播放

### ISSUE THREAD

**Issue by ErHu1993** [renzifeng/ZFPlayer#198]
如果视频是竖着拍的,项目要求点击放大查看时为竖着全屏播放,当收到重力感应时才为横着播放,请问这个效果要怎么实现

**Comment by AKin28** [comment]
同求，你实现了吗？

**Comment by PengJuWang** [comment]
这个要求很不合常理




发自网易邮箱大师
在2017年04月11日 18:21，潇潇无边 写道：

如果视频是竖着拍的,项目要求点击放大查看时为竖着全屏播放,当收到重力感应时才为横着播放

**Comment by ErHu1993** [comment]
勉强实现吧  我用swizzing替换了ZFPlayerView 中的 interfaceOrientation: 方法, 把我需要的效果替换成我们需求的了

**Comment by ErHu1993** [comment]
+ (void)load
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [self exchangeInstanceMethod1:NSSelectorFromString(@"interfaceOrientation:") method2:@selector(interfaceOrientationSwizzle:)];
    });
}

//- (instancetype)init {
//    if (self = [super init]) {
//        self.montionManager = [[CMMotionManager alloc] init];
//        [self startUpdateCurrentOrientation];
//    }
//    return self;
//}

/**
 *  屏幕转屏
 *
 *  @param orientation 屏幕方向
 */
- (void)interfaceOrientationSwizzle:(UIInterfaceOrientation)orientation {
    if (self.frame.size.width == self.frame.size.height) {
        [self setOrientationPortraitFullScreenConstraint];
    }else{
        [self interfaceOrientationSwizzle:orientation];
    }
}

- (void)setOrientationPortraitFullScreenConstraint{
    
    [self removeFromSuperview];
    
    ZFBrightnessView *brightnessView = [ZFBrightnessView sharedBrightnessView];
    [[UIApplication sharedApplication].keyWindow insertSubview:self belowSubview:brightnessView];
    [self mas_remakeConstraints:^(MASConstraintMaker *make) {
        make.width.equalTo(@([UIScreen mainScreen].bounds.size.width));
        make.height.equalTo(@([UIScreen mainScreen].bounds.size.height));
        make.center.equalTo([UIApplication sharedApplication].keyWindow);
    }];
    
    // iOS6.0之后,设置状态条的方法能使用的前提是shouldAutorotate为NO,也就是说这个视图控制器内,旋转要关掉;
    // 也就是说在实现这个方法的时候-(BOOL)shouldAutorotate返回值要为NO
    [[UIApplication sharedApplication] setStatusBarOrientation:UIInterfaceOrientationPortrait animated:NO];
    // 获取旋转状态条需要的时间:
    [UIView beginAnimations:nil context:nil];
    [UIView setAnimationDuration:0.3];
    // 更改了状态条的方向,但是设备方向UIInterfaceOrientation还是正方向的,这就要设置给你播放视频的视图的方向设置旋转
    // 给你的播放视频的view视图设置旋转
    self.transform = CGAffineTransformIdentity;
    self.transform = [self getTransformRotationAngle];
    // 开始旋转
    [UIView commitAnimations];
    [[self valueForKey:@"controlView"] layoutIfNeeded];
    [[self valueForKey:@"controlView"] setNeedsLayout];
}

/**
 * 获取变换的旋转角度
 *
 * @return 角度
 */
- (CGAffineTransform)getTransformRotationAngle {
    // 状态条的方向已经设置过,所以这个就是你想要旋转的方向
    UIInterfaceOrientation orientation = [UIApplication sharedApplication].statusBarOrientation;
    // 根据要进行旋转的方向来计算旋转的角度
    if (orientation == UIInterfaceOrientationPortrait) {
        return CGAffineTransformIdentity;
    } else if (orientation == UIInterfaceOrientationLandscapeLeft){
        return CGAffineTransformMakeRotation(-M_PI_2);
    } else if(orientation == UIInterfaceOrientationLandscapeRight){
        return CGAffineTransformMakeRotation(M_PI_2);
    }
    return CGAffineTransformIdentity;
}
