### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by BB9z** [renzifeng/ZFPlayer#20]
项目里打算用 ZFPlayer，我们的场景是进入播放页面不立即播放，在播放页面有多个视频可以任意切换。

调研中目前发现了这些问题：

- [ ] 如果不立即播放，播放器控件的初始状态不合理，比如返回不会显示
- [ ] 控件不能直接用 videoURL 切换
  - [x] 直接切，playerItem 会 KVO 异常，在列表模式下有时也会出现，已提 PR #19 
  - [x] 调用 resetPlayer 会把整个 playerview 从父 view 移除。如果视频非悬浮，任何时候都不应该自己就把自己移除的，已提 PR #21 
- [ ] 只能通过 player 本身的返回才能被正确释放，这个设定不合理，这样不支持导航默认的侧滑返回手势，使用起来也不便

一些问题已经尝试修正了，我会把代码同步到 https://github.com/BB9z/ZFPlayer ，保险的修正会提 PR，这个列表也会随之更新。

其他建议：

- ZFPlayerView 管理了太多 UI 的逻辑了，有些逻辑放到 ZFPlayerControlView 会清晰一些

**Comment by renzifeng** [comment]
谢谢你的pull request，我还在抽取ZFPlayerView代码。
