### ISSUE TITLE
在全屏播放的时候，在横着的角度上，两个手指按照放大网页的手势触摸，会有一定概率（20%），导致播放器错乱布局

### ISSUE THREAD

**Issue by lly4155** [renzifeng/ZFPlayer#200]

**Comment by nnianhou-** [comment]
![wechatimg1](https://cloud.githubusercontent.com/assets/10951126/25844987/ccdc47c2-34de-11e7-9744-23b43a7f7b75.jpeg)
还真可以这样哈

**Comment by MirrorZyb** [comment]
同样的问题
