### ISSUE TITLE
播放器上的所有按钮有延迟

### ISSUE THREAD

**Issue by sayiwen** [renzifeng/ZFPlayer#208]
你好，首先感谢你的作品，非常棒！发现播放器的上的所有按钮都有延迟，返回按钮的延迟比较明显。包括播放按钮，你的demo也是一样，希望你跟其他的播放器比较一下。看看有没有这个事情

**Comment by QiuDaniel** [comment]
@sayiwen 可以尝试在ZFPlayerView的- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch方法中增加
if ([touch.view isKindOfClass:[UIButton class]]) { 
        return NO;
    }
