### ISSUE TITLE
连续播放10几个视频后出现无法继续加载视频的情况

### ISSUE THREAD

**Issue by bird1423** [renzifeng/ZFPlayer#219]
您好：
      具体描述：
             在视频播放详情页，上部分视图播放视频，下部分是视频列表，从视频列表一层一层往下push，到
      10多层的时候，发现视频无法继续播放，提示加载失败，点击重试，点击后也无法继续播放，但是回退
      之前页面还可以继续播放，很奇怪的问题。播放url地址有打印出来，没有问题，我直接可以在网页播
      放，因此排除地址不对的情况，麻烦帮我分析下可能哪里出问题了，谢谢！！！
      PS：（无法上传附件，不然截图给你）

**Comment by zbleftover** [comment]
是不是可能内存的问题，avplayer无法被回收？

**Comment by bird1423** [comment]
每次回退上一页还保存上次播放的状态，然后继续播放，会不会是这个引起的，缓存太多了，我再盘查下，谢谢回复！！！

**Comment by bird1423** [comment]
我通过push的时候resetplayer，pop回来重新播放视频的方式，不会出现这个问题了，还是谢谢你的无私奉献。。。
