### ISSUE TITLE
左上角的backBtn觸摸大小問題

### ISSUE THREAD

**Issue by LazyScream** [renzifeng/ZFPlayer#222]
左者所預設的backBtn非常的小，導致非常的難點擊
有沒有任何方法可以改善？或者協助，我只能跪求了

**Comment by RMKitty** [comment]
返回按钮可以自己设定 （ZFControlView里设定）

**Comment by RMKitty** [comment]
返回按钮可以自己设定 （ZFPlayerControlView里设定）
