### ISSUE TITLE
真机上有error in __connection_block_invoke_2: Connection interrupted警告

### ISSUE THREAD

**Issue by tangguiqiang** [renzifeng/ZFPlayer#226]
真机上有error in __connection_block_invoke_2: Connection interrupted警告，而且视频加载不出来
大家伙有遇到过这个么。直接运行demo都这样，是需要设置什么吗？

**Comment by RMKitty** [comment]
你可以参考[https://stackoverflow.com/questions/30651171/ios-error-in-connection-block-invoke-2-connection-interrupted](url)
