### ISSUE TITLE
怎么在第二次播放的时候在第一次播放的基础之上进行播放

### ISSUE THREAD

**Issue by buqin** [renzifeng/ZFPlayer#233]
1> 在单元格中播放视频的时候,怎么在第二次播放的时候在第一次播放的基础之上进行播放?
2> 从单元格push到对应的视频的详情页的时候,怎么将播放时间同步(比如说这个视频在list流中播放到了3:00,再push到该视频的详情页时,使其从3:00开始播放)

**Comment by RMKitty** [comment]
你可以记录 播放 时间。 ZFPlayer 支持 从xxx 时间开始播放（传入seekTime）seekTime 默认0

**Comment by XuanYuLin** [comment]
记录时间的话，还得重新加载，没那么顺畅。 用单例做就可以，

**Comment by buqin** [comment]
> 记录时间的话，还得重新加载，没那么顺畅。 用单例做就可以，

好的，谢谢

**Comment by shuLeesin** [comment]
> 记录时间的话，还得重新加载，没那么顺畅。 用单例做就可以，

可否把你写的单例 借鉴一下
