### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by caoyunxiao** [renzifeng/ZFPlayer#236]
<img width="347" alt="2017-06-19 16 53 07" src="https://user-images.githubusercontent.com/15682437/27277127-d1081f50-550f-11e7-88e3-6ce141505e3b.png">
Pod导入后编译报以上错误

**Comment by CoderJackie** [comment]
而且无法点击查看详细错误信息

**Comment by CoderJackie** [comment]
原来是项目里面集成了WSProgress，导致MMMaterialDesignSpinner重复导入了

**Comment by caoyunxiao** [comment]
哦，这样啊

**Comment by CoderJackie** [comment]
你项目里面没有集成MMMaterialDesignSpinner？右键点击错误信息，然后选择reveal in log,看一下详细信息
