### ISSUE TITLE
请问视频的缓冲和下载是分开的吗？

### ISSUE THREAD

**Issue by ghysrc** [renzifeng/ZFPlayer#24]
最近需要播放视频的功能，这个确实挺好用。
我有个疑问，我不太懂视频这方面的东西，所以可能是我想的太简单了。
我以为视频缓冲好的时候代表视频也就下载好了，比如当 ZFPlayer 的进度条已经到底时，是否就可以直接把这个视频保存到我的相册里呢？
一个已经缓冲好的视频，再进行播放，确实就不需要再进行网络请求。所以有没有办法可以把视频的缓存直接转换成视频文件，保存到相册里。
我用的一个软件有这样的功能，我不懂这方面的，所以不确定是如何做到的。

**Comment by renzifeng** [comment]
缓冲和下载是两回事，我提供了下载的功能，就是类似于各大视频软件那个下载，没网状态也可以点击观看。

**Comment by ghysrc** [comment]
@renzifeng 不好意思，应该是我想错了，也是受我手机里一个软件的影响。它播放视频时有一个下载按钮，如果我点下载的时候，视频没有缓冲完，它就会叫我等一会儿；如果已经缓冲完，就直接保存到相册而没有单独再下载。
我不太了解这方面的知识，所以不知道视频的缓存跟下载的文件本身有怎样的关系，只是感觉这种方式挺好用，缓冲好的视频直接可以保存。
谢谢你的回复，ZFPlayer挺好用。其他的功能得靠自己去研究了。

**Comment by renzifeng** [comment]
谢谢你的支持，更多功能还在添加中，敬请期待！
