### ISSUE TITLE
你好，我测试您的播放器，发现播放不了我的url

### ISSUE THREAD

**Issue by s-l-zhang** [renzifeng/ZFPlayer#241]
你好，我测试您的播放器，发现播放不了我的url，提示加载失败，但是可以用chrome浏览器播放。
url：
http://i.immu.edu.cn/smilecampus_immu/upload//2017/06/30/5955fc38b9ad8.mp4

**Comment by Sky0372Lsk** [comment]
http://www.jianshu.com/p/7a62e44c75f7 参考一下吧
