### ISSUE TITLE
怎么监测播放进度呢？

### ISSUE THREAD

**Issue by yubin2010rain** [renzifeng/ZFPlayer#246]
想请问怎么可以把视频播放时间放出来？麻烦给点建议。

**Comment by guyuliunian** [comment]
/**
 * 正常播放
 
 * @param currentTime 当前播放时长
 * @param totalTime   视频总时长
 * @param value       slider的value(0.0~1.0)
 */
- (void)zf_playerCurrentTime:(NSInteger)currentTime totalTime:(NSInteger)totalTime sliderValue:(CGFloat)value {}

**Comment by guyuliunian** [comment]
这个方法里面有提供

**Comment by imTango** [comment]
这是获取播放进度吗  ？？？？？

**Comment by sushushu** [comment]
@guyuliunian   这个方面在.m里面的,我把它弄到.h 好像也没响应.

**Comment by guyuliunian** [comment]
你自己写个回调，从这个方法回调出来，在你用到播放器的地方实现这个回调就好了

**Comment by Bofearless** [comment]
@guyuliunian 你这种方式只能改动原作者源码来操作，原则上是不应该去动作者源代码的。

**Comment by guyuliunian** [comment]
不改动源代码的我还没试过，我用的时候改动源码较多
