### ISSUE TITLE
你好 这个问题很棘手  希望您能帮助看看

### ISSUE THREAD

**Issue by 18667366881** [renzifeng/ZFPlayer#253]
2017-07-30 01:56:25.170 video[52899:1272495] *** Assertion failure in -[UITableView dequeueReusableCellWithIdentifier:forIndexPath:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.7.47/UITableView.m:6730
2017-07-30 01:56:25.247 video[52899:1272495] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier playerCell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110505b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010fbfa141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110509cf2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010ee533b6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x0000000110e92af5 -[UITableView dequeueReusableCellWithIdentifier:forIndexPath:] + 241
	5   video                               0x000000010dc9e5cc -[ViewController tableView:cellForRowAtIndexPath:] + 108
	6   UIKit                               0x000000011117fa48 -[_UIFilteredDataSource tableView:cellForRowAtIndexPath:] + 98
	7   UIKit                               0x0000000110ea5762 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 750
	8   UIKit                               0x0000000110ea59a8 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 74
	9   UIKit                               0x0000000110e7a2e9 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2845
	10  UIKit                               0x0000000110eae97c -[UITableView _performWithCachedTraitCollection:] + 111
	11  UIKit                               0x0000000110e95b2a -[UITableView layoutSubviews] + 233
	12  UIKit                               0x0000000110dfc20b -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1268
	13  QuartzCore                          0x0000000110ae7904 -[CALayer layoutSublayers] + 146
	14  QuartzCore                          0x0000000110adb526 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 370
	15  QuartzCore                          0x0000000110adb3a0 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	16  QuartzCore                          0x0000000110a6ae92 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 294
	17  QuartzCore                          0x0000000110a97130 _ZN2CA11Transaction6commitEv + 468
	18  QuartzCore                          0x0000000110a97b37 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 115
	19  CoreFoundation                      0x00000001104ab717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	20  CoreFoundation                      0x00000001104ab687 __CFRunLoopDoObservers + 391
	21  CoreFoundation                      0x0000000110490038 CFRunLoopRunSpecific + 440
	22  UIKit                               0x0000000110d3302f -[UIApplication _run] + 468
	23  UIKit                               0x0000000110d390d4 UIApplicationMain + 159
	24  video                               0x000000010dcc56cf main + 111
	25  libdyld.dylib                       0x00000001130f965d start + 1
	26  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by QiuDaniel** [comment]
unable to dequeue a cell with identifier playerCell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard.错误提示已经很明显了。请检查nib或sb中的identifier设置

**Comment by 18667366881** [comment]
谢谢
