### ISSUE TITLE
真机播放不了

### ISSUE THREAD

**Issue by PLwales** [renzifeng/ZFPlayer#255]
在模拟器上可以播放， 在真机上 所有视频都播放不了，demo里面的视频也不行？   没有报错，可以加载，可以快进   就是画面不动。  下载成功后， 本地也不能播放了
 有人遇到过么

**Comment by 18667366881** [comment]
小朋友  网络权限设置了吗？

**Comment by PLwales** [comment]
网络权限没设置  可以下载么？ 用demo里的下载功能下载了本地 也播放不了的
 plist里面设置了， 不设置 模拟器能播放？

**Comment by 18667366881** [comment]
没问题呀 我这边的demo 全部都可以播放 包含 全屏 旋转    亮度调整 等  机型还是  4s

**Comment by PLwales** [comment]
我用的还是6， 加个QQ 聊下呗  271650409

**Comment by PLwales** [comment]
我换了一台6   iOS 9的    跑起来可以播放，还借了其他同事的手机  都可以
 就我自己用的这个这个6 iOS 10.1 不可以
