### ISSUE TITLE
iOS 11 - Cannot play video in background mode.

### ISSUE THREAD

**Issue by kiwi07** [renzifeng/ZFPlayer#256]
Please help me fix this.

**Comment by mzeeshanid** [comment]
In AppDelegate I do something like this for background video playback.

    func applicationDidEnterBackground(_ application: UIApplication) {        
        let playerManager = PlayerViewController.shared.playerManager
        if let playerLayer = playerManager.view.layer as? AVPlayerLayer {
            playerLayer.player = nil
            
            debugPrint("playerLayer's player is now nil")
        }
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
        
        let playerManager = PlayerViewController.shared.playerManager
        if let playerLayer = playerManager.view.layer as? AVPlayerLayer, let player = playerManager.value(forKey: "player") as? AVPlayer {
            playerLayer.player = player
            
            debugPrint("playerLayer's player restored")
        }
    }
