### ISSUE TITLE
在B页面加了播放器，在点击播放器的返回按钮返回A页面时如果同时横手机，播放器会跳出来，并没有销毁

### ISSUE THREAD

**Issue by double-Dou** [renzifeng/ZFPlayer#260]
在B页面加了播放器，在点击播放器的返回按钮返回A页面时如果同时横手机，播放器会跳出来，并没有销毁，尝试很多方法销毁，问题仍然存在

**Comment by pusswzy** [comment]
我也是 一直都有这个bug  不知道为什么没有销毁

**Comment by ghyzx** [comment]
我也出现了这个问题，调试发现：如果是用手势返回退出播放页面，播放还在继续（有声音，没界面），如果这时手机横屏，播放的声音、界面就都出来了。
希望能早日解决这个bug。

**Comment by ghyzx** [comment]
补充：之前用Xcode 8编译、打包的App没出现这个问题，最近的版本用的Xcode 9，就有这个问题了， 不知和Xcode 9有没有关系。

**Comment by theHeroisBack** [comment]
你解决了吗 我这里也是

**Comment by tinoras** [comment]
留给后来者，在player的代理方法，加入reset 解决，横屏和返回仍有声音的情况
- (void)zf_playerBackAction {
    [self.playerView resetPlayer];
    [self.navigationController popViewControllerAnimated:YES];
}

**Comment by tinoras** [comment]
留给后来者，在player的代理方法，加入reset 解决，横屏和返回仍有声音的情况
- (void)zf_playerBackAction {
    [self.playerView resetPlayer];
    [self.navigationController popViewControllerAnimated:YES];
}
