### ISSUE TITLE
ZFDownloadManager 审核被拒

### ISSUE THREAD

**Issue by liangzcn** [renzifeng/ZFPlayer#263]
Regarding this issue, your downloading feature is at the coding level.

It would be appropriate to complete remove codes such as ZFDownloadManager and others which related to downloading feature.

拒绝的理由是5.2.3 Your app still allows users to save or download music, video, or other media content without authorization from the relevant third-party sources. 但是我APP的视频都是公司所有，不存在什么第三方资源，问他们为什么拒就说了上面这条。

**Comment by Recky-Lin** [comment]
提供书面版权声明的影印版本给review team

**Comment by liangzcn** [comment]
We allow apps to download when the resource is owned by your app vendor. However, it is not allowed to hide the download code in the binary.

To solve this issue, please either enable the download feature only for ownership videos, or complete remove this feature from the coding level.

以上是Apple最后的回复，最后还是删了相关下载代码重新提交了。
