### ISSUE TITLE
视频播放被拉伸了，请问有解决办法吗？

### ISSUE THREAD

**Issue by qq954499615** [renzifeng/ZFPlayer#266]
![img_6385](https://user-images.githubusercontent.com/9332292/29394173-3ea3959a-833b-11e7-95de-a2f2041619c2.PNG)
![img_6386](https://user-images.githubusercontent.com/9332292/29394174-3edd5c8a-833b-11e7-8284-3d5b6048df02.PNG)

**Comment by iOSleep** [comment]
尝试修改默认的拉伸方式playerLayerGravity
