### ISSUE TITLE
cell跳屏问题

### ISSUE THREAD

**Issue by CDYeah** [renzifeng/ZFPlayer#27]
UITableView中我自定义了两种cell，都能播放视频，点击播放会出现向上跳屏，有时候自动跳，概率事件

**Comment by renzifeng** [comment]
你是用的哪个版本的呢，前几个版本我就修复了这个问题。现在点击播放不跳屏，点击全屏在返回成小屏，会cell会转到屏幕中间。

**Comment by CDYeah** [comment]
是的，是我用的版本太低了，问题已解决，项目不错，感谢分享，已点赞

**Comment by hqwsun** [comment]
使用的是最新版本的，你的demo还是出现问题，uitableviewcell随便滑动后自动变成小屏而且UI变的混乱
