### ISSUE TITLE
BUG 修改   

### ISSUE THREAD

**Issue by XU515835632** [renzifeng/ZFPlayer#273]
在 ZFPlaverView.m  文件 705行左右
            ZFBrightnessView *brightnessView = [ZFBrightnessView sharedBrightnessView];
           [[UIApplication sharedApplication].keyWindow insertSubview:self belowSubview:brightnessView];
调用这个方法的时候可能导致图层混乱。 播放器的图层会加到 uiwindow的最底层。
建议修改成 [[UIApplication sharedApplication].keyWindow addSubview:self];
加到视图的最上面。

**Comment by renzifeng** [comment]
好的
