### ISSUE TITLE
退出全屏Cell布局错误

### ISSUE THREAD

**Issue by FSAnonymous** [renzifeng/ZFPlayer#276]
你好. ZFPlayer  发现两个bug , 当全平时, 按住屏幕 然后点击返回按钮, 或者是同时按屏幕和返回按钮, 都是两个手指操作, 要多试几次, 然后你会发现, 再单独点击 返回按钮 没有反应, 要多点好几下 退出全屏, 退出全屏后, cell 布局为横屏布局了, cell整体放大, 播放器模式变为小窗口(我没设置这个 就出现了小窗口) , 然后列表自动到顶部, log里面报了约束错误, 不知道哪里的错误,  然后你的demo里面  也有这个,不过  , 除了这个之外,你的demo,也是这种操作, 退出全屏后 会再屏幕中间 显示一个竖向的小窗口播放器, 然后滑动cell  被重用到其他cell上面, 总之会错乱

**Comment by hqwsun** [comment]
我也发现这种问题，有没有解决办法
