### ISSUE TITLE
cell跳屏问题

### ISSUE THREAD

**Issue by CDYeah** [renzifeng/ZFPlayer#28]
UITableView中我自定义了两种cell，都能播放视频，点击播放会出现向上跳屏，有时候自动跳，概率事件
cell是动态计算高度，现在用的是UITableView+FDTemplateLayoutCell计算cell高度

**Comment by renzifeng** [comment]
可能是你计算动态计算高度的问题，playerView是加到那个imageView上的，理论上不会跳动的。
