### ISSUE TITLE
导航栏和状态栏重合了

### ISSUE THREAD

**Issue by CherishSmile** [renzifeng/ZFPlayer#281]
重新步骤：点击视屏播放，进入全屏模式，让控制栏消失后（即状态栏消失后），切换到后台，再进入前台，返回为小屏，导航栏和状态栏重合了。百分百重现，望解决。

**Comment by lilin87788** [comment]
我也遇到了

**Comment by Qjune** [comment]
重新步骤：点击视屏播放，进入全屏模式，让控制栏消失后（即状态栏消失后），切换到后台，再进入前台，返回为小屏，导航栏和状态栏重合了。百分百重现，望解决。

真机下百分百重现

**Comment by lilin87788** [comment]
我目前的解决方案：
1、工程配置里面设置设备的方向只能是potrait
2、作者demo里面的是用的push，我改成present 一个新的nav + 播放器VC
解决导航栏和状态栏重合的问题，但是带来一些副作用，不是最佳解决方案，如果产品对屏幕旋转没有什么需求，这个方案可行

**Comment by webMing** [comment]
你们的问题解决了吗？ @CherishSmile  @lilin87788 @Qjune @BB9z @  目前也遇到这个问题.

**Comment by BB9z** [comment]
at 我也没用，现在的实现有点失控。如果只需很少的功能的话，可以试试[我的分支](https://github.com/BB9z/ZFPlayer)。

**Comment by lilin87788** [comment]
> 你们的问题解决了吗？ @CherishSmile @lilin87788 @Qjune @BB9z @ 目前也遇到这个问题.

没有解决 哎好尴尬啊 希望作者 能帮我一把

**Comment by webMing** [comment]
> > 你们的问题解决了吗？ @CherishSmile @lilin87788 @Qjune @BB9z @ 目前也遇到这个问题.
> 
> 没有解决 哎好尴尬啊 希望作者 能帮我一把

还没有解决. 作者有解决打算. 我也提了一个bug 标题是 布局混乱....

**Comment by renzifeng** [comment]
https://blog.csdn.net/Bloody_Leaves/article/details/76572313 亲测有效，果断关闭啦
