### ISSUE TITLE
视频播放-(void)play方法无效问题。求解答，

### ISSUE THREAD

**Issue by lizhen01** [renzifeng/ZFPlayer#286]
视频界面设置为默认禁止自动播放，自己写一个播放按钮，去调用play方法无效，但是调用pause方法则有效，请问，是我哪里设置出问题了吗？
![image](https://user-images.githubusercontent.com/14814927/30470326-da652262-9a26-11e7-8433-a6983a9a0afa.png)

**Comment by iOSleep** [comment]
使用autoplaye

**Comment by lizhen01** [comment]
好的，我试一下。
