### ISSUE TITLE
作者能否用“VIMediaCache”这个方案加入视频边下边播？

### ISSUE THREAD

**Issue by ruichou** [renzifeng/ZFPlayer#290]
如果支持边下边播，ZFPlayer可以说是目前最完美的播放器了！

另外问一下，在tableview播放视频的时候，前3秒左右是卡住不动的这是为什么？

**Comment by iOSleep** [comment]
边下边播对m3u8不支持, 估计是跟这个有关系所以没有加入.
可以使用GCDWebserver, 来处理缓存存储的问题.

**Comment by renzifeng** [comment]
有什么好的方案吗，这个我也很想加的

**Comment by applejian** [comment]
像我这种有洁癖的人 为了想实现边下边播 又不想去改pod的源码 那只能runtime 方式 注入支持的缓存类和方法 附上能支持缓存的几个类和扩展 不用修改zfplayer 本身，zfplayer 在ios11上不能正常播放，作者看下是不是哪里的问题
[ZFPlayer边下边播.zip](https://github.com/renzifeng/ZFPlayer/files/1314248/ZFPlayer.zip)

**Comment by ruichou** [comment]
老铁，玩的6啊。目前测试了一下感觉还不错。

**Comment by renzifeng** [comment]
给力 我参考着更新一下 @applejian

**Comment by LiberalChen** [comment]
@renzifeng 等你更新呢哈，把这个功能加上吧

**Comment by ilpanda** [comment]
@applejian  你好,你是否遇到过这样的问题, 例如 : 加载本地缓存,加载到一半,暂停,播放,暂停,播放...
这样重复操作,之后视频无法播放..

**Comment by yanashenyang** [comment]
我接手公司的项目就是用的这个库，感觉这个库问题很多，有更好的封装播放器推荐吗

**Comment by qxc122** [comment]
> 像我这种有洁癖的人 为了想实现边下边播 又不想去改pod的源码 那只能runtime 方式 注入支持的缓存类和方法 附上能支持缓存的几个类和扩展 不用修改zfplayer 本身，zfplayer 在ios11上不能正常播放，作者看下是不是哪里的问题
> [ZFPlayer边下边播.zip](https://github.com/renzifeng/ZFPlayer/files/1314248/ZFPlayer.zip)

为什么我下载了你的文件，报错，说好几个文件没有
