### ISSUE TITLE
ZFPlayer边下边播 通过扩展方式实现 不用修改ZFPlayer本身代码

### ISSUE THREAD

**Issue by applejian** [renzifeng/ZFPlayer#291]
[ZFPlayer边下边播.zip](https://github.com/renzifeng/ZFPlayer/files/1393340/ZFPlayer.zip)
把这个解压了 然后拖到工程中 编译运行
找个视频播放下，播放完之后，再断网找到那条视频再播放试试看

**Comment by LiberalChen** [comment]
楼主写个使用说明啊

**Comment by applejian** [comment]
[ZFPlayer.zip](https://github.com/renzifeng/ZFPlayer/files/1393338/ZFPlayer.zip)
把这个解压了 然后拖到工程中 编译
找个视频播放下，播放完之后，再断网找到那条视频再播放试试看

**Comment by LiberalChen** [comment]
好的，谢喽
