### ISSUE TITLE
Xcode9,iOS11 bug

### ISSUE THREAD

**Issue by ChildrenGreens** [renzifeng/ZFPlayer#294]
播放器显示：“加载失败，点击重试”
错误日志：
CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;
}
初次进入，无法播放。

**Comment by stickor** [comment]
今天我也遇到了这个, 你解决了么?

**Comment by nutcn** [comment]
播放h265视频的时候遇到这个问题
[AVURLAsset URLAssetWithURL:_playUrl options:avplayerHeader];

**Comment by tunnyios** [comment]
在使用AVPlayerItem的时候也出现这个bug，导致播放视频流m3u8的时候，很多次不成功。status 回调不执行。现在有解决方法吗？跪求

**Comment by BaiHaoYang** [comment]
哇 原来这么多人遇到  我是挂了VPN之后播放 youtube视频 就出现了这个问题 现在解决了吗？

**Comment by crossPQW** [comment]
关注中，遇到同样的问题。

**Comment by xzpCoder** [comment]
最主要的是页面还卡顿...

**Comment by huangrun** [comment]
遇到同样问题，有人解决吗

**Comment by TongFangyuan** [comment]
有人解决吗，遇到同样问题

**Comment by rockerkekex** [comment]
同遇到了这个问题 可以播放 但是滑动特别卡

**Comment by LYongLiang** [comment]
+1有人解决了吗？ 第一次播放失败
