### ISSUE TITLE
Xcode7.3 在工程中添加Exception Breakpoint，总是无法编译通过

### ISSUE THREAD

**Issue by MrZhuGe** [renzifeng/ZFPlayer#30]
我已经尝试查找原因，才疏学浅，还是无法定位到问题所在，有空看下哟，项目确实很好，这个问题解决了，我就准备用到项目中了

**Comment by renzifeng** [comment]
Add your exception breakpoint and edit the exception type from "All" to "Objective-C exceptions"
Some classes in AVPlayer throw regular C++ exceptions. You can filter them off this way.

**Comment by MrZhuGe** [comment]
Thank you very much.
