### ISSUE TITLE
视频url包含文字加载失败

### ISSUE THREAD

**Issue by MingLeiVV** [renzifeng/ZFPlayer#300]
作者你好，近期出现了url中带文字一直加载不播放的问题，不知其他使用者是否出现此问题，不知是否是解析出错，烦请作者麻烦追一下问题

**Comment by Smiacter** [comment]
包含中文的时候会播放不出来，把视频播放地址urlEncode一下就行，Swift代码如下：
(注：我是直接String extension，要抽成函数，你把参数加上就行)
`func urlEncoded() -> String {
        let encodeUrlString = self.addingPercentEncoding(withAllowedCharacters:
            .urlQueryAllowed)
        return encodeUrlString ?? ""
    }`
