### ISSUE TITLE
iphoneX全屏适配

### ISSUE THREAD

**Issue by GitZhouQi** [renzifeng/ZFPlayer#304]

**Comment by smallmx** [comment]
iPhoneX全屏模式下，锁定🔒按钮会被刘海遮住一半。。。苹果审核会被拒吗？

**Comment by iOSleep** [comment]
+1

**Comment by iOSleep** [comment]
看了下源码，初步方案应该是在ZFPlayerView中加入一层contaninerView, 在切换全屏小屏的时候修改contaninerView相对playerView的inset值。。这应该是最简单的方式了

**Comment by crossPQW** [comment]
@iOSleep 简单的修改 controlView 的inset 值四周会有白边，因为 controlView 上部分跟下部分各有一个黑色渐变的背景铺满。所以这个问题其实是比较麻烦的，需要自己修改 controlView 内部所有控件的约束.....所以这块其实还是作者源码做一下兼容

**Comment by tom8507** [comment]
+!

**Comment by lizhen01** [comment]
@iOSleep @crossPQW iPhone X的适配解决了吗? 我也遇到这个问题了.告知一下方案呗
