### ISSUE TITLE
ipad横屏启动时，切换横竖屏布局错误

### ISSUE THREAD

**Issue by fengyesha** [renzifeng/ZFPlayer#307]
![live](https://user-images.githubusercontent.com/15646424/31760041-f25a12ae-b4e5-11e7-8602-74d6fee6c37f.gif)

**Comment by JunsW** [comment]
请问最后怎么解决的？

**Comment by jiazufei** [comment]
我也遇到类似的问题
![222](https://user-images.githubusercontent.com/3351691/45614182-38c60980-ba9b-11e8-9b58-a558c220a2f7.gif)

**Comment by jiazufei** [comment]
我也有类似的情况
