### ISSUE TITLE
关于iPad横屏适配的问题

### ISSUE THREAD

**Issue by guyuliunian** [renzifeng/ZFPlayer#310]
之前提到过关于iPad横屏播放适配问题，在iOS9以上系统没问题，在iOS8系统上可以复现，所以我的猜测是和系统适配有关，具体操作如下：
首先我的项目默认是竖屏显示，只有在播放视屏并且手动切换到横屏模式下才会横屏。在iOS8系统的iPad上，我横屏的时候启动app，进入到视频播放页面，播放视频，然后点击全屏按钮，就会出现我之前提到过的问题，这个应该是系统的问题，不知道作者有没有对iOS8着重进行过适配？
这个问题比较坑爹，用户不升级手机系统，一堆抱怨丢过来，也是无奈啊，还请作者能就这个问题尽快解决，我自己也会尝试看看适配问题，多谢了

**Comment by renzifeng** [comment]
好的 我会尽快

**Comment by guyuliunian** [comment]
这个问题已经解决了，我是将库中UIViewController的分类，shouldAutorotate返回值设置为YES，就可以了，如果不设置的话，我横屏启动项目布局会出现错乱问题

**Comment by Liyongcong** [comment]
> 这个问题已经解决了，我是将库中UIViewController的分类，shouldAutorotate返回值设置为YES，就可以了，如果不设置的话，我横屏启动项目布局会出现错乱问题

你好，我现在遇到的问题是，iPad上，默认是横屏，点击全屏按钮后，还想展示横屏播放怎么控制，现在的问题是，iPad默认横屏，点击全局播放按钮后，就成竖屏播放了

**Comment by weilLove** [comment]
这个要艾特作者去适配iPad了，你看下点击全屏后，源码里面的屏幕控制方面的代码，是不是参数变成了竖屏啥的
