### ISSUE TITLE
想要一进入播放界面就横屏播放？

### ISSUE THREAD

**Issue by guyuliunian** [renzifeng/ZFPlayer#321]
现在是进去之后是先竖屏播放，然后点击全屏按钮才能全屏播放，楼主可以让一进去就自动全屏播放吗？这个需求点应该不少的，这里是否可以把库给完善一下呢？我进入库中修改了一些东西才能实现这个需求，不过感觉可塑性不好，害怕引发别的问题，这里楼主能否提供出来一个属性设置呢？

**Comment by guyuliunian** [comment]
这个问题已解决，直接在点击播放的时候调用
    if ([self.playerView respondsToSelector:@selector(_fullScreenAction)]) {//这个可以使得进入播放器就横屏播放
        [self.playerView performSelector:@selector(_fullScreenAction)];
    }
就可以了

**Comment by renzifeng** [comment]
我加个方法吧
