### ISSUE TITLE
是否提供全屏播放的时候，也是竖屏播放的接口呢？

### ISSUE THREAD

**Issue by erduoniba** [renzifeng/ZFPlayer#324]
是这样的，我这边有这样的需求，就是在播放视频时，点击全屏播放的按钮，需要依然是竖屏播放。我相信这样的需求也是比较常见的，比如微信朋友圈的小视频播放的效果。
功能我已经实现了，看是否能麻烦你支持一下呢？

**Comment by erduoniba** [comment]
只是在ZFPlayerView.h中添加了一个新的属性：
/** 是否强制竖屏播放，默认为NO */
@property (nonatomic, assign) BOOL     forcePortrait;

设置这个forcePortrait=YES的时候全屏播放就是竖屏了。

效果图如下：

![效果](http://7xqhx8.com1.z0.glb.clouddn.com/ZFPlayer.gif)

**Comment by guyuliunian** [comment]
我如果想要强制横屏呢？就是一播放就是横屏，这个怎么实现呢

**Comment by erduoniba** [comment]
@guyuliunian 你这个好处理，在点击播放的那个方法中，添加如下代码就好：
 if ([self.playerView respondsToSelector:@selector(_fullScreenAction)]) {
            [self.playerView performSelector:@selector(_fullScreenAction)];
}

**Comment by yjjwxy2** [comment]
@erduoniba    兄弟   能把你实现的代码发我看看吗  全屏的时候画面竖直

**Comment by erduoniba** [comment]
@yjjwxy2 https://github.com/erduoniba/ZFPlayer

**Comment by yjjwxy2** [comment]
能不能根据视频的尺寸动态控制，比如我竖着拍的视频，横屏就还是竖着的


| |
姚佳俊
iOS工程师
|
|
13777895961
邮箱：yjjwxy2@163.com
|

签名由 网易邮箱大师 定制

在2017年12月25日 13:28，紫枫 写道：

Closed #324.
