### ISSUE TITLE
全屏之后再回来没有播放界面了

### ISSUE THREAD

**Issue by zengqingf** [renzifeng/ZFPlayer#327]
viewController上放上playerFatherView 
[self presentViewController:viewController animated:YES completion:nil];
播放页面正常；
这时候我点击全屏按钮，这时候播放器界面就没了，从视图层级上看，播放器好像跑到viewController后面了

**Comment by guyuliunian** [comment]
这个应该是present的关系，你试试push估计就没这个问题，在全屏切换这块，present和push之间差别还是很大的
