### ISSUE TITLE
大神在播放本地视频的时候遇到个问题

### ISSUE THREAD

**Issue by pengghong** [renzifeng/ZFPlayer#329]
网络视频可以播放，但是本地视频总是加载失败，我试了几个本地视频都不行，但是url是能读出来的。大家有没有遇到这个问题啊，卡死在这里了。一下是部分代码。
-(ZFPlayerModel *)playerModel
{
    if (!_playerModel) {
        _playerModel = [[ZFPlayerModel alloc]init];
        _playerModel.title = @"演唱会";
        NSURL *url = [NSURL URLWithString:self.dataSource[arc4random()%self.dataSource.count]];
        NSString *locaPath = [[NSBundle mainBundle] pathForResource:@"hs_testVideo" ofType:@"mp4"];
        //http://v1.mukewang.com/a45016f4-08d6-4277-abe6-bcfd5244c201/L.mp4
//        url = [NSURL URLWithString:@"http://test.miaocaiwang.com/app/rm.mp4"];
        
        url = [NSURL URLWithString:locaPath];
        _playerModel.videoURL = url;
        _playerModel.placeholderImage = [UIImage imageNamed:@"loading_bgView1"];
        _playerModel.fatherView = self.playerFatherView;
    }
    return _playerModel;
}

**Comment by guyuliunian** [comment]
URL生成方式不对，应该用[NSURL fileURLWithPath:videoPath]这个方法，URLWithString是网络地址
