### ISSUE TITLE
播放界面  push 到 下一页面 旋转屏幕播放器会显示出来

### ISSUE THREAD

**Issue by liuhy412484577** [renzifeng/ZFPlayer#334]
请问作者怎么解决？

**Comment by tinoras** [comment]
暴力解决
- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    // push出下一级页面时候暂停
    if (self.playerView && !self.playerView.isPauseByUser)
    {
        self.isPlaying = YES;
# //这行注视打开
        [self.playerView pause];
        self.playerView.playerPushedOrPresented = YES;
    }
}

**Comment by risechen** [comment]
只要打开过视频，只要一横屏就出现了，这个问题我也遇到过了
