### ISSUE TITLE
全屏状态下resetToPlayNewVideo，UI出现混乱

### ISSUE THREAD

**Issue by theHeroisBack** [renzifeng/ZFPlayer#341]
全屏状态下我播放下一个视频的时候使用resetToPlayNewVideo方法，但是播放界面退出了全屏状态，但是手机其实还是横屏的状态
![img_2659](https://user-images.githubusercontent.com/30762999/34203848-771f2bb2-e5b7-11e7-8d0f-61185f457685.PNG)

**Comment by tom8507** [comment]
我也是UI乱了，加载新视频的时候，你解决了吗。

**Comment by theHeroisBack** [comment]
我目前的解决办法是，全屏状态下播放新视频的时候，先把全屏转成竖屏，然后resetToPlayNewVideo,然后再转成横屏，代码如下

    BOOL backToFull = NO;
    if (self.playerView.isFullScreen) {
        [self.playerView _fullScreenAction];
        backToFull = YES;
    }
    
    [self.playerView resetToPlayNewVideo:self.NewplayerModel];
    
    if (backToFull) {
        [self.playerView _fullScreenAction];
    }
