### ISSUE TITLE
在1M 网速下，下载速度120K/s 开始播放时 无法播放。。。

### ISSUE THREAD

**Issue by tinoras** [renzifeng/ZFPlayer#342]
KVO方法中

else if ([keyPath isEqualToString:@"playbackBufferEmpty"]) {
            
            // 当缓冲是空的时候    
            if (self.playerItem.playbackBufferEmpty) {
                self.state = ZFPlayerStateBuffering;
                [self bufferingSomeSecond];
            }
            
        } else if ([keyPath isEqualToString:@"playbackLikelyToKeepUp"]) {

 在限网速100K左右的情况下，点击进入页面直接自动播放时，
 if (self.playerItem.playbackBufferEmpty)
该判断中self.playerItem一直是nil，只是注释掉此判断后，发现在缓冲为空时，self.player.currentItem.status == AVPlayerItemStatusReadyToPlay，播放不了。然后过几秒后能明显看到缓冲条已经缓冲了一段距离了，接着走[self bufferingSomeSecond]; 却播放不了。不明白为什么。求大神解答。

**Comment by BigShow1949** [comment]
我才应该是 playbackLikelyToKeepUp 的问题

**Comment by BigShow1949** [comment]
会有这种情况，加载状态返回（8:缓冲状态），然后返回4（缓冲基本完成），视频播放了，但是没有返回2（播放状态）
