### ISSUE TITLE
问一个问题

### ISSUE THREAD

**Issue by hupfei** [renzifeng/ZFPlayer#344]
请问像今日头条那样在列表播放某一视频，点击cell进入详情页面，视频还会接着播放，并没有创建新的视频，要如何实现？

**Comment by renzifeng** [comment]
做成单例就行

**Comment by hupfei** [comment]
一般很少把view做成单例的吧

**Comment by hupfei** [comment]
view做成单例貌似不太好吧？会不会造成内存泄漏？并没有那么简单，求解
