### ISSUE TITLE
播放时内存消耗太严重

### ISSUE THREAD

**Issue by WilliamCheen** [renzifeng/ZFPlayer#35]
未播放时大概50几MB的内存占用，播放视频时基本上瞬间增加到150MB以上，这样的内存暴增有些恐怖

**Comment by renzifeng** [comment]
请在真机测试，模拟器不准的，我看了真机播放前播放中也就20MB，没超过30

**Comment by jxdwinter** [comment]
真机表现非常好,一直在20M左右.
