### ISSUE TITLE
超级严重的一个bug

### ISSUE THREAD

**Issue by zengqingf** [renzifeng/ZFPlayer#350]
在UIViewController+ZFPlayerRotation.m 中
`// 是否支持自动转屏
\- (BOOL)shouldAutorotate {
    return NO;
}

// 支持哪些屏幕方向
\- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskPortrait;
}`

[代码在这里](https://github.com/renzifeng/ZFPlayer/blob/master/ZFPlayer/Category/UIViewController%2BZFPlayerRotation.m)
这些代码会修改ViewController默认行为，特别是像webView中的h5视频，弹出来的是是"MPMoviePlayerViewController"或者是"AVFullScreenViewController"，直接会影响他们的默认行为，导致他们不能够跟随设备进行旋转。

**Comment by oshiwei** [comment]
有没有解决办法，感觉这样写的确不太合适。

**Comment by imyellow** [comment]
这个搞了我一晚上，我 webview 里的视频死活就是不会旋转，折腾了一晚上搜索旋转才发现是这货坑的。
另外还有个 bug，就是设备旋转的时候，他转来转去会把屏幕和视频的旋转方向搞反导致视频也没饭关闭也看不到操作按钮。如图：
![](http://ww1.sinaimg.cn/large/5f789f8fgy1fo1z944j6ej20yi1pcax9.jpg)
