### ISSUE TITLE
全屏播放导致状态栏横竖屏错乱BUG

### ISSUE THREAD

**Issue by huanglei1926** [renzifeng/ZFPlayer#351]
在Demo TableView页面中,点击播放视频->点击全屏播放->再次点击回退到TableView页面->滑动TableView直到Cell中的播放画面变成预览->关闭预览图层->再次滑动到刚才的页面,再次点击播放->点击全屏播放->全屏状态下,此时只要滑动界面,播放界面就会消失,并且此时TableView仍为横屏界面,会导致界面错乱,并且再次点击Cell中的播放按钮时,弹出的播放界面为顺时针90度的画面,此时系统仍为横屏状态.

**Comment by Danie1s** [comment]
我也遇到了
