### ISSUE TITLE
videoGravity设置了没有作用。

### ISSUE THREAD

**Issue by LittleChuan** [renzifeng/ZFPlayer#36]
self.zf_player.playerLayerGravity = ZFPlayerLayerGravityResizeAspectFill;
self.zf_player.videoURL = movieURL;

视频没有被拉伸

**Comment by renzifeng** [comment]
那是因为视频的原因，你看我demo的第一个url的视频

**Comment by LittleChuan** [comment]
好像也没有办法填充全屏，有没有什么解决方案？

**Comment by LittleChuan** [comment]
看了下必须先设置videoURL才有playerLayer，这两句顺序换一下就行了

**Comment by renzifeng** [comment]
是的呀
