### ISSUE TITLE
没有适配ipad？

### ISSUE THREAD

**Issue by 2360219637** [renzifeng/ZFPlayer#364]
在ipad上视频播放器不能随着横竖屏的切换而切换
![simulator screen shot - ipad pro 12 9-inch - 2018-01-17 at 09 15 09](https://user-images.githubusercontent.com/13285489/35020423-f4817a0a-fb66-11e7-889d-e8cb4839accb.png)

**Comment by 2360219637** [comment]
![untitled](https://user-images.githubusercontent.com/13285489/35022695-3cf94c4e-fb72-11e7-8a1e-b5766269f323.gif)

**Comment by JunsW** [comment]
遇到了同样的问题，请最后是怎么解决的？
