### ISSUE TITLE
didFailedtoPlay delegate method

### ISSUE THREAD

**Issue by ibhavin** [renzifeng/ZFPlayer#368]
I have integrated ZFPlayer in my project successfully. I want to add delegate method if player did fail to play video from url.
How to integrate delegate method for `didFailedtoPlay`.

**Comment by diepchicuong** [comment]
This is very easy. You can write your own PlayerControlView (ZFPlayerControlView for reference) and add your custom delegate. Then call the didFailedtoPlay protocol in the zf_playerItemStatusFailed function.

```
override func zf_playerItemStatusFailed(_ error: Error!) {
	customDelegate?.didFailedtoPlay()
}
```
