### ISSUE TITLE
有些mp4格式的视频播放不了啊，有没有遇到的

### ISSUE THREAD

**Issue by topjx** [renzifeng/ZFPlayer#370]

**Comment by CellMeChopper** [comment]
我这的mp4格式的只有声音没图像。我用楼主的ZFPlayer和系统简单集成的MPMoviePlayerController、AVPlayerViewController都是一样的情况。我Android的同事说，他们把缓存去掉了就好了。很惆怅....是不是iOS 11更新方法了，我也没找到

**Comment by risechen** [comment]
同样的问题，怎么是黑屏，蛋疼

**Comment by 1277393484** [comment]
我也遇到部分mp4无法播放，请问有解决办法吗

**Comment by nthtrung09it** [comment]
+1

**Comment by CoderDoraemon** [comment]
模拟器能播放比较卡，真机黑屏一直转菊花
http://business.holike.com/prod/course/section/video/2019-09-29/8632df9aeae6f5aefab9cb98416b9fe0.mp4

**Comment by HuDingfeng** [comment]
> 模拟器能播放比较卡，真机黑屏一直转菊花
> http://business.holike.com/prod/course/section/video/2019-09-29/8632df9aeae6f5aefab9cb98416b9fe0.mp4

请问解决了吗？
