### ISSUE TITLE
Property 'delegate' with type 'PayTopViewDelegate?' cannot override a property with type 'ZFPlayerControlViewDelagate!'

### ISSUE THREAD

**Issue by IceTears1** [renzifeng/ZFPlayer#374]
Property 'delegate' with type 'PayTopViewDelegate?' cannot override a property with type 'ZFPlayerControlViewDelagate!'

**Comment by IceTears1** [comment]
swift 项目 出现代理冲突的情况

**Comment by diepchicuong** [comment]
Use another name for your own 'delegate'
