### ISSUE TITLE
小屏幕播放严重bug.

### ISSUE THREAD

**Issue by BestLeeSinCN** [renzifeng/ZFPlayer#375]
在tableview上播放视频, 设置必须竖屏播放的情况下。

做双指捏合手势，依旧可以小窗口播放. 

        _playerView.delegate = self;
        // 当cell播放视频由全屏变为小屏时候，不回到中间位置
        _playerView.cellPlayerOnCenter = NO;
        _playerView.forcePortrait = YES;
        // 当cell划出屏幕的时候停止播放
         _playerView.stopPlayWhileCellNotVisable = YES;
        _playerView.disablePanGesture = NO;

当把disablePanGesture设置为YES的情况下, 只需要随便拖移，就可以小窗口播放. 

在设置tableview.scrollsToTop = NO了之后, 第一行的视频播放不会出现这种情况, 

后面的每一行都会出现.

**Comment by zhaodanfeng235** [comment]
大神我也遇到了你怎么解决的？
