### ISSUE TITLE
ios 11.2 真机必现bug  

### ISSUE THREAD

**Issue by 2272229234** [renzifeng/ZFPlayer#380]
tableview 播放视频，横竖屏切换界面闪屏，严重影响用户体验 模拟器没问题才发现！！！请查看我说的原因O(∩_∩)O谢谢

**Comment by WJLollipop** [comment]
我也遇到了这个问题，横竖屏切换界面闪屏

**Comment by Janlor** [comment]
我重启手机后 OK了😅

**Comment by zhaodanfeng235** [comment]
@Janlor  最后是怎么解决闪屏问题的，我里出现的频繁
