### ISSUE TITLE
Some question about the license

### ISSUE THREAD

**Issue by JackLauu** [renzifeng/ZFPlayer#382]
Hello, renzifeng. Thanks for your project, I will use it in my close-source app. I have a question about the copyright about the icons in your project. Could I use the interface icons directly in my app or should I design and replace them all?

I don't know the source of those icons and care about their copyright. Wish you give me some advice and reply. Thank you.

Also, I want to know if Mit license or other code license like Apache license still work for image resources?

**Comment by renzifeng** [comment]
If you're worried about this, you can replace the icons.
