### ISSUE TITLE
首次进入app,播放视频，点击全屏按钮不起作用，但按钮图片变了。之后点击正常

### ISSUE THREAD

**Issue by CherishSmile** [renzifeng/ZFPlayer#385]

**Comment by WJLollipop** [comment]
我也遇到了这种情况

**Comment by CherishSmile** [comment]
ZFPlayerShared.isLockScreen = NO;
我发现这个问题，是由于这个属性设置为YES,导致的。把它设置为NO。就正常了

**Comment by maltsugar** [comment]
我也是，按照你说的ZFPlayerShared.isLockScreen = NO; 暂时解决， 这样设置 以横屏就自动全屏了，先将就着
