### ISSUE TITLE
视频从窗口和全屏之间相互切换有闪烁

### ISSUE THREAD

**Issue by risechen** [renzifeng/ZFPlayer#394]

**Comment by xnxy** [comment]
我也遇到过~~  但只是偶尔会出去~~~目前还没找到什么原因~~

**Comment by zhaodanfeng235** [comment]
@xnxy 你好你是怎么解决闪屏的？

**Comment by HqRaining78** [comment]
- (void)addPlayerToFatherView:(UIView *)view {
    // 这里应该添加判断，因为view有可能为空，当view为空时[view addSubview:self]会crash
    if (view) {
        [self removeFromSuperview];
        [view addSubview:self];
        [self mas_remakeConstraints:^(MASConstraintMaker *make) {
            make.edges.equalTo(view);
        }];
    }
}
试试
