### ISSUE TITLE
播放视频时控制台会打印：CredStore - performQuery - Error copying matching creds.  Error=-25300……

### ISSUE THREAD

**Issue by xnxy** [renzifeng/ZFPlayer#395]
在播放视频的时候，控制台会打印：
2018-03-27 11:40:48.784135+0800 Player[96812:11818187] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;
}

但视频的播放并没问题……  有人遇到过这个问题吗？
目前正在查找原因……

**Comment by NOMBER2011** [comment]
我也遇到了这个问题。我使用WMPlayer这个库的时候也出现了这个问题。你现在解决了没？

**Comment by xnxy** [comment]
https://www.jianshu.com/p/b90b43114d7f

**Comment by dagundejuzi** [comment]
我也遇到了，但是我们后台确实需要认证，这怎么办。。。

**Comment by iloveOS** [comment]
+1，遇到了同样情况，SOS
