### ISSUE TITLE
设置静音后，调节音量也没声音

### ISSUE THREAD

**Issue by q858333** [renzifeng/ZFPlayer#396]
想显示的时候静音，后面自己调音量，结果发现调音量了也是静音

**Comment by ankit-betterbutter** [comment]
is this solved?

**Comment by renzifeng** [comment]
可以设置player静音或者系统静音，API是`ZFPlayerMediaPlayback`或者`ZFPlayerController`的`muted`

**Comment by q858333** [comment]
@ankit-betterbutter  configureVolume Mothed ，MPVolumeSlider addtarget UIControlEventValueChanged
