### ISSUE TITLE
连续播放15次之后, 就无法再加载任何视频, 必须要关闭APP后才能继续播放

### ISSUE THREAD

**Issue by xinluqi001** [renzifeng/ZFPlayer#401]
Error Domain=AVFoundationErrorDomain Code=-11839 "无法解码" UserInfo={NSLocalizedDescription=无法解码, NSUnderlyingError=0x1c1851f10 {Error Domain=NSOSStatusErrorDomain Code=-12913 "(null)"}, NSLocalizedRecoverySuggestion=停止其他所有对媒体解密的操作，然后再试一次。, NSLocalizedFailureReason=此媒体所需的解码器正忙。}

**Comment by xinluqi001** [comment]
[] <<<< AVOutputDeviceDiscoverySession (FigRouteDiscoverer) >>>> -[AVFigRouteDiscovererOutputDeviceDiscoverySessionImpl outputDeviceDiscoverySessionDidChangeDiscoveryMode:]: Setting device discovery mode to DiscoveryMode_None

**Comment by xinluqi001** [comment]
iOS 10 和 iOS 11 多设备都会 出现. 必然出现的bug, 很无解

**Comment by xinluqi001** [comment]
找到解决办法了 
[self.player replaceCurrentItemWithPlayerItem:nil]; 在每次离开页面, 或者不需要plyer的时候, 加上这句代码就行. 把plyer完全释放掉. 这个问题主要是内存泄漏造成了的

**Comment by huiyumiao** [comment]
> 找到解决办法了
> [self.player replaceCurrentItemWithPlayerItem:nil]; 在每次离开页面, 或者不需要plyer的时候, 加上这句代码就行. 把plyer完全释放掉. 这个问题主要是内存泄漏造成了的

请问下，这个方法是 AVPlayer 的方法，你是如何调用的呢？

**Comment by cnzlh** [comment]
这w

> 找到解决办法了 [self.player replaceCurrentItemWithPlayerItem:nil]; 在每次离开页面, 或者不需要plyer的时候, 加上这句代码就行. 把plyer完全释放掉. 这个问题主要是内存泄漏造成了的

PlayerManager中stop方法中不是有这个调用吗？但是内存还是在不断增加啊,CPU占用也是越来越高，直至卡死
