### ISSUE TITLE
i cant use the ZFPlayer on my project...

### ISSUE THREAD

**Issue by fernandomatheus** [renzifeng/ZFPlayer#41]
im using swift:
here is my code:

> import UIKit
import ZFPlayer

class ViewController: UIViewController {

    @IBOutlet weak var viewVideo: ZFPlayerView!
    
    var url = NSURL(string: "http://jplayer.org/video/m4v/Big_Buck_Bunny_Trailer.m4v")
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.viewVideo.videoURL = url
        self.viewVideo.hasDownload = false
        
        
        weak var weakSelf = self
        self.viewVideo.goBackBlock = {() -> Void in
            weakSelf!.navigationController!.popViewControllerAnimated(true)
        }
    }

here is the result: 
![captura de tela 2016-04-19 as 13 59 16](https://cloud.githubusercontent.com/assets/12262451/14648338/2ea3bb9c-0638-11e6-82c4-78e6c63e30df.png)

**Comment by renzifeng** [comment]
The default is to support HTTPS，in order to support HTTP,you should add "App Transport Security Settings" in Info.plist.

**Comment by fernandomatheus** [comment]
i did this, the video is running ok but the player is not equal to the original.
![Here is the player](https://cloud.githubusercontent.com/assets/12262451/14751839/61ff48b4-08a2-11e6-8072-996412ec1daa.png)

i already have this problem with some video players, like KRVideoPlayer.

Can you help me with this?

**Comment by renzifeng** [comment]
In ZFPlayer you can use `self.playerView.playerLayerGravity = ZFPlayerLayerGravityResizeAspect;`this enum to setting the player Fill mode

**Comment by fernandomatheus** [comment]
@renzifeng 
the problem still remains...

i checked my console, here is what is happening:

2016-04-25 15:03:48.834 VideoPlayer[6414:313483] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<MASLayoutConstraint:0x7c29a100 ZFPlayerView:0x7c273760.height == 213.333>",
    "<NSLayoutConstraint:0x7c272c20 ZFPlayerView:0x7c273760.height == 375>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7c272c20 ZFPlayerView:0x7c273760.height == 375>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-04-25 15:03:48.839 VideoPlayer[6414:313483] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<MASLayoutConstraint:0x7c29a100 ZFPlayerView:0x7c273760.height == 213.333>",
    "<NSLayoutConstraint:0x7c272c20 ZFPlayerView:0x7c273760.height == 375>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7c272c20 ZFPlayerView:0x7c273760.height == 375>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

i checked my constraints on my UIView, and all are ok.

![Here is my storyboard](https://cloud.githubusercontent.com/assets/12262451/14794272/8bd78d46-0af9-11e6-9312-c8f09dd8a79c.png)

**Comment by renzifeng** [comment]
Your constraints is not ok,this make your video is not equal to the original,you can make the video aspect ratio of 16:9.

**Comment by fernandomatheus** [comment]
i did the modification but still not working

![captura de tela 2016-04-27 as 14 49 32](https://cloud.githubusercontent.com/assets/12262451/14862358/59bea382-0c87-11e6-9803-fcb708331559.png)
