### ISSUE TITLE
如何简单获取当前视频的播放时间

### ISSUE THREAD

**Issue by wangguoming0** [renzifeng/ZFPlayer#413]
如何简单获取当前视频的播放时间 ？求助.....

**Comment by simplismvip** [comment]
- (void)backBtnClick:(UIButton *)sender {
    // 状态条的方向旋转的方向,来判断当前屏幕的方向
    UIInterfaceOrientation orientation = [UIApplication sharedApplication].statusBarOrientation;
    // 在cell上并且是竖屏时候响应关闭事件
    if (self.isCellVideo && orientation == UIInterfaceOrientationPortrait) {
        if ([self.delegate respondsToSelector:@selector(zf_controlView:closeAction:)]) {
            [self.delegate zf_controlView:self closeAction:sender];
        }
    } else {
        if ([self.delegate respondsToSelector:@selector(zf_controlView:backAction:)]) {
            [self.delegate zf_controlView:self backAction:sender];
            
            NSArray *times = [_currentTimeLabel.text componentsSeparatedByString:@":"];
            sender.tag = [times.firstObject integerValue] *60+[times.lastObject integerValue];
        }
    }
}

我的方法， 当前时间回调使用按钮tag值传出去了，

这个回调可以获取实时时间，自己写个回调也能实时获取
self.currentTimeLabel.text       = [NSString stringWithFormat:@"%02zd:%02zd", proMin, proSec];
