### ISSUE TITLE
swit引用问题

### ISSUE THREAD

**Issue by xiaotuota** [renzifeng/ZFPlayer#422]
当swift import 此框架后,导致swift 中的view 不能正常使用代理, 因为此框架扩展了view的代理属性,当swift的view中使用同名的delegate时,提示不能使用此属性delegate,可以把框架中扩展代理属性不要暴露出来么

**Comment by melote** [comment]
+1

**Comment by melote** [comment]
这个问题很大啊，使用扩展或者OC的分类添加自己的属性时，如果是写框架或者库代码一定要加前缀啊，你看人家snapkit或者masonry怎么做的，不然用常用到的属性名会和别人的起冲突，无法编译。

**Comment by renzifeng** [comment]
ok
