### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by ArchForge** [renzifeng/ZFPlayer#425]
Hi!

I'm working with ZFPlayer and I think it's an amazing pod, but I have a few suggestions on minor additions that would be nice:

1. The ability to disable onDeviceOrientationChange method on zfplayer. It could be solved by a simple bool that is checked when adding the observer

2. A delegate method for when the player is going to/from fullscreen mode. I'd like to e.g. use pan gestures only in fullscreen, so this would be helpful

3. I prefer showing the controls until the user presses the video, so an option to show it on loading would be nice

4. Showing the total time of the video from the start (now it's says 00:00 until pressing play)

5. Making it possible to set the message strings (and replay image) outside the pod to make localization easier

6. A delegate method for when user pressed play would also be nice.

You might have gotten some of these suggestions before, but unfortunately I can't read Chinese. Again, I really appreciate your work.

**Comment by renzifeng** [comment]
Thank you. I will take your advice and make ZFPlayer better
