### ISSUE TITLE
UIScrollView+ZFPlayer导致crash

### ISSUE THREAD

**Issue by allran** [renzifeng/ZFPlayer#427]
集成最新版本后，启动app时导致如下crash：

2018-06-04 11:33:20.960052+0800 DoveApp[746:70918] *** -[UIFieldEditor scrollViewKVO]: message sent to deallocated instance 0x148831600

<img width="1382" alt="2018-06-04 11 37 20" src="https://user-images.githubusercontent.com/1505892/40897146-d96240fa-67eb-11e8-8770-d26b56d88e16.png">

**Comment by renzifeng** [comment]
delloc里边两行代码调换一下顺序，再试一下

**Comment by 986138497** [comment]
@implementation ZFKVOController {
    __weak NSObject *_target;
    NSMutableArray  *_observerArray;
}
   


在这个类中,吧__ weak 去掉就好了

**Comment by flybear123** [comment]
去掉__weak还是会有问题，以上两种方案都不行额

**Comment by 986138497** [comment]
你是啥系统,我是10.3 ,我改了这个就好了

**Comment by hqwsun** [comment]
你确定去掉__weak不会造成内存泄漏的问题吗？我查看了一下，应该是提前释放了，而后kvo没有删除成功，导致kvo对野指针操作。在11的系统是没问题的，但是10以下的系统都会崩溃。
现在我的解决是吧UIScrollView+ZFPlayer的kvo监听方法给注释掉，然后再外部重新定义，就看作者了，只要11以下的版本都会直接说闪退，这么明显的bug
