### ISSUE TITLE
UIScrollView+ZFPlayer导致crash

### ISSUE THREAD

**Issue by StarShare** [renzifeng/ZFPlayer#428]
滑动任意 UIScrollView cpu暴涨崩溃

![_f23bc973-4381-46b3-a188-169da8d5de13](https://user-images.githubusercontent.com/32382044/41024577-36536f84-69a2-11e8-83ca-1a6419ab2d4f.png)

**Comment by StarShare** [comment]
`- (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView {
    self.offsetY_last = scrollView.contentOffset.y;
}`

为什么要用代理的方法名，递归了～

**Comment by StarShare** [comment]
Dervice: iPhone 5s
Version: 10.1.1

**Comment by renzifeng** [comment]
收到，我在优化一下

**Comment by renzifeng** [comment]
可以加一下我qq吗 459643690，帮我一块测试完善一下。

**Comment by StarShare** [comment]
已经申请加你了

    
        
            
                
                    
                        
                    
                    
                        
                            levi akeman
                            
                            
                                
                                    邮箱：objc.wr@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
在2018年06月06日 17:09，紫枫 写道： 可以加一下我qq吗 459643690，帮我一块测试完善一下。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/renzifeng/ZFPlayer/issues/428#issuecomment-395000169","url":"https://github.com/renzifeng/ZFPlayer/issues/428#issuecomment-395000169","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/renzifeng/ZFPlayer","title":"renzifeng/ZFPlayer","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/renzifeng/ZFPlayer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@renzifeng in #428: 可以加一下我qq吗 459643690，帮我一块测试完善一下。"}],"action":{"name":"View Issue","url":"https://github.com/renzifeng/ZFPlayer/issues/428#issuecomment-395000169"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [renzifeng/ZFPlayer] UIScrollView+ZFPlayer导致crash (#428)",
"sections": [
{
"text": "",
"activityTitle": "**紫枫**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@renzifeng",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"renzifeng/ZFPlayer\",\n\"issueId\": 428,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"renzifeng/ZFPlayer\",\n\"issueId\": 428\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/renzifeng/ZFPlayer/issues/428#issuecomment-395000169"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 342927509\n}"
}
],
"themeColor": "26292E"
}
