### ISSUE TITLE
屏幕不支持旋转怎么全屏播放视频？

### ISSUE THREAD

**Issue by iGhibli** [renzifeng/ZFPlayer#43]
屏幕不支持旋转怎么全屏播放视频？

**Comment by renzifeng** [comment]
首先你工程的横屏不能禁掉，你可以参考我demo中MainViewcontroller中设置，其他页面只支持竖屏

**Comment by iGhibli** [comment]
我之前就是这样处理的，但发现了一个Bug，就是正常tabBarController是不会横屏的，但手机横着从一个界面取消模态到tabBarController时tabBarController就成为横屏了。可能是我设置问题。求大神指教，这个怎么解决？
