### ISSUE TITLE
新版闪退问题

### ISSUE THREAD

**Issue by Fighting-MrWeng** [renzifeng/ZFPlayer#433]
新版的ZFPlayer tableView播放的情况下在iPhone5上会crash

**Comment by Fighting-MrWeng** [comment]
ZFPlayer_Example[45760:432057] -[__NSCFString longValue]: unrecognized selector sent to instance 0x7a791820
2018-06-14 17:38:02.198 ZFPlayer_Example[45760:432057] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString longValue]: unrecognized selector sent to instance 0x7a791820'

**Comment by Fighting-MrWeng** [comment]
试着模拟器跑下崩溃在这个方法 的赋值操作了- (void)requestData {

        [data setValuesForKeysWithDictionary:dataDic];

}，另外用KSMediaPlayerManager播放avi时候也会有闪退，ZFAVPlayerManager播放打得话会黑屏，另外还有在cell上播放以前版本有关闭按钮，现在只能暂停或者继续播放了，希望能加回来

**Comment by renzifeng** [comment]
能否提供一下avi播放地址，关于控制层的问题可以完全自定义，我只是提供一个默认的控制层

**Comment by Fighting-MrWeng** [comment]
http://47.92.101.231:8080/video/33.avi  这个是avi的
http://47.92.101.231:8080/video/3.WMV 这个是wmv
在tableview中貌似都无法播放

**Comment by Fighting-MrWeng** [comment]
主要是在iPhone 5上tableview的情况下播放问题多一点，KSMediaPlayerManager在其他设备播放avi是可以的

**Comment by renzifeng** [comment]
这视频在ijk、ksy、avplayer都会播放出错
