### ISSUE TITLE
#import <ZFPlayer/ZFAVPlayerManager.h>库文件不存在啊

### ISSUE THREAD

**Issue by luo-h** [renzifeng/ZFPlayer#440]
大佬、#import <ZFPlayer/ZFAVPlayerManager.h>库文件不存在、3.0.7版本

**Comment by luo-h** [comment]
ZFPlayerControlView也没有

**Comment by renzifeng** [comment]
看readme， 默认只是Core，不包含这些

**Comment by luo-h** [comment]
大佬、那我要做成demo的效果是直接从demo中去把ZFAVPlayerManager和ZFPlayerControlView拷贝过来蛮

**Comment by renzifeng** [comment]
可以拷贝，可以pod

**Comment by luo-h** [comment]
大佬、pod的地址是什么呢，没写呢，我觉得应该和demo同步，demo里面这些东西在我们导入的库都没有，像我们这些小白就很尴尬啦

**Comment by luo-h** [comment]
好的，谢谢大佬、我一pod update，我pod所有的库都更新了，这下有得等了

**Comment by luo-h** [comment]
大佬、我把player的assetURLs传进去了啊，为啥还是一直‘加载失败，点击重试’，我调试到self.currentPlayerManager.playerPlayStatChanged里面的ZFAVPlayerManager的assetURL是空值，还可能是哪儿的问题哦

**Comment by luo-h** [comment]
大佬、找到问题了、是你- (void)playTheIndexPath:(NSIndexPath *)indexPath scrollToTop:(BOOL)scrollToTop这个方法取值是indexPath.row，我的是indexPath.section

**Comment by luo-h** [comment]
大佬、最后一个问题、我滑动tableView的时候视频就会停止播放，我对照了好久没发现问题，播放器应该任然在运行指示没显示出来

**Comment by luo-h** [comment]
大佬、滑动tableView的时候视频就会停止播放，我对照了好久没发现问题，播放器应该任然在运行只是没显示出来

**Comment by luo-h** [comment]
/// 以下设置滑出屏幕后不停止播放
    self.player.stopWhileNotVisible = NO;
    CGFloat margin = 20;
    CGFloat w = ZFPlayer_ScreenWidth/2;
    CGFloat h = w * 9/16;
    CGFloat x = ZFPlayer_ScreenWidth - w - margin;
    CGFloat y = ZFPlayer_ScreenHeight - h - margin;
    self.player.smallFloatView.frame = CGRectMake(x, y, w, h);

我要是加了这几句代码就会出现滑动tableView时cell上的视频停止播放，并且没有小窗出现，但是能听到播放的声音
若不加则不会出现滑动视频停止播放的情况

**Comment by renzifeng** [comment]
这个bug 已经修复了
