### ISSUE TITLE
麻烦添加视频暂停、视频播放、视频结束等接口！！！

### ISSUE THREAD

**Issue by CCBrother** [renzifeng/ZFPlayer#441]
接口太少了，我们又不让修改源码，太蛋疼了

**Comment by wulinfeng198810** [comment]
是的，这个回调加一下，还有获取当前播放进度的接口（已播放到多少秒）

**Comment by wulinfeng198810** [comment]
暂停回调的时候把当前播放进度带上

**Comment by mmx1101** [comment]
playStateChanged代理啊，还有当前进度currentTime代理

**Comment by MrStock007** [comment]
每天好多关于ZFPLAYER的邮件啊
，这是怎么回事啊各位
发自我的 iPhone
