### ISSUE TITLE
退出全屏问题

### ISSUE THREAD

**Issue by luo-h** [renzifeng/ZFPlayer#445]
如果在view.m中去完成添加播放器，进入全屏播放后点击返回无响应，播放完成后会自动返回原来的非全屏状态，再次点击播放会在非全屏的小窗口全屏播放

**Comment by renzifeng** [comment]
在控制器中添加
```
- (BOOL)shouldAutorotate {
    return NO;
}
```

**Comment by luo-h** [comment]
还有个问题，通过重力感应变成全屏播放，当视频播放完成后不能回到重新播放的状态（会停留在播放完成的最后画面，并且播放和暂停按钮不起作用），手动点击全屏按钮不会出现此问题
此时如果把shouldAutorotate设置为YES，则不会出现问题，只是通过重力感应变成全屏后无法回到非全屏状态（需要手动点击返回按键）
