### ISSUE TITLE
拖动进度条 _failBtn的bug 

### ISSUE THREAD

**Issue by Monkey-D-Mark** [renzifeng/ZFPlayer#447]
这两天在使用过程发现一个_failBtn显示的bug，反复来回拖动进度条，直到加载失败，显示_failbtn的内容，此时不点击按钮。继续拖动，加载成功后，_failBtn没有隐藏。我在state playing pasused两个监听里加了self.failBtn.hidden = YES;解决了，作者自己可以再测测

**Comment by renzifeng** [comment]
ok
