### ISSUE TITLE
下拉通知栏或上拉快捷栏重新播放已关闭的视频声音

### ISSUE THREAD

**Issue by MQLiu** [renzifeng/ZFPlayer#45]
在已将视频页面关闭的情况下，发生下拉通知栏或上拉快捷栏重新播放已关闭的视频声音，麻烦告知一下如何解决。我在页面的-dealloc方法中已做了如下操作：
[_playerView pause];
 [_playerView cancelAutoFadeOutControlBar];
 [_playerView removeFromSuperview];
  _playerView = nil;
  [[ZFBrightnessView sharedBrightnesView] removeFromSuperview];

**Comment by renzifeng** [comment]
你应该是没走playerView的delloc的方法。至于什么问题，还得具体代码具体分析

**Comment by MQLiu** [comment]
打开了playerView的dealloc的打印，确实有执行到那里。
我执行了这个方法[_playerView resetPlayer]解决了这个问题，但发现了内存无法释放的问题，想问一下这个是AVPlayer本身的问题还是我还需要做什么处理？

**Comment by renzifeng** [comment]
不是AVPlayer问题，是你可能有些东西没释放吧
