### ISSUE TITLE
能不能自动更加视频的尺寸进行全屏

### ISSUE THREAD

**Issue by zhanghongdou** [renzifeng/ZFPlayer#454]
比如手机竖屏拍摄的，zfplayer全屏时和手机录制的时候一样竖屏全屏播放，能横屏的横屏播放

**Comment by renzifeng** [comment]
可以获取到视频的尺寸，然后根据尺寸竖屏全屏播放，横屏播放，自己写更灵活一些，我封装到里边不太好
