### ISSUE TITLE
视频播放进度保存问题

### ISSUE THREAD

**Issue by coder-Jackie** [renzifeng/ZFPlayer#458]
我们现在的需求是,退出正在播放视频的时候保存当前的播放进度,再次进入的时候,从保存的播放进度开始播放,这个功能怎么实现???

**Comment by renzifeng** [comment]
这个退出时候要记录一下当前播放时间的，然后再次进入seek到记录的时间就行

**Comment by janicezhw** [comment]
[playerManager seekToTime:seetTime completionHandler:^(BOOL finished) {
                   
                }];

我这么调用，在ios8系统，会崩溃。 其他系统没问题。
