### ISSUE TITLE
media control残留问题

### ISSUE THREAD

**Issue by Monkey-D-Mark** [renzifeng/ZFPlayer#459]
列表短视频，2分钟以内，那种能直接拖到结尾的视频。在播放后点击全屏播放，直接拖动到结束。在模拟器上会停滞0.5s的样子退出全屏，再返回列表。此时再点击同一个视频播放是正常的。
但在真机上执行相同操作，视频结束后，直接返回列表，此时再点击同一个视频时，在当前cell 中残留media control 层，导致视频无法再次播放。
此bug在我的手机 iPhone 6 11.3 下必现

**Comment by shengxiaolei** [comment]
demo怎么跑起来 老铁

**Comment by Monkey-D-Mark** [comment]
demo git clone下来跑不了吗？

**Comment by Monkey-D-Mark** [comment]
不知道什么情况在判断里加了个判断又好了
else if (state == ZFPlayerPlayStatePlayStopped){

}

**Comment by renzifeng** [comment]
好的 我处理一下
