### ISSUE TITLE
响应didSelectRowAtIndexPath

### ISSUE THREAD

**Issue by CoderHua** [renzifeng/ZFPlayer#46]
点击播放中的视频区域,会响应didSelectRowAtIndexPath.
怎么回事,是cell高度动态计算的原因吗?如果是请问我应该如何解决呢?
菜鸟一枚,真心请教!

**Comment by zhengwu119** [comment]
确实是有这个问题。

**Comment by lihanst** [comment]
这是我的理解，可能有不对的地方：在playerView.m的createGesture方法里作者添加了单击和双击两个手势，并且使用了方法requireGestureRecognizerToFail，让单击手势在双击手势识别失败后才识别。这样的话当用户单击了cellPlayerView，手势识别器先捕捉到touch，然后发送hit-textview，两者各自做出响应，在单击识别器还在识别该touch时（在等待双击识别器识别），此touch已经传递到了cell上去了，cell识别了它，响应了didSelectRowAtIndexPath这个方式。如果将requireGestureRecognizerToFail去除，touch会立刻被单击识别器识别，触发单击事件，cell不会识别该touch， 但是当用户双击cellPlayerView时，则会同时响应单击双击事件，这是一个处理方式。第二个处理方式，增加一句代码tap. delaysTouchesBegan = true,这样的话，在单击识别器识别到一个touch时，并不会传递给hit-testView,cell没有touch到达，所以单双击手势不会被同时识别，但是单击事件的识别会慢0.15ms。我选择第二个处理方式。参考：http://www.jianshu.com/p/2e074db792ba，http://www.codes51.com/article/detail_308743.html

**Comment by renzifeng** [comment]
thank you

**Comment by lihanst** [comment]
将ZFPlayerControlBarAutoFadeOutTimeInterval减去0.15 完美

**Comment by ctwlilei** [comment]
我现在就是和didselet冲突了。我的操作是push到新的页面。有无解决办法？

**Comment by lihanst** [comment]
上面两个comment你看了没？

**Comment by ctwlilei** [comment]
@lihanst  @renzifeng  我是说作者不修改代码解决这个问题么？  如果我改了代码，将来怎么再更新呀

**Comment by renzifeng** [comment]
我前些天就修复了这个bug啦

**Comment by ctwlilei** [comment]
@renzifeng  我刚刚参考 @zhengwu119 的修改成功。不过我要改多处，现在才改好一处。看来我要回滚了。那你为何不关掉bug呀

**Comment by ctwlilei** [comment]
@renzifeng  现在我更新到最新的pods 版 1.1.7  问题并没有解决。 然后下载了demo安装pod之后发现各种报错。根本运行不起来。
![image](https://cloud.githubusercontent.com/assets/13645606/17505859/b6624f2a-5e36-11e6-86a3-f7d9ea26aa97.png)
![image](https://cloud.githubusercontent.com/assets/13645606/17505864/c5365e24-5e36-11e6-8f28-e43a2d33d142.png)
