### ISSUE TITLE
能否把播放错误的error提供一个接口呢？

### ISSUE THREAD

**Issue by LittleCuteCat** [renzifeng/ZFPlayer#460]
如题所示，项目中需要对播放错误的视频进行错误统计处理，这里怎样去拿到视频播放错误的error呢？

**Comment by renzifeng** [comment]
可以的  下个版本提供

**Comment by LittleCuteCat** [comment]
谢谢，我现在是用运行时查找_playItem获取的，另外，我在cocoapods中pod 'ZFPlayer','~>3.0.7'的时候没找到，是不是还没更新呢，我看demo中都到了3.0.9了

**Comment by LittleCuteCat** [comment]
可以了
