### ISSUE TITLE
播放时退到后台，播放器方向问题

### ISSUE THREAD

**Issue by mortal-master** [renzifeng/ZFPlayer#462]
- 正常播放点击全屏进入全屏状态，此时按home键退到后台，再次进入app，播放器会调整为竖屏状态，能不能记忆播放器方向，再次进入app时和原来一样？

- 锁定时没问题，未锁定必现

**Comment by LittleCuteCat** [comment]
你用的是最新的吗？我这边用最新的没毛病，退出什么的都正常

**Comment by renzifeng** [comment]
好的，我在内部加上
