### ISSUE TITLE
滑动调整亮度和音量崩溃

### ISSUE THREAD

**Issue by lypcliuli** [renzifeng/ZFPlayer#464]
正常播放没问题 但是滑动屏幕改变音量和亮度的时候 出现该崩溃：
invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
libc++abi.dylib: terminate_handler unexpectedly threw an exception
![wechatimg1907](https://user-images.githubusercontent.com/12068023/42272468-c197b268-7fb8-11e8-81a3-5d53c36f36c9.jpeg)

**Comment by lypcliuli** [comment]
之前的问题提错了  不是亮度和音量导致的崩溃，因为我播放的是rtmp拉流的，此时是我pan手势滑屏幕调整进度，就会崩溃

**Comment by lypcliuli** [comment]
有没有办法可以关闭滑动屏幕调整进度的功能呢？

**Comment by renzifeng** [comment]
有的，`ZFPlayerControlView`中 `disableGestureTypes`

**Comment by MakeBetterMe** [comment]
> 有的，`ZFPlayerControlView`中 `disableGestureTypes`

没了吧
