### ISSUE TITLE
如何彻底释放playerView

### ISSUE THREAD

**Issue by godshow** [renzifeng/ZFPlayer#47]
我这样写的：

self.playerView.goBackBlock = ^{
                    [weakSelf.playerView removeFromSuperview];
                };

页面是没了，但是仍能听到声音，weakSelf.playerView = nil;要过一会声音才消失

**Comment by uSERken** [comment]
我是在ZFPlayerView.m中点击返回方法（backButtonAction）时在if (self.goBackBlock)之前加的self.player = nil;和self.playerLayer = nil;，就可以页面消失时关闭视频的

**Comment by godshow** [comment]
@uSERken 
你叫唐佳诚？我在github上经常遇到你哦

**Comment by uSERken** [comment]
@godshow  抱歉，我不是啦 :)
