### ISSUE TITLE
全屏播放问题

### ISSUE THREAD

**Issue by Monkey-D-Mark** [renzifeng/ZFPlayer#471]
版本:最新
issue: 播放视频后全屏，然后home挂起app，再进入app，此时会先显示列表，然后才显示播放的全屏5上必现，6上没有这个情况，6p上会先显示全屏播放，然后再跳出启动页，然后在显示播放层。以上bug均在真机上，模拟器未发现。
另外建议在controlview里再加一个api
-(void)showTitle:(NSString *)title coverURLString:(NSString *)coverUrl fullScreenMode:(ZFFullScreenMode)fullScreenMode data:(id)data;
data由使用者传播放时的data，可以用于详情页分享。

**Comment by renzifeng** [comment]
如果要应用退到后台或者锁屏返回来,界面会不被重置为竖屏状态
 ```objc
- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    if (self.player.currentOrientation == UIInterfaceOrientationPortrait) {
        return UIInterfaceOrientationMaskPortrait;
    } else if (UIInterfaceOrientationIsLandscape(self.player.currentOrientation)) {
        return UIInterfaceOrientationMaskLandscape;
    }
    return UIInterfaceOrientationMaskAllButUpsideDown;
}
```
这样才不会被重置为竖屏,才能保持前后状态一致.

**Comment by Monkey-D-Mark** [comment]
我记得之前谁好像提过这个问题，因为我基本今年的issue都看了一遍，建议写到demo里吧，省得下次又有人问

**Comment by renzifeng** [comment]
已更新demo
