### ISSUE TITLE
有没有帮我下，tableviewVideo状态栏始终不旋转？

### ISSUE THREAD

**Issue by NOMBER2011** [renzifeng/ZFPlayer#473]
全屏状态下不显示状态栏

**Comment by NOMBER2011** [comment]
这个方法始终不走
- (BOOL)shouldAutorotate {
    return self.player.shouldAutorotate;
}

**Comment by renzifeng** [comment]
始终不走是因为项目层级的问题，不会调用当前控制器的`shouldAutorotate `,具体问题得结合项目来改

**Comment by NOMBER2011** [comment]
只有列表的时候不走这个方法，其他的都走。还有一个问题 当我播放一个视频后关闭，将程序进入后台，等上差不多5min，进入app，会播放刚才那个视频声音

**Comment by NOMBER2011** [comment]
![4181531446577_ pic_hd](https://user-images.githubusercontent.com/13688441/42668217-1ba00c86-8682-11e8-999c-c60d08f95b53.jpg)
你是不是在腾讯上班啊？腾讯云视频好像在用ZFPlayer

**Comment by renzifeng** [comment]
没在腾讯云上班，腾讯云用的老版本的ZFPlayer改的

**Comment by NOMBER2011** [comment]
当我播放一个视频后关闭，将程序进入后台，等上差不多5min，进入app，会播放刚才那个视频声音。这个问题帮我看下

**Comment by renzifeng** [comment]
这个你找腾讯云吧

**Comment by NOMBER2011** [comment]
我用的是你写的3.1.1这个版本。

**Comment by NOMBER2011** [comment]
demo中allowOrentitaionRotation这个方法不起作用
