### ISSUE TITLE
关于播放视频黑屏闪一下的问题和什么时间调用play播放的问题

### ISSUE THREAD

**Issue by CherishSmile** [renzifeng/ZFPlayer#474]
应该说这两个是同一个问题。我也研究可好长时间AVPlayer的视频播放。后来发现当status为AVPlayerStatusReadyToPlay时，播放器有时并不会去播放视频，即使有时缓存很长也不会播放，这就会导致用户体验不好，明明菊花不转了，却不会播放。但是如果把播放和结束菊花都写在playbackLikelyToKeepUp这里面，一切问题好像都迎刃而解了。我在网上查阅到：playbackBufferEmpty是监听播放器的缓冲数据的状态，如果缓冲不足会自动暂停，这里面可以写pasue和开始转动菊花的方法；playbackLikelyToKeepUp，是缓冲到可播放程度，这里才是真正可以无障碍的播放，由于 AVPlayer 缓存不足就会自动暂停，所以缓存充足了需要手动播放，才能继续播放，因此这里写play和结束菊花的方法。如果仅仅就播放而言，这两个方法应该可以处理好自动播放，菊花消失和自动暂停菊花出现。而AVPlayerStatusReadyToPlay，并非真正意思上的播放，但当播放器为这个状态时，仅仅可以去获取到视频的总时长，和该视频的一些参数而已，而真正的播放，还要通过监听playbackLikelyToKeepUp。这是我的理解，希望对你的播放器有所帮助，如果我的理解是正确的，也希望你能修复我所提到的一些问题。谢谢！

**Comment by CherishSmile** [comment]
我在这里这样写，可以解决黑屏闪一下的问题。不知道会不会导致其他的问题。
<img width="760" alt="qq20180712-183828 2x" src="https://user-images.githubusercontent.com/17586122/42628502-e912c9fe-8602-11e8-8ff5-33e0353591d2.png">

**Comment by renzifeng** [comment]
暂时先这么解决吧

**Comment by CherishSmile** [comment]
再请教你一个问题。我遇到一种情况，就是进度条再走，但是视频没有播放，这个问题怎么解决。

**Comment by CherishSmile** [comment]
我感觉应该是timeObserver和playbackLikelyToKeepUp没有同步导致的，时间已经走了，timeObserver已经监听到了，但是此时的状态却不是playbackLikelyToKeepUp，所以视频不会播放。有没有什么办法，解决这个问题^_^
