### ISSUE TITLE
缓冲进度条的问题

### ISSUE THREAD

**Issue by CherishSmile** [renzifeng/ZFPlayer#475]
网速慢的时候，缓冲进度条有时候冲到屏幕外边

**Comment by CherishSmile** [comment]
具体情况就是视频很大，但时间很短，网速不好的时候，缓冲一直进行着，但视频不会播放，此时缓冲进入条会冲到屏幕边缘

**Comment by renzifeng** [comment]
这个应该是`ZFSliderView`的bug

**Comment by CherishSmile** [comment]
我觉得应该是没有获取到视频时长的缘故，虽然一直缓冲，但一直不会播放，视频时长没有获取到，导致的，应该。我在试试，看能不能复现这个问题。其实在readyToPlay的时候就可以获取到视频时长了。

**Comment by CherishSmile** [comment]
把初始时间回调写在这里就没有问题了
<img width="728" alt="qq20180712-181555 2x" src="https://user-images.githubusercontent.com/17586122/42627507-d2f31be0-85ff-11e8-9565-e733cf55ad80.png">

[](url)

**Comment by zhangferry** [comment]
@CherishSmile @renzifeng Hello，我也遇到了一直缓存，但是一直不播放，差不多缓存走了5、6s才开始播放。
我没用ZFPlayer，是自己写的，在readyToPlay的时候调的[player play]。请问还有其他什么原因引起这种延迟的吗

**Comment by zhangferry** [comment]
#解决了。加上下面这一句设置。
`self.player.automaticallyWaitsToMinimizeStalling = NO;`
