### ISSUE TITLE
ZFOrientationObserver 获取kWindow的问题

### ISSUE THREAD

**Issue by CherishSmile** [renzifeng/ZFPlayer#476]
kWindow = [(id)[UIApplication sharedApplication].delegate valueForKey:@"window"];

这种KVO获取方法，可能会有问题，对有的项目来说，获取到的window可能为空。如果在appdelegate手动创建根视图控制器，类似于下面这样写，window获取到就是nil.
 _window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
 ZTLoginVC *loginVC = [[ZTLoginVC alloc] init];
 _window.rootViewController = loginVC;

而改成        kWindow = [UIApplication sharedApplication].keyWindow;
就没有问题了

**Comment by renzifeng** [comment]
好的，我改一下
