### ISSUE TITLE
viewWillLayoutSubviews 全屏调用改变

### ISSUE THREAD

**Issue by lotus-lotus** [renzifeng/ZFPlayer#477]
AppDelegate 使用UIInterfaceOrientationMaskAllButUpsideDown,在视频播放界面全屏不会调用preferredStatusBarStyle,prefersStatusBarHidden,preferredStatusBarUpdateAnimation,shouldAutorotate方法,并且会调用viewWillLayoutSubviews ,因为containerView布局是写在viewWillLayoutSubviews上的,所以全屏的有问题,但是测试demo代码,全屏并不会调用viewWillLayoutSubviews,不知道什么原因

**Comment by renzifeng** [comment]
不调用`preferredStatusBarStyle,prefersStatusBarHidden,preferredStatusBarUpdateAnimation,shouldAutorotate`导致的，这些调用和项目层级结构有关

**Comment by lotus-lotus** [comment]
看来是我以前人写代码的坑，它的层级完全不对，后来改成tabbarvc+nav+vc 在tabbarvc和nav重写让所在控制器自己控制是否旋转就解决了上面所述问题，谢谢
