### ISSUE TITLE
横屏应用切换到全屏后视频变为了竖屏

### ISSUE THREAD

**Issue by wstown** [renzifeng/ZFPlayer#479]
应用不支持横屏时，视频全屏播放功能正常，但是当应用支持横屏时，在横屏模式下播放视频，切换到全屏模式后视频变为了竖屏。
具体步骤如下，修改Example的plist文件，增加横屏支持。
ZFPlayer-Info.plist
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
手机横屏模式，启动Example，进入“列表点击播放”，播放任意视频。
点击全屏按钮后，在手机横屏模式下视频变为了竖屏播放。
期望在横屏模式下的全屏播放，视频依然是横屏，不要变为竖屏

**Comment by jiangyongchang126** [comment]
你的竖屏问题怎解决的？
