### ISSUE TITLE
cell上播放视频问题

### ISSUE THREAD

**Issue by CherishSmile** [renzifeng/ZFPlayer#481]
我想问一下，cell上播放视频后，控制cell划出屏幕，播放器自动停止是哪个方法。我现在遇到的问题是，我的cell朝下滑，cell底部离屏幕底部还有40px左右，就自动停止了。

**Comment by renzifeng** [comment]
已经有API可以设置，滑出的百分比了，具体可以设置`ZFPlayerController`中`playerDisapperaPercent`属性

**Comment by CherishSmile** [comment]
playerDisapperaPercent这个属性我设置了，可是还是有那个问题。cell朝上划没有问题，可是cell朝下滑，**cell底部**离**屏幕底部**还有40px左右，此时cell还完全在屏幕之中，就自动停止了。我的TableView设置了tableHeaderView，是不是tableHeaderView导致的

**Comment by renzifeng** [comment]
使用3.1.2，看看还有没有这个问题

**Comment by CherishSmile** [comment]
大哥，新版本改了什么呀，为什么cell上播放中的视频，滑动到屏幕外，不会自动停止了，加了什么其他属性吗，急！！！
