### ISSUE TITLE
请支持竖屏hideControlView的同时隐藏状态栏

### ISSUE THREAD

**Issue by ebenmo** [renzifeng/ZFPlayer#483]
现在ZFPortraitControlView的hideControlView是写死了显示状态栏，也没有回调。对于像我这种实现竖屏浸润式没有导航栏的要在hideControlView的同时隐藏状态栏只能重写ZFPlayerControlView和ZFPortraitControlView，能不能提供一个回调来自定义状态栏的显隐？或者在ZFPortraitControlView增加一个属性标志状态栏是否隐藏也好

**Comment by renzifeng** [comment]
其实可以让这个内部隐藏无效的，只需要在控制器重写这个方法，改为YES就可以完全隐藏
```objc
- (BOOL)prefersStatusBarHidden {
    return YES;
}
```
