### ISSUE TITLE
播放 m3u8 TS 切片文件, 快进快退会很卡顿相比于MP4文件

### ISSUE THREAD

**Issue by yinqiangw** [renzifeng/ZFPlayer#485]
m3u8  播放 TS 切片文件, 快进快退会很卡顿相比于MP4文件.

大佬们有什么解决方案吗

**Comment by pusswzy** [comment]
同问

**Comment by renzifeng** [comment]
Fix at 3.1.4，卡段原因是m3u8，每次快进status都会变为AVPlayerItemStatusReadyToPlay，在kvo监听status改变里添加播放方法，可以解决
