### ISSUE TITLE
swift4.1 屏幕旋转貌似有issue

### ISSUE THREAD

**Issue by hujiaju** [renzifeng/ZFPlayer#486]
作者您好，我在swift4.1上，有一个界面需要支持竖屏、横屏切换，貌似有点问题，而同样的代码在oc上是正常的，猜测是应该是swift框架支持的问题，问一下能做一下相关的兼容么？

**Comment by Lcccocoa** [comment]
也碰到了。 swift下，player?.orientationWillChange 不会被执行
