### ISSUE TITLE
播放视频时闪一下的问题

### ISSUE THREAD

**Issue by CherishSmile** [renzifeng/ZFPlayer#491]
真心希望解决点击播放视频，闪一下黑屏的问题，希望可以平稳过渡。产品经理扣住这个问题了，还拿微博，微信说事，人家播放视频的时候，为什么不闪一下。希望能解决，谢谢。

if (state == ZFPlayerLoadStatePrepare) {
        self.coverImageView.hidden = NO;
    } else if (state == ZFPlayerLoadStatePlayable) {
        self.coverImageView.hidden = YES;
    }

现在改成这样，虽然不闪了，但是会造成，视频已经播放，封面却没有消失的问题。
希望能找到正确的方法，解决这个问题

**Comment by renzifeng** [comment]
3.1.3已结解决这个问题了呢

**Comment by CherishSmile** [comment]
已经更新到最新了，为啥我的还是要黑屏闪一下呢？
你可以看一下，这个压缩文件里的视频效果。
[ScreenRecording_07-23-2018 16-43-41.mp4.zip](https://github.com/renzifeng/ZFPlayer/files/2218740/ScreenRecording_07-23-2018.16-43-41.mp4.zip)

**Comment by 1277393484** [comment]
@CherishSmile 你好  我也遇到这个问题了，有解决办法么
