### ISSUE TITLE
升级最新版出现在使用多个第三方框架WMPageController时候崩溃

### ISSUE THREAD

**Issue by nnianhou-** [renzifeng/ZFPlayer#492]
@renzifeng  旧版本以前没问题，不知道是ZFPlayer还是WMPageController问题
[Xcode崩溃截图](http://lc-5k2saqjm.cn-n1.lcfile.com/5f3a4178d1e2b7a21f21.png)

**Comment by renzifeng** [comment]
好的，我验证一下

**Comment by renzifeng** [comment]
麻烦提供个demo给我，我调试一下
