### ISSUE TITLE
阅读源码时不解请教

### ISSUE THREAD

**Issue by swsdyg** [renzifeng/ZFPlayer#494]
作者您好，我在阅读您的源码的过程中，看到下面的写法有点疑惑，‘isBuffering’仅仅是一个局部变量吧，这样写是不是有点不太合理呢？希望能得到您的回复。
![1532507864311](https://user-images.githubusercontent.com/8267484/43189437-2c440956-9029-11e8-8921-a429326d8e41.jpg)

**Comment by renzifeng** [comment]
这有点问题，已经被修复了
