### ISSUE TITLE
视频后台播放

### ISSUE THREAD

**Issue by dota2AndTI** [renzifeng/ZFPlayer#495]
这个框架怎么实现后台及锁频播放？我试了没成功，请问怎么做？

**Comment by renzifeng** [comment]
后台播放需要设置在工程配置 
![image](https://user-images.githubusercontent.com/10377362/43569193-58ab9892-9669-11e8-8ffa-2d6219e3f95f.png)
并设置`pauseWhenAppResignActive`为NO

**Comment by dota2AndTI** [comment]
我设置了，在进后台的时候我通过通知将_playerLayer.player = nil回到APP时_playerLayer.player = _player，用来只播放音频但是ios11以后按home键就暂停了，而且播放状态没变还是播放状态没有变成暂停状态
