### ISSUE TITLE
25300错误，有声音没有画面，iOS真机上会出现，模拟器iOS9不会

### ISSUE THREAD

**Issue by lotus-lotus** [renzifeng/ZFPlayer#496]
网络大视频超过100M，iOS11的真机就会出现只有声音，没有画面，然而小视频是可以的，看到b站开源的框架也有这种问题，但是看回答应该是解决这个问题了，作者可以自己试试大视频在iOS11真机上会黑屏，只有声音，留下没技术的眼泪💧

**Comment by lotus-lotus** [comment]
经过测试发现视频分辨率很高 差不多是个2k视频，但是高分辨率的视频模拟器可以播放，真机有声音没有画面 https://github.com/Bilibili/ijkplayer/issues/3643好像也有这个问题 ，期待回复

**Comment by renzifeng** [comment]
这个issues不是已经给出答案了吗，修改`IJKSDLGLView.m`里的代码

**Comment by lotus-lotus** [comment]
我使用的是ZFAVPlayerManager，出现的问题

**Comment by renzifeng** [comment]
你好可以给我提供一个100兆以上的视频吗 我测试一下

**Comment by LittleCuteCat** [comment]
在模拟器上的核心是电脑，估计手机上会有问题，我们的APP也有用户反馈播放本地mp4的时候出现过只有声音画面不动的情况，不知道是不是和这个原因相同，至今我没测试遇到过

**Comment by zry754331875** [comment]
ios MPEG4 video codec up to 2.5 Mbps,you can check your video or convert .

**Comment by qiaoyijie** [comment]
请问解决了吗，我也遇到了这个问题，比较大的本地视频会出现这个问题，真机

**Comment by qiaoyijie** [comment]
我可以给您提供测试视频，请问怎么发给您呢

**Comment by lotus-lotus** [comment]
转成720的视频

**Comment by Jayxiang** [comment]
Error Domain=AVFoundationErrorDomain Code=-11821 "Cannot Decode" UserInfo={NSLocalizedFailureReason=The media data could not be decoded. It may be damaged., NSLocalizedDescription=Cannot Decode, NSUnderlyingError=0x283b6e820 {Error Domain=NSOSStatusErrorDomain Code=-12911 "(null)          格式不知道哪里不对，报错信息就是这
