### ISSUE TITLE
拖动进度条，时间会往回跳动几秒。

### ISSUE THREAD

**Issue by BigShow1949** [renzifeng/ZFPlayer#497]
比如我拖动进度条到12：45秒观看，但是松开指头，时间可能会跳到12:39秒。

另外，能增加一个功能吗？比如，我拖动进度条，画面跟着移动

**Comment by renzifeng** [comment]
进度条拖动时候不能精准seek，看看播放器时候提供精准seek的方法。你说的这功能都是控制层的东西，可以自定义控制层，提供的默认控制层并不能照顾到所有人。

**Comment by BigShow1949** [comment]
CMTimeMake(1,1) 改为 kCMTimeZero 就可以了
