### ISSUE TITLE
在swift 里面自定义PlayerControlView 的时候需要用到self.player?.currentPlayerManager.scalingMode 这个属性

### ISSUE THREAD

**Issue by leiyuncun** [renzifeng/ZFPlayer#498]
在swift 里面自定义PlayerControlView 的时候需要用到self.player?.currentPlayerManager.scalingMode 这个属性，但是这个属性是一个readonly，我们需要改变 scalingMode 会报错提示是一个只读属性，这里建议做兼容

**Comment by renzifeng** [comment]
这个属性并不是readonly的

**Comment by leiyuncun** [comment]
刚查看了下，最新版本还是有这个问题

**Comment by renzifeng** [comment]
currentPlayerManager是readonly的，下个版本我改成readwrite的吧

**Comment by leiyuncun** [comment]
还有一个问题页一起看看能不能改下：就是切换进入后台在ZFAVPlayerManager 里面有一个KVO ，当进入后台会暂停播放视频，进入前台会继续播放视频，这里能改成支持程序员自己设定是否继续播放在进入后台前正在播放的视频？不然每次不想在进入后台在回到前台继续播放都需要清空现在的的播放器，或者监听进入前台的通知调用暂停函数(PS:这里的通知会在KVO事件前发生所以调用的时候会有发生play 和 pause 的冲突)

**Comment by SwiftNie** [comment]
<img width="945" alt="屏幕快照 2019-07-07 下午2 20 44" src="https://user-images.githubusercontent.com/13481962/60764798-b9a1d080-a0c2-11e9-8a5b-737c498b7848.png">
请问下这个是怎么回事

**Comment by SwiftNie** [comment]
<img width="1074" alt="屏幕快照 2019-07-07 下午2 24 07" src="https://user-images.githubusercontent.com/13481962/60764820-1604f000-a0c3-11e9-8e9b-cb87a730340f.png">
请问下这个是怎么回事

**Comment by LiYuLong012** [comment]
> <img alt="屏幕快照 2019-07-07 下午2 24 07" width="1074" src="https://user-images.githubusercontent.com/13481962/60764820-1604f000-a0c3-11e9-8e9b-cb87a730340f.png">
> 
> 请问下这个是怎么回事

你那个问题解决了吗，我也遇到了😁
