### ISSUE TITLE
视频的状态的监听

### ISSUE THREAD

**Issue by CDYeah** [renzifeng/ZFPlayer#50]
我现在在做监听视频播放的时长，没有找到相应的方法来知道视频开始播放跟结束播放的时间，可以添加这个功能么？

**Comment by renzifeng** [comment]
有方法能获取到视频总长度啊

**Comment by CDYeah** [comment]
不是视频的长度，是要统计用户观看的总的时间，我要知道，开始，结束，暂停

**Comment by CDYeah** [comment]
视频的播放，暂停可以加一个通知么，可以在外边直接监听，我看现在是播放的函数调用很多次，确定不了什么时候在播放状态什么时候在停止状态
