### ISSUE TITLE
IJKMediaFramework - Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by RunzhiZhao** [renzifeng/ZFPlayer#508]
打包的时候报错
Undefined symbols for architecture armv7:
  "_avio_open_dyn_buf", referenced from:
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxAsync.o)
      _vtbformat_init in IJKMediaFramework(IJKVideoToolBoxSync.o)
      _decode_video_internal in IJKMediaFramework(IJKVideoToolBoxSync.o)
 ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Showing first 200 notices only

命令行查看库信息：
lipo -info IJKMediaFramework.framework/IJKMediaFramework 
Architectures in the fat file: IJKMediaFramework.framework/IJKMediaFramework are: armv7 i386 x86_64 arm64

**Comment by StefBiao** [comment]
我刚刚也遇到了同样的问题,删除armv7就可以了.
armv7：iPhone4｜iPhone4S｜iPad｜iPad2｜iPad3(The New iPad)｜iPad mini｜iPod Touch 3G｜iPod Touch.
所以不用担心,这些旧设备很少有人使用了.

**Comment by luckyhong** [comment]
是否只能remove掉armv7，没有其他办法？如果需要支持armv7呢？
