### ISSUE TITLE
播放在线mp4格式视频提示“加载失败，点击重试”

### ISSUE THREAD

**Issue by YYYYCY** [renzifeng/ZFPlayer#509]
playerPlayFailed 里有回调error内容如下
Error Domain=AVFoundationErrorDomain Code=-11850 "Operation Stopped" UserInfo={NSLocalizedFailureReason=The server is not correctly configured., NSLocalizedDescription=Operation Stopped, NSUnderlyingError=0x604001c4ed00 {Error Domain=NSOSStatusErrorDomain Code=-12939 "(null)"}}

**Comment by shls77cxl** [comment]
我也遇到了这个bug，必现的,点击视频播放列表跳转视频详情页，反复二十次以上，就会出现“加载失败，点击重试”的提示

**Comment by shls77cxl** [comment]
提示错误：CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;
}

**Comment by shls77cxl** [comment]
不好意思，问题已解决，在退出时，将播放器关联的视频地址置空
