### ISSUE TITLE
播放着音乐再启动我的APP音乐会停止播放

### ISSUE THREAD

**Issue by luo-h** [renzifeng/ZFPlayer#510]
播放着音乐的情况下启动我的APP音乐会停止播放，出去继续播放音乐后再进入我的APP又会停止播放音乐

**Comment by Junnor** [comment]
我也有这样的问题，请求楼主解决了吗？如果解决了，是怎样处理的呢？

**Comment by renzifeng** [comment]
这个我可以自定义AVAudioSession，只需要设置`customAudioSession`为YES，然后自己设置就可以啦
