### ISSUE TITLE
可以播放yuv数据吗

### ISSUE THREAD

**Issue by lypcliuli** [renzifeng/ZFPlayer#511]
我用的网易云的音视频服务 自己写的播放 效果不太好，刚好项目里面倒入了你的这个，想咨询一下是否有该功能，或者建议添加，谢谢

**Comment by MakeHui** [comment]
网易的播放器好像就是用的`ijkplayer`实现的，你可以实践一下
过段时间也得处理这块的东西，可行的话麻烦告知一下谢谢
