### ISSUE TITLE
建议ZF播放音频的时候显示占位图.不然黑色框框不太好看

### ISSUE THREAD

**Issue by MeteoriteMan** [renzifeng/ZFPlayer#512]

**Comment by MeteoriteMan** [comment]
嗯嗯.现在自定义控制层了.很舒服.多谢作者了

**Comment by guojingjingghost** [comment]
you can get the first picture in video by yourself ,then set .

**Comment by MeteoriteMan** [comment]
有些人私信问我怎么做的了.emmm.这里献丑了.controlView里面有个UIImage类型的placeholderImage属性.在未播放状态的话显示的是这张图片.当播放状态的时候显示的就是"视频"内容了(如果是音频的话.那理所当然就是黑的了).如果想在音频的时候设置占位图.那么是音频的时候需要给播放的那个View(我这里用的是ZFPlayerControlView)的layer的content设置一个CGImage上去就OK了.
