### ISSUE TITLE
获取视频的方向有问题,全屏方向有问题.

### ISSUE THREAD

**Issue by StefBiao** [renzifeng/ZFPlayer#513]
![simulator screen shot - iphone 7 - 2018-08-09 at 17 57 16](https://user-images.githubusercontent.com/18573476/43892119-b253c740-9bfd-11e8-8b01-7681113d3b58.png)

全屏应该为竖屏才对.还有本来是竖屏拍摄的,小屏却横向显示,找了半天也没找到可以修改的apipod 'ZFPlayer', '~> 3.1.4' + pod 'ZFPlayer/ControlView', '~> 3.0'+ pod 'ZFPlayer/ijkplayer', '~> 3.0'

**Comment by BigShow1949** [comment]
横屏，手机水平，退出后台，手机竖着打开app，这个时候应该是横屏，但是是竖屏状态，我直接比较手机宽高
