### ISSUE TITLE
Can't controll AutoPlay with diifferrent cell

### ISSUE THREAD

**Issue by targetbena** [renzifeng/ZFPlayer#514]
I have 2 cell & I want to set one cell Autoplay & other cell Not Autoplay the same time in collectionview. anyone know how to solved it ?

**Comment by renzifeng** [comment]
You can see the demo,and the demo has the function of writing what you say

**Comment by targetbena** [comment]
yes, i see it . thank you 
but now I want to set one cell always AutoPlay & other cell will play if i click it . can you tell me how to solved it ?

**Comment by renzifeng** [comment]
This feature has not been added yet
