### ISSUE TITLE
占位图和视频切换时黑屏闪一下

### ISSUE THREAD

**Issue by MrHT** [renzifeng/ZFPlayer#516]
占位图和视频切换时黑屏闪一下，每次播放视频之前都要黑屏闪一下，切换能否在流畅一些，平滑又占位图播放视频，建议直接使用视频的第一帧作为占位图

**Comment by BlackBones** [comment]
@MrHT  请问你解决了嘛？我也觉得闪一下体验很不好

**Comment by BlackBones** [comment]
原来是展位图的隐藏导致了屏幕闪一下，注释掉就不会再闪了
/// 加载状态改变
- (void)videoPlayer:(ZFPlayerController *)videoPlayer loadStateChanged:(ZFPlayerLoadState)state {
    if (state == ZFPlayerLoadStatePrepare) {
        self.coverImageView.hidden = NO;
    } else if (state == ZFPlayerLoadStatePlaythroughOK) {
        self.coverImageView.hidden = YES;
    }

**Comment by MrHT** [comment]
这样也会有一个问题，当占位图和视频不是一样大的时候，比如占位图是满屏，而视频是那种半屏视频的时候就会出现视频背景还可以看到占位图

**Comment by BlackBones** [comment]
确实如此，尝试了一下，加点过渡动画让占位图消失，始终还是会闪一下，

**Comment by woxihejinghao** [comment]
请问有解决方案了吗？闪到眼睛都累

**Comment by woxihejinghao** [comment]
查了资料  这个原因主要是 虽然播放器监听到可以播放了  但是其实播放器还在解码  所以会有短暂的黑屏 因此，就造成了 占位图隐藏了 但是播放器是黑屏的

**Comment by study123456** [comment]
> 查了资料 这个原因主要是 虽然播放器监听到可以播放了 但是其实播放器还在解码 所以会有短暂的黑屏 因此，就造成了 占位图隐藏了 但是播放器是黑屏的



> 我现在的操作是不把占位图隐藏 直接把视频拉伸铺满 但是如果占位图不是第一帧的话 还是会有跳动的感觉，不过比黑屏舒服

这问题你有好的解决方案吗
