### ISSUE TITLE
偶现bug，UIScrollView+ZFPlayer 分类中对scrollView 代理方法的监听导致崩溃

### ISSUE THREAD

**Issue by jerrywangjing** [renzifeng/ZFPlayer#517]
具体崩溃位置：UIscrollView+ZFPlayer.m    line: 136
代码：
```
- (void)zf_scrollViewWillBeginDragging:(UIScrollView *)scrollView {
   [scrollView add_scrollViewWillBeginDragging:scrollView];    ---> Thread 1: EXC_BAD_ACCESS (code=2, address=0x7ffee59bfff8)
    [self zf_scrollViewWillBeginDragging:scrollView];
}

```
希望能排查下原因，谢谢。

**Comment by 383889553** [comment]
我也遇到了，都还没调用，只在pod里添加了试试工程就奔溃了

**Comment by jerrywangjing** [comment]
我暂时没有使用这个分类，这个分类是在使用tableView或collectionView时做滑动事件监听用的，我调试发现是递归调用导致的崩溃
。
发自我的 iPhone

**Comment by renzifeng** [comment]
我准备删掉分类里边 method swizzling相关的代码

**Comment by jerrywangjing** [comment]
好的，希望优化下代码。这个视频库写的很好，谢谢作者的分享。

**Comment by colla2me** [comment]
![1535097405082](https://user-images.githubusercontent.com/26298112/44572417-519e1080-a7b6-11e8-9f65-44499d5d6ee6.jpg)

唉，已经崩溃几次了

- Hook 1 (expr -- @import UIKit)

- Hook 2 (target stop-hook disable)
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

**Comment by melote** [comment]
我也遇到了，参考这个 #480
