### ISSUE TITLE
uiscrollView中不能播放

### ISSUE THREAD

**Issue by CDYeah** [renzifeng/ZFPlayer#52]
- (ZFPlayerView *)playerView{
  if (_playerView == nil) {
  _playerView = [[ZFPlayerView alloc] init];
  }
  
  return _playerView;
  }
- (IBAction)clickPlayButton:(id)sender {
  
  __weak typeof(self) weakSelf = self;
  
     [self.newsImageView addSubview:self.playerView];
  [self.playerView mas_makeConstraints:^(MASConstraintMaker *make) {
  
  ```
  //make.top.equalTo(self.view).offset(70);
  //make.left.right.equalTo(self.view);
  
  //make.height.equalTo(self.playerView.mas_width).multipliedBy(9.0f/16.0f).with.priority(750);
  
  make.top.leading.bottom.trailing.equalTo(self.newsImageView);
  ```
  
  }];
  
  DLog(@"%@",self.newsDetailsModel.video);
  self.playerView.videoURL = [NSURL URLWithString:self.newsDetailsModel.video];
  
  self.playerView.goBackBlock = ^{
      [weakSelf.navigationController popViewControllerAnimated:YES];
  };

}

视频是MP4格式

**Comment by renzifeng** [comment]
得看具体代码，你这描述的我也不清楚呀。不能播放是指的提示播放失败吗

**Comment by CDYeah** [comment]
沾出来的代码就是啊，ZFPlayerView这个对象粘贴到uiscrollview中的一个imageview上边，点击imageview上的播放button，进行创建ZFPlayerView 对象，添加视图，指定url，然后播放，之歌过程有问题么？这个是粘贴你的实例的代码

**Comment by renzifeng** [comment]
看着是没问题的呀，你看一下是不是视频源的问题，用我demo的视频地址？

**Comment by CDYeah** [comment]
你的视频地址可以，我看一下怎么回事，你的视频播放开始的时候显示的图片我去掉了没有问题吧loading_bgView  就是这个图片，没有他下边的按钮好像遮盖不住啊
