### ISSUE TITLE
rate设置比1小的时候，本地视频播放会随着rate减小越发的卡顿

### ISSUE THREAD

**Issue by DreamParagon** [renzifeng/ZFPlayer#522]

**Comment by renzifeng** [comment]
rate本身就是倍速播放，小于1自然会播放缓慢，会有卡顿的现象吧

**Comment by DreamParagon** [comment]
<img width="1358" alt="2018-08-30 10 15 38" src="https://user-images.githubusercontent.com/5466178/44825558-b1287000-ac3d-11e8-942e-d26391e5c4a6.png">
我查到是这行代码的问题，我把这个注释掉后，视频在低于1rate的情况下，可以流畅的缓慢播放
