### ISSUE TITLE
死循环

### ISSUE THREAD

**Issue by lionjohn** [renzifeng/ZFPlayer#524]
遇到一个死循环，看代码发现是zf_scrollViewDidScroll调用引起的，确定下面的代码自己调用自己，不会死循环吗？ 还是我的使用方式有问题？

- (void)zf_scrollViewDidEndDecelerating:(UIScrollView *)scrollView {
    [scrollView add_scrollViewDidEndDecelerating:scrollView];
    [self zf_scrollViewDidEndDecelerating:scrollView];
}

- (void)zf_scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate {
    [scrollView add_scrollViewDidEndDragging:scrollView willDecelerate:decelerate];
    [self zf_scrollViewDidEndDragging:scrollView willDecelerate:decelerate];
}

- (void)zf_scrollViewDidScrollToTop:(UIScrollView *)scrollView {
    [scrollView add_scrollViewDidScrollToTop:scrollView];
    [self zf_scrollViewDidScrollToTop:scrollView];
}

- (void)zf_scrollViewDidScroll:(UIScrollView *)scrollView {
    [scrollView add_scrollViewDidScroll:scrollView];
    [self zf_scrollViewDidScroll:scrollView];
}

- (void)zf_scrollViewWillBeginDragging:(UIScrollView *)scrollView {
    [scrollView add_scrollViewWillBeginDragging:scrollView];
    [self zf_scrollViewWillBeginDragging:scrollView];
}

**Comment by melote** [comment]
我也也遇到了，提交了#480，请查看，我目前使用了一个分类临时性的解决了该问题。

**Comment by renzifeng** [comment]
这个问题，我近期会改，去掉分类里的hook代码
