### ISSUE TITLE
一个小问题,希望能得到您的回复

### ISSUE THREAD

**Issue by CoderST** [renzifeng/ZFPlayer#529]
大神你好,框架很强大,但是demo中视频的占位图和视频切换播放的瞬间,会闪一下,有时候会黑一下,看到您的代码里添加了下面代码,但是感觉还是会黑闪一下.我也看了此类的issues,在加载状态里添加动画过渡,在快速来回滚动视频,偶尔还会出现黑闪,希望能得到您的解答,谢谢!
- (void)setPlayer:(ZFPlayerController *)player {
    _player = player;
    /// 封面图加到播放视图底部了，解决播放时候黑屏闪一下问题
    [player.currentPlayerManager.view insertSubview:self.coverImageView atIndex:0];
    self.coverImageView.frame = player.currentPlayerManager.view.bounds;
    self.coverImageView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
}

**Comment by renzifeng** [comment]
这个暂时还没想到更好的解决办法
