### ISSUE TITLE
按下锁定按钮，依然可以手势操作

### ISSUE THREAD

**Issue by heyehao2008** [renzifeng/ZFPlayer#53]
还有其他一些细小bug，偶尔出现了两次。不能复现。写的非常不错了。希望加入播放状态的代理。比如按下暂停、播放。开始播放，完成播放等。很多时候需要在暂停是弹出广告，或者播放前先播放一段视频广告。

**Comment by renzifeng** [comment]
好的，谢谢、

**Comment by shiwensong** [comment]
你好，就是这个点击了锁频按钮，依然可以手势操作界面这个问题解决了？我现在这里还是会出现这样的问题，版本号：2.1.1。
