### ISSUE TITLE
slider 和 bufferProgress 错位

### ISSUE THREAD

**Issue by colla2me** [renzifeng/ZFPlayer#530]
3.1.5 版本
横屏切换回竖屏，slider 和 bufferProgress 会错位
调用 replay 之后，slider 和 bufferProgress 会错位

**Comment by JuneWithJuly** [comment]
1分钟以下的视频，手动拉进度条reply时进度条往前错位


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
