### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by 1277393484** [renzifeng/ZFPlayer#534]
作者你好，tableView小窗播放中，如何只允许左右滑动，不能上下滑动(调整亮度，音量)手势，Demo中小窗播放中把滑动手势全部禁止了。

**Comment by 1277393484** [comment]
已解决

**Comment by WanMeg** [comment]
你好，请问你的小窗模式是（比如点击按钮进入视频播放页面，这时返回上个页面 显示出小窗播放）这种类型吗

**Comment by renzifeng** [comment]
不是，里边的小窗模式是列表滑出可见区域后显示的
