### ISSUE TITLE
视频播放的时候，调节音量有bug

### ISSUE THREAD

**Issue by DotaAntiMagic** [renzifeng/ZFPlayer#539]
你好,视频播放的时候,手动滑动屏幕调节音量有明显的bug

**Comment by renzifeng** [comment]
是在真机吗

**Comment by f2yu** [comment]
是不是哪个地方取值有问题，断点volumeBrightnessView.updateProgress这个方法赋值的地方，把相关的代码贴出来，我把控制层用swift写了一次，处理通知的时候类型处理错了，改一下就没问题了。
    /// 音量改变的通知
    @objc func volumeChanged(notification: Notification) {
        let volume = notification.userInfo?["AVSystemController_AudioVolumeNotificationParameter"] as? Float ?? 0
        if self.player?.isFullScreen ?? false {
            self.volumeBrightnessView.updateProgress(CGFloat(volume), with: .typeVolume)

        } else {
            self.volumeBrightnessView.addSystemVolumeView()

        }
    }
