### ISSUE TITLE
在下载过程中进入下载控制器此时更换控制器时出现bug

### ISSUE THREAD

**Issue by uSERken** [renzifeng/ZFPlayer#54]
问题：在点击下载后，视频界面pop掉，进入一个主控制的viewcontroller，再点击push进入下载的控制器，正常显示下载内容及下载过程。但是在下载过程中，pop回主控制器后再进入另一主控制器时报错。

报错位置：ZFDownloadManager.m 中 
 dispatch_async(dispatch_get_main_queue(), ^{
        if ([self.delegate respondsToSelector:@selector(downloadResponse:)]) {
            [self.delegate downloadResponse:sessionModel];
        }
   });
错误提示：Thread1: EXC_BAD_ACCESS(code=EXC_1386_GPFLT)

**Comment by chengxianghe** [comment]
此处主要是delegate 属性是 assgin的缘故 改为 weak即可
