### ISSUE TITLE
大佬，demo播放视频，然后退到后台，播放停止了， self.player.pauseWhenAppResignActive = NO;这个是允许后台播放的

### ISSUE THREAD

**Issue by iOSYXT** [renzifeng/ZFPlayer#541]
大佬，demo播放视频，然后退到后台，播放停止了，但是 self.player.pauseWhenAppResignActive = NO;这个是允许后台播放的

**Comment by dota2AndTI** [comment]
先看看这个https://www.jianshu.com/p/71ab0e828c0a，从zfplayer中找到 ZFAVPlayerManager类在.m中添加通知并实现方法，记住需要在连个地方添加 ZFAVPlayerManager的init和ZFPlayerPresentView的setPlayer:(AVPlayer *)player。我是这么完成的

**Comment by renzifeng** [comment]
首先工程里得配置支持后台播放

**Comment by dota2AndTI** [comment]
只是配置好了，也不能实现点击home键后实现继续播放

**Comment by iOSYXT** [comment]
大佬，我是直接下载并运行你的demo，退到后台，视频播放停止了，

**Comment by iOSYXT** [comment]
简书链接打不开，404了。。

**Comment by iOSYXT** [comment]
大神，厉害，我在ZFAVPlayerManager的init和ZFPlayerPresentView两个地方都添加通知，并实现方法，闪退了，但是我只在ZFPlayerPresentView里添加通知，是可以实现后台播放，但是出现一个问题，回到前台，视频是黑屏状态，声音是播放的，这是为什么

**Comment by renzifeng** [comment]
我这边测试正常啊

**Comment by dota2AndTI** [comment]
- (void)setPlayer:(AVPlayer *)player {
    if (player == _player) return;
    _player = player;
    self.avLayer.player = player;
    
    NSNotificationCenter *center = [NSNotificationCenter defaultCenter];
    [center addObserver:self
               selector:@selector(resetPlayerToPlayerLayer)
                   name:UIApplicationWillEnterForegroundNotification
                 object:nil];
    [center addObserver:self
               selector:@selector(removePlayerOnPlayerLayer)
                   name:UIApplicationDidEnterBackgroundNotification
                 object:nil];
}

**Comment by iOSYXT** [comment]
谢谢大神，_player = player;  就差这句，加上就好了，ZFAVPlayerManager的init里不添加通知是不是也没问题，因为init里加了通知会闪退

**Comment by dota2AndTI** [comment]
我这两个地方都有，你的没问题就行了。这个问题我想折改了一天。。。。

**Comment by iOSYXT** [comment]
GitHub上的这个版本，我下载了直接运行，不修改任何代码，确实是无法后台播放的。按照dota2AndTI兄弟说的，添加通知以后，就可以后台播放了，不明白到底是为啥。

**Comment by iOSYXT** [comment]
两位大佬，我把新加的通知代码都去掉了，重新测试了一下GitHub的版本，又没有问题了，但是我确实什么也没改。我发现播放视频然后退到后台的时候，视频声音会卡顿一下，是不是因为这个原因，导致了有很小的几率直接卡住视频，无法继续播放？

**Comment by dota2AndTI** [comment]
ios11以后卡顿了之后就无法继续播放了

**Comment by Aduir** [comment]
> * (void)setPlayer:(AVPlayer *)player {
>   if (player == _player) return;
>   _player = player;
>   self.avLayer.player = player;
>   NSNotificationCenter *center = [NSNotificationCenter defaultCenter];
>   [center addObserver:self
>   selector:@selector(resetPlayerToPlayerLayer)
>   name:UIApplicationWillEnterForegroundNotification
>   object:nil];
>   [center addObserver:self
>   selector:@selector(removePlayerOnPlayerLayer)
>   name:UIApplicationDidEnterBackgroundNotification
>   object:nil];
>   }

你好，我发现这个方式在最新的4.0.2版本反而是失效了(在线m3u8地址)。旧版本反而可以，太奇怪了
