### ISSUE TITLE
播放网络视频为何一卡一卡的? 你们有遇到吗?

### ISSUE THREAD

**Issue by xiaohange** [renzifeng/ZFPlayer#542]

**Comment by xiongq** [comment]
兄弟  肯定是用的AVplayer....视频原因，Chrome 播放都是卡卡卡。。。Safari 也是

**Comment by xiaohange** [comment]
> 兄弟 肯定是用的AVplayer....视频原因，Chrome 播放都是卡卡卡。。。Safari 也是

这个不会错的, 最终使用了 ffmpeg 源码改造

**Comment by xiongq** [comment]
视频是啥原因
能详细说说么
