### ISSUE TITLE
希望添加一个适配UIAlertController旋转的分类

### ISSUE THREAD

**Issue by chaserr** [renzifeng/ZFPlayer#548]
如果全屏播放状态下直接点击返回按钮，在返回按钮中添加alert事件导致崩溃
crash日志：
UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [UIAlertController shouldAutorotate] is returning YES

**Comment by Monkey-D-Mark** [comment]
自己百度一个啊，我也遇到这个问题了，就几行代码
@implementation UIAlertController (SupportedInterfaceOrientations)
#if __IPHONE_OS_VERSION_MAX_ALLOWED < 90000
- (NSUInteger)supportedInterfaceOrientations{
    return UIInterfaceOrientationMaskPortrait;
}
#else
- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskPortrait;
}
#endif

**Comment by chaserr** [comment]
@Monkey-D-Mark 嗯，thx,我只是希望这个库能包含这个可能性，完善一点

**Comment by renzifeng** [comment]
楼上正解，建议自己加
