### ISSUE TITLE
iOS7视频全屏

### ISSUE THREAD

**Issue by bengyuejiejie** [renzifeng/ZFPlayer#55]
想问下在iOS7，iPhone4s下点击全屏的时候没有全屏播放，约束不正确，其它系统上是OK的

**Comment by renzifeng** [comment]
我知道iOS7，iPhone4s下全屏有问题，没有去适配，最低支持iOS8+

**Comment by niunaruto** [comment]
能不能做下适配呢

**Comment by renzifeng** [comment]
没办法测试，暂时没做适配计划

**Comment by zhengwu119** [comment]
/**
 *设置横屏的约束
 */
-(void)setOrientationLandscape{
    if (self.isCellVideo) {
        
        // 横屏时候移除tableView的观察者
        if (self.tableView && [self observationInfo]){
            @try {
                [self.tableView removeObserver:self forKeyPath:kZFPlayerViewContentOffset];
            }
            @catch(NSException *exception){NSLog(@"exception:%@",exception);}
        }
        
        [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent animated:YES];
        // 亮度view加到window最上层
        ZFBrightnessView *brightnessView = [ZFBrightnessView sharedBrightnessView];
         if (iOS7 && !self.isBottomVideo){
             UIViewController *viewCtl = [Tools getTopMostViewController];
             [viewCtl.view insertSubview:self belowSubview:brightnessView];
         }else{
             [[UIApplication sharedApplication].keyWindow insertSubview:self belowSubview:brightnessView];
         }
        [self mas_remakeConstraints:^(MASConstraintMaker *make) {
            make.edges.insets(UIEdgeInsetsMake(0, 0, 0, 0));
        }];
        
        self.controlView.fullScreenBtn.selected = YES;
    }
}

**Comment by vaercly** [comment]
适配一下iPhone4的机型就完美了,期待..
