### ISSUE TITLE
快来适配xcode10

### ISSUE THREAD

**Issue by GPPG** [renzifeng/ZFPlayer#550]
ibrary not found for -lstdc++.6

**Comment by renzifeng** [comment]
IJKMediaFramework已经适配支持了

**Comment by GPPG** [comment]
KSYMediaPlayer_iOS这个库依然不支持

**Comment by GPPG** [comment]
> IJKMediaFramework已经适配支持了

KSYMediaPlayer_iOS这个库依然不支持

**Comment by renzifeng** [comment]
这个库得找金山来更新
