### ISSUE TITLE
作者能回答我的问题吗 ？

### ISSUE THREAD

**Issue by guojingjingghost** [renzifeng/ZFPlayer#551]
为什么？ZAPlayer 调用了stop和然后置为nil 离开播放页面那个ZFplayer并没有立刻释放有时要等好几分钟释放呢？ 人为的一直进播放页面播放视频在离开播放页面 内存增长很快 。。。。大神能帮我解决下吗

**Comment by guojingjingghost** [comment]
已解决 === 那个可能是在viewDidAppear里发送释放播放器的通知造成释放缓慢 === 造成延迟释放  ===在viewWillDisappear里发送通知就可以了

**Comment by renzifeng** [comment]
issues回复不及时，有问题建议还是去QQ群
