### ISSUE TITLE
播放优酷视频的问题

### ISSUE THREAD

**Issue by Easyzhan** [renzifeng/ZFPlayer#558]
点击开始播放，屏幕闪一下，然后就黑屏了，进度条一直进，但是还是黑屏的状态

**Comment by Easyzhan** [comment]
拖一下进度条又播了一下，然后接着黑屏

**Comment by Easyzhan** [comment]
用//    ZFAVPlayerManager *playerManager = [[ZFAVPlayerManager alloc] init];
播放就黑屏，但进度条在前进，用
    ZFIJKPlayerManager *playerManager = [[ZFIJKPlayerManager alloc] init];
就自动跳播，还会报错
 -[UIApplication applicationState]
PID: 8697, TID: 144716, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   Badminton                           0x000000010a2321b3 -[IJKSDLGLView isApplicationActive] + 83
5   Badminton                           0x000000010a23270c -[IJKSDLGLView display:] + 53
6   libdispatch.dylib                   0x000000011397d7ab _dispatch_call_block_and_release + 12
7   libdispatch.dylib                   0x000000011397e7ec _dispatch_client_callout + 8
8   libdispatch.dylib                   0x000000011398a61d _dispatch_root_queue_drain + 1353
9   libdispatch.dylib                   0x000000011398a076 _dispatch_worker_thread3 + 132
10  libsystem_pthread.dylib             0x0000000113eac6ee _pthread_wqthread + 619
11  libsystem_pthread.dylib             0x0000000113eac415 start_wqthread + 13
2018-09-27 10:13:14.395051+0800 Badminton[8697:144716] [reports] Main Thread Checker:

**Comment by Zhumeng223** [comment]
我也遇到了这个问题，请问您解决了吗？
