### ISSUE TITLE
为什么我集成的3.0版本的，点击全屏按钮，不可以横屏

### ISSUE THREAD

**Issue by zhangqi02060227m** [renzifeng/ZFPlayer#559]
为什么我集成的3.0版本的，点击全屏按钮，不可以横屏，显示的是横屏的全屏。
我是把播放器集成在了一个单独的view 中。在view 中写了
//  是否支持自动转屏
- (BOOL)shouldAutorotate
{
    return YES;
}

- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    if (self.player.isFullScreen) {
        return UIInterfaceOrientationMaskLandscape;
    }
    return UIInterfaceOrientationMaskPortrait;
}

- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation
{
    return UIInterfaceOrientationPortrait;
}

**Comment by halocq** [comment]
兄弟，已经好了吗？我也遇到这个问题了
