### ISSUE TITLE
coverImageView 和 - (void)showTitle:(NSString *)title coverURLString:(NSString *)coverUrl fullScreenMode:(ZFFullScreenMode)fullScreenMode 区别

### ISSUE THREAD

**Issue by zhangqi02060227m** [renzifeng/ZFPlayer#560]
/// 封面图
@property (nonatomic, strong, readonly) UIImageView *coverImageView;

/// 设置标题、封面、全屏模式
- (void)showTitle:(NSString *)title coverURLString:(NSString *)coverUrl fullScreenMode:(ZFFullScreenMode)fullScreenMode;

这两个有什么区别，为什么我两个一起设置就不能全屏了，有什么冲突吗？

**Comment by renzifeng** [comment]
封面的url就是使用coverImageView来展示的，经测试同时使用不会造成无法全屏
