### ISSUE TITLE
切换到横屏后手势识别有问题

### ISSUE THREAD

**Issue by woxihejinghao** [renzifeng/ZFPlayer#564]
从竖屏切换到横屏播放后,手势识别会错乱,右半边区域手势识别错误,单击会调用拖拉的手势方法,并且在右边添加控件后不能触发控件的点击方法

**Comment by renzifeng** [comment]
怎么复现的 麻烦提供demo

**Comment by itdongbaojun** [comment]
我也遇到同样的问题了，这个问题最后怎么解决的？ @woxihejinghao @renzifeng

**Comment by itdongbaojun** [comment]
问题已解决，和业务方项目结构有关系，如果使用UITabbarController的时候，在viewDidLoad执行完成后，如果对应的UITabbarController还没有viewControllers，就会有一定概率导致横屏后存在问题。目前通过限制业务方的使用方法来解决了。特此记录一下。
