### ISSUE TITLE
视频插件播放的背景图开发出来

### ISSUE THREAD

**Issue by lingsui** [renzifeng/ZFPlayer#57]
![loading_bgview](https://cloud.githubusercontent.com/assets/9814013/16066206/e9be859c-32e3-11e6-8e10-ba96cde339b6.png)

**Comment by lingsui** [comment]
请问作者这个背景图什么时候公开出来或者提供接口修改

**Comment by rydensun** [comment]
这个一直有啊。你仔细看一下就有了。

**Comment by renzifeng** [comment]
这个接口我已经增加啦，更新代码看看，暂时是设置本地图片，网络图片的话你改一下代码就知道怎么设置啦。

**Comment by lingsui** [comment]
不好意思，看到了，我没有更新
