### ISSUE TITLE
swift4.2下头文件引用问题

### ISSUE THREAD

**Issue by hujiaju** [renzifeng/ZFPlayer#573]
环境swift4.2下，3.1.8pod安装没有问题，3.2.0下pod直接安装头文件引用报错！

**Comment by renzifeng** [comment]
你先用3.1.8，我想办法解决下

**Comment by hujiaju** [comment]
好的，谢谢




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            胡家驹
                            
                            
                                
                                    邮箱：nanhujiaju@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


在2018年10月16日 10:05，紫枫 写道： 你先用3.1.8，我想办法解决下

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/renzifeng/ZFPlayer","title":"renzifeng/ZFPlayer","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/renzifeng/ZFPlayer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@renzifeng in #573: 你先用3.1.8，我想办法解决下"}],"action":{"name":"View Issue","url":"https://github.com/renzifeng/ZFPlayer/issues/573#issuecomment-430075042"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/renzifeng/ZFPlayer/issues/573#issuecomment-430075042",
"url": "https://github.com/renzifeng/ZFPlayer/issues/573#issuecomment-430075042",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [renzifeng/ZFPlayer] swift4.2下头文件引用问题 (#573)",
"sections": [
{
"text": "",
"activityTitle": "**紫枫**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@renzifeng",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"renzifeng/ZFPlayer\",\n\"issueId\": 573,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"renzifeng/ZFPlayer\",\n\"issueId\": 573\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/renzifeng/ZFPlayer/issues/573#issuecomment-430075042"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 392821049\n}"
}
],
"themeColor": "26292E"
}
]
