### ISSUE TITLE
怎么禁止APP其他页面横屏，使用播放器时可自转横屏

### ISSUE THREAD

**Issue by luo-h** [renzifeng/ZFPlayer#579]
我在Xcode中取消勾选Landscape Left和Landscape Right后还能横屏，是因为播放器里设置了shouldAutorotate为YES吗，那有没有办法让APP其他页面禁止横屏，仅在使用播放器时可自转横屏？

**Comment by renzifeng** [comment]
可以在APPDelageate实现`- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window ` 只在需要横屏的页面支持横屏，其他页面只支持竖屏
