### ISSUE TITLE
使用ijkplayer播放拉流类视频地址，声音跟画面不同步

### ISSUE THREAD

**Issue by chsla** [renzifeng/ZFPlayer#580]
ZFIJKPlayerManager *playerManager = [[ZFIJKPlayerManager alloc] init];  播放flv视频。跟网页端的直播相比，声音同步，但是画面明显会延迟很多。

**Comment by lujun5678275** [comment]
`[options setPlayerOptionIntValue:5 forKey:@"framedrop"];`
加上这一句话试试
