### ISSUE TITLE
播放本地视频黑屏

### ISSUE THREAD

**Issue by goodcyg** [renzifeng/ZFPlayer#584]
我是一直循环播放本地视频，播着播着。。。。，就出现黑屏了，我搜索了相关讨论说的代码，也没有找到地方，代码已经被我柔和我到项目中了，更新不太方便。这个问题是啥原因引起的？我应该在哪里定位问题？请楼主明示。建议在本地代码里也加个版本号，这样好区分下载代码版本，否则时间长了，不知道版本号了。

**Comment by huangyanan423** [comment]
请问有解决这个问题吗？我这里也遇到了
