### ISSUE TITLE
iPhone 已经出6.5寸屏了，ZFLandScapeControlView用x的那个宏不够用，作者及时更新哦

### ISSUE THREAD

**Issue by Monkey-D-Mark** [renzifeng/ZFPlayer#585]

**Comment by renzifeng** [comment]
这个宏刚出手机时候就已经更新过了 已经支持了

**Comment by Monkey-D-Mark** [comment]
在ZFPortraitControlView里 playOrPauseBtn的动画与bottomToolView不一致， 分别在以下方法中加入以下代码
- (void)layoutSubviews{
if(!self.isShow){self.playOrPauseBtn.y = self.height;}
else{self.playOrPauseBtn.y = self.height - self.playOrPauseBtn.height;}
 }

- (void)showControlView {
self.playOrPauseBtn.y = self.height - self.playOrPauseBtn.height;
}
- (void)hideControlView{
self.playOrPauseBtn.y = self.height;
}
