### ISSUE TITLE
IJKFFOptions 作者可否能把这个属性开放出来可写?

### ISSUE THREAD

**Issue by xiaohange** [renzifeng/ZFPlayer#588]
@property (nonatomic, strong, readonly) IJKFFOptions *options;

**Comment by renzifeng** [comment]
你直接在外边设置options就可以了，比如 `[ijkManager.options setPlayerOptionIntValue:1 forKey:@"enable-accurate-seek"]`

**Comment by xiaohange** [comment]
👌
