### ISSUE TITLE
在播放视频控制器页面打开滑动返回手势，当拖动时声音正常画面出现卡顿..

### ISSUE THREAD

**Issue by tiantiankaixin** [renzifeng/ZFPlayer#59]
拖动时画面卡顿音频正常，然后取消拖动；视频画面会突然变快，过一会儿恢复正常...
这是我录制的一个gif
http://7xt6lm.com1.z0.glb.clouddn.com/ZFPlayer.gif
@renzifeng @BB9z  @wukwei  @kangyeting  @XQ0820

**Comment by lihanst** [comment]
@renzifeng

**Comment by renzifeng** [comment]
https://forums.developer.apple.com/message/64110#64110
