### ISSUE TITLE
全屏之后statusBar还是竖屏状态

### ISSUE THREAD

**Issue by halocq** [renzifeng/ZFPlayer#590]
shouldAutorotate, supportedInterfaceOrientations都走了

**Comment by renzifeng** [comment]
还是竖屏状态这个和项目结构有关，打断点看会不会调用到当前播放器控制器的`shouldAutorotate`方法，必须保证所在控制器的shouldAutorotate返回NO

**Comment by halocq** [comment]
当前所在的控制器shouldAutorotate是为NO的

**Comment by halocq** [comment]
发现在点击全屏按钮的时候没有走shouldAutorotate的
