### ISSUE TITLE
更新之后，报错找不到头文件

### ISSUE THREAD

**Issue by CherishSmile** [renzifeng/ZFPlayer#591]
<img width="439" alt="image" src="https://user-images.githubusercontent.com/17586122/47408559-7c92e980-d792-11e8-99cf-cbee48cb4a10.png">

**Comment by renzifeng** [comment]
首先你是在swift里使用吗，如果在swift用的话使用3.1.8版本，3.2.0后会有问题

**Comment by CherishSmile** [comment]
没有在swift中使用，是OC项目，我把库删了，重新pod,也报头文件错误

**Comment by xiaoyao20084321** [comment]
对的,跟楼上一样
<img width="967" alt="qq20181025-165943 2x" src="https://user-images.githubusercontent.com/10344550/47488728-85112000-d877-11e8-8555-35bfd303dc22.png">

**Comment by cwli-cc** [comment]
同样，刚 pod update 了一下，头文件报错了

**Comment by renzifeng** [comment]
好的我查一下

**Comment by renzifeng** [comment]
我怀疑你们在podfile添加了 `use_frameworks!`

**Comment by CherishSmile** [comment]
基于项目的本身的原因，现在必须用use_frameworks，请问在用use_frameworks时，如何解决这个问题

**Comment by chaijh** [comment]
晕，这就不管了？

**Comment by esodck** [comment]
你好，有缘看到你的博客，我是cp直客，希望寻求你的合作，qq，2222223863

**Comment by esodck** [comment]
你好，有缘看到你，我是cp直客，寻求h5技术上架合作，加我qq：2222223863
