### ISSUE TITLE
iOS12下报错

### ISSUE THREAD

**Issue by alreadyRight** [renzifeng/ZFPlayer#594]
作者你好,导入您的库之后再xcode10,iOS12的环境下报错
报错内容为:ld: library not found for -lstdc++.6
应该如何解决

**Comment by alreadyRight** [comment]
好吧,删掉stdc++.6这个就行了

**Comment by WZSlike** [comment]
请问下在哪里删的？我用的cocopods引入的，知道这该怎么处理吗？
