### ISSUE TITLE
获取当前player

### ISSUE THREAD

**Issue by amoylong** [renzifeng/ZFPlayer#595]
请问有没有方法可以获取到当前活动的ZFPlayerController。因为项目用到的player放在childViewController。旋转动作在父控制器上，获取上很不方便。以前旧版还有个单例[ZFBrightnessView sharedBrightnessView]来获取当前player，现在一直没找到获取当前player的方法，求告知

**Comment by renzifeng** [comment]
以前版本是单例，现在已经不是单例了，你可以自己用单例保存一下当前player，不用时候记得置nil，不然有内存问题
