### ISSUE TITLE
全屏返回后，导航栏变窄，看起来状态栏重叠在一起了

### ISSUE THREAD

**Issue by lilin87788** [renzifeng/ZFPlayer#599]
![wechatimg107](https://user-images.githubusercontent.com/1483811/47637653-61134e80-db97-11e8-9e5e-4e3ad7bd9d12.jpeg)

**Comment by gleeeli** [comment]
同问

**Comment by renzifeng** [comment]
https://blog.csdn.net/Bloody_Leaves/article/details/76572313 亲测有效，果断关闭啦

**Comment by programmework** [comment]
https://blog.csdn.net/Bloody_Leaves/article/details/76572313  亲测无效
