### ISSUE TITLE
Auto Rotate Player View

### ISSUE THREAD

**Issue by xthaohg** [renzifeng/ZFPlayer#600]
Hi! I have a issue with zfplayer. I want disable auto rotate when device rotate. 

Excuse for using Google translate
Thank you so much!

**Comment by renzifeng** [comment]
you can set the `ZFPlayerController` property `allowOrentitaionRotation` to NO

**Comment by renzifeng** [comment]
You can set the `ZFPlayerController` property `allowOrentitaionRotation` to NO
