### ISSUE TITLE
播放器cell复用了

### ISSUE THREAD

**Issue by xiaoyao20084321** [renzifeng/ZFPlayer#601]
列表点击播放       ,在不播放的时候,滑动tableView,展示的信息是不复用的, 当点击播放的时候,滑动tableView, 会出现cell复用的情况,上面的在播放, 下面的也在播放同一个视频

**Comment by melo30** [comment]
> 列表点击播放 ,在不播放的时候,滑动tableView,展示的信息是不复用的, 当点击播放的时候,滑动tableView, 会出现cell复用的情况,上面的在播放, 下面的也在播放同一个视频
> 
> 没事了,我自己的问题

请问下你是什么原因
