### ISSUE TITLE
更新之后，报错找不到头文件

### ISSUE THREAD

**Issue by BeingCode** [renzifeng/ZFPlayer#607]
<img width="495" alt="126ba2c6-0ed5-4bed-85c0-2d4b7f24ceff" src="https://user-images.githubusercontent.com/44461496/47989392-d1821880-e11f-11e8-9c95-c806b2376714.png">

**Comment by MeteoriteMan** [comment]
改成双引号导入即可
```
#import "ZFPlayer.h"
```

**Comment by MeteoriteMan** [comment]
你这个应该是pod导入的.pod的话只能是3.1.8以及以下的...我是拖出来维护的...改成""括号了...
