### ISSUE TITLE
请问scrollVIew滚动出屏幕后画面暂停但是声音继续播放是什么问题

### ISSUE THREAD

**Issue by yukifeng** [renzifeng/ZFPlayer#610]

**Comment by yukifeng** [comment]
播放的cell滚出可视范围后，画面暂停了，但是声音还在，求教如何处理

**Comment by renzifeng** [comment]
滑出屏幕调用stopCurrentPlayingCell了吗

**Comment by yukifeng** [comment]
> 滑出屏幕调用stopCurrentPlayingCell了吗
设置self.player.stopWhileNotVisible = NO; 滑出屏幕后
zf_playerDidDisappearInScrollView没有回调。要自己监听contentoffset来关闭播放吗  我看到demo里面好像没有调用contentoffset呀
是点击播放（非自动）

**Comment by renzifeng** [comment]
看demo里 你肯定少写uiscrollview的那些代理了
