### ISSUE TITLE
抖音样式使用UICollectionview实现的滚动出现在问题

### ISSUE THREAD

**Issue by jolincheng** [renzifeng/ZFPlayer#614]
你好，我现在用collectionview实现抖音效果，水平滚动的时候 zf_scrollViewDidStopScrollCallback这个回调没有走，请问要怎么修改才能实现？zf_filterShouldPlayCellWhileScrolled这个回调也没有走

**Comment by renzifeng** [comment]
collectionView横屏还没适配
