### ISSUE TITLE
播放很短视频

### ISSUE THREAD

**Issue by jianqingyu** [renzifeng/ZFPlayer#616]
你好、播放很短视频的时候少于1秒。进度条的位置出现错乱

**Comment by jianqingyu** [comment]
而且每播放一次视频，进度就往左边移动一点

**Comment by jianqingyu** [comment]
应该是播放浮点型的比如3.04秒的视频   播放完进度条会往左移动

**Comment by amoylong** [comment]
我解决了个进度条位置错乱的问题，不知道和你说的是不是同一个问题
