### ISSUE TITLE
首次push到播放页卡顿

### ISSUE THREAD

**Issue by ChildrenGreens** [renzifeng/ZFPlayer#618]
第一次从其他页面push到播放页，很卡顿，这又什么解决办法么？

**Comment by xiangkesi** [comment]
在界面完全显示的时候在开始播放

**Comment by Allenzhan1225** [comment]
AVPlayer加载资源的时候造成主线程卡顿。导致collectionView 一段时间滑动不了

**Comment by guojingjingghost** [comment]
不是卡顿吧 是那个  - (UIStatusBarStyle)preferredStatusBarStyle {
    return UIStatusBarStyleDefault;
}
在控制器里加上这句代码试试

**Comment by DevinChiu** [comment]
我也有问题
