### ISSUE TITLE
下载回调的delegate 应该使用weak属性

### ISSUE THREAD

**Issue by chengxianghe** [renzifeng/ZFPlayer#62]
首先感谢作者的开源;
我在使用的时候偶发崩溃,经查阅应该是此处出了问题,还望及时更新.
ZFDownloadManager.h 59行
@property (nonatomic, assign) id<ZFDownloadDelegate> delegate;
此处应该改为:
@property (nonatomic, weak) id<ZFDownloadDelegate> delegate;

**Comment by renzifeng** [comment]
更新啦，谢谢
