### ISSUE TITLE
Swift4.2

### ISSUE THREAD

**Issue by xiangkesi** [renzifeng/ZFPlayer#623]
pod 引入3.1.8直接闪退 dyld: Symbol not found: _OBJC_CLASS_$_ZFAVPlayerManager
  Referenced from: /Users/zs/Library/Developer/CoreSimulator/Devices/1FBEDFEE-1768-49F9-8794-7D227BAF3166/data/Containers/Bundle/Application/3759C336-98AB-42A8-839B-B7EBF3E47474/ben_son.app/ben_son
  Expected in: /Users/zs/Library/Developer/CoreSimulator/Devices/1FBEDFEE-1768-49F9-8794-7D227BAF3166/data/Containers/Bundle/Application/3759C336-98AB-42A8-839B-B7EBF3E47474/ben_son.app/Frameworks/ZFPlayer.framework/ZFPlayer
 in /Users/zs/Library/Developer/CoreSimulator/Devices/1FBEDFEE-1768-49F9-8794-7D227BAF3166/data/Containers/Bundle/Application/3759C336-98AB-42A8-839B-B7EBF3E47474/ben_son.app/ben_son

**Comment by renzifeng** [comment]
从闪退信息看出ZFAVPlayerManager没有找到
