### ISSUE TITLE
podfile引用use_frameworks，怎么解决库引用冲突及路径配置问题？

### ISSUE THREAD

**Issue by Mr-Dsg** [renzifeng/ZFPlayer#626]
podfile引用use_frameworks，导入播放库冲突，而且找不到ZFPlayer里面的类，这个怎么解决的呢？

**Comment by renzifeng** [comment]
用3.2.2

**Comment by chaijh** [comment]
直接加代码

**Comment by Ai-FFei** [comment]
[!] The 'Pods-***' target has transitive dependencies that include static binaries: (/Users/js/Desktop/***/Pods/KSYMediaPlayer_iOS/framework/vod/KSYMediaPlayer.framework)
用了3.2.2，但是一直报错，求帮助，谢谢~

**Comment by renzifeng** [comment]
你用的swift吧，那你自己加代码吧

**Comment by 596932151** [comment]
> 直接加代码

怎么加，求解
