### ISSUE TITLE
打断其他app（比如音乐播放器）播放声音，怎么没有开放接口设置AVAudioSessionCategory ，我看你里面默认设置的playback

### ISSUE THREAD

**Issue by nibaJin** [renzifeng/ZFPlayer#630]

**Comment by nibaJin** [comment]
我如何修改音频的category

**Comment by nibaJin** [comment]
我只要初始化player 就会打断掉其他app的音乐播放，请问这个如何解决

**Comment by iwantFB** [comment]
> 我只要初始化player 就会打断掉其他app的音乐播放，请问这个如何解决

这个需要去设置AVAudioSession 的category 和 options 还有mode

**Comment by renzifeng** [comment]
下个版本我改一下

**Comment by nibaJin** [comment]
好的 thankyou

**Comment by shaop** [comment]
还在处理这个问题吗？ @renzifeng

**Comment by renzifeng** [comment]
已经处理完了，
设置customAudioSession为YES，然后自己设置AVAudionSession就行了
