### ISSUE TITLE
ijkplay不支持https吗？有时候播放不了，有时候能播放 换成avplay的时候就都能播放了？

### ISSUE THREAD

**Issue by tc1993** [renzifeng/ZFPlayer#636]
ijkplay不支持https吗？有时候播放不了，有时候能播放 换成avplay的时候就都能播放了？是不是打包ijk的时候没有添加

如果使用 https, 那么需要手动给 IJKMediaFramework 添加 libcrypto.a 和 libssl.a 文件, 默认不会添加

ps: 这两个依赖库的目录为: ijkplayer-ios/ios/build/universal/lib, 只有进行了上面跟 openssl 相关的操作, 才会在这个目录下有生成 libcrypto.a 和 libssl.a

**Comment by tc1993** [comment]
我试了 ijk是支持https的，但是在列表播放的时候，如果播放了https的 再切换播放http的 然后就播放不了https的视频了 应该是哪里没有清空 或者重置播放器  avplayer就不会出现这个问题，当杀死APP 再进去又能播放了

**Comment by renzifeng** [comment]
关于这个问题，可以自己重新打包ijk的framework
