### ISSUE TITLE
急：  后台锁屏后 2倍数播放，音频播放断断续续 （不正常）。

### ISSUE THREAD

**Issue by wscqs** [renzifeng/ZFPlayer#640]
添加了后台控制。  后台锁屏后 倍数播放，音频播放断断续续 （不正常）。
用自己封装的AVPlayer锁屏后台2倍数播放正常。

**Comment by lsqiang** [comment]
同样的问题

**Comment by wscqs** [comment]
else if ([keyPath isEqualToString:kLoadedTimeRanges]) {
            
            //Fix:倍数播放卡顿
//            if (self.isPlaying && self.playerItem.playbackLikelyToKeepUp) [self play];
            
            NSTimeInterval bufferTime = [self availableDuration];
            self->_bufferTime = bufferTime;
            if (self.playerBufferTimeChanged) self.playerBufferTimeChanged(self, bufferTime);
        } else if ([keyPath isEqualToString:kPresentationSize]) {
            self->_presentationSize = self.playerItem.presentationSize;
        } else {
            [super observeValueForKeyPath:keyPath ofObject:object change:change context:context];
        }

**Comment by lsqiang** [comment]
我这样改了 但是无法后台播放了

**Comment by wscqs** [comment]
> 我这样改了 但是无法后台播放了
我的可以正常后台播,你查看下是什么原因导致

**Comment by lsqiang** [comment]
是的

**Comment by lsqiang** [comment]
解决了 UIApplicationDidEnterBackgroundNotification   监听进入后台的通知  然后再进入后台以后   延迟0.5秒执行  [self play]  就可以继续播了

**Comment by wscqs** [comment]
> 解决了 UIApplicationDidEnterBackgroundNotification 监听进入后台的通知 然后再进入后台以后 延迟0.5秒执行 [self play] 就可以继续播了

我也想到这方法， 但是没设置延迟，继续播放无效。 哈哈，延迟有时真好用，延迟0.1秒就可以了（虽然还是有断播状态）

**Comment by shiwei93** [comment]
> else if ([keyPath isEqualToString:kLoadedTimeRanges]) {
> 
> ```
>         //Fix:倍数播放卡顿
> ```
> // if (self.isPlaying && self.playerItem.playbackLikelyToKeepUp) [self play];
> 
> ```
>         NSTimeInterval bufferTime = [self availableDuration];
>         self->_bufferTime = bufferTime;
>         if (self.playerBufferTimeChanged) self.playerBufferTimeChanged(self, bufferTime);
>     } else if ([keyPath isEqualToString:kPresentationSize]) {
>         self->_presentationSize = self.playerItem.presentationSize;
>     } else {
>         [super observeValueForKeyPath:keyPath ofObject:object change:change context:context];
>     }
> ```

注释了这段代码，会在慢网速的情况下，无法在缓存完成后正常自动播放。也会使得后台播放中断(虽然后台播放视频，有点中二)，可以在监听 `AVPlayerItem.isPlaybackLikelyToKeepUp` 中判断是否正在播放，来继续播放

```
 } else if ([keyPath isEqualToString:kPlaybackLikelyToKeepUp]) {
     // When the buffer is good
     if (self.playerItem.playbackLikelyToKeepUp) {
         self.loadState = ZFPlayerLoadStatePlayable;
          if (self.isPlaying) [self play];
      }
}
```

**Comment by lsqiang** [comment]
> > 解决了 UIApplicationDidEnterBackgroundNotification 监听进入后台的通知 然后再进入后台以后 延迟0.5秒执行 [self play] 就可以继续播了
> 
> 我也想到这方法， 但是没设置延迟，继续播放无效。 哈哈，延迟有时真好用，延迟0.1秒就可以了（虽然还是有断播状态）

哈哈  是的  系统的机制问题

**Comment by wscqs** [comment]
> > else if ([keyPath isEqualToString:kLoadedTimeRanges]) {
> > ```
> >         //Fix:倍数播放卡顿
> > ```
> > // if (self.isPlaying && self.playerItem.playbackLikelyToKeepUp) [self play];
> > ```
> >         NSTimeInterval bufferTime = [self availableDuration];
> >         self->_bufferTime = bufferTime;
> >         if (self.playerBufferTimeChanged) self.playerBufferTimeChanged(self, bufferTime);
> >     } else if ([keyPath isEqualToString:kPresentationSize]) {
> >         self->_presentationSize = self.playerItem.presentationSize;
> >     } else {
> >         [super observeValueForKeyPath:keyPath ofObject:object change:change context:context];
> >     }
> > ```
> 
> 注释了这段代码，会在慢网速的情况下，无法在缓存完成后正常自动播放。也会使得后台播放中断(虽然后台播放视频，有点中二)，可以在监听 `AVPlayerItem.isPlaybackLikelyToKeepUp` 中判断是否正在播放，来继续播放
> 
> ```
>  } else if ([keyPath isEqualToString:kPlaybackLikelyToKeepUp]) {
>      // When the buffer is good
>      if (self.playerItem.playbackLikelyToKeepUp) {
>          self.loadState = ZFPlayerLoadStatePlayable;
>          if (self.isPlaying) [self play];
>      }
> }
> ```

这方法我也试过，但是进入后台，没有马上执行你这方法。
