### ISSUE TITLE
国内ipv6wifi下播放报 IJKSDLGLView: setupDisplay not ready 

### ISSUE THREAD

**Issue by xiaohange** [renzifeng/ZFPlayer#641]
这个是什么原因呢?

**Comment by queli1990** [comment]
请问，你用IJK播放的时候拖动进度条，可以实现快进吗？

**Comment by xiaohange** [comment]
> 请问，你用IJK播放的时候拖动进度条，可以实现快进吗？

可以

**Comment by renzifeng** [comment]
这个问题是打包的那个framework不支持ipv6吧

**Comment by xiaohange** [comment]
@renzifeng 通过询问IJK作者得知, 手动调用清理CDN缓存可以解决!

**Comment by queli1990** [comment]
手动调用清理CDN缓存可以解决!请问是哪里的缓存？怎么清理呢？
