### ISSUE TITLE
ZFAVPlayerManager ZFIJKPlayerManager currentTime 存在小于0的问题

### ISSUE THREAD

**Issue by pengpaiGuo** [renzifeng/ZFPlayer#645]
- (void)update {
    NSTimeInterval currentPlaybackTime = self.player.currentPlaybackTime;
    self->_currentTime = currentPlaybackTime < 0 ? 0 : currentPlaybackTime;
    self->_totalTime = self.player.duration;
    self->_bufferTime = self.player.playableDuration;
    if (self.playerPlayTimeChanged) self.playerPlayTimeChanged(self, self.currentTime, self.totalTime);
    if (self.playerBufferTimeChanged) self.playerBufferTimeChanged(self, self.bufferTime);
}

**Comment by pengpaiGuo** [comment]
- (NSTimeInterval)currentTime {
    NSTimeInterval sec = CMTimeGetSeconds(self.playerItem.currentTime);
    if (isnan(sec)) {
        return 0;
    }
    if (sec < 0) {
        return 0;
    }
    return sec;
}

**Comment by renzifeng** [comment]
thank you
