### ISSUE TITLE
iPhoneX系列横屏后适配问题

### ISSUE THREAD

**Issue by LXJason** [renzifeng/ZFPlayer#652]
iPhonex全屏 左右两边没适配好  求解决代码!  谢谢了

**Comment by LXJason** [comment]
刚刚看了源码 全屏下有捏合手势

**Comment by LXJason** [comment]
刚刚看了下源码 全屏下有捏合手势,  或者改scalingMode:               player.currentPlayerManager.scalingMode = ZFPlayerScalingModeFill;

**Comment by ixiaozhi** [comment]
谢谢。
