### ISSUE TITLE
怎样播放分段的m3u8视频？

### ISSUE THREAD

**Issue by Zhumeng223** [renzifeng/ZFPlayer#653]
你好，我想请问一下怎样播放多个分段的m3u8的视频呢？

**Comment by sixqq** [comment]
> 你好，我想请问一下怎样播放多个分段的m3u8的视频呢？

我想问一下播放m3u8的视频，用zfplayer的那个Manager，我这边播放不了啊

**Comment by renzifeng** [comment]
分段的M3U8 是不支持的

**Comment by dumplingsChina** [comment]
用ijk的

**Comment by Zhumeng223** [comment]
那么分段的mp4格式支持吗？
