### ISSUE TITLE
有个bug不好复现，我在viewWillDisappear已经把视频stop，但有时候莫名就会有视频播放的声音，怎么弄都消失不掉，重新进入视频界面就会变成2个声音在播放

### ISSUE THREAD

**Issue by chsla** [renzifeng/ZFPlayer#656]
-(void)viewWillDisappear:(BOOL)animated{

    [super viewWillDisappear:YES];
    
    if (self.player.currentPlayerManager.isPlaying) {
        
        [self.player stop];
    }
 
}

这是视频播放界面

**Comment by chueh** [comment]
我也遇到这问题了，请问您是怎么解决的
