### ISSUE TITLE
布局混乱

### ISSUE THREAD

**Issue by webMing** [renzifeng/ZFPlayer#657]
###问题复现:
在demo 例子中, 点击-->普通样式-->点击播放按钮-->点击进入横屏的按钮-->进入横屏后 点击home键; 进入后台, 等待3~4秒再次打开demo --> 点击横屏状态下的返回按钮 返回到竖屏状态,发现界面布局发生混乱;(如果不能还原多试几次)

###可能出现问题的地方: statusBar的隐藏和显示，在进入后台的时候没有处理好.. 试着改了一些代码但是没有效果

###引发的另一个问题
 IQKeyBoard 输入的时候 IQToolBar显示位置不正确，
在横屏播放视频的时候只要进入后台，再返回，然后进入到任意有可以输入的VC中进行输入就会出现这个问题, 令人困惑的地方是 只要再进入一次后台，然后再次返回后进行输入这个问题就没有了, 
![](https://github.com/webMing/SFImages/blob/master/SFImages/IMG_2298.PNG?raw=true)

 ###可能出现问题的地方: ZFPlayerController.notifaction.willResignActive  和  ZFPlayerController.notifaction.didBecomeActive 处理逻辑 可能和 controllerView autoFadeOutControlView 有冲突？？？？？？

试了很多办法，暂时还没有解决这个问题,麻烦作者处理这个问题的时候也看一下 IQKeyBorad 的问题.

**Comment by webMing** [comment]
在issues 中看到相同的问题编号: #599  #281 ,发现如果出现这种问题，再进入后台一次然后再回到前台就好了.....................   哪位可以解答一下o .

**Comment by shenhaihua002** [comment]
全屏的时候设置状态栏直接隐藏或者显示

**Comment by webMing** [comment]
> 全屏的时候设置状态栏直接隐藏或者显示

嗯，最早想到的也是这个方法.但如果项目中引用IQKeyBoard的话, 会出现输入框位置错乱.

**Comment by renzifeng** [comment]
https://blog.csdn.net/Bloody_Leaves/article/details/76572313  亲测有效，果断关闭啦

**Comment by zzzzzyijie** [comment]
1. 不用设置  self.navigationController.navigationBar.jz_height = (iPhoneXSeries ? 88 : 64);

2. 不用调用 self.videoPlayer.isStatusBarHidden;
//- (BOOL)prefersStatusBarHidden {
//    return self.videoPlayer.isStatusBarHidden;
//}

3. 改为这样
-(BOOL)prefersStatusBarHidden {
    UIInterfaceOrientation oritentation = [[UIApplication sharedApplication] statusBarOrientation];
    return UIInterfaceOrientationIsLandscape(oritentation);
}

完美解决这个问题。（  测试环境iOS12、iOS 13 非刘海屏和刘海屏 ， 都没问题
