### ISSUE TITLE
视频下载

### ISSUE THREAD

**Issue by 2952883085** [renzifeng/ZFPlayer#658]
你好，请问怎么将视频下载完成保存到相册呢？我记得以前demo直接有下载案例的

**Comment by renzifeng** [comment]
下载是单独的模块，之前写的那个有bug，后期没用再更新了

**Comment by 2952883085** [comment]
你好！我在新版本里下载功能用了你写的ZFDownLoad，我在新版本播放界面加入了下载按钮，当点击下载按钮的时候，视频突然从全屏变成小屏，而且导航栏也出来了，能加入下载功能吗？感觉写的真不错，能发我一份有下载功能demo不？谢谢了
