### ISSUE TITLE
Demo不是3.0的版本吗？

### ISSUE THREAD

**Issue by ywdonga** [renzifeng/ZFPlayer#665]
Demo不是3.0的版本吗？感觉不太会用，看Dmeo又发现版本对不上，求更新啊。。。

**Comment by renzifeng** [comment]
demo就是3.x版本，你如果用2.x的化肯定对不上

**Comment by ywdonga** [comment]
![image](https://user-images.githubusercontent.com/16291063/50671721-89438180-100e-11e9-9c3b-90581cb7a516.png)
为啥Demo里面的pod有`ZFAVPlayerManager`但是我的`3.0`的pod里面没`ZFAVPlayerManager`类呢？

**Comment by renzifeng** [comment]
只pod ZFPlayer，只有core文件夹下载类，avplayer需要单独pod，请看readme

**Comment by ywdonga** [comment]
明白了
