### ISSUE TITLE
进度条时长展示出问题

### ISSUE THREAD

**Issue by lypcliuli** [renzifeng/ZFPlayer#675]
实现了获取播放进度的block回掉playerPlayTimeChanged，就看不到视频时长数值了，不实现这个block就正常可以看到进度条总时长和进度移动数。
![code](https://user-images.githubusercontent.com/12068023/50942218-d28a4a00-14c2-11e9-9fe6-870f33ef29d7.png)
![bug](https://user-images.githubusercontent.com/12068023/50942223-d61dd100-14c2-11e9-8b33-0f4c7e29507b.jpg)

**Comment by lypcliuli** [comment]
这个问题我把你的demo下载下来测试了 也是存在的。是不是还有别的方式获取实时的播放进度？

**Comment by xingyev587** [comment]
你判断一下到这个时间暂停 然后再播放会不会有问题?

**Comment by lypcliuli** [comment]
> 你判断一下到这个时间暂停 然后再播放会不会有问题?

判断到指定时间停止可以正常停止，然后再播放也没问题可以播放，也就是说功能是好使的 。
就是进度条两头展示不出来时间了 都是00:00,感觉是这个block有问题playerPlayTimeChanged。

![指定时间暂停再播放](https://user-images.githubusercontent.com/12068023/51291891-c31b7b80-1a43-11e9-97c9-ecfd40263766.png)

后来我通过自定义一个controlView，通过ZFPlayerMediaControl协议，把里面的进度变化方法回掉出来，实现了我的需求。

**Comment by xingyev587** [comment]
不要调停止方法 调暂停方法啊!  pause   你这样不知道你后期会不会出问题!

**Comment by renzifeng** [comment]
外边不能调用currentManager.playerPlayTimeChanged应该直接使用 player.playerPlayTimeChanged
