### ISSUE TITLE
加载ZFPlayer会暂停网易音乐等app的播放，怎么解决

### ISSUE THREAD

**Issue by halocq** [renzifeng/ZFPlayer#676]

**Comment by StefBiao** [comment]
本就应该暂停其它音乐播放的.试问你正在播放着网易云音乐,再打开qq音乐会两个同时播放歌曲吗?

**Comment by halocq** [comment]
> 本就应该暂停其它音乐播放的.试问你正在播放着网易云音乐,再打开qq音乐会两个同时播放歌曲吗?

不应该啊，微博就是播放的时候才会停掉其他的

**Comment by renzifeng** [comment]
这个设置AudioSession 就行了

**Comment by renzifeng** [comment]
你可以设置 `customAudioSession` 为YES，然后自己设置AudioSession就可以了
