### ISSUE TITLE
最新版为什么不能自己设置占位图了

### ISSUE THREAD

**Issue by jaymees** [renzifeng/ZFPlayer#68]
我也没有找到新的API支持替换的，望大神告知下，灰常感谢

**Comment by renzifeng** [comment]
自己看一下readme

**Comment by NickWarrior** [comment]
我也是，placeholderImageName这个属性好像都没了。。。

**Comment by NSMichael** [comment]
你的demo可以全屏，为什么集成到我的项目就不能全屏了
_playerView = [[ZFPlayerView alloc] initWithFrame:CGRectMake(0, 0, kScreen_Width, kScreen_Width/2)];

**Comment by renzifeng** [comment]
@NSMichael 请使用autolayout

**Comment by nnianhou-** [comment]
placeholderImageName 能不能设置UIImage或者网络地址  有可能是网络图片 @renzifeng
