### ISSUE TITLE
小窗模式只能在tableview的情况下使用吗？普通模式可以吗

### ISSUE THREAD

**Issue by WanMeg** [renzifeng/ZFPlayer#682]
小窗模式只能在tableview的情况下使用吗？普通模式可以吗？
比如点击按钮进入视频播放页面，这时返回上个页面 显示出小窗播放，这可以实现吗，
对demo做了修改没有实现，麻烦解答一下疑惑，万分感谢

**Comment by renzifeng** [comment]
修改containerView就可以显示到任意view上，直接加到你的自定义的小窗view上试试

**Comment by WanMeg** [comment]
好的，我再试试，感谢解答

**Comment by WanMeg** [comment]
> 修改containerView就可以显示到任意view上，直接加到你的自定义的小窗view上试试

我在详情页返回的时候把player(ZFPlayerController)传回了上个页面，并添加显示在了smallFloatView(ZFFloatView)，在smallFloatView上添加了(ZFSmallFloatControlView)，可以正常的自动播放，但是没有办法拖动smallFloatView，会和player的controlView控制层冲突，单击小窗也不能实现全屏模式。我尝试着对它们的各种属性做修改，但是没能解决，麻烦帮忙解答一下吧谢谢

**Comment by renzifeng** [comment]
因为你没有屏蔽controlView上的手势

**Comment by WanMeg** [comment]
> 因为你没有屏蔽controlView上的手势
嗯嗯 谢谢回答 我再研究研究

**Comment by WanMeg** [comment]
> 因为你没有屏蔽controlView上的手势

嗯嗯 谢谢回答 我再研究研究
