### ISSUE TITLE
从播放列表页到播放页面播放 , 重复10几次 会出现问题 

### ISSUE THREAD

**Issue by hangzhou123** [renzifeng/ZFPlayer#683]
错误信息: Error Domain=AVFoundationErrorDomain Code=-11839 "无法解码" UserInfo={NSLocalizedDescription=无法解码, NSUnderlyingError=0x1c6446d50 {Error Domain=NSOSStatusErrorDomain Code=-12913 "(null)"}, NSLocalizedRecoverySuggestion=停止其他所有对媒体解密的操作，然后再试一次。, NSLocalizedFailureReason=此媒体所需的解码器正忙。}

网上说法: https://www.jianshu.com/p/5d166c4bb7c1
https://stackoverflow.com/questions/41514623/check-when-resources-are-available-from-avfoundation

**Comment by renzifeng** [comment]
fix
