### ISSUE TITLE
使用ZFIJKPlayerManager管理 滑动slider前进 或者后退 slider会返回到0 一直显示00：01

### ISSUE THREAD

**Issue by dumplingsChina** [renzifeng/ZFPlayer#686]
使用ZFIJKPlayerManager管理 

全屏左右滑动 或者 滑动slider前进 后退 

slider会返回到0 一直显示00：01

**Comment by Monkey-D-Mark** [comment]
这个问题新版应该修复了 self->_currentTime = self.player.currentPlaybackTime > 0 ? self.player.currentPlaybackTime : 0; ZFIJKPlayerManager.h line: 207
