### ISSUE TITLE
为什么不能全屏？

### ISSUE THREAD

**Issue by NSMichael** [renzifeng/ZFPlayer#69]
_playerView = [[ZFPlayerView alloc] initWithFrame:CGRectMake(0, 0, kScreen_Width, kScreen_Width/2)];

```
self.playerView.videoURL = [NSURL URLWithString:@"http://wvideo.spriteapp.cn/video/2016/0328/56f8ec01d9bfe_wpd.mp4"];

//（可选设置）可以设置视频的填充模式，内部设置默认（ZFPlayerLayerGravityResizeAspect：等比例填充，直到一个维度到达区域边界）
self.playerView.playerLayerGravity = ZFPlayerLayerGravityResizeAspect;
// 是否自动播放，默认不自动播放
//    [self.playerView autoPlayTheVideo];


// 如果想从xx秒开始播放视频
self.playerView.seekTime = 0;

__weak typeof(self) weakSelf = self;
self.playerView.goBackBlock = ^{
    [weakSelf.navigationController popViewControllerAnimated:YES];
};
[self.mScrollView addSubview:_playerView];
```

**Comment by renzifeng** [comment]
使用Autolayout

**Comment by Vergil-H** [comment]
我也碰到了同样的问题，自己的demo可以全屏集成到项目就不行。试用autolayout具体是指。storyboard中的viewcontroller点了autolayout了。

**Comment by NSMichael** [comment]
必须使用AutoLayout才可以，而且ZFPlayerView的宽高比还得16:9才可以哦

**Comment by Vergil-H** [comment]
![f788f895-ae9e-4476-bc82-7d817f22a116](https://cloud.githubusercontent.com/assets/17638435/17504411/3258b7b0-5e2b-11e6-8a2a-a449d610114b.png)
![cdc72644-f65e-4541-9dc5-b1d61a12d356](https://cloud.githubusercontent.com/assets/17638435/17504419/433953fa-5e2b-11e6-99d2-0cbca270e72c.png)

@NSMichael 
 是这个样子么，但是我的项目中还是不能全屏，求解T_T

**Comment by NSMichael** [comment]
楼上那位兄弟你现在是什么效果呢，上个图看看，
![image](https://cloud.githubusercontent.com/assets/3736158/17508728/fe1eb6de-5e48-11e6-8997-bd3dd0ac4db4.png)

**Comment by Vergil-H** [comment]
没有全屏的时候是这样的：
![img_0994](https://cloud.githubusercontent.com/assets/17638435/17509865/af0c4b6e-5e4e-11e6-9ce8-beaabda011d0.jpg)
点全屏按钮的时候是这样的：
![img_0995](https://cloud.githubusercontent.com/assets/17638435/17509876/b854b594-5e4e-11e6-8a65-732c4a32a4e8.jpg)
奇怪的就是我自己新建一个demo的时候是可以的，但是在项目中用得时候就是这个结果 费解T_T

**Comment by renzifeng** [comment]
@Vergil-H 你把项目的横屏给禁止了，当然不能横屏啦

**Comment by Vergil-H** [comment]
确实如此...项目把横屏禁了，本菜鸟受教了，谢谢指导。

**Comment by iuzumakin** [comment]
zf大大，，在xib 中的全屏的时候是   屏幕横了，但是视频并没有铺满屏幕，，不知道姿势哪里错啦～

**Comment by 10000TB** [comment]
不用 AutoLayout 的话， 可以自己手动更新 playView 的 constraints 去实现全频效果
