### ISSUE TITLE
pause之后依然在缓冲

### ISSUE THREAD

**Issue by nemo316** [renzifeng/ZFPlayer#690]
- (void)pause {
    [self.player pause];
    self->_isPlaying = NO;
    self.playState = ZFPlayerPlayStatePaused;
    [_playerItem cancelPendingSeeks];
    [_asset cancelLoading];
}
ZFAVPlayerManager虽然在pause中添加了
[_playerItem cancelPendingSeeks];
[_asset cancelLoading];
但暂停后依然在缓冲

**Comment by haian-zhizhou** [comment]
暂停的同时  停止缓冲，问题解决是怎么处理的？
