### ISSUE TITLE
ZFPlayerControlView showTitle:nil coverURLString:nil fullScreenMode:ZFFullScreenModePortrait doesn't support device rotation

### ISSUE THREAD

**Issue by umyumm** [renzifeng/ZFPlayer#692]
When set

[self.controlView showTitle:nill
                 coverURLString:nill
                 fullScreenMode:layout.**ZFFullScreenModePortrait**:];

The player no longer goes full screen when the user rotates the device to landscape orientation.

Can you update so that when user rotates to landscape, the video is played in Portrait orientation but full screen?  Video should continue in full screen mode until the user clicks the full screen button.  v2.0 of the zfplayer had this behaviour.

**Comment by renzifeng** [comment]
You can set `allowOrentitaionRotation` to NO and use `ZFPlayerControlView showTitle:nil coverURLString:nil fullScreenMode:ZFFullScreenModeLandscape`

**Comment by umyumm** [comment]
I still want to set allowOrentitaionRotation to YES.  When user rotates screen it should go full screen, but I believe ZF player should allow this for ZFFullScreenModePortrait.  Right now it does not.

**Comment by umyumm** [comment]
If you set:

        [self->playerView setAllowOrentitaionRotation:YES];
        [self->controllerView showTitle:self.item[@"title"]
                         coverURLString:nil
                         fullScreenMode:ZFFullScreenModePortrait];

The device does not go full screen when you rotate it.  I believe it should.
