### ISSUE TITLE
全屏模式下返回，导航栏样式错误

### ISSUE THREAD

**Issue by haian-zhizhou** [renzifeng/ZFPlayer#694]
在全屏模式下，进如后台，再进入前台，退出播放   导航栏布局错乱  在iOS9、10、12下均存在，在iOS12下tabbar也会出错

**Comment by MineJay** [comment]
我这边会状态栏出问题，tabbar 也会出错，老哥有找到解决办法吗？

**Comment by xkser** [comment]
我也碰到这个问题。发现demo之所以不出现，是因为没有在外层嵌套一层tabbarcontroller。但是没法根治

**Comment by renzifeng** [comment]
#657 参考这个

**Comment by xkser** [comment]
> #657 参考这个

试了。并没有效果啊。根视图是Tabbar。且后台切换改frame没用

**Comment by caicai0525** [comment]
@Aduir 请问您解决这个问题了吗

**Comment by WIndFate** [comment]
因为有tabbarcontroller，还是没有解决
