### ISSUE TITLE
抖音控制器播放视频,只有一个视频数据上拉失效

### ISSUE THREAD

**Issue by JockerLUO** [renzifeng/ZFPlayer#695]
在ZFDouYinViewController中播放视频,如果进入页面的时候只有一个数据,上拉加载会失效,

在示例demo中因为是通过requestData本地加载数据,不会出现加载数据失败的情况,列表中的数据必定是多个,但在应用中是通过网络加载数据,就会出现只有一个数据加载更多数据失败的情况,

在进人页面的时候就触发了一次UIScrollView (ZFPlayer)中的_findCorrectCellWhenScrollViewDerectionVertical方法,
会直接赋值self.zf_shouldPlayIndexPath = indexPath,

再次上拉结束调用zf_scrollViewDidEndDecelerating方法,
当zf_scrollViewDidEndDecelerating方法调到zf_filterShouldPlayCellWhileScrolled在517行因为在进入页面时就设置过self.zf_playingIndexPath,会使判断失效,

当列表中只有一个数据触发不了zf_scrollViewDidStopScrollCallback,无法触发上拉加载,当第一次进入界面加载数据失败没有补救措施,建议去掉"UIScrollView+ZFPlayer.m"517行的判断,但不清楚会有什么影响.

**Comment by renzifeng** [comment]
ok，我先看一下，解决后来关闭
