### ISSUE TITLE
全屏播放的时候调用seekToTime后视频总时长获取不到，用的ZFIJKPlayerManager

### ISSUE THREAD

**Issue by gu2890961** [renzifeng/ZFPlayer#696]
播放记录列表，点进去直接是全屏播放，调用下面方法后，视频的总时长获取不到，且也不能从seekTime进行播放，还是从0开始播放
demo不存在这个问题，将demo改成ZFIJKPlayerManager后就会出现这种问题
@weakify(self)
        [self.player seekToTime:self.seekTime completionHandler:^(BOOL finished) {
            @strongify(self)
            if (finished) {
                [self.player savePlayHistory];
            }
        }];

**Comment by renzifeng** [comment]
直接播放就seek不能使用这个方法，要用属性`seekTime`
