### ISSUE TITLE
使用cocoapods导入报错

### ISSUE THREAD

**Issue by vistaLin** [renzifeng/ZFPlayer#701]
cocoapods导入:
#pod 'ZFPlayer', '~> 3.0'
#pod 'ZFPlayer/ControlView', '~> 3.0'
#pod 'ZFPlayer/AVPlayer', '~> 3.0'
#pod 'ZFPlayer/ijkplayer', '~> 3.0'
#pod 'ZFPlayer/KSYMediaPlayer', '~> 3.0'
报错如下:
[!] The 'Pods-HappyRentAHouse' target has transitive dependencies that include static binaries: (/Users/linxingkuan/Desktop/HappyRentAHouse/Pods/IJKMediaFramework/IJKMediaFramework/Classes/IJKMediaFramework.framework and /Users/linxingkuan/Desktop/HappyRentAHouse/Pods/KSYMediaPlayer/KSYMediaPlayer/Classes/Frameworks/KSYMediaPlayer.framework)

**Comment by renzifeng** [comment]
你那边是swift的项目吧

**Comment by vistaLin** [comment]
> 你那边是swift的项目吧

是OC嵌套了swift的一些第三方库

**Comment by renzifeng** [comment]
`#pod 'ZFPlayer/ijkplayer', '> 3.0'
#pod 'ZFPlayer/KSYMediaPlayer', '~> 3.0'`
只能同时使用一个
