### ISSUE TITLE
禁止自动播放不起作用

### ISSUE THREAD

**Issue by Zhumeng223** [renzifeng/ZFPlayer#704]
到播放页面shouldAutoPlay这个方法设置了之后还是自动播放了啊

**Comment by renzifeng** [comment]
shouldAutoPlay这个只有在列表上使用有效

**Comment by Marcello168** [comment]
> shouldAutoPlay这个只有在列表上使用有效

不是在列表中使用的时候，那怎么禁止自动播放呢
