### ISSUE TITLE
3.2.6版本会和SD_AutoLayout布局库有冲突.希望内部实现一些属性的时候加个zf_前缀

### ISSUE THREAD

**Issue by MeteoriteMan** [renzifeng/ZFPlayer#709]
只要是关于SD_AutoLayout布局的库样式全乱了

**Comment by renzifeng** [comment]
和SD_AutoLayout有关的也就是UIView的分类了，里边的属性都有加zf_

**Comment by MeteoriteMan** [comment]
之前用的是3.1.5.如果升级了3.2.6用SD布局的就乱了(表现为全部移动到左上角,相当于木有布局).不升级的话就没问题(用, '3.2.6')这种形式install的.看了终端打印,排除其他库的影响.

**Comment by renzifeng** [comment]
我试了在demo引入SD_AutoLayout，并没有出现你说的问题，麻烦你提供demo，我好定位出是哪的问题

**Comment by MeteoriteMan** [comment]
pod 'ZFPlayer', '3.1.5'
pod 'ZFPlayer/ControlView', '3.1.5'
pod 'ZFPlayer/AVPlayer', '3.1.5'

用到了这仨...Demo的话.等会啊.我抽一个出来

**Comment by MeteoriteMan** [comment]
不好意思啊.SD的版本问题.版本太旧.然后和你的不兼容.我用Pod重新导入最新的就没事儿了(PS.外包真的很坑.三方库全是拖进去的...)
