### ISSUE TITLE
你好可不可以加预加载功能，秒播下一条短视频？

### ISSUE THREAD

**Issue by xiaojiguang** [renzifeng/ZFPlayer#710]

**Comment by Mr-yuwei** [comment]
看源码应该是不可以的
1.源码中没有"缓存功能"
2.数据源`assetURLs`可能不满足，在实际开发中同一个列表的数据会多变（用户播放一个视频，系统需要推荐相似视频，assetURLs每次可能都要设置).播放下一个的时候通过delegate去拿资源比较合适。

**Comment by renzifeng** [comment]
@Mr-yuwei 嗯，你说的这种情况我也准备适配一下
