### ISSUE TITLE
自定义UISlider是不是无法接收到用户事件?

### ISSUE THREAD

**Issue by seanLee** [renzifeng/ZFPlayer#715]
我这里本来想自己实现一个ControlView,所以一开始自己添加了一个UISlider,然后发现接收用户事件很不正常.虽然后来用您提供的```ZFSliderView```这个类解决问题,但是还是想知道一下是不是因为重写响应链方法导致得这个问题,我自己创建一个空白项目之后,发现UISlider可以正常使用.

**Comment by renzifeng** [comment]
因为slider手势和cotrolView的滑动手势冲突了，我在内部处理了

**Comment by seanLee** [comment]
好的～了解了 谢谢解答

**Comment by zj381652512** [comment]
> 好的～了解了 谢谢解答

_player.disableGestureTypes = ZFPlayerDisableGestureTypesAll
