### ISSUE TITLE
手势/slider 拖动到结束 会走playerDidToEnd然后再走一次playerPlayStateChanged

### ISSUE THREAD

**Issue by Gaozn** [renzifeng/ZFPlayer#717]
怎么回事 求解啊

**Comment by Gaozn** [comment]
找到了问题所在，当我拖动到视频结束时 走了这个方法。这里有个延迟三秒的方法，我查看了我的情况 的确是playerDidToEnd三秒之后走的playerPlayStateChanged 所以进行了是否播放结束的判断
/**
 *  缓冲较差时候回调这里
 */
- (void)bufferingSomeSecond {
    // playbackBufferEmpty会反复进入，因此在bufferingOneSecond延时播放执行完之前再调用bufferingSomeSecond都忽略
    if (self.isBuffering) return;
    self.isBuffering = YES;
    if (self.playState!=ZFPlayerPlayStatePlayStopped) {
        //    // 需要先暂停一小会之后再播放，否则网络状况不好的时候时间在走，声音播放不出来
        [self.player pause];
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            // 如果此时用户已经暂停了，则不再需要开启播放了
            if (!self.isPlaying) {
                self.isBuffering = NO;
                return;
            }
            [self play];
            // 如果执行了play还是没有播放则说明还没有缓存好，则再次缓存一段时间
            self.isBuffering = NO;
            if (!self.playerItem.isPlaybackLikelyToKeepUp) [self bufferingSomeSecond];
        });
    }
}

**Comment by renzifeng** [comment]
嗯，确实有这情况，我改一下
