### ISSUE TITLE
最新的版本有闪退的现象

### ISSUE THREAD

**Issue by Zhumeng223** [renzifeng/ZFPlayer#719]
pod最新版本之后出现闪退，崩在ZFPlayerController.m文件这里：
self.currentPlayerManager.playerReadyToPlay = ^(id<ZFPlayerMediaPlayback>  _Nonnull asset, NSURL * _Nonnull assetURL) {
        @strongify(self)
        if (self.playerReadyToPlay) self.playerReadyToPlay(asset,assetURL);
    };
出现了[KSMediaPlayerManager setPlayerReadyToPlay:]: unrecognized selector sent to instance这个错误

**Comment by renzifeng** [comment]
你那不是最新版吧，pod update一下

**Comment by Zhumeng223** [comment]
pod update 之后还是崩：
self.currentPlayerManager.playerReadyToPlay = ^(id<ZFPlayerMediaPlayback>  _Nonnull asset, NSURL * _Nonnull assetURL) {
        @strongify(self)
        if (self.playerReadyToPlay) self.playerReadyToPlay(asset,assetURL);
        if (!self.customAudioSession) {
            // Apps using this category don't mute when the phone's mute button is turned on, but play sound when the phone is silent
            [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback withOptions:AVAudioSessionCategoryOptionAllowBluetooth error:nil];
            [[AVAudioSession sharedInstance] setActive:YES error:nil];
        }
    };这次是崩到这里
