### ISSUE TITLE
pod update 到最新版本之后还是有闪退的现象

### ISSUE THREAD

**Issue by Zhumeng223** [renzifeng/ZFPlayer#720]
还是闪退到ZFPlayerController.m:
self.currentPlayerManager.playerReadyToPlay = ^(id<ZFPlayerMediaPlayback>  _Nonnull asset, NSURL * _Nonnull assetURL) {
        @strongify(self)
        if (self.playerReadyToPlay) self.playerReadyToPlay(asset,assetURL);
        if (!self.customAudioSession) {
            // Apps using this category don't mute when the phone's mute button is turned on, but play sound when the phone is silent
            [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback withOptions:AVAudioSessionCategoryOptionAllowBluetooth error:nil];
            [[AVAudioSession sharedInstance] setActive:YES error:nil];
        }
    };
这里，还是[KSMediaPlayerManager setPlayerReadyToPlay:]: unrecognized selector sent to instance这个问题

**Comment by Wriky** [comment]
我也遇到了同样的问题，请问你这个是什么原因导致的呢？ @Zhumeng223

**Comment by Wriky** [comment]
回到3.2.2版本就好了

**Comment by dagundejuzi** [comment]
少了一句
 @synthesize playerReadyToPlay              = _playerReadyToPlay;

**Comment by maxwell44** [comment]
更新到最新同问题崩溃现象，指定3.2.2版本 还是是崩溃
