### ISSUE TITLE
HLS 视频流播放失败

### ISSUE THREAD

**Issue by LiGuanWen** [renzifeng/ZFPlayer#723]
http://vs1.baduziyuan.com/share/bEUC0Q2aPVZvu3VL  这种视频 播放不了，请问是否有解决方案

**Comment by VillageMud** [comment]
求问

**Comment by chenbin0522** [comment]
self.player.assetURL = [NSURL URLWithString:@"http://vs1.baduziyuan.com/20190112/aDgBM6uw/index.m3u8?sign=bfae07adc873665a3a8634bb993d8ca893eb93b0fbe74ee2d184948d585e6ee00f8d808652f1874086b640f0459c61b213e832713baa61fa3c49dd12612aaf61"];
测试了,可以播放,你是不是直接设置的网页地址,而不是m3u8地址??
