### ISSUE TITLE
大佬 问题问题为什么升级了报这个错？？？Duplicate interface definition for class 'ZFPlayerControlView'

### ISSUE THREAD

**Issue by guojingjingghost** [renzifeng/ZFPlayer#724]

**Comment by beforeold** [comment]
项目中有两个 'ZFPlayerControlView' 类，找到并删除一个多余的

**Comment by guojingjingghost** [comment]
> 项目中有两个 'ZFPlayerControlView' 类，找到并删除一个多余的

但是项目中没有两个多余的类啊

**Comment by beforeold** [comment]
整个 workspace 里搜索 @interface ZFPlayerControlView

**Comment by beforeold** [comment]
看看这个[类似的问题](https://www.jianshu.com/p/351cd5417ef1)，还有可能是你 import 的方式有问题，你看看

**Comment by guojingjingghost** [comment]
> 看看这个[类似的问题](https://www.jianshu.com/p/351cd5417ef1)，还有可能是你 import 的方式有问题，你看看

谢谢你解决了

**Comment by beforeold** [comment]
> > 看看这个[类似的问题](https://www.jianshu.com/p/351cd5417ef1)，还有可能是你 import 的方式有问题，你看看
> 
> 谢谢你解决了

怎么解决了，如果解决了，可以把思路贴出来，然后把这个 issue 关闭哦

**Comment by guojingjingghost** [comment]
> > > 看看这个[类似的问题](https://www.jianshu.com/p/351cd5417ef1)，还有可能是你 import 的方式有问题，你看看
> > 
> > 
> > 谢谢你解决了
> 
> 怎么解决了，如果解决了，可以把思路贴出来，然后把这个 issue 关闭哦
pch 文件注释了两个import  引用
#import <ZFPlayer.h>
//#import <ZFPlayerControlView.h>
//#import <ZFPlayer/ZFPlayerController.h>
#import <ZFPlayer/ZFPlayerControlView.h>
