### ISSUE TITLE
非列表格式的播放器如何设置进入后禁止自动播放？

### ISSUE THREAD

**Issue by Zhumeng223** [renzifeng/ZFPlayer#726]
非列表格式的播放器如何设置进入后禁止自动播放？在playerReadyToPlay回调中设置playerManager.pause()只有当seekTime为0的时候起作用，seekTime不等于0的时候不起作用

**Comment by Zhumeng223** [comment]
当seekTime是0的时候好像是管用的，当seekTime不为0的时候就不管用了

**Comment by renzifeng** [comment]
等待需要播放时候再初始化播放器就行
