### ISSUE TITLE
播放一个1G大小的本地视频闪退（内存暴增）

### ISSUE THREAD

**Issue by jingchangfa** [renzifeng/ZFPlayer#727]
// self.beforeModel.path 是个本地视频的路径，视频大小1g多

ZFAVPlayerManager *playerManager = [[ZFAVPlayerManager alloc] init];
playerManager.assetURL = [NSURL fileURLWithPath:self.beforeModel.path];

**Comment by renzifeng** [comment]
这个是 AVPlayer的问题
