### ISSUE TITLE
Loading 没有了

### ISSUE THREAD

**Issue by shaop** [renzifeng/ZFPlayer#729]
3.2.5版本之后，由于 `ZFAVPlayerManager` 的 state 初始状态变成了 `ZFPlayerLoadStatePrepare` 导致控制层的 loading 逻辑出现了问题，望修补一下

**Comment by guojingjingghost** [comment]
if (state == ZFPlayerLoadStatePrepare && videoPlayer.currentPlayerManager.isPlaying) {
[self.activity startAnimating];
} else {
[self.activity stopAnimating];
}那个判断改成这样你试试

**Comment by renzifeng** [comment]
专门这样改的
