### ISSUE TITLE
多级跳转视频问题

### ISSUE THREAD

**Issue by xuanyi0627** [renzifeng/ZFPlayer#73]
您好，我有一个需求是这样的，在一个tableview的视频播放页（页面1）可以进入到这个视频的推荐列表页（页面2），推荐列表页（页面2）可以再点击进入一个视频播放页（页面3），问题是，从页面3返回到页面1的时候页面1的视频那层就没有了，获取到的playerView的值是页面3的创建的playerView。请问这个怎么解决呢？

**Comment by renzifeng** [comment]
因为在tableView上的playerView是一个单例

**Comment by xuanyi0627** [comment]
那我应该怎么解决这个问题呢

**Comment by xuanyi0627** [comment]
请问这个问题要怎么解决呢
