### ISSUE TITLE
在ios10下,播放hls直播流有问题.一直重复显示loading,不播放.

### ISSUE THREAD

**Issue by chenbin0522** [renzifeng/ZFPlayer#731]

**Comment by xiaowangqinghui** [comment]
这位 老哥 请问怎么改呢  我这边 iOS10也播放不了

**Comment by chenbin0522** [comment]
> 这位 老哥 请问怎么改呢 我这边 iOS10也播放不了
我的临时解决方法,是在设置播放url前设置一个标志位,然后在
initializePlayer中设置_player.automaticallyWaitsToMinimizeStalling = _isLiveStream ? YES : NO;

**Comment by xiaowangqinghui** [comment]
ni所说的标志位是指判断是否是iOS10吗 那直接在initializePlayer这个方法里面判断不就行了 而且我这边怎么只有initializeThePlayer这个方法  没有 initializePlayer这个

**Comment by chenbin0522** [comment]
> ni所说的标志位是指判断是否是iOS10吗 那直接在initializePlayer这个方法里面判断不就行了 而且我这边怎么只有initializeThePlayer这个方法 没有 initializePlayer这个

标记一下是不是直播流,然后根据这个参数来设置automaticallyWaitsToMinimizeStalling值.

**Comment by xiaowangqinghui** [comment]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/15713276/55695611-ed019000-59eb-11e9-9012-3d6bab3cbf73.png">
不起作用啊  我是播放网络视频

**Comment by chenbin0522** [comment]
直播流应该为YES

**Comment by xiaowangqinghui** [comment]
YES 和 NO都不行

**Comment by chenbin0522** [comment]
由于版本不同,我不太确定这个参数在这里设置是否合适,不过问题,应该是这个参数导致.
<img width="651" alt="WX20190408-105426@2x" src="https://user-images.githubusercontent.com/8023372/55695796-d0198c80-59ec-11e9-9ceb-138adcc1fbd5.png">
