### ISSUE TITLE
iOS能加载但播放不了

### ISSUE THREAD

**Issue by xiaowangqinghui** [renzifeng/ZFPlayer#733]
iOS播放不了，是哪里的问题呢

**Comment by xiaowangqinghui** [comment]
iOS10

**Comment by guojingjingghost** [comment]
> iOS10

pod 'ZFPlayer/ControlView' 我刚升级到最新版本 请问我这边会出现这样的问题吗   我的手机是10.3.3 的可以播放  但是有小几率会出现切换视频突然没声音的问题   但是从新就去就没问了，还有长时间连续切换 加载缓慢问题
