### ISSUE TITLE
大佬请问下 == pod 'ZFPlayer/ControlView'我更新到最新版本但是在播放前会有一个框然后在出来画面，这个框能去掉吗

### ISSUE THREAD

**Issue by guojingjingghost** [renzifeng/ZFPlayer#734]

**Comment by guojingjingghost** [comment]
- (void)videoPlayer:(ZFPlayerController *)videoPlayer loadStateChanged:(ZFPlayerLoadState)state {
    if (state == ZFPlayerLoadStatePrepare) {
        self.coverImageView.hidden = YES;
    } else if (state == ZFPlayerLoadStatePlaythroughOK || state == ZFPlayerLoadStatePlayable) {
        self.coverImageView.hidden = YES;
        if (self.effectViewShow) {
            self.effectView.hidden = YES;
        } else {
            self.effectView.hidden = YES;
            self.player.currentPlayerManager.view.backgroundColor = [UIColor blackColor];
        }
    }
    if (state == ZFPlayerLoadStatePrepare && videoPlayer.currentPlayerManager.isPlaying) {
        [self.activity startAnimating];
    } else {
        [self.activity stopAnimating];
    }
}解决了 另外 判断改成  state == ZFPlayerLoadStatePrepare && videoPlayer.currentPlayerManager.isPlaying  才能显示出 加载动画  还是我的设置有问题按照群主的不显示动画

**Comment by renzifeng** [comment]
框框问题是默认 placeholder有问题，我在新版本改了一下
