### ISSUE TITLE
更新了ZFPlayer 3.2.9，还有卡顿

### ISSUE THREAD

**Issue by 877209649** [renzifeng/ZFPlayer#736]
self.player.controlView = self.controlView;
注释掉这个就没事，但是需要用到controlView，大神怎么解决/

**Comment by renzifeng** [comment]
没有测出来控制层哪里卡啊

**Comment by 877209649** [comment]
#define ZFPlayer_Image(file)                 [UIImage imageNamed:@""]
我这样搞一下就没事， 加载这些图片不至于有1秒的卡顿啊，[捂脸][捂脸][捂脸]
