### ISSUE TITLE
你提供的Demo一直都在狂报错，还无所知？

### ISSUE THREAD

**Issue by Bofearless** [renzifeng/ZFPlayer#737]
1、首先Demo下载后，无法直接运行，看不到效果；
2、你的podfile文件里指向本地的develop pods 地址，然后demo里有很多头文件却引用了其他的pod组件，你不如直接在podfile里面把需要pod的组件全部写全，这样搞有什么意义？
3、KSYMediaPlayer.framework这个一直在报错，应该是引入时IJKFF的问题。

好好搞搞Demo吧，源码本身好不好仁者见仁吧，别辜负了给你的这5000 star

**Comment by renzifeng** [comment]
不懂就别瞎逼逼，核心思想和思路都不懂，无法运行自己不好好看 readme 怨谁
