### ISSUE TITLE
大佬  最新的pod 'ZFPlayer/ControlView为什么刚开始播放没声音 等会才有声音，以前的版本都没事。iOS 10.3.3

### ISSUE THREAD

**Issue by guojingjingghost** [renzifeng/ZFPlayer#738]

**Comment by guojingjingghost** [comment]
有时有声音，有时没有声音，能修复下吗？？？

**Comment by renzifeng** [comment]
没有测出这个问题啊iOS10.2

**Comment by guojingjingghost** [comment]
> 没有测出这个问题啊iOS10.2

我这是概率有事没有声音有时有声音  
- (ZFPlayerController *)player {
    if (_player == nil) {
        ZFAVPlayerManager *playerManager = [[ZFAVPlayerManager alloc] init];
        _player = [ZFPlayerController playerWithPlayerManager:playerManager containerView:self];
        _player.controlView = self.controlView;
        _player.shouldAutoPlay = NO;
        playerManager.volume = 0.7;
        _player.volume = 0.7;
        _player.pauseWhenAppResignActive = YES;
    }
    return _player;
}
但是没声音时把app进入后台在进入前台就有声音了

**Comment by guojingjingghost** [comment]
> 没有测出这个问题啊iOS10.2
大佬你看看我设置的有没有问题
