### ISSUE TITLE
大佬我发现了一点规律刚开始播放没声音-（进入后台在切换到前台就有声音）

### ISSUE THREAD

**Issue by guojingjingghost** [renzifeng/ZFPlayer#743]

**Comment by guojingjingghost** [comment]
网络稍微不好时 就会出现这种问题  ===

是不是那个你写的ZFPlayerManager 这个类 下面的方法造成的 请群主尽快修复
- (void)bufferingSomeSecond {
    // playbackBufferEmpty会反复进入，因此在bufferingOneSecond延时播放执行完之前再调用bufferingSomeSecond都忽略
    if (self.isBuffering || self.playState == ZFPlayerPlayStatePlayStopped) return;
    self.isBuffering = YES;
    
    // 需要先暂停一小会之后再播放，否则网络状况不好的时候时间在走，声音播放不出来
    [self.player pause];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        // 如果此时用户已经暂停了，则不再需要开启播放了
        if (!self.isPlaying) {
            self.isBuffering = NO;
            return;
        }
        [self play];
        // 如果执行了play还是没有播放则说明还没有缓存好，则再次缓存一段时间
        self.isBuffering = NO;
        if (!self.playerItem.isPlaybackLikelyToKeepUp) [self bufferingSomeSecond];
    });
}

**Comment by renzifeng** [comment]
目前就你自己反应这个 bug，我这边没没测出来，你可以加群找我详聊_

**Comment by VillageMud** [comment]
这个问题确实存在的
