### ISSUE TITLE
几个小bug

### ISSUE THREAD

**Issue by Z-hui** [renzifeng/ZFPlayer#744]
1.initializePlayer中self.player.shouldAutoplay应设置在prepareToPlay之前否则会自动播放：
self.player.shouldAutoplay = NO;    
[self.player prepareToPlay];
2:mediaIsPreparedToPlayDidChange中playerReadyToPlay中判断block是否存在写错：
    if (self.playerPrepareToPlay) self.playerReadyToPlay(self, self.assetURL);
应该为：
    if (self.playerReadyToPlay) self.playerReadyToPlay(self, self.assetURL);

**Comment by renzifeng** [comment]
谢谢，我来改一下
