### ISSUE TITLE
你好  我不使用控制层controlView的时候   我自己设置的所有手势和点击事件都失效  

### ISSUE THREAD

**Issue by xuhuaping** [renzifeng/ZFPlayer#746]

**Comment by renzifeng** [comment]
设置disableGestureTypes = ZFPlayerDisableGestureTypesAll

**Comment by xuhuaping** [comment]
> ZFPlayerDisableGestureTypesAll

好的  谢谢   
![image](https://user-images.githubusercontent.com/18001988/56777987-b0fd6600-6806-11e9-81fd-6660470a08d3.png)还有就是列表自动播放的时候会执行三次

**Comment by xuhuaping** [comment]
> 设置disableGestureTypes = ZFPlayerDisableGestureTypesAll

![image](https://user-images.githubusercontent.com/18001988/56778264-02f2bb80-6808-11e9-9631-915b25f7ef0d.png)
调用play的时候会进入死循环  开始播放然后就马上播放结束
