### ISSUE TITLE
您好，我使用IJKPlayer的时候播放总是闪退，但是用IJKPlayer的demo播放就没有问题。

### ISSUE THREAD

**Issue by GitZhouQi** [renzifeng/ZFPlayer#747]
<img width="640" alt="WeChat3a47caf395f22e3e165ac9c1d6f80e70" src="https://user-images.githubusercontent.com/15603961/56875185-aa265b80-6a71-11e9-8b92-612659be9595.png">
<img width="1002" alt="WeChat838ecf0d4ae1fa975bbc21f724a03619" src="https://user-images.githubusercontent.com/15603961/56875186-aa265b80-6a71-11e9-896e-4c5619611632.png">
这是报错截图

**Comment by renzifeng** [comment]
代码更新到最新版试试

**Comment by GitZhouQi** [comment]
是最新的啊，昨天下载的最新的，ijk也是最新的，我看是调用ijkplayer的prepareToPlay之后引起的

**Comment by renzifeng** [comment]
稍等我一会更pod，还没更新上去

**Comment by renzifeng** [comment]
这个可能是ijkframework的问题
