### ISSUE TITLE
ZFPlayerController dealloc 问题

### ISSUE THREAD

**Issue by JockerLUO** [renzifeng/ZFPlayer#749]
当ZFPlayerController销毁时触发dealloc;
ZFPlayerController中第73行[self.currentPlayerManager stop];
调用后会回调至第144行,
此时block内self为nil;设置customAudioSession不会生效,
即使使用weak_self调用,走到114行时,
BOOL res = [weak_self respondsToSelector:@selector(customAudioSession)];
res为NO;分类中的方法已无法调用,
如果引用ZFPlayerController对象的控制内有其他全局的音频播放,会造成退出界面时调用146行停止音频播放,设置customAudioSession也无效.

**Comment by JockerLUO** [comment]
建议把ZFPlayerController第144行改为
if (playState != ZFPlayerPlayStatePlaying && [self respondsToSelector:@selector(customAudioSession)] && !self.customAudioSession)

**Comment by renzifeng** [comment]
这段代码我准备删掉了
```objc
        if (playState != ZFPlayerPlayStatePlaying && !self.customAudioSession) {
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                [[AVAudioSession sharedInstance] setActive:NO withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation error:nil];
            });
        }
```
AVAudioSession这个卡线程，你可以自己在外边`playerPlayStateChanged`回调写了
