### ISSUE TITLE
你好 列表自动播放的  首个第一次播放时候会执行很多次

### ISSUE THREAD

**Issue by xuhuaping** [renzifeng/ZFPlayer#751]
![image](https://user-images.githubusercontent.com/18001988/57210420-2d662500-700f-11e9-9b87-2946cec58195.png)

**Comment by renzifeng** [comment]
你指的是哪里会执行多次

**Comment by xuhuaping** [comment]
> 你指的是哪里会执行多次

就是playerPlayStateChanged监听播放状态这里

**Comment by xuhuaping** [comment]
> 你指的是哪里会执行多次

http://1254376069.vod2.myqcloud.com/46c92074vodsh1254376069/c3ef331d5285890788745329536/h2qAHpre4uoA.mp4 只有这个视频会卡顿，然后多次执行  其它视频不会  但是我自己用AVPlayer写了播放器测试不会

**Comment by renzifeng** [comment]
那我改一下吧,`ZFAVPlayerManager.m`  377行改为` if (self.isPlaying) [self.player play];
`
