### ISSUE TITLE
@property (nonatomic, copy, nullable) NSArray <NSURL *>*assetURLs;

### ISSUE THREAD

**Issue by LJW008** [renzifeng/ZFPlayer#752]
/// if tableView or collectionView has only one section , use sectionAssetURLs.
/// if normal model set this can use `playTheNext` `playThePrevious` `playTheIndex:`.
@property (nonatomic, copy, nullable) NSArray <NSURL *>*assetURLs;
这个的注释写错了吧，

**Comment by renzifeng** [comment]
/// If tableView or collectionView has only one section , use `assetURLs`.
/// If tableView or collectionView has more sections , use `sectionAssetURLs`.
/// Set this you can use `playTheNext` `playThePrevious` `playTheIndex:` method.
