### ISSUE TITLE
ZFPlayerControlView初始化导致的卡顿

### ISSUE THREAD

**Issue by hucong730** [renzifeng/ZFPlayer#755]
demo第一次打开视频播放控制器的时候，会卡1秒左右，后面就好了，用instruments检测到是ZFPlayerControlView initWithFrame导致的，

**Comment by hucong730** [comment]
发生在这个宏定义ZFPlayer_Image中，imageNamed加载bundle图片导致的卡顿，初始化时很多控件要加载资源，导致的，我换了一个图片加载方法imageWithContentsOfFile就好了

**Comment by renzifeng** [comment]
imageNamed:先将图片缓存到内存中，然后在显示。
imageWithContentsOfFile：仅加载图片，图像数据不会缓存。
