### ISSUE TITLE
Video scrubbing

### ISSUE THREAD

**Issue by nthtrung09it** [renzifeng/ZFPlayer#756]
When playing video in a slow connection and user drags on slider, can you please tell me how can I pause the video, then show a loading indicator and wait until the content is loaded?

I see Apple has an article about video scrubbing: https://developer.apple.com/library/archive/qa/qa1820/_index.html. I think it will be good if this library supports it.

Thanks.

**Comment by renzifeng** [comment]
you can custom the controlView or change the `ZFPlayerControlView`  
```objc
- (void)gestureEndedPan:(ZFPlayerGestureControl *)gestureControl panDirection:(ZFPanDirection)direction panLocation:(ZFPanLocation)location
```
