### ISSUE TITLE
引入ijkPlayer和KSYMediaPlayer之后编译报错

### ISSUE THREAD

**Issue by zhl5213** [renzifeng/ZFPlayer#757]
我按照Readme中的说明，使用podfile引入了ijkPlayer和KSYMediaPlayer，pod install正常，两个播放器正常添加了，但是一编译就报错：

Undefined symbols for architecture arm64:
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for h265_codec::CDecTaskManageST in KSYMediaPlayer(DecTaskManage.o)
      typeinfo for h265_codec::CDecTaskManageMT in KSYMediaPlayer(DecTaskManage.o)
      typeinfo for h265_codec::CDecCabac in KSYMediaPlayer(DecCabac.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for h265_codec::CHevcDecoder in KSYMediaPlayer(DecTop.o)
      typeinfo for h265_codec::IDecTaskManage in KSYMediaPlayer(DecTaskManage.o)
      typeinfo for h265_codec::CComRefManagerBase in KSYMediaPlayer(ComRefManager.o)
      typeinfo for h265_codec::CComCabacEngine in KSYMediaPlayer(DecCabac.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "operator new[](unsigned long)", referenced from:
      qy_util::MemPoolInstance() in KSYMediaPlayer(memAlloc.o)
      qy_util::createMemPool() in KSYMediaPlayer(memAlloc.o)
      qy_util::mallocBase(int, char const*, int) in KSYMediaPlayer(memAlloc.o)
      qy_util::mallocBaseMemPool(int, char const*, int) in KSYMediaPlayer(memAlloc.o)
      qy_util::getMemBlock(unsigned int, qy_util::TMemPool*, char const*, int, char*) in KSYMediaPlayer(memAlloc.o)
  "operator new(unsigned long)", referenced from:
      _QY265DecoderCreate in KSYMediaPlayer(DecTop.o)
      h265_codec::CHevcDecoder::init(QY265DecConfig*) in KSYMediaPlayer(DecTop.o)
      h265_codec::IDecTaskManage::createDecTaskManage(h265_codec::TDecParam*, h265_codec::SPS*, h265_codec::CHevcDecoder*, qy265ThreadPool_t*) in KSYMediaPlayer(DecTaskManage.o)
      h265_codec::createDecFrame(void*) in KSYMediaPlayer(DecFrame.o)
      h265_codec::createDecSliceSegment(void*) in KSYMediaPlayer(DecSlice.o)
      h265_codec::CDecCu::init() in KSYMediaPlayer(DecCu.o)
  "operator delete[](void*)", referenced from:
      qy_util::deleteMemPool(qy_util::TMemPool*) in KSYMediaPlayer(memAlloc.o)
      qy_util::freeBase(void*, char const*, int) in KSYMediaPlayer(memAlloc.o)
  "operator delete(void*)", referenced from:
      _QY265DecoderCreate in KSYMediaPlayer(DecTop.o)
      h265_codec::CHevcDecoder::init(QY265DecConfig*) in KSYMediaPlayer(DecTop.o)
      h265_codec::CHevcDecoder::uninit() in KSYMediaPlayer(DecTop.o)
      h265_codec::CHevcDecoder::~CHevcDecoder() in KSYMediaPlayer(DecTop.o)
      h265_codec::IDecTaskManage::createDecTaskManage(h265_codec::TDecParam*, h265_codec::SPS*, h265_codec::CHevcDecoder*, qy265ThreadPool_t*) in KSYMediaPlayer(DecTaskManage.o)
      h265_codec::CDecTaskManageST::~CDecTaskManageST() in KSYMediaPlayer(DecTaskManage.o)
      h265_codec::CDecTaskManageMT::~CDecTaskManageMT() in KSYMediaPlayer(DecTaskManage.o)
      ...
  "_BZ2_bzDecompressInit", referenced from:
      _matroska_decode_buffer in KSYMediaPlayer(matroskadec.o)
  "_BZ2_bzDecompress", referenced from:
      _matroska_decode_buffer in KSYMediaPlayer(matroskadec.o)
  "___gxx_personality_v0", referenced from:
      _QY265DecoderCreate in KSYMediaPlayer(DecTop.o)
      h265_codec::CHevcDecoder::init(QY265DecConfig*) in KSYMediaPlayer(DecTop.o)
      h265_codec::CHevcDecoder::uninit() in KSYMediaPlayer(DecTop.o)
      h265_codec::CHevcDecoder::~CHevcDecoder() in KSYMediaPlayer(DecTop.o)
      h265_codec::IDecTaskManage::createDecTaskManage(h265_codec::TDecParam*, h265_codec::SPS*, h265_codec::CHevcDecoder*, qy265ThreadPool_t*) in KSYMediaPlayer(DecTaskManage.o)
      h265_codec::CDecTaskManageST::~CDecTaskManageST() in KSYMediaPlayer(DecTaskManage.o)
      h265_codec::CDecTaskManageMT::~CDecTaskManageMT() in KSYMediaPlayer(DecTaskManage.o)
      ...
  "_BZ2_bzDecompressEnd", referenced from:
      _matroska_decode_buffer in KSYMediaPlayer(matroskadec.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

这个按照网上的说法是部分动态库缺失，我就在linker中添加了对应的库libc++、libstdc++、libbz2等等，但是编译报错一点变化都没有，还是一模一样的，求解应该如何解决？？是不是我引入的方式不对？？

**Comment by renzifeng** [comment]
这两个同时引用编译会报错，只使用其中一个就行了

**Comment by zhl5213** [comment]
使用一个也报错，我现在只引入了KSYMediaPlayer，编译也是一样的报错

**Comment by zhl5213** [comment]
不知道是不是因为我在podfile里面加了这样一行代码：

  pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
 end

加这行代码是因为我引入pod 'ZFPlayer/KSYMediaPlayer', '~> 3.0' 之后，如果直接pod update，会报错：

[!] The 'Pods-Demo' target has transitive dependencies that include static binaries: (/Users/zhuhuilin/Downloads/MyProject/MainProject/iOSLearning/iOSSyntaxAndPrinciple/Pods/KSYMediaPlayer/KSYMediaPlayer/Classes/Frameworks/KSYMediaPlayer.framework)

根据网上的建议，我加了上面的代码，这个报错问题就消除了

**Comment by firebrk** [comment]
> 不知道是不是因为我在podfile里面加了这样一行代码：
> 
> pre_install do |installer|
> # workaround for [CocoaPods/CocoaPods#3289](https://github.com/CocoaPods/CocoaPods/issues/3289)
> Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
> end
> 
> 加这行代码是因为我引入pod 'ZFPlayer/KSYMediaPlayer', '~> 3.0' 之后，如果直接pod update，会报错：
> 
> [!] The 'Pods-Demo' target has transitive dependencies that include static binaries: (/Users/zhuhuilin/Downloads/MyProject/MainProject/iOSLearning/iOSSyntaxAndPrinciple/Pods/KSYMediaPlayer/KSYMediaPlayer/Classes/Frameworks/KSYMediaPlayer.framework)
> 
> 根据网上的建议，我加了上面的代码，这个报错问题就消除了

最后怎么解决了 遇到同样的问题
