### ISSUE TITLE
引入 pod 'ZFPlayer/KSYMediaPlayer', '~> 3.0'报错

### ISSUE THREAD

**Issue by zhl5213** [renzifeng/ZFPlayer#758]
出现报错：
[!] The 'Pods-iOSSyntaxAndPrinciple' target has transitive dependencies that include static binaries: (/Users/zhuhuilin/Downloads/MyProject/MainProject/iOSLearning/iOSSyntaxAndPrinciple/Pods/KSYMediaPlayer/KSYMediaPlayer/Classes/Frameworks/KSYMediaPlayer.framework)

**Comment by renzifeng** [comment]
Make sure that you `use use_frameworks! ` in the podfile
