### ISSUE TITLE
after `use_frameworks! ` in the podfile，still pod error: target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by zhl5213** [renzifeng/ZFPlayer#762]
Make sure that you `use use_frameworks! ` in the podfile

_Originally posted by @renzifeng in https://github.com/renzifeng/ZFPlayer/issues/758#issuecomment-491665226_

**Comment by zhl5213** [comment]
这是我的podfile：
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'someThingForTest' do

  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'ZFPlayer', '~> 3.0'
  pod 'ZFPlayer/ijkplayer', '~> 3.0'
  pod 'ZFPlayer/ControlView', '~> 3.0'
  pod 'ZFPlayer/AVPlayer', '~> 3.0'

end

然后pod install，依然报错
[!] The 'Pods-someThingForTest' target has transitive dependencies that include static binaries: (/Users/zhuhuilin/Downloads/MyProject/someThingForTest/Pods/IJKMediaFramework/IJKMediaFramework/Classes/IJKMediaFramework.framework)

只有我一个人有这问题吗？好无奈！    看网上说，要在podsepec里面，定义依赖库的static_framework = true，不知道是不是这个原因啊

**Comment by renzifeng** [comment]
Until this issue is resolved we worked around the static library check by simply disabling it in the Podfile:
```
pre_install do |installer|
    internalInstaller = installer.installer
    def internalInstaller.verify_no_static_framework_transitive_dependencies; end
end
```
We can build again :)
