### ISSUE TITLE
播放器更改为VLC，不显示ControlView

### ISSUE THREAD

**Issue by connerwu** [renzifeng/ZFPlayer#764]
根据文档将AVPlayer替换成VLC，可以正常播放，无法显示ControlView，但是StatusBar可以正常显示和隐藏。
VLC的播放器是通过drawable显示的，不是addSubview，可能和这个有关，希望作者能提供帮助，谢谢！
![Simulator Screen Shot - iPhone SE - 2019-05-22 at 11 16 03](https://user-images.githubusercontent.com/5482864/58144954-06505a00-7c83-11e9-8b8d-737210afc067.png)
![Simulator Screen Shot - iPhone SE - 2019-05-22 at 11 16 05](https://user-images.githubusercontent.com/5482864/58144955-06e8f080-7c83-11e9-849f-ad003a32ade6.png)

**Comment by renzifeng** [comment]
控制层被视频view遮挡了，你可以提供demo给我看一下

**Comment by connerwu** [comment]
已解决，控制层bringToFront就可以了，谢谢。

**Comment by wangjinwei0806** [comment]
具体是哪里啊

**Comment by connerwu** [comment]
> 具体是哪里啊

    self.controlView.controlViewAppearedCallback = ^(BOOL appeared) {
        @strongify(self)
        [self.controlView.superview bringSubviewToFront:self.controlView];
    };

**Comment by wangjinwei0806** [comment]
谢谢 回复 我之前加了 touchesBegan，去显示了
