### ISSUE TITLE
刚开始加载视频时黑屏或者是灰色

### ISSUE THREAD

**Issue by tianyewai** [renzifeng/ZFPlayer#766]
我用的是3.2.11版本的，从prepareToPlay到真正加载到视频之间这段时间一直是黑屏，在弱网情况下尤其明显。请问有什么办法可以避免吗。

**Comment by baiyidjp** [comment]
我是先展示一张图片.等开始播放在隐藏图片

**Comment by renzifeng** [comment]
可以按2楼说做

**Comment by scyios** [comment]
> 可以按2楼说做

图片要怎么加  加载哪里? 会覆盖控制层上的控件吗?
