### ISSUE TITLE
你好,请问播放完视频之后如何展示我的原视图

### ISSUE THREAD

**Issue by baiyidjp** [renzifeng/ZFPlayer#767]
具体
1. 播放完,我调用了 stop 方法,这时候展示的是一个黑色的
2. 我如何将这个黑色的 presendView 从我自己的 playBackView 中移除.
3. 展示我的 playBackView

   ZFPlayerController *playerController = [[ZFPlayerController alloc] initWithPlayerManager:playerManager containerView:playBackView];

**Comment by renzifeng** [comment]
调用ZFPlayerController 的 `stop`方法，该方法会移除presendView

**Comment by baiyidjp** [comment]
> 调用ZFPlayerController 的 `stop`方法，该方法会移除presendView

嗯 已经使用了.当时看demo以为就一个stop方法呢
