### ISSUE TITLE
为什么能搜到最新的,却pod不下来?

### ISSUE THREAD

**Issue by RomanticEncounter** [renzifeng/ZFPlayer#77]
为什么能search最新的,却pod不下来1.2.1,只能只有1.1.0,另一台电脑是1.1.7,墙也翻了,也重新pod setup了求助个解决方法

**Comment by renzifeng** [comment]
需要在终端执行cd转换文件路径命令退回到desktop，然后执行pod setup命令更新本地spec缓存（可能需要几分钟），然后再搜索就可以了。

**Comment by PromiscuousYouth** [comment]
谢谢,问题已经解决,将支持最低版本7.0 改为8.0即可

**Comment by pingcoco** [comment]
你好！！我pods了最新却显示缺少ZFFileModel这个和ZFHttpRequest这个是什么原因呢？

**Comment by PromiscuousYouth** [comment]
`pod 'ZFDownload'`

**Comment by pingcoco** [comment]
这个下载必须得用ASI吗、？？我项目中用的是AFN！我不想导俩套网络框架啊！！请问这个你是怎么解决的？

**Comment by PromiscuousYouth** [comment]
Demo中用的是ASI,你可以新建个工程,`pod 'ZFPlayer', '~> 1.2.1'`  ,尝试下,pod下来的是ZFPlayer和Masonry这个依赖库,没有ASI

**Comment by pingcoco** [comment]
缺少ZFFileModel这个和ZFHttpRequest！希望你可以给我发一份不带ASI的Demo可以吗？谢谢了！

**Comment by PromiscuousYouth** [comment]
留下邮箱,等会发你

**Comment by pingcoco** [comment]
ping_struggle@126.com
