### ISSUE TITLE
crash 问题

### ISSUE THREAD

**Issue by DreamHuman** [renzifeng/ZFPlayer#770]
45001 wakeups over the last 164 seconds (274 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
你好! 播放视频多个视频并切换,奔溃,日志, 提示线程唤醒超过 150次每秒  300秒内, 这个问题该怎么解决?  

我用 系统跟踪 显示 收到 三次 内存 警告 ,接着我的APP 被杀死.

**Comment by renzifeng** [comment]
这个问题是切换视频造成的吗，你这样描述我也不知道怎么帮你，可能说的不太明白
