### ISSUE TITLE
进入全屏方法，无法设置关闭动画

### ISSUE THREAD

**Issue by MakeHui** [renzifeng/ZFPlayer#771]
https://github.com/renzifeng/ZFPlayer/blob/38d0bcf4b738088c761e4c9252f21bdea961c723/ZFPlayer/Classes/Core/ZFPlayerController.m#L696-L699

https://github.com/renzifeng/ZFPlayer/blob/38d0bcf4b738088c761e4c9252f21bdea961c723/ZFPlayer/Classes/Core/ZFPlayerController.m#L701-L704

这两处的`[self.orientationObserver enterPortraitFullScreen:fullScreen animated:YES];`的`animated`是固定值
这样处理是有什么特殊的原因吗？
BTW: 我尝试改成`animated`并未发现有什么不对

**Comment by renzifeng** [comment]
写错了，多谢提醒
