### ISSUE TITLE
单个视频播放结束，再次点击播放，loading动画一直显示

### ISSUE THREAD

**Issue by wangtongvip** [renzifeng/ZFPlayer#773]
在GSFullScreenViewController这个demo中发现，视频播放完毕，再次通过双击屏幕或点击播放按钮播放，loading就会一直出现。

**Comment by renzifeng** [comment]
这个是什么demo，我提供的demo中没有这个类

**Comment by wangtongvip** [comment]
不好意思，写错了，是 ZFFullScreenViewController。
不过我把ZFIJKPlayerManager中
- (void)loadStateDidChange:(NSNotification*)notification；
if (self.player.currentPlaybackTime > 0) {
    self.loadState = GSLPlayerLoadStatePlayable;
}
的判断，改为 “>= 0”就好了。

感谢ZF共享这么棒的播放器哈

**Comment by Jayxiang** [comment]
= 0赶紧不太合理吧
