### ISSUE TITLE
手动点击退出全屏按钮和视频播放完成冲突

### ISSUE THREAD

**Issue by caicai0525** [renzifeng/ZFPlayer#775]
如果点击退出全屏按钮时，视频即将播放完成或播放完成时，退出全屏后，视频无法重新播放，播放按钮失效

**Comment by renzifeng** [comment]
播放完成的回调是你自己写的，你做了什么操作

**Comment by caicai0525** [comment]
执行了stopCurrentPlayingCell

**Comment by caicai0525** [comment]
我看demo中也有这个问题

**Comment by renzifeng** [comment]
这个是停止播放并移除当前播放的view，你自己处理播放完的回调就行

**Comment by caicai0525** [comment]
现在的问题是如果我正好在视频播放完成时点击了退出全屏的按钮，播放的view没从cell上移除

**Comment by GeekLee609** [comment]
> 现在的问题是如果我正好在视频播放完成时点击了退出全屏的按钮，播放的view没从cell上移除

麻烦给一下复现场景
