### ISSUE TITLE
老哥，画面只有声音没有画面 m3u8格式的

### ISSUE THREAD

**Issue by ZeKunLi** [renzifeng/ZFPlayer#776]
https://aliyun-v.feibiao.info/460897e33bfb4d229b6ad30f46a76792/dc8c582c334c4d22abb3469fb7bd9bb4-23e4c5a80e377506ce3f152f52b6c0b2-sd.m3u8

**Comment by GeekLee609** [comment]
估计是和这个视频源有关系，切换成 ZFPlayer/ijkplayer 播放器是可以播放的
