### ISSUE TITLE
setPlayerReadyToPlay Crash 

### ISSUE THREAD

**Issue by maxwell44** [renzifeng/ZFPlayer#780]
我将主工程打包成SDK（不依赖Pod）
新建工程通过pod导入ZFPlayer,使用最新版本 还有3.2.2  3.1.5  调用到setPlayerReadyToPlay依然崩溃

**Comment by ffzf** [comment]
最新版同样崩溃了

**Comment by renzifeng** [comment]
专门解决过这个问题，使用最新3.2.12也是如此吗

**Comment by maxwell44** [comment]
是的依然崩溃。

**Comment by maxwell44** [comment]
> 最新版同样崩溃了

你好 请问你的问题解决了么
