### ISSUE TITLE
使用Block返回视频截图

### ISSUE THREAD

**Issue by connerwu** [renzifeng/ZFPlayer#782]
ZFPlayerMediaPlayback.h中的 - (UIImage *)thumbnailImageAtCurrentTime;方法返回视频截图。但是某些播放器（VLC）返回当前帧的截图是异步的，没法使用此方法。
希望昨天考虑将此方法改成Block返回截图。

**Comment by renzifeng** [comment]
这个我会加到计划中的

**Comment by renzifeng** [comment]
vlc你能给我提供一下你写好的playerManager吗，我好做测试兼容

**Comment by climlove** [comment]
@connerwu 你这个vlc有内存泄漏的问题 ，您这边有解决么
