### ISSUE TITLE
进入页面使用ijkplayer播放的时候 ，会卡顿一段时间 

### ISSUE THREAD

**Issue by xuhuaping** [renzifeng/ZFPlayer#783]

**Comment by suweiz19890921** [comment]
我也是，第一次进入播放页面会卡很久！

**Comment by xuhuaping** [comment]
> 我也是，第一次进入播放页面会卡很久！

用金山云的

**Comment by oRhino** [comment]
我也是

**Comment by renzifeng** [comment]
卡顿之前是控制层读取bundle的image卡顿，还是播放器的？

**Comment by luanlzsn** [comment]
播放器的，只有第一次进入的时候会卡顿，下次再进去就不卡了

**Comment by xuhuaping** [comment]
> 卡顿之前是控制层读取束的图像卡顿，还是播放器的？

第一次进入创建UI的时候 会卡个几秒钟

**Comment by xxxIxxxx** [comment]
各位有什么好的解决方法吗？

**Comment by xxxIxxxx** [comment]
如果不连着Xcode，还是挺快的。应该没问题

**Comment by renzifeng** [comment]
@xuhuaping UI卡顿已经解决了

**Comment by sunwell** [comment]
@renzifeng 
请问你是怎么解决这个问题的？
有代码或者commit可以参考吗？
