### ISSUE TITLE
Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

### ISSUE THREAD

**Issue by chaziyjs** [renzifeng/ZFPlayer#784]
最近在处理后台持续播放的时候发现了这个问题.(在app进入后台时报错)
Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.
在实现方法时,我首先修改pauseWhenAppResignActive为true.
然后手动设置 AVAudioSession 的 setActive:YES error:nil 方法;
但是进入后台后就会被系统强制停止播放. (pauseWhenAppResignActive = NO,注释掉手动设置的代码时同样会发生该情况).请问有什么解决方法么?

**Comment by chaziyjs** [comment]
补充:
重写了个项目进行测试,在各个系统版本上运行都没有问题.只能分析出,项目中还有其他功能在使用或者占用了audio session I/O.

**Comment by renzifeng** [comment]
播放器内部有修改AVAudioSession，你要自定义有个属性customAudioSession可以关闭内部修改的audioSession。你的问题可能有其他类有修改这个
