### ISSUE TITLE
部分视频模拟机可以正常播放、真机却无画面只有声音

### ISSUE THREAD

**Issue by XueYangLee** [renzifeng/ZFPlayer#790]
mp4格式视频真机播放  有的可以正常播放，有的播放只有声音没有画面
但同样的视频在电脑模拟机上可以正常播放
使用demo文件替换视频同样问题
问题视频地址之一：https://file.wchoosemall.com/video/20190614/14437407677359653.mp4

**Comment by codeliu6572** [comment]
你解决了么？我也遇到了

**Comment by flyWhite** [comment]
同样问题
