### ISSUE TITLE
播放加密的m3u8

### ISSUE THREAD

**Issue by YYHNobug** [renzifeng/ZFPlayer#791]
iOS播放加密的m3u8视频，后台把每个ts的地址进行加密(自定义的加密算法)，客户端进行解密后播放，此demo支持吗？现在用AVPlayer已经实现，但是AVPlayer播放不了h265的视频，有其它方案吗

**Comment by GeekLee609** [comment]
可以尝试用其他播放器，ijkplayer或者KSYMediaPlayer，解密方法参考你实现的AVPlayer
