### ISSUE TITLE
关于全屏模式下，手势调节音量的问题

### ISSUE THREAD

**Issue by robin-chow** [renzifeng/ZFPlayer#793]
您好，感谢提供这么好的库，有个小问题请教一下。就是在全屏模式下，用手势调节音量时快速滑动时，volumeBrightnessView 的音量类型下，progress条连续跳动。

**Comment by kllie** [comment]
这种情况怎么解决？怎么才能保证和调节亮度那么流畅呢？

**Comment by monkiyang** [comment]
同问
