### ISSUE TITLE
新版倍速问题

### ISSUE THREAD

**Issue by YearRen** [renzifeng/ZFPlayer#796]
新版倍速有个bug，初始化设置倍速为非1倍的时候，不会倍速播放 @renzifeng 看看这样改会不会有问题
![image](https://user-images.githubusercontent.com/13882689/60519261-ca92c080-9d15-11e9-95ff-186d6a6207bd.png)

**Comment by guojingjingghost** [comment]
只有新版本才支持倍速播放吗

**Comment by YearRen** [comment]
不是，这个功能是早开发的吧

**Comment by guojingjingghost** [comment]
我查了下我前几个月升级的版本还没看到支持倍速播放啊

**Comment by xxThomas** [comment]
ZFAVPlayerManager就是对avplayer的一个封装, playerManager.player.rate即便不提供也可以使用倍速, 只不过之前的版本倍速后会有卡顿, 所以后来作者又把它重新弄了一下. 现在只需要playerManager.rate 就行.

**Comment by renzifeng** [comment]
@YearRen 这样也行，我改出了一些问题，导致倍速播放失效，我现在在播放时间的回调里写的

**Comment by Liyongcong** [comment]
> ZFAVPlayerManager就是对avplayer的一个封装, playerManager.player.rate即便不提供也可以使用倍速, 只不过之前的版本倍速后会有卡顿, 所以后来作者又把它重新弄了一下. 现在只需要playerManager.rate 就行.

我在他的demo里面这样设置的为什么没效果呢
    ZFAVPlayerManager *playerManager = [[ZFAVPlayerManager alloc] init];
//
    playerManager.player.rate = 1.5;

    /// player的tag值必须在cell里设置
    self.player = [ZFPlayerController playerWithScrollView:self.tableView playerManager:playerManager containerViewTag:100];
    self.player.controlView = self.controlView;
    self.player.assetURLs = self.urls;
    /// 0.8是消失80%时候，默认0.5
    self.player.playerDisapperaPercent = 0.8;
    /// 移动网络依然自动播放
    self.player.WWANAutoPlay = YES;

**Comment by huangxianyu** [comment]
倍速问题 我这么改的源码
--> ZFAVPlayerManager
 else if ([keyPath isEqualToString:kPlaybackLikelyToKeepUp]) {
    // When the buffer is good
    if (self.playerItem.playbackLikelyToKeepUp) {
        self.loadState = ZFPlayerLoadStatePlayable;
        if (self.isPlaying) [self.player play];
        --> 改为
        if (self.isPlaying) {
             [self.player play];
             self.player.rate = self.rate;
        }
    }
 }
