### ISSUE TITLE
很生气，反馈了bug不闻不问，我在回退版本时把代码弄丢了

### ISSUE THREAD

**Issue by chenjin0624** [renzifeng/ZFPlayer#798]
好不容易添加了一些自定义功能，一想到这个版本有bug就回退了下版本，pod Install了一下代码全没了。最新版本播放本地视频后退一直有转圈的的bug还解决吗？

**Comment by renzifeng** [comment]
我想说把代码弄丢这锅甩给我了？自己修改pod里的代码不单独拿出来怨谁，bug还没时间解决，我还有一些事情在忙。
