### ISSUE TITLE
进度条拖拽的时候视频没有暂停播放

### ISSUE THREAD

**Issue by TheLittleBoy** [renzifeng/ZFPlayer#8]
当拖拽并没有结束的时候，视频不应该继续播放吧。

**Comment by renzifeng** [comment]
这个还没加，并不难实现。

**Comment by TheLittleBoy** [comment]
good

**Comment by renzifeng** [comment]
这个问题我已经解决，更新代码看看吧

**Comment by TheLittleBoy** [comment]
恩，看了看，感觉UIGestureRecognizerDelegate里边的 屏幕下方slider区域不响应pan手势，这种实现方法不是很完美（进度条拖动依然不灵敏），应该有更好的解决方案哦。

**Comment by renzifeng** [comment]
那静待你的pull request咯

**Comment by TheLittleBoy** [comment]
恩，我抽时间看看。
