### ISSUE TITLE
新版自动播放问题

### ISSUE THREAD

**Issue by jianqingyu** [renzifeng/ZFPlayer#800]
升级到新版之后，一滑动tableview就重新播放，没有旧版的那种触发播放

**Comment by maple1994** [comment]
旧版这里是这样的
`- (void)zf_filterShouldPlayCellWhileScrolled:(void (^ __nullable)(NSIndexPath *indexPath))handler {
    if (!self.zf_shouldAutoPlay) return;
    @weakify(self)
    [self zf_filterShouldPlayCellWhileScrolling:^(NSIndexPath *indexPath) {
        @strongify(self)
        /// 如果当前控制器已经消失，直接return
        if (self.zf_viewControllerDisappear) return;
        if ([ZFReachabilityManager sharedManager].isReachableViaWWAN && !self.zf_WWANAutoPlay) {
            /// 移动网络
            self.zf_shouldPlayIndexPath = indexPath;
            return;
        }
        if (!self.zf_playingIndexPath) {
            if (handler) handler(indexPath);
            self.zf_playingIndexPath = indexPath;
        }
    }];
}`
新版是
`
if (handler) handler(indexPath);
        self.zf_playingIndexPath = indexPath;
`
少了!self.zf_playingIndexPath这个判断，所以滑动时会重新播放

**Comment by jianqingyu** [comment]
那请问怎么改呢

**Comment by maple1994** [comment]
> 那请问怎么改呢

指定旧版本吧，先用旧版本，这个等原作者修复或者回复呗

**Comment by jianqingyu** [comment]
好吧。。。

**Comment by maple1994** [comment]
参考最新的Demo吧，在外部进行判断
```
_tableView.zf_scrollViewDidStopScrollCallback = ^(NSIndexPath * _Nonnull indexPath) {
            @strongify(self)
            if (!self.player.playingIndexPath) {
                [self playTheVideoAtIndexPath:indexPath scrollToTop:NO];
            }
        };
```

**Comment by jianqingyu** [comment]
好像可以了  谢谢
