### ISSUE TITLE
swift scalingMode属性无法访问

### ISSUE THREAD

**Issue by SwiftNie** [renzifeng/ZFPlayer#801]
swift 中设置player?.currentPlayerManager.scalingMode 属性报错
<img width="1074" alt="屏幕快照 2019-07-07 下午2 24 07" src="https://user-images.githubusercontent.com/13481962/60764832-48165200-a0c3-11e9-8153-e15a07b21683.png">

**Comment by XLMARK** [comment]
我也遇到了

**Comment by CoderWeiLee** [comment]
怎么解决的啊

**Comment by CoderWeiLee** [comment]
> 我也遇到了

解决了吗

**Comment by huangyingqiu** [comment]
我也遇到了，解决方法也很简单，用OC封装一个函数过来用就行了

**Comment by 321nanjiang** [comment]
//配置填充模式
* (void)setFullScreenSwitch:(UISwitch *)sender {
* [self.player.currentPlayerManager pause];
* if (sender.isOn) {
* self.player.currentPlayerManager.scalingMode = ZFPlayerScalingModeAspectFill;
* } else {
* self.player.currentPlayerManager.scalingMode = ZFPlayerScalingModeAspectFit;
* }
* [self.player.currentPlayerManager play];
* }
暂停状态可以配置填充模式，短期解决方案，可以先实现。

**Comment by 321nanjiang** [comment]
swift 问题 应该是 规范问题 直接自己加个OC方法吧。
