### ISSUE TITLE
新版3.0横竖屏自动切换问题：横屏自动切换竖屏失败，原因：横屏状态下状态栏仍是竖屏状态。

### ISSUE THREAD

**Issue by yuankai01** [renzifeng/ZFPlayer#803]
做视频横竖屏切换功能（设备：iPhone6，iOS12.1）：发现竖屏可用自动切换横屏，当时当横屏自动切换竖屏时失败，断点调试发现获取到状态栏方向和当前设备要旋转的方向一致，直接被return掉了；发现横屏时状态仍是竖屏显示的，所以导致自动切换竖屏时失败。(手动切换没问题，虽然横屏时状态栏仍是竖屏样式的)。
 UIInterfaceOrientation currentOrientation = [UIApplication sharedApplication].statusBarOrientation;
    // Determine that if the current direction is the same as the direction you want to rotate, do nothing
    if (_currentOrientation == currentOrientation && !self.forceDeviceOrientation) return;
最终原因：横屏状态是，状态栏仍是竖屏样式显示，没有自动切换为横屏状态。

**Comment by yuankai01** [comment]
原因是使用了DoraemonKit导致的

**Comment by lzylzy1991** [comment]
使用了DoraemonKit导致的   ？？？？  大佬 这是 什么？？

**Comment by yuankai01** [comment]
> 使用了DoraemonKit导致的 ？？？？ 大佬 这是 什么？？

一种第三方库APP检测工具，gitHub可以搜到。
