### ISSUE TITLE
3.2.12 1. 小窗滑动； 2.tableview上的播放器重新加载

### ISSUE THREAD

**Issue by ethanCun** [renzifeng/ZFPlayer#810]
你好，ZFPlayer很👍，我在使用的过程中遇到了下面一些问题，反馈一下

版本：3.2.12 

1. 小窗滑动滑动距离长消失，但是声音还在，滑动上去对应的Cell不播放；有时UI还会错乱，卡顿严重；
2.tableview上的播放器刚开始加载进度的时候滑动一段距离松手，对应cell就得重新加载播放器，等待一段时间再滑动就没有类似的情况

**Comment by renzifeng** [comment]
1、首先考虑cell的复用问题，2、zf_scrollViewDidStopScrollCallback 回调里要判断，当前player.playingIndexPath是否为nil，当为nil的时候再去播放找到的indexPath的视频
