### ISSUE TITLE
有没有可以彻底停止cell播放器的方法

### ISSUE THREAD

**Issue by huangyisheng** [renzifeng/ZFPlayer#811]
像以前2.1.6等低版本 有个resetPlayer 这方法可以彻底停止，但是现在的版本调用stopCurrentPlayingCell 不管用。场景是segment下装控制器下的view，view里面有list，当前在播放的cell，切换上方tab ，前一个播放器无法停止

**Comment by renzifeng** [comment]
[player stop];
