### ISSUE TITLE
ZFAVPlayerManager  stop 方法中代码顺序的合理性

### ISSUE THREAD

**Issue by LJW008** [renzifeng/ZFPlayer#812]
这个方法中先 replaceCurrentItemWithPlayerItem，
然后     self.playState = ZFPlayerPlayStatePlayStopped; 
这时候会回调  playerPlayStateChanged 这个方法，这样的话如果开发者想在回调中拿到之前播放对象的一些信息就拿不到了，比如 视频播放时长统计，加记忆播放的功能，请教作者下，你之前这么些是有别的原因还是什么呢？

**Comment by renzifeng** [comment]
没有别的原因，可以修改一下
