### ISSUE TITLE
ios release模式下 ios 12 的系统重力感应 横竖屏 切换问题

### ISSUE THREAD

**Issue by lzylzy1991** [renzifeng/ZFPlayer#813]
ios release模式下 ios 12 的系统重力感应 横竖屏 切换 
self.player.forceDeviceOrientation = YES;
重力感应横屏成这个样子，如图，点击全屏按钮是正常的

ios debug模式 是正常的

![IMG_0036(20190715-202015)](https://user-images.githubusercontent.com/14507003/61215823-1efc4f80-a6c9-11e9-86bf-2d4c8f532a34.jpg)

**Comment by renzifeng** [comment]
需要重写 - (BOOL)shouldAutorotate 返回YES， -(UIInterfaceOrientationMask)supportedInterfaceOrientations  返回支持的方向
