### ISSUE TITLE
self.player.playingIndexPath 一直是nil，视频已经播放中

### ISSUE THREAD

**Issue by 542604974** [renzifeng/ZFPlayer#817]
_tableView.zf_scrollViewDidStopScrollCallback = ^(NSIndexPath * _Nonnull indexPath) {
            @strongify(self)
            if (!self.player.playingIndexPath || self.player.playingIndexPath.row != indexPath.row) {

            }
        };

(lldb) po self.player.playingIndexPath
 nil
(lldb)

**Comment by 542604974** [comment]
![屏幕快照 2019-07-24 上午9 35 48](https://user-images.githubusercontent.com/15099430/61758216-751e7080-adf6-11e9-8769-1acbb7110015.png)
这里playingIndexPath是nil

**Comment by renzifeng** [comment]
有点问题，我修改了一下
