### ISSUE TITLE
ZFPlayerControlView 设置muted 为啥会弹出系统的的音量控制

### ISSUE THREAD

**Issue by 542604974** [renzifeng/ZFPlayer#818]
ZFPlayerControlView 设置muted 为啥会弹出系统的的音量控制

**Comment by renzifeng** [comment]
首先你调用的是player.muted,这个是修改的系统静音，要是不谈系统音量控制可以修改播放器静音，player.currentPlayerManager.muted,遇到问题请先看注释

**Comment by 542604974** [comment]
player.currentPlayerManager.muted 我调用这个也是一样弹出系统的的音量控制，self.player.volume  self.controlView.player.volume 都是结果一样，修改的系统静音
