### ISSUE TITLE
控制面板点击暂停，视频依然播放

### ISSUE THREAD

**Issue by 951501195** [renzifeng/ZFPlayer#819]
iphone 6p点击播放视频以后，小页面播放和全屏播放点击暂停按钮都没有作用，按钮图标点击后已经变成暂停状态，但是视频依然在播放，这是什么原因？

**Comment by a624500136** [comment]
我这边也是出现这个问题，使用的是AVPlayer

**Comment by chongzone** [comment]
我现在解决了，好像直接导入IJK对应的SDK需要配置这个'-all_load'，可能这样你会出现编译错误， 类似这样的'https://blog.csdn.net/w15117957952/article/details/83061132'，不过还好，这个可以解决掉
链接：https://blog.csdn.net/xfy6238/article/details/77505744

在 2019-07-29 15:43:49，"DemoMrCe" <notifications@github.com> 写道：


我这边也是出现这个问题，使用的是AVPlayer
