### ISSUE TITLE
iOS13横竖屏切换会导致导航栏显示错乱

### ISSUE THREAD

**Issue by suwenclub** [renzifeng/ZFPlayer#822]
iOS13横竖屏切换会导致导航栏显示错乱

**Comment by umyumm** [comment]
Using translator to english

"Horizontal and vertical screen switching will cause the navigation bar to display confusion"

I'm also seeing this issue when testing on iPhone Xr simulator iOS 13.  When switch to full screen and then out of full screen the navigation bar is hidden.  Screenshot below:

<img width="459" alt="iOS 13 Before FullScreen" src="https://user-images.githubusercontent.com/20023499/62002827-1fc9b400-b0c1-11e9-966f-a5cb6d92f0e0.png">

<img width="459" alt="iOS 13 After FullScreen" src="https://user-images.githubusercontent.com/20023499/62002831-23f5d180-b0c1-11e9-94f4-b2773c24de1a.png">

**Comment by WIndFate** [comment]
这个还是没有解决啊，在有tabbarcontroller的时候，视频全屏后退到后台，重新进来退出全屏，就看到导航栏上移

**Comment by YangChaoJie** [comment]
这个问题解决了没呀
