### ISSUE TITLE
大神,你好,为什么我pod会出现问题呢?

### ISSUE THREAD

**Issue by hzhh110** [renzifeng/ZFPlayer#823]
pod 'IJKMediaFramework'
pod 'ZFPlayer', '~> 3.2.9'
pod 'ZFPlayer/ControlView', '~> 3.0'
pod 'ZFPlayer/AVPlayer', '~> 3.0'
pod 'ZFPlayer/ijkplayer'

The 'Pods-IoTiOS' target has transitive dependencies that include static binaries: (/Users/huangzhenhui/Desktop/巨晖项目/IoTiOS/Pods/IJKMediaFramework/IJKMediaFramework/Classes/IJKMediaFramework.framework)

**Comment by hzhh110** [comment]
表示我直接把ZFPlayer拉进去,不使用pod管理解决.......

**Comment by renzifeng** [comment]
你这是swift项目吧，你得找个，podfile里得use_frameworks!去掉，或者你用动态库的IJKMediaFramework
