### ISSUE TITLE
前台有两个视频页, 后台返回会播放两个视频, 声音嘈杂

### ISSUE THREAD

**Issue by xiaohange** [renzifeng/ZFPlayer#829]

**Comment by yszhangjiayu** [comment]
解决了吗 我也遇到了相同的问题

**Comment by xiaohange** [comment]
> 解决了吗 我也遇到了相同的问题

暂未解决, 临时将进入后台源码stop改成autostop了,

**Comment by meiyingda1** [comment]
} else if ([keyPath isEqualToString:kPlaybackBufferEmpty]) {
            // When the buffer is empty
            if (self.playerItem.playbackBufferEmpty) {
                self.loadState = ZFPlayerLoadStateStalled;
                 #warning 解决后台返回前台会播放两个视频的bug
                if (!self.isPlaying) {
                    return;
                }
                
                [self bufferingSomeSecond];
            }
        }

**Comment by xiaohange** [comment]
> } else if ([keyPath isEqualToString:kPlaybackBufferEmpty]) {
> // When the buffer is empty
> if (self.playerItem.playbackBufferEmpty) {
> self.loadState = ZFPlayerLoadStateStalled;
> #warning 解决后台返回前台会播放两个视频的bug
> if (!self.isPlaying) {
> return;
> }
> 
> ```
>             [self bufferingSomeSecond];
>         }
>     }
> ```

没有验证，可以验证后确认下
