### ISSUE TITLE
swift我用pod集成，项目为什么找不到framwork

### ISSUE THREAD

**Issue by qs991011** [renzifeng/ZFPlayer#836]

**Comment by CoderWeiLee** [comment]
可以看一下你的pod文件里引用的对不对

**Comment by CoderWeiLee** [comment]
Podfile里应该是像这样:
target 'your projectName' do
use_frameworks!
pod 'ZFPlayer'
pod 'ZFPlayer/ControlView'
pod 'ZFPlayer/AVPlayer'

**Comment by GeekLee609** [comment]
目前已经支持 use_frameworks!
