### ISSUE TITLE
UITableView reloadRowsAtIndexPaths 视频暂停问题

### ISSUE THREAD

**Issue by hao1993** [renzifeng/ZFPlayer#852]
老哥，你好，遇到个问题，请教如何解决。
问题：UITableView reloadRowsAtIndexPaths 视频会暂停，再次reloadRowsAtIndexPaths，视频会继续播放。reload时候怎样能不影响视频的播放？

**Comment by MakeBetterMe** [comment]
读了一下源码，你在reload方法后面，调用下这个方法 

self.player.addPlayerViewToCell()
