### ISSUE TITLE
zf_shouldPlayIndexPathCallback 方法

### ISSUE THREAD

**Issue by LJW008** [renzifeng/ZFPlayer#853]
- (void)setZf_shouldPlayIndexPath:(NSIndexPath *)zf_shouldPlayIndexPath {
    if (self.zf_shouldPlayIndexPathCallback) self.zf_shouldPlayIndexPathCallback(zf_shouldPlayIndexPath);
    objc_setAssociatedObject(self, @selector(zf_shouldPlayIndexPath), zf_shouldPlayIndexPath, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}
这个地方如果我不是自动播放，而是点击播放的话，zf_shouldPlayIndexPathCallback在这个回调里取 self.tableView.zf_shouldPlayIndexPath 是取不到的呀。感觉应该先set再block吧

**Comment by renzifeng** [comment]
好的

**Comment by Lee0820** [comment]
我看新版的这里又改回去了呢 @ @renzifeng
