### ISSUE TITLE
ios13上状态栏不会旋转了

### ISSUE THREAD

**Issue by 1546461417** [renzifeng/ZFPlayer#856]

**Comment by NSObject-RC** [comment]
是因为setStatusBarOrientation 在iOS13下API失效了
解决：允许控制器旋转，iOS13横屏时会自动隐藏状态栏。ZF提供了TurnOnVCRotation开启控制器旋转

**Comment by NSObject-RC** [comment]
解决二：更简单，横屏的时候人为隐藏状态栏：

(BOOL)prefersStatusBarHidden {
if (@available(iOS 13.0, *)) {
return self.player.isFullScreen;
}
return NO;
}
这里我判断了是否iOS13。
