### ISSUE TITLE
iOS13-beta后切换横屏,状态栏没有切换

### ISSUE THREAD

**Issue by Lixyss** [renzifeng/ZFPlayer#857]
iOS13后通过这个方法[UIApplication sharedApplication].statusBarOrientation = orientation设置状态栏失效. 
系统提示: [Assert] -[UIApplication setStatusBarOrientation:] and -[UIApplication setStatusBarOrientation:animated:] API have been deprecated on iOS 8.0 and are no-ops on iOS 13.0

**Comment by githubhuxian** [comment]
同样遇到了，如果是用Xcode 11打包的，就会出现， 貌似用10.3打包，即使在iOS13上，也是可以正常旋转的

**Comment by zengqingf** [comment]
同遇到了，就因为这个，appStore上有用户给我打了个差评 ，哈哈，坐等作者更新修复

**Comment by NSObject-RC** [comment]
是因为setStatusBarOrientation 在iOS13下API失效了
解决：允许控制器旋转，iOS13横屏时会自动隐藏状态栏。ZF提供了TurnOnVCRotation开启控制器旋转

**Comment by NSObject-RC** [comment]
解决二：更简单，横屏的时候人为隐藏状态栏：

(BOOL)prefersStatusBarHidden {
if (@available(iOS 13.0, *)) {
return self.player.isFullScreen;
}
return NO;
}
这里我判断了是否iOS13。

**Comment by Lixyss** [comment]
人为隐藏状态栏, 自动切换全屏,无法返回到竖屏, 我的处理方法是取消zfplayer设备旋转监听, 自己监听,旋转

**Comment by NSObject-RC** [comment]
最简单就是设置控制器旋转，iOS13，会自动隐藏状态栏------------------ 原始邮件 ------------------
发件人: "li_xy"<notifications@github.com>
发送时间: 2019年9月28日(星期六) 下午4:24
收件人: "renzifeng/ZFPlayer"<ZFPlayer@noreply.github.com>;
抄送: "小虎牙"<379561695@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [renzifeng/ZFPlayer] iOS13-beta后切换横屏,状态栏没有切换 (#857)



人为&#x9690;藏状态栏, 自动切换全屏,无法返回到竖屏, 我的处理方法是取消zfplayer设备旋转监听, 自己监听,旋转
 
&mdash;

**Comment by NSObject-RC** [comment]
最简单就是设置控制器旋转，在iOS13下，系统会自动隐藏状态栏

**Comment by Gaozn** [comment]
> 是因为setStatusBarOrientation 在iOS13下API失效了
> 解决：允许控制器旋转，iOS13横屏时会自动隐藏状态栏。ZF提供了TurnOnVCRotation开启控制器旋转

这个方法在哪，没见到啊

**Comment by jeff201903** [comment]
> > 是因为setStatusBarOrientation 在iOS13下API失效了
> > 解决：允许控制器旋转，iOS13横屏时会自动隐藏状态栏。ZF提供了TurnOnVCRotation开启控制器旋转
> 
> 这个方法在哪，没见到啊

同问

**Comment by niyaoyao** [comment]
> 解决二：更简单，横屏的时候人为隐藏状态栏：
> 
> (BOOL)prefersStatusBarHidden {
> if (@available(iOS 13.0, *)) {
> return self.player.isFullScreen;
> }
> return NO;
> }
> 这里我判断了是否iOS13。

那就需要做很多兼容了

**Comment by liyinjie01** [comment]
> 人为隐藏状态栏, 自动切换全屏,无法返回到竖屏, 我的处理方法是取消zfplayer设备旋转监听, 自己监听,旋转

你好，你是怎么做的能发来参考一下吗

**Comment by liyinjie01** [comment]
。。

**Comment by xiaxingname** [comment]
试试没有后续了
