### ISSUE TITLE
网速比较差的情况下，页面卡住不能顺畅播放，但是下边的时间轴还在正常进行

### ISSUE THREAD

**Issue by jiaNanZhu** [renzifeng/ZFPlayer#859]
页面卡住以后，loading中，但是下边的时间轴还在按正常的播放速度前进

**Comment by Spr1ngHall** [comment]
你可以再ZFAVPlayerManager里面的` -(void)itemObserving `方法里面的
***
if (self.isPlaying ）
self.player.rate = self.rate;
***
 改为
***
if (self.isPlaying && self.loadState != ZFPlayerLoadStateStalled) 
self.player.rate = self.rate; 
***
然后将` -(void)bufferingSomeSecond `方法里面的
***
if (!self.isPlaying) {
            self.isBuffering = NO;
            return;
        }
***
改为
***
if (!self.isPlaying && self.loadState == ZFPlayerLoadStateStalled) {
            self.isBuffering = NO;
            return;
        }
***
以上两处修改之后基本上解决了这个问题。

**Comment by GeekLee609** [comment]
> 你可以再ZFAVPlayerManager里面的`-(void)itemObserving`方法里面的
> 
> if (self.isPlaying ）
> self.player.rate = self.rate;
> 
> 改为
> 
> if (self.isPlaying && self.loadState != ZFPlayerLoadStateStalled)
> self.player.rate = self.rate;
> 
> 然后将`-(void)bufferingSomeSecond`方法里面的
> 
> if (!self.isPlaying) {
> self.isBuffering = NO;
> return;
> }
> 
> 改为
> 
> if (!self.isPlaying && self.loadState == ZFPlayerLoadStateStalled) {
> self.isBuffering = NO;
> return;
> }
> 
> 以上两处修改之后基本上解决了这个问题。

谢谢，我们测试一下这个
