### ISSUE TITLE
iOS 13 全屏模式 音量键

### ISSUE THREAD

**Issue by jianqingyu** [renzifeng/ZFPlayer#866]
iOS 13全屏模式下点击播放会出现音量控件

**Comment by lzylzy1991** [comment]
这是由于监听 系统音量 通知 导致，在处理音量监听的方法中 加入音量改变的判断就可以了
- (void)volumeChanged:(NSNotification *)notification {
}
在 该方法中加入如下判断
            NSString *reason = [[notification userInfo] objectForKey:@"AVSystemController_AudioVolumeChangeReasonNotificationParameter"];
            if ([reason isEqualToString:@"ExplicitVolumeChange"]) {
/// 音量 调节的 view 
                [self.volumeBrightnessView updateProgress:volume withVolumeBrightnessType:ZFHKNormalVolumeBrightnessTypeVolume];
            }

**Comment by jianqingyu** [comment]
谢谢
