### ISSUE TITLE
iOS13全屏bug，效果如下：

### ISSUE THREAD

**Issue by HHuiHao** [renzifeng/ZFPlayer#868]
![image](https://user-images.githubusercontent.com/8486113/66543768-dee22700-eb68-11e9-8991-075b23437946.png)

![image](https://user-images.githubusercontent.com/8486113/66543624-827f0780-eb68-11e9-95e6-f62c08f9bd5f.png)

**Comment by wxhAtGithub** [comment]
同样的问题

**Comment by YuZeDaGeGe** [comment]
同样的问题

**Comment by Absurd-BC** [comment]
有解决吗？

**Comment by ReyZhang** [comment]
这个问题，其实是因为在ios13下设置状态栏方向的方法被废弃导致的问题
`[[UIApplication sharedApplication] setStatusBarOrientation:xxx animated:xx];`

修复如下：
在 ZFPlayerView 中可以使用一下局部变量来保存方法传递进来的需要旋转的方向，找到如下的设置代码
`[[UIApplication sharedApplication] setStatusBarOrientation:orientation animated:NO];`
改成使用局部变量保存，如：声明一个 _statusBarOrientation
`_statusBarOrientation = orientation;
`

在根据旋转方向获取视图旋转角度的方法 getTransformRotationAngle 中，从原有的获取方向的代码：
`UIInterfaceOrientation orientation = [UIApplication sharedApplication].statusBarOrientation;`
改成从局部变量中读取就可以了
`UIInterfaceOrientation orientation = _statusBarOrientation;`

**Comment by ReyZhang** [comment]
> 有解决吗？

请参考我的回复

**Comment by YuZeDaGeGe** [comment]
好的谢谢，我现在隐藏了 - -

**Comment by BaranBerk** [comment]
Deprecated! Anyone else have any solution?

**Comment by vlay1314** [comment]
@HHuiHao  你的是结合Jxcatygory做的吗？可以横屏播放吗？
