### ISSUE TITLE
不自动播放的时候，点击左下角的播放按钮，但是并没播放

### ISSUE THREAD

**Issue by AlleniCode** [renzifeng/ZFPlayer#87]
不自动播放的时候，点击左下角的播放按钮，但是并没播放，是我的设置有问题吗？还是什么原因啊？谢谢！

**Comment by zJunZ** [comment]
作者有行代码让中间播放按钮以外全部透明,但打开时会调用layoutSubviews,里面[self animateShow]又将其他按钮显示了出来,我的做法是注释掉,暂时没发现问题

**Comment by AlleniCode** [comment]
@zJunZ 好的，我试试，谢谢啦！
