### ISSUE TITLE
限定时长

### ISSUE THREAD

**Issue by sunlight2728** [renzifeng/ZFPlayer#873]
比如我有1个小时的播放时长
可是我限定在三分钟
三分钟后就不能继续播放了
这个有思路吗

**Comment by sunlight2728** [comment]
> 比如我有1个小时的播放时长
> 可是我限定在三分钟
> 三分钟后就不能继续播放了
> 这个有思路吗

**Comment by sunlight2728** [comment]
ZFPlayer试看，没人做过吗

**Comment by Joneze** [comment]
我也正有这个需求，还没找到 接口。
