### ISSUE TITLE
iOS 13 setStatusBarOrientation 处理下吧，大佬

### ISSUE THREAD

**Issue by LJW008** [renzifeng/ZFPlayer#880]
[Assert] -[UIApplication setStatusBarOrientation:] and -[UIApplication setStatusBarOrientation:animated:] API have been deprecated on iOS 8.0 and are no-ops on iOS 13.0.

**Comment by lsqiang** [comment]
是的  这个确实废了

**Comment by liyinjie01** [comment]
你好  现在找到什么替代方案吗

**Comment by ReyZhang** [comment]
参考一下 这个问题 #868  下我的回复

**Comment by coderchou** [comment]
有解决方案吗

**Comment by renzifeng** [comment]
fix

**Comment by Sky891028** [comment]
怎么解决的 有提交吗 ？
