### ISSUE TITLE
关于pod里 ijk引入 无法使用 use_frameworks! 命令冲突

### ISSUE THREAD

**Issue by ljssafe** [renzifeng/ZFPlayer#881]
由于pod里不少库 必须引入use_frameworks! 命令否则会报错  
可是 ijk 以及 金山云的库 都是必须 屏蔽这句才能下载的 ，请问有办法能避开这个冲突么？

**Comment by GeekLee609** [comment]
目前不能避开，需要修改对应的 podspec 配置，支持动态库

**Comment by GeekLee609** [comment]
已经修复了，请更新最新版试试

**Comment by ljssafe** [comment]
好的 ，我试试看，👍 这下就方便用了  否则手动导入ijk 要配置一堆系统库 倒腾死😝
