### ISSUE TITLE
ios13有声音无画面是什么问题呢？

### ISSUE THREAD

**Issue by 1224860397** [renzifeng/ZFPlayer#885]

**Comment by GeekLee609** [comment]
可以把视频连接给一下，必现么？

**Comment by souls-shaohui** [comment]
> 可以把视频连接给一下，必现么？

http://qiniuyun.sdjmm.net/0f2eded1-076b-4ae3-9439-018ab67bcfc0.mp4

**Comment by souls-shaohui** [comment]
部分视频

**Comment by GeekLee609** [comment]
> 部分视频，系统12.0.1，
> 真机上不行，模拟器可以。
> http://qiniuyun.sdjmm.net/2536e7aa5c9f4757b0f7e1937096246a

你用的是系统的AVPlayer 么？可以试试IJK的看看

**Comment by weilLove** [comment]
> > 部分视频，系统12.0.1，
> > 真机上不行，模拟器可以。
> > http://qiniuyun.sdjmm.net/2536e7aa5c9f4757b0f7e1937096246a
> 
> 你用的是系统的AVPlayer 么？可以试试IJK的看看

IJK的UI展现上的瑕疵如何避免呢?而且，今天测试遇到，ijk播放m3u8也会有黑屏问题，但不是必现，在网络弱的时候偶现

**Comment by weilLove** [comment]
您好，有声音无画面的问题解决了吗，我这边遇到的是播放一段时间后，画面卡死，声音和进度正常

**Comment by Hanrovey** [comment]
你好，有声音无画面，在swift项目里面，这个问题能帮忙看下吗？

**Comment by Mryawn** [comment]
> 您好，有声音无画面的问题解决了吗，我这边遇到的是播放一段时间后，画面卡死，声音和进度正常

你好。请问下，问题后面怎么解决的呢？
