### ISSUE TITLE
大佬，您好！我有几个问题想请教一下。望回复。

### ISSUE THREAD

**Issue by Ya0HJ** [renzifeng/ZFPlayer#887]
我想问问如果要做全屏播放下可以选集和选择倍速播放，应该怎么做？还有想做试看功能，改怎么处理？望回复，谢谢！！！

**Comment by renzifeng** [comment]
倍速播放自定义UI使用rate属性
选集功能自定义UI点击播放不同的URL就行
试看功能，就监测播放时间，到一定的时间就停止播放
