### ISSUE TITLE
use_frameworks!

### ISSUE THREAD

**Issue by Rookie920** [renzifeng/ZFPlayer#888]
你好作者，
描述：
我的项目是OC，因为用到了三方库是 swift，在包含use_frameworks!情况下，pod 'ZFPlayer/ijkplayer', '~> 3.0'报错 [!] The 'Pods-iphoneLive' target has transitive dependencies that include statically linked binaries: (/Users/yb007/Desktop/short/Pods/IJKMediaFramework/IJKMediaFramework/Classes/IJKMediaFramework.framework)

**Comment by GeekLee609** [comment]
这个后续可以改进下，支持动态库和静态库

**Comment by Rookie920** [comment]
> 这个后续可以改进下，支持动态库和静态库

辛苦

**Comment by GeekLee609** [comment]
已经支持了，请更新一下最新版

**Comment by Rookie920** [comment]
> 已经支持了，请更新一下最新版
感谢！

**Comment by iOSyifeng** [comment]
我更新到最新版 也没用啊 [!] The '' target has transitive dependencies that include statically linked binaries: (ZFPlayer)
