### ISSUE TITLE
ijkplayer下的问题

### ISSUE THREAD

**Issue by Rookie920** [renzifeng/ZFPlayer#889]
您好   使用ijkplayer控制台会报，是不是 ijk库的版本问题？
 <<<< AVOutputDeviceDiscoverySession (FigRouteDiscoverer) >>>> -[AVFigRouteDiscovererOutputDeviceDiscoverySessionImpl outputDeviceDiscoverySessionDidChangeDiscoveryMode:]: Setting device discovery mode to DiscoveryMode_None

**Comment by GeekLee609** [comment]
应该不是版本的问题，有对应视频的url地址么？直接在demo中运行的？

**Comment by Rookie920** [comment]
> 应该不是版本的问题，有对应视频的url地址么？直接在demo中运行的？

直接demo运行就行

**Comment by GeekLee609** [comment]
> > 应该不是版本的问题，有对应视频的url地址么？直接在demo中运行的？
> 
> 直接demo运行就行

demo中用的还是 AV 的，没有导入 ijkplayer 的库，而且我没有复现你说的

**Comment by Rookie920** [comment]
> > > 应该不是版本的问题，有对应视频的url地址么？直接在demo中运行的？
> > 
> > 
> > 直接demo运行就行
> 
> demo中用的还是 AV 的，没有导入 ijkplayer 的库，而且我没有复现你说的

ijk是我自己导入的详细步骤是：
1.导入ijkplayer
2.我使用的 是 竖向抖音（collectionView）
3.这种情况只会出现在xcode运行的第一次，

**Comment by GeekLee609** [comment]
> > > > 应该不是版本的问题，有对应视频的url地址么？直接在demo中运行的？
> > > 
> > > 
> > > 直接demo运行就行
> > 
> > 
> > demo中用的还是 AV 的，没有导入 ijkplayer 的库，而且我没有复现你说的
> 
> ijk是我自己导入的详细步骤是：
> 1.导入ijkplayer
> 2.我使用的 是 竖向抖音（collectionView）
> 3.这种情况只会出现在xcode运行的第一次，

好的，等会我试试看

**Comment by Rookie920** [comment]
> > > > > 应该不是版本的问题，有对应视频的url地址么？直接在demo中运行的？
> > > > 
> > > > 
> > > > 直接demo运行就行
> > > 
> > > 
> > > demo中用的还是 AV 的，没有导入 ijkplayer 的库，而且我没有复现你说的
> > 
> > 
> > ijk是我自己导入的详细步骤是：
> > 1.导入ijkplayer
> > 2.我使用的 是 竖向抖音（collectionView）
> > 3.这种情况只会出现在xcode运行的第一次，
> 
> 好的，等会我试试看

#401这个issues 中也提到这个问题，不知道有没有帮助

**Comment by Rookie920** [comment]
之前使用ijk播放的卡线程我以为是
<<<< AVOutputDeviceDiscoverySession (FigRouteDiscoverer) >>>> -[AVFigRouteDiscovererOutputDeviceDiscoverySessionImpl outputDeviceDiscoverySessionDidChangeDiscoveryMode:]: Setting device discovery mode to DiscoveryMode_None
这个导致的，我有分析了下，麻烦看下这个日志：
2019-11-18 09:02:45.125204+0800 开发板[18944:1495071] IJKSDLGLView: setupDisplay not ready
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 18944, TID: 1495109, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   开发板                           0x0000000100cfc758 -[IJKSDLGLView isApplicationActive] + 100
5   开发板                           0x0000000100cfccf0 -[IJKSDLGLView display:] + 64
6   libdispatch.dylib                   0x0000000105f21260 _dispatch_call_block_and_release + 24
7   libdispatch.dylib                   0x0000000105f21220 _dispatch_client_callout + 16
8   libdispatch.dylib                   0x0000000105f32a84 _dispatch_root_queue_drain + 1172
9   libdispatch.dylib                   0x0000000105f32584 _dispatch_worker_thread3 + 136
10  libsystem_pthread.dylib             0x0000000181317fac _pthread_wqthread + 1176
11  libsystem_pthread.dylib             0x0000000181317b08 start_wqthread + 4
2019-11-18 09:02:45.131631+0800 开发板[18944:1495109] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 18944, TID: 1495109, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   开发板                           0x0000000100cfc758 -[IJKSDLGLView isApplicationActive] + 100
5   开发板                           0x0000000100cfccf0 -[IJKSDLGLView display:] + 64
6   libdispatch.dylib                   0x0000000105f21260 _dispatch_call_block_and_release + 24
7   libdispatch.dylib                   0x0000000105f21220 _dispatch_client_callout + 16
8   libdispatch.dylib                   0x0000000105f32a84 _dispatch_root_queue_drain + 1172
9   libdispatch.dylib                   0x0000000105f32584 _dispatch_worker_thread3 + 136
10  libsystem_pthread.dylib             0x0000000181317fac _pthread_wqthread + 1176
11  libsystem_pthread.dylib             0x0000000181317b08 start_wqthread + 4
2019-11-18 09:03:01.598456+0800 开发板[18944:1495109] IJKSDLGLView: setupDisplay not ready
这样看来这两个是不是都有可能导致ijk播放卡顿(卡顿指的是使用xcode第一次运行，第一次播放第一个视频的时候的卡顿)

**Comment by Rookie920** [comment]
ijk下还有个新问题就是 #859 这个问题

**Comment by GeekLee609** [comment]
> # 之前使用ijk播放的卡线程我以为是
> <<<< AVOutputDeviceDiscoverySession (FigRouteDiscoverer) >>>> -[AVFigRouteDiscovererOutputDeviceDiscoverySessionImpl outputDeviceDiscoverySessionDidChangeDiscoveryMode:]: Setting device discovery mode to DiscoveryMode_None
> 这个导致的，我有分析了下，麻烦看下这个日志：
> 2019-11-18 09:02:45.125204+0800 开发板[18944:1495071] IJKSDLGLView: setupDisplay not ready
> Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
> PID: 18944, TID: 1495109, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
> Backtrace:
> 4 开发板 0x0000000100cfc758 -[IJKSDLGLView isApplicationActive] + 100
> 5 开发板 0x0000000100cfccf0 -[IJKSDLGLView display:] + 64
> 6 libdispatch.dylib 0x0000000105f21260 _dispatch_call_block_and_release + 24
> 7 libdispatch.dylib 0x0000000105f21220 _dispatch_client_callout + 16
> 8 libdispatch.dylib 0x0000000105f32a84 _dispatch_root_queue_drain + 1172
> 9 libdispatch.dylib 0x0000000105f32584 _dispatch_worker_thread3 + 136
> 10 libsystem_pthread.dylib 0x0000000181317fac _pthread_wqthread + 1176
> 11 libsystem_pthread.dylib 0x0000000181317b08 start_wqthread + 4
> 2019-11-18 09:02:45.131631+0800 开发板[18944:1495109] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
> PID: 18944, TID: 1495109, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
> Backtrace:
> 4 开发板 0x0000000100cfc758 -[IJKSDLGLView isApplicationActive] + 100
> 5 开发板 0x0000000100cfccf0 -[IJKSDLGLView display:] + 64
> 6 libdispatch.dylib 0x0000000105f21260 _dispatch_call_block_and_release + 24
> 7 libdispatch.dylib 0x0000000105f21220 _dispatch_client_callout + 16
> 8 libdispatch.dylib 0x0000000105f32a84 _dispatch_root_queue_drain + 1172
> 9 libdispatch.dylib 0x0000000105f32584 _dispatch_worker_thread3 + 136
> 10 libsystem_pthread.dylib 0x0000000181317fac _pthread_wqthread + 1176
> 11 libsystem_pthread.dylib 0x0000000181317b08 start_wqthread + 4
> 2019-11-18 09:03:01.598456+0800 开发板[18944:1495109] IJKSDLGLView: setupDisplay not ready
> 这样看来这两个是不是都有可能导致ijk播放卡顿(卡顿指的是使用xcode第一次运行，第一次播放第一个视频的时候的卡顿)

这个已经更新修复
