### ISSUE TITLE
偶现画面卡住，进度条继续走

### ISSUE THREAD

**Issue by coderWeil** [renzifeng/ZFPlayer#892]
bug描述：
播放过程中，偶现视频画面卡到某一帧，而后不动，但是进度条或者声音都在走，而且进度条走完检测不到视频播放结束的代理，导致当前播放时间会超出总时间。这种问题从很久以前的版本就存在了，一直查不到原因，目前的处理方式是在时长更新代理中判断时长和总时长防止超出时间这一问题。
作者可以帮忙检查下吗，猜测复现场景是弱网环境

**Comment by cai3804007** [comment]
一样，会遇到，有啥解决的、

**Comment by cnzlh** [comment]
2年了，有谁解决了吗
