### ISSUE TITLE
pod 'ZFPlayer/ijkplayer' 导入失败

### ISSUE THREAD

**Issue by weilLove** [renzifeng/ZFPlayer#893]
pod 'ZFPlayer/ijkplayer' 导入许久后失败，是网络原因吗？

**Comment by GeekLee609** [comment]
> pod 'ZFPlayer/ijkplayer' 导入许久后失败，是网络原因吗？

有可能，或者把失败原因贴出来

**Comment by weilLove** [comment]
这个解决了，是库太大，网络的问题
