### ISSUE TITLE
这个不支持.mkv格式的么？

### ISSUE THREAD

**Issue by jasonpakio** [renzifeng/ZFPlayer#896]

**Comment by GeekLee609** [comment]
> No description provided.

默认使用的播放器是 AVPlayer，它是支持 .mkv 的视频格式的

**Comment by jasonpakio** [comment]
确实是播放不起，我放了一个mkv的视频链接

**Comment by liyinjie01** [comment]
用ijkMnager

**Comment by GeekLee609** [comment]
> 确实是播放不起，我放了一个mkv的视频链接

换一个播放器试试看，其他的播放器兼容性会好点

**Comment by weilLove** [comment]
> 用ijkMnager

感觉ijkPlayer在UI方面体验没有AV好，楼主有没有什么好的建议呢？特别是跳帧方面，seekTo的时候
