### ISSUE TITLE
关于iOS13 旋转屏幕的问题

### ISSUE THREAD

**Issue by liyinjie01** [renzifeng/ZFPlayer#897]
iOS 13  iPhone XS Max  旋转手机横屏前坪以后，再旋转回竖屏，视频没有自动跟着转回来，只能点返回才能旋转回来，有碰到这个问题的吗

**Comment by xiaochuangwu** [comment]
iOS13 横屏播放 状态栏显示在竖屏的地方，请问这个怎么解决

**Comment by liyinjie01** [comment]
> iOS13 横屏播放 状态栏显示在竖屏的地方，请问这个怎么解决

旋转的时候隐藏吧，这个应该是因为旋转状态栏的方法被弃用的问题

**Comment by xiaochuangwu** [comment]
隐藏代码写了不起作用，你隐藏了么？

**Comment by liyinjie01** [comment]
> 隐藏代码写了不起作用，你隐藏了么？

隐藏了，你出现过我这种情况吗

**Comment by xiaochuangwu** [comment]
你怎么隐藏的啊，你那种情况我没有，全屏的时候我把 全屏切换按钮隐藏了，只能返回

**Comment by xiaochuangwu** [comment]
是的 你说这个问题 有的，我刚试了

**Comment by xiaochuangwu** [comment]
哥们 你怎么隐藏的状态栏？

**Comment by liyinjie01** [comment]
> 哥们 你怎么隐藏的状态栏？

-(BOOL)prefersStatusBarHidden{

    if (self.player.isFullScreen) {
        return YES;
    }

    return NO;
}
这个是系统的，控制器重写就行
然后在播放器的全屏切换回调的时候手动刷新一下
       self.player.orientationWillChange = ^(ZFPlayerController * _Nonnull player, BOOL isFullScreen) {
           @strongify(self)
           [self setNeedsStatusBarAppearanceUpdate];
       };

**Comment by xiaochuangwu** [comment]
嗯嗯 谢了啊

**Comment by liyinjie01** [comment]
> 嗯嗯 谢了啊

我这个问题得找解决方案 不然也是用不了

**Comment by xiaochuangwu** [comment]
嗯，你说那个问题我也发现了，的确是个问题，可以禁掉屏幕自动旋转，只让手动操作



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liyinjie01 <notifications@github.com&gt;
发送时间: 2019年11月12日 16:58
收件人: renzifeng/ZFPlayer <ZFPlayer@noreply.github.com&gt;
抄送: xiaochuangwu <249250168@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[renzifeng/ZFPlayer] 关于iOS13 旋转屏幕的问题 (#897)



 
嗯嗯 谢了啊
  
我这个问题得找解决方案 不然也是用不了

**Comment by FTC-Chen** [comment]
监听屏幕方向旋转：

**Comment by FTC-Chen** [comment]
**监听屏幕方向旋转：**
[[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(changeRotate:) name:UIDeviceOrientationDidChangeNotification object:nil];

**然后执行退出全屏模式就行了：**
- (void)changeRotate:(NSNotification *)noti {
    if ([[UIDevice currentDevice] orientation] == UIInterfaceOrientationPortrait) {
        //竖屏
        NSLog(@"竖屏");
        [self.player enterFullScreen:NO animated:YES];
    } 
}

**Comment by FTC-Chen** [comment]
**监听屏幕旋转方向：**
 [[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(changeRotate:) name:UIDeviceOrientationDidChangeNotification object:nil];

**执行退出全屏模式：**
-(void)changeRotate:(NSNotification *)noti {
    if ([[UIDevice currentDevice] orientation] == UIInterfaceOrientationPortrait) {
        //竖屏
        NSLog(@"竖屏");
        [self.player enterFullScreen:NO animated:YES];
    } else {
        //横屏
        NSLog(@"横屏");
    }
}

**Comment by renzifeng** [comment]
fix

**Comment by Sky891028** [comment]
@renzifeng  有提交吗 ?

**Comment by renzifeng** [comment]
有提交 更新最新代码就行
