### ISSUE TITLE
cell视频播放调用设置视频URL方法报错

### ISSUE THREAD

**Issue by xqqlv** [renzifeng/ZFPlayer#90]
大神，自己写了个视频播放的cell，调用- (void)setVideoURL:(NSURL *)videoURL withTableView (UITableView *)tableView AtIndexPath:(NSIndexPath *)indexPath withImageViewTag:(NSInteger)tag方法设置视频URL时，报错：*** Assertion failure in -[MASViewConstraint setSecondViewAttribute:], /Users/xqq/Desktop/VideoPlay/Pods/Masonry/Masonry/MASViewConstraint.m:130新手求教

**Comment by Lijunjie66** [comment]
出现这个崩溃主要原因就是约束关联到了一个还没有进行初始化的控件 :

_img = [UIImageView new];
[self addSubview:_img];
[_img mas_makeConstraints:^(MASConstraintMaker *make) {
      make.top.equalTo(_titlel.mas_bottom).offset(5); 
      make.left.equalTo(self.mas_left).offset(10);
      make.size.mas_equalTo(CGSizeMake(25, 25));
}];

_titlel = [UILabel new];
_titlel.font = [UIFont systemFontOfSize:14];
_titlel.numberOfLines = 0;
[self addSubview:_titlel];
[_titlel mas_makeConstraints:^(MASConstraintMaker *make) {
      make.left.equalTo(self.mas_left).offset(10);
      make.centerY.equalTo(self.mas_centerY);
      make.right.equalTo(self.mas_right).offset(-10);
}];
