### ISSUE TITLE
ZFPlayer 最新的版本播放一段时间缓冲就会冲不动然后不停的loading闪视频声音一直卡顿

### ISSUE THREAD

**Issue by ljssafe** [renzifeng/ZFPlayer#900]
ZFPlayer 最新的版本播放一段时间缓冲就会冲不动然后不停的loading闪视频声音一直卡顿，拖动进度后会恢复一阵子但是又播放个几分钟后 又缓冲不动了，视频特别卡的buffer 并没有暂停loading等缓冲一部分后继续播放，这是不是新版bug？之前的版本好像没有这个问题？

**Comment by ljssafe** [comment]
https://videos.wisburg.com/dfb09bc2-b4cc-4da7-b0fa-b6c0911bce76.mp4  
就这个视频buffer_start没多久就buffer_end 然后一直播着几分钟后就开始一直卡着不停load 声音很卡很卡但有继续再播只能是拖动后重新 buffer_start然后buffer_End才好，感觉这个缓冲机制有问题？？应该不是ijk本身问题吧？？

**Comment by ljssafe** [comment]
翻阅以前的issue  发现 好像这个问题在 zfavplayer 有处理？ 不过我这边用的zfijkmanager好像没有处理

**Comment by ljssafe** [comment]
好像只有debug模式存在该问题，不论模拟器或者真机都有  release模式好像是好的，👌🏻

**Comment by smileAllYears** [comment]
@ljssafe 那我们把这个关掉了

**Comment by xiangchangming** [comment]
我也遇到这个问题缓冲条会倒退，然后就出现了卡顿，loading加载框 ，现在还没有解决这个问题，只是部分视频会出现这个问题（https://www.youtube.com/watch?v=U72RoGixS0Y）
