### ISSUE TITLE
抖音样式UITableView有约束错误。。。。

### ISSUE THREAD

**Issue by zhiYong964941772** [renzifeng/ZFPlayer#903]
[TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x11580a000; frame = (0 0; 375 812); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x280daf270>; layer = <CALayer: 0x28034eaa0>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <ZFDouYinViewController: 0x10fe13010>>

**Comment by renzifeng** [comment]
这个是xcode 的bug，你更新到最新xcode就可以啦
