### ISSUE TITLE
ios13旋转之后的状态栏问题有解决方案吗？不想隐藏

### ISSUE THREAD

**Issue by SethCody** [renzifeng/ZFPlayer#906]
全屏之后状态栏还在竖屏状态下的顶部 @renzifeng

**Comment by lsqiang** [comment]
一样的  我也没解决 它这代码不好改

**Comment by SethCody** [comment]
我提交了一个pull request，已解决这个问题。 @renzifeng @lsqiang

**Comment by LessonFirst** [comment]
@SethCody  怎么解决的问题？？有没有code

**Comment by lsqiang** [comment]
> 我提交了一个pull request，已解决这个问题。 @renzifeng @lsqiang

刚才试了 不行

**Comment by NSObject-RC** [comment]
什么叫不想隐藏？iOS13系统就这样设置的，横屏下隐藏状态栏。其实参考下直播App或B站，，都是自己写的一个简单的状态栏，用来显示当前时间和电量，我看了虎牙直播，它的时间显示就是顶部工具条显示的时候获取当前时间显示，是不变的！！！！但是顶部工具条会过几秒就隐藏，取巧了。至于电池电量系统有方法但是经过测试，获取的数据和手机系统显示的数据有时候会有1%的误差，虎牙的电池电量显示就是这样的。想要精确显示也可以用runtime获取状态栏具体的信息，个人感觉没必要。所以自己自定义控制层，至于旋转可以参考作者自己来监听旋转。

**Comment by NSObject-RC** [comment]
你这个方案行不通，控制器必须要开启能够旋转才行。 @lsqiang @SethCody

**Comment by lsqiang** [comment]
你关了干嘛 没解决就关了

**Comment by luyinuo** [comment]
横屏系统默认隐藏了状态栏，目前各大视频应用都是横屏自己绘制状态栏的解决方案，参考B站，写了一个自定义的状态栏，有需要可以自取：
[YNStatusBar](https://github.com/luyinuo/YNStatusBar)
