### ISSUE TITLE
collectionView 刷新的时候，不播放。

### ISSUE THREAD

**Issue by ViterbiDevelopment** [renzifeng/ZFPlayer#908]
我的步骤，
1:请求网络列表
2:停止当前播放
3:设置player的asserts
4:实现zf_filterShouldPlayCellWhileScrolled

然后就是不播放，在初始化collection的时候也实现了zf_scrollViewDidStopScrollCallback方法
望回复

**Comment by renzifeng** [comment]
从这些描述来说看不出问题，你把详细代码贴上
