### ISSUE TITLE
请教一个问题:avplayer有声音，但无图像  怎么解决啊 大神

### ISSUE THREAD

**Issue by LiGuanWen** [renzifeng/ZFPlayer#910]
请教一个问题:avplayer有声音，但无图像  怎么解决啊 大神

**Comment by LifeForLove** [comment]
哪个是视频格式的问题 把ZFAVPlayerManager 换成ZFIJKPlayerManager

**Comment by smileAllYears** [comment]
@LiGuanWen 使用LifeForLove推荐的方法，还有问题吗

**Comment by Hanrovey** [comment]
swift项目会出现有声音没画面，OC就没问题，希望作者调研下问题。

**Comment by Hanrovey** [comment]
> 哪个是视频格式的问题 把ZFAVPlayerManager 换成ZFIJKPlayerManager

ZFIJKPlayerManager这个在swift里面引用不了文件

**Comment by hellogaojun** [comment]
也刚刚遇到一个视频有声音无图像

**Comment by LifeForLove** [comment]
换成ijk的库，能解决H265格式视频有声音无图像的问题。
