### ISSUE TITLE
求教怎么在控制器view中添加播放器

### ISSUE THREAD

**Issue by Howeix** [renzifeng/ZFPlayer#918]
看了你的demo演示全都是建立在控制器层面的, ZFPlayerView也并没有提供任何接口, 对于如果想在view中添加你的播放器扩展性不是很好

**Comment by renzifeng** [comment]
想在view中添加播放器，在自定义view上添加一个containerView和你自定义的view一样大，指定播放器的containerView就行啦

**Comment by Howeix** [comment]
有没有demo呀  有个需求就是要把播放器放在一个view当中   我用了ZFNormalViewController这个类感觉不可行啊  把这个类型控制器的containerView添加到项目的view中点击播放没有响应
