### ISSUE TITLE
缓冲时系统菊花的显示只有一开始才有...拖动或点击进度条后缓冲并不显示菊花

### ISSUE THREAD

**Issue by lixiaonan** [renzifeng/ZFPlayer#92]
如题

**Comment by shengxiaolei** [comment]
同样问题，这个问题应该怎么解决呢？

**Comment by shengxiaolei** [comment]
// 当缓冲好的时候
            if (self.playerItem.playbackLikelyToKeepUp && self.state == ZFPlayerStateBuffering){
                self.state = ZFPlayerStatePlaying;
            }

发现作者已经解决了  ！~

**Comment by lixiaonan** [comment]
@shengxiaolei 其实这个并没有什么用.....感觉不灵吧...缓冲的时候并不出现菊花

**Comment by shengxiaolei** [comment]
嗯咯  只是有优化吧

**Comment by shengxiaolei** [comment]
@lixiaonan 嗯咯  只是有优化吧
