### ISSUE TITLE
版本适配全屏的一个小问题

### ISSUE THREAD

**Issue by coderWeil** [renzifeng/ZFPlayer#921]
我的项目是tabbar+nav+vc的框架，在iOS8.1系统上，我刚进入app，直接去播放视频，其他的tabbarItem对应的vc还没有初始化，我点击播放视频，全屏的时候其他控制器的初始化方法会执行，在其他系统上就不会出现这个问题，这种情况有时候有意外崩溃出现，还有就是如果我做了根据屏幕宽度或者高度适配UI，也会造成UI布局的问题，这个问题在很早的版本之前就有了，我也是最近一个用户提到了这个bug，去排查的时候发现的，大神能不能对这块进行覆盖测试一下看有方法解决吗

**Comment by renzifeng** [comment]
关于转屏这一块，我最近一个版本3.2.16有修改，你在iOS8上测试一下是否有问题
