### ISSUE TITLE
当使用iphoneX播放时，如果只是改变playerView到横屏，不改变控制器到横屏状态，横屏后点击返回按钮和播放暂停按钮，涂层的frame 改变有问题

### ISSUE THREAD

**Issue by WalkerSkyer** [renzifeng/ZFPlayer#923]
而且此时的播放按钮和返回按钮的点击无效
![image](https://user-images.githubusercontent.com/18542955/71470841-7c640300-2808-11ea-8faf-60b164bd9bbc.png)

**Comment by WalkerSkyer** [comment]
问题版本号3.2.16
之前用的3.1.8 无此问题

**Comment by renzifeng** [comment]
你这种情况是怎么复现的，播放器view横屏了，控制器不横屏，关于控制层的问题，可以自行fork一份来修改

**Comment by WalkerSkyer** [comment]
对的，指横屏播放器view， 控制器不横屏的情况下就有这个问题。好的，我暂时先fork下。

**Comment by renzifeng** [comment]
怎么出现的横屏播放器view， 控制器不横屏

**Comment by WalkerSkyer** [comment]
找到问题了，项目需求在AppDelegate里做了一些处理，刚好和最新版本中上面截图的代码处理冲突了，相当于UIInterfaceOrientationIsLandscape([UIApplication sharedApplication].statusBarOrientation))这个方法永远获取到的是竖屏状态
![image](https://user-images.githubusercontent.com/18542955/71472214-247bcb00-280d-11ea-8c84-6fe9a004efe3.png)
