### ISSUE TITLE
AppDelegate限定某几个转屏方向, 进入全屏视屏会iOS10会闪退, 13暂时不会

### ISSUE THREAD

**Issue by skytoup** [renzifeng/ZFPlayer#924]
应用仅支持向上的竖屏
```
func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
    return [.portrait]
}
```

转屏进入视屏全屏时, ZFFullViewController 赋值到 customWindow时, 因为 VC的shouldAutorotate 返回true, 但是AppDelegate的支持转屏方法返回了不支持的转屏方向, 导致在iOS 10闪退, 13暂时没发现闪退

暂时在AppDelegate的支持转屏方法特殊判断window是否为ZFFullViewController所在的windows时, 返回支持所有转屏

**Comment by renzifeng** [comment]
因为设备不支持其他方向，转屏肯定会导致崩溃。这么解决是可以的，或者你在appdelegate直接返回 UIInterfaceOrientationMaskAllButUpsideDown，不支持转屏的控制器shouldAutorotate 返回false就行

**Comment by skytoup** [comment]
暂时根据UIWindow, 返回不同的转向

**Comment by xuanmeijan** [comment]
@skytoup 我swift项目也遇到这个问题，你怎么写的呀，我没能拿到ZFFullViewController，大神指导下

**Comment by skytoup** [comment]
> @skytoup 我swift项目也遇到这个问题，你怎么写的呀，我没能拿到ZFFullViewController，大神指导下
``` Swift
    func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        // FIXME: - 特殊为ZFPlayerr允许转屏 3.2.16
        guard window != nil, window?.subviews.count != 0 else {
            return .all
        }
        return [.portrait]
    }
```

随便做判断, 如果还有其它UIWindow, 自行修改逻辑

@renzifeng 可以考虑ZFFullViewController的UIWindow做些特殊标识(继承之类的), 可以让开发者准确判断是否为ZFFullViewController的UIWindow

**Comment by Spr1ngHall** [comment]
在ZFOrientationObserver.m这个文件中把-shouldAutorotate返回为NO，暂时解决了这个问题，不过就是只能代码引入的方式，不能用pod了，希望到时候更新之后能修改这个问题

**Comment by JoanLeeo** [comment]
> > @skytoup 我swift项目也遇到这个问题，你怎么写的呀，我没能拿到ZFFullViewController，大神指导下
> 
> ```swift
>     func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
>         // FIXME: - 特殊为ZFPlayerr允许转屏 3.2.16
>         guard window != nil, window?.subviews.count != 0 else {
>             return .all
>         }
>         return [.portrait]
>     }
> ```
> 
> 随便做判断, 如果还有其它UIWindow, 自行修改逻辑
> 
> @renzifeng 可以考虑ZFFullViewController的UIWindow做些特殊标识(继承之类的), 可以让开发者准确判断是否为ZFFullViewController的UIWindow

在appdelegate 添加这段代码后会出现statusBar 显示的bug

**Comment by skytoup** [comment]
> > > @skytoup 我swift项目也遇到这个问题，你怎么写的呀，我没能拿到ZFFullViewController，大神指导下
> > 
> > 
> > ```swift
> >     func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
> >         // FIXME: - 特殊为ZFPlayerr允许转屏 3.2.16
> >         guard window != nil, window?.subviews.count != 0 else {
> >             return .all
> >         }
> >         return [.portrait]
> >     }
> > ```
> > 
> > 
> > 随便做判断, 如果还有其它UIWindow, 自行修改逻辑
> > @renzifeng 可以考虑ZFFullViewController的UIWindow做些特殊标识(继承之类的), 可以让开发者准确判断是否为ZFFullViewController的UIWindow
> 
> 在appdelegate 添加这段代码后会出现statusBar 显示的bug

根据自己项目调整一下吧
