### ISSUE TITLE
全屏播放，回到后台，在进入程序，关闭全屏播放，UI会错乱

### ISSUE THREAD

**Issue by xiaochuangwu** [renzifeng/ZFPlayer#925]
iOS13以下，全屏播放，状态栏没问题，但是全屏的时候，进入后台在进入前台，退出全屏播放，UI会错乱，iOS13全屏播放，状态栏，屏幕方向还是不对

**Comment by xiaochuangwu** [comment]
没说完整，应该是在iOS13的手机上 全屏到后台 再回前台，UI会错乱

**Comment by AllisonWangJiaoJiao** [comment]
确实存在UI错乱的问题，效果如下图链接所示：
https://hbimg.huabanimg.com/35d590bf3eb567d12805c43b590e164ae9bf40b129df8-W2YV7N_fw658
https://hbimg.huabanimg.com/6f5060f9ed110c31b54222b70e8fd87c29bf6035b82b3-IUd0XX_fw658

**Comment by renzifeng** [comment]
这个应该和播放器无关，全屏后进入后台在进入前台，导致状态条上移，至于怎么解决，我也没找到好的解决办法。

**Comment by DDfans** [comment]
遇到了同样的问题,

**Comment by BJnandi503** [comment]
我试了下，demo也有这个问题，同求怎么样解决

**Comment by BJnandi503** [comment]
> 没说完整，应该是在iOS13的手机上 全屏到后台 再回前台，UI会错乱

请问下这个问题解决了吗？

**Comment by Allenzhan1225** [comment]
同样的问题，没啥好的解决方案

**Comment by mjwz5294** [comment]
解决了吗？

**Comment by mjwz5294** [comment]
目前我找到一种方案，就是在_notification.willResignActive中，转为竖屏。但这种方式产品无法接受～

**Comment by xiaochuangwu** [comment]
我就是这样解决的，我们产品没说什么



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wuxiaolong <notifications@github.com&gt;
发送时间: 2020年4月2日 11:14
收件人: renzifeng/ZFPlayer <ZFPlayer@noreply.github.com&gt;
抄送: xiaochuangwu <249250168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[renzifeng/ZFPlayer] 全屏播放，回到后台，在进入程序，关闭全屏播放，UI会错乱 (#925)





 
目前我找到一种方案，就是在_notification.willResignActive中，转为竖屏。但这种方式产品无法接受～

**Comment by Allenzhan1225** [comment]
我也是这么解决的，产品也没说啥，我看了西瓜视频也是转成竖屏的

**Comment by mjwz5294** [comment]
> 我也是这么解决的，产品也没说啥，我看了西瓜视频也是转成竖屏的

我要把你的回复拿去给我们产品看～～

**Comment by anxiongsir** [comment]
这个将window的rootViewController的view向左右偏移1个像素再偏回来，可以恢复

**Comment by Jason-lyl** [comment]
@renzifeng 能否告知 全屏播放，回到后台，在进入程序，ui会错乱的原因是什么，我发现最新代码，你已经修复了，但是我没找到根本原因？谢谢啦

**Comment by zhuozhuo** [comment]
我下载最新的Demo也有这个问题，全屏后退出后台再进来，返回，界面布局就乱了。
