### ISSUE TITLE
Bitcode support of IJKPlayer

### ISSUE THREAD

**Issue by macpraveen** [renzifeng/ZFPlayer#927]
Can you please rebuild ijkplayer with bitcode support? 

> ld: bitcode bundle could not be generated because '/..../Pods/IJKMediaFramework/IJKMediaFramework/Classes/IJKMediaFramework.framework/IJKMediaFramework(IJKAVMoviePlayerController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/..../Pods/IJKMediaFramework/IJKMediaFramework/Classes/IJKMediaFramework.framework/IJKMediaFramework' for architecture arm64

**Comment by GeekLee609** [comment]
Yes, IJKMediaFramework 0.1.5 has solved this problem, please try to update
