### ISSUE TITLE
ZFPlayer.bundle> (not yet loaded)

### ISSUE THREAD

**Issue by sunlight2728** [renzifeng/ZFPlayer#928]
ZFPlayer.bundle> (not yet loaded)

+ (UIImage *)imageNamed:(NSString *)name {
    if (name.length == 0) return nil;
    int scale = (int)UIScreen.mainScreen.scale;
    if (scale < 2) scale = 2;
    else if (scale > 3) scale = 3;
    NSString *n = [NSString stringWithFormat:@"%@@%dx", name, scale];
    UIImage *image = [UIImage imageWithContentsOfFile:[self.bundle pathForResource:n ofType:@"png"]];
    if (!image) image = [UIImage imageWithContentsOfFile:[self.bundle pathForResource:name ofType:@"png"]];
    return image;
}

self.bundle 没有获取到bundle，导致快进快退的时候 闪退

**Comment by renzifeng** [comment]
这个问题你看一下工程中是否有ZFPlayer.bundle 这个文件
