### ISSUE TITLE
thumbnailImageAtCurrentTime 获取当前时间的帧对应的图像的问题

### ISSUE THREAD

**Issue by weilLove** [renzifeng/ZFPlayer#933]
视频是m3u8格式的时候，通过thumbnailImageAtCurrentTime获取的图像为nil，MP4格式的正常

**Comment by renzifeng** [comment]
这个方法只是包了一层底层播放器，获取到是nil，可能就是底层的问题了。

**Comment by weilLove** [comment]
也不算是，我查过，对mp4格式的用你封装的那个可以，m3u8格式的就不行了，有人说iOS对这两种格式的处理并非用同一个API，这点算是iOS这边的一个恶心处

**Comment by Coder-God** [comment]
大哥，这个m3u8截图确实是nil，有没有解决方案啊
