### ISSUE TITLE
横版全屏播放后，系统的状态栏无法显示

### ISSUE THREAD

**Issue by brainiron** [renzifeng/ZFPlayer#935]
已经将程序里所有的隐藏系统状态栏相关的代码都移除了，还是无法显示系统的状态栏。

**Comment by huangyingqiu** [comment]
遇到了同样的问题

**Comment by WDaDa** [comment]
遇到同样的问题，解决了吗

**Comment by DDfans** [comment]
遇到了同样的问题

**Comment by fengweizhao** [comment]
哪位有解决方法了请指教下，谢谢

**Comment by luyinuo** [comment]
横屏系统默认隐藏了状态栏，目前各大视频应用都是横屏自己绘制状态栏的解决方案，参考B站，写了一个自定义的状态栏，有需要可以自取：
[YNStatusBar](https://github.com/luyinuo/YNStatusBar)
