### ISSUE TITLE
Support on Shared Extension

### ISSUE THREAD

**Issue by jhpassion0621** [renzifeng/ZFPlayer#940]
I am creating a shared extension app and I would like to use this library to play a video. But it gives errors when I add this library to shared extension pod. Please help how to solve this. Thanks.
![Screen Shot 2020-02-28 at 5 11 38 PM](https://user-images.githubusercontent.com/7741402/75591300-69aabc00-5a4d-11ea-88e9-623cd702ca7d.png)

**Comment by jueXying** [comment]
UIApplication is not allowed use in extension!

**Comment by jhpassion0621** [comment]
Yes I know, So Is there a way to use your library in extension?
