### ISSUE TITLE
播放报错AVFoundationErrorDomain Code=-11829 

### ISSUE THREAD

**Issue by sensencoder** [renzifeng/ZFPlayer#941]
Error Domain=AVFoundationErrorDomain Code=-11829 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media may be damaged., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x6000013966a0 {Error Domain=NSOSStatusErrorDomain Code=-12848 "(null)"}}

**Comment by smileAllYears** [comment]
@sensencoder 什么功能报的这个错误，是保持，还是录制的时候，在真机上还是模拟器上？

**Comment by smileAllYears** [comment]
@sensencoder 什么功能报的这个错误，是保存，还是录制的时候？

**Comment by sensencoder** [comment]
> @sensencoder 什么功能报的这个错误，是保存，还是录制的时候？

我是把这个播放器去掉layer层，播放音频的时候出现的，出现这样的错误是安卓那边实际录制的音频文件是mp3格式，但是他传后台的时候直接把后缀改成了m4a,是一个音频mp3格式后缀是m4a的音频，我记得AVFoundation这么强大，是可以自己处理这样的音视频啊~最后选择的是ijkplayer,可以问下是什么原因吗?谢谢

**Comment by smileAllYears** [comment]
@sensencoder 我们看看，具体原因我们排查一下

**Comment by yongshideweiyi** [comment]
> @sensencoder 我们看看，具体原因我们排查一下

播放mp4文件，同样报错  11829

Error Domain=AVFoundationErrorDomain Code=-11829 "打不开" UserInfo={NSLocalizedFailureReason=此媒体可能已损坏。, NSLocalizedDescription=打不开, NSUnderlyingError=0x283408f30 {Error Domain=NSOSStatusErrorDomain Code=-12848 "(null)"}}
