### ISSUE TITLE
横屏播放时下拉通知栏，然后转回到竖屏时，状态栏会错乱

### ISSUE THREAD

**Issue by WJLollipop** [renzifeng/ZFPlayer#942]
demo中也会出现这种情况：横屏播放时下拉通知栏，然后转回到竖屏时，状态栏会错乱 @renzifeng

**Comment by fengweizhao** [comment]
我也遇到这样的情况，请问你怎么解决的？

**Comment by WJLollipop** [comment]
@fengweizhao 我现在的做法是：拉下通知栏时，转为竖屏

**Comment by fengweizhao** [comment]
拉下通知栏时，转为竖屏 ,请问这样做会影响自动切换横竖屏吗？  请问你具体怎么写的？谢谢

**Comment by renzifeng** [comment]
这个问题我这边没有复现呀，具体是系统版本是多少

**Comment by WJLollipop** [comment]
> 这个问题我这边没有复现呀，具体是系统版本是多少

iOS13的系统都会

**Comment by WJLollipop** [comment]
> 会



> 拉下通知栏时，转为竖屏 ,请问这样做会影响自动切换横竖屏吗？ 请问你具体怎么写的？谢谢

横屏时下拉通知栏，我自动把视频转到竖屏了，有点影响用户体验

**Comment by mjwz5294** [comment]
目前我找到一种方案，就是在_notification.willResignActive中，转为竖屏。但这种方式产品无法接受～
