### ISSUE TITLE
IOS13全屏下拉通知栏返回到上个控制器转屏的bug

### ISSUE THREAD

**Issue by qq738818311** [renzifeng/ZFPlayer#952]
布局结构是tabbarcontroller->nav->controller
全屏播放下拉通知栏后,返回小屏界面错乱 @renzifeng 
见下图：
![image](https://user-images.githubusercontent.com/18345358/77223495-1d5c2300-6b98-11ea-8f78-7121b75baa56.png)

**Comment by mjwz5294** [comment]
mark

**Comment by opleonnn** [comment]
我也遇到了同样的问题，有解决方案么

**Comment by WIndFate** [comment]
这个应该和全屏后退到后台再回来是一个问题，有tabbarcontroller的话，屏幕旋转判定不太对，导航栏上移。可以的话，希望作者尽快解决

**Comment by wesleyzhang001** [comment]
我也遇到了同样的问题，可以的话，希望作者尽快解决,感谢！ @renzifeng

**Comment by wesleyzhang001** [comment]
> 布局结构是tabbarcontroller->nav->controller
> 全屏播放下拉通知栏后,返回小屏界面错乱 @renzifeng
> 见下图：
> ![image](https://user-images.githubusercontent.com/18345358/77223495-1d5c2300-6b98-11ea-8f78-7121b75baa56.png)

请问你解决了么？

**Comment by WIndFate** [comment]
> 我也遇到了同样的问题，可以的话，希望作者尽快解决,感谢！ @renzifeng

<img width="1304" alt="82971886-c008a600-a00e-11ea-8e4d-eb02cf5c32fb" src="https://user-images.githubusercontent.com/14509638/85992901-8291a100-ba30-11ea-93ae-75b27444e7d6.png">

我临时这样解决的，你试试吧
