### ISSUE TITLE
exitFullScreenWhenStop

### ISSUE THREAD

**Issue by soulbind** [renzifeng/ZFPlayer#953]
UITableView  
exitFullScreenWhenStop = false
竖屏全屏播放完自动退出，UI无法交互
横屏播放完 直接黑屏了。
>
看了一下源码，这个地方判断没对啊😄
>
**如果是全屏，设置为播放结束不退出全屏，stop里面直接将player移除了**

<img width="799" alt="Screen Shot 2020-03-21 at 22 30 40" src="https://user-images.githubusercontent.com/3039672/77228664-cec47e00-6bc3-11ea-98ff-4e896d687033.png">

**Comment by iFallen** [comment]
另外播放结束不能自动回到初始状态？

**Comment by steven2008** [comment]
横屏模式播放完成自动回到竖屏后没有回到初始状态，不能再次播放
