### ISSUE TITLE
[Assert] Attempted to access the table view's visibleCells while they were in the process of being updated

### ISSUE THREAD

**Issue by Lee0820** [renzifeng/ZFPlayer#955]
Xcode 11.3.1，混合cell样式会打印一堆这种日志
[Assert] Attempted to access the table view's visibleCells while they were in the process of being updated, which is not allowed. Make a symbolic breakpoint at UITableViewAlertForVisibleCellsAccessDuringUpdate to catch this in the debugger and see what caused this to occur. Perhaps you are trying to ask the table view for the visible cells from inside a table view callback about a specific row? Table view: <UITableView: 0x104867e00; frame = (0 0; 414 622); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x283e6c8d0>; layer = <CALayer: 0x283096cc0>; contentOffset: {0, 174.33333333333334}; contentSize: {414, 2566}; adjustedContentInset: {0, 0, 44, 0}; dataSource: <ESHomeViewController: 0x10456ac10>>

**Comment by Tapeju** [comment]
解决了吗

**Comment by pengshengsongcode** [comment]
同问
