### ISSUE TITLE
经过测试在iOS12下，视频播放只有声音没有画面。最新的SDK。

### ISSUE THREAD

**Issue by NSObject-RC** [renzifeng/ZFPlayer#956]
经过测试在iOS12下，视频播放只有声音没有画面，有时候会报OutputDeviceUID is nil 扬声器: (null)错误。用的是最新的SDK。
手机升级到iOS13一切就OK了。

**Comment by NSObject-RC** [comment]
定位到了，，应该是自定义就控制层有问题。示例demo中“自定义控制层”好像也无法播放

**Comment by smileAllYears** [comment]
@NSObject-RC 我在12.4上是可以播放出画面的，能详细描述你的使用的流程和功能吗

**Comment by NSObject-RC** [comment]
应该是自定义的有问题，我就是自定义的控制层，完全复制了ZF的，在此layoutSubviews中调整了一些按钮和进度条的位置，添加了一个选集的功能。最新的Demo中的自定义控制层好像也无法播放。
