### ISSUE TITLE
抬起手机orientationWillChange也会调用, 导致播放器跳动 

### ISSUE THREAD

**Issue by huangxianyu** [renzifeng/ZFPlayer#958]
![QQ20200324-170648](https://user-images.githubusercontent.com/20720740/77407938-f00ab180-6df1-11ea-9c33-c49a81026185.gif)
抬起手机orientationWillChange也会调用, 导致播放器跳动
具体原因一直没找到, 
代码和demo上的一模一样,
急求解决!!!   
万分感谢!!!

**Comment by huangxianyu** [comment]
屏幕没有旋转, 只是把手机头部抬起.

**Comment by huangxianyu** [comment]
- (void)seekToTime:(NSTimeInterval)time completionHandler:(void (^)(BOOL))completionHandler;
seek完成后不回调

**Comment by zp0708** [comment]
我也遇到同样的问题了
原因大致看了应该是ZFOrientationObserver(161行)下面代码导致的
在调用handleDeviceOrientationChange方法后，最后还会调用一次，但是旋转的值是UIInterfaceOrientationUnknown
所以来回晃动 _currentOrientation = currentOrientation一直是不成立的，一次会出现晃动的现象
```
    if (UIDeviceOrientationIsValidInterfaceOrientation([UIDevice currentDevice].orientation)) {
        UIInterfaceOrientation currentOrientation = (UIInterfaceOrientation)[UIDevice currentDevice].orientation;
        if (_currentOrientation == currentOrientation) return;
        _currentOrientation = currentOrientation;
    } else {
        _currentOrientation = UIInterfaceOrientationUnknown;
        return;
    }
```
我的解决版本是尽量不影响源代码，在外接保留一下最后一次currentOrientation，每次orientationWillChange调用时，对比一下前后的Orientation，如果相同就设置duration为0.0，已
去除动画晃动的情况
```
    @weakify(self)
    self.player.orientationWillChange = ^(ZFPlayerController * _Nonnull player, BOOL isFullScreen) {
        @strongify(self)
        UIInterfaceOrientation orientation = player.orientationObserver.currentOrientation;
        player.orientationObserver.duration = self.videoOrigentation == orientation ? 0.0 : 0.3;
        self.videoOrigentation = orientation;
        /// 解决导航栏上移问题
        self.navigationController.navigationBar.vHeight = NAVBAR_HEIGHT;
        [self setNeedsStatusBarAppearanceUpdate];
    };
```
如果有更好的办法，交流一下

**Comment by hushilin** [comment]
enterLandscapeFullScreen 方法里面加一个判断 就好了

**if(_currentOrientation == orientation || orientation == UIInterfaceOrientationUnknown) return;**

**Comment by renzifeng** [comment]
我已经修复了
