### ISSUE TITLE
为何我设置请求头referer无效

### ISSUE THREAD

**Issue by LeeFengHY** [renzifeng/ZFPlayer#959]
ZFAVPlayerManager *playerManager = [[ZFAVPlayerManager alloc] init];
    SystemInfoModel *system = [DataHelp getSystemModel];
    if (system.video_header_domain) {
        [playerManager setRequestHeader:@{@"referer":system.video_header_domain}];
    }
  
    self.player = [ZFPlayerController playerWithScrollView:self.tableView playerManager:playerManager containerViewTag:100];

**Comment by LeeFengHY** [comment]
已解决：
ZFAVPlayerManager *playerManager = [[ZFAVPlayerManager alloc] init];
    SystemInfoModel *system = [DataHelp getSystemModel];
    if (system.video_header_domain) {
        NSMutableDictionary *header = [NSMutableDictionary new];
        [header setValue:system.video_header_domain forKey:@"referer"];
        [playerManager setRequestHeader:@{@"AVURLAssetHTTPHeaderFieldsKey":header}];
    }

**Comment by yongshideweiyi** [comment]
> 已解决：
> ZFAVPlayerManager *playerManager = [[ZFAVPlayerManager alloc] init];
> SystemInfoModel *system = [DataHelp getSystemModel];
> if (system.video_header_domain) {
> NSMutableDictionary *header = [NSMutableDictionary new];
> [header setValue:system.video_header_domain forKey:@"referer"];
> [playerManager setRequestHeader:@{@"AVURLAssetHTTPHeaderFieldsKey":header}];
> }

给大佬点赞
