### ISSUE TITLE
全屏返回箭头位置下移 很难点中

### ISSUE THREAD

**Issue by CNDEVE** [renzifeng/ZFPlayer#960]
你好 我是复制了你ZFNoramlViewController里的代码的 但是修改项目只支持竖屏的时候全屏播放返回箭头和标题会下移而且很难点到 如果修改项目支持横屏就不会下移 但是我看你的工程也只支持竖屏 是需要自己针对视频播放页面做横竖屏处理吗？

**Comment by renzifeng** [comment]
控制层是支持完全自定义的，根据自己需求来自定义就行。
