### ISSUE TITLE
pod 'ZFPlayer/KSYMediaPlaye"  运行报错

### ISSUE THREAD

**Issue by WoNiu361** [renzifeng/ZFPlayer#961]
pod 一起导入 pod 'ZFPlayer/KSYMediaPlayer', '~> 3.0' ，则会报错iOS开发, 
Showing All Messages
112 duplicate symbols for architecture arm64
，去掉  ZFPlayer/KSYMediaPlayer' 则没有问题，请作者查看是什么问题导致的

**Comment by scwang90** [comment]
遇到相同问题，去掉  pod 'ZFPlayer/KSYMediaPlayer', '~> 3.0'  就可以

**Comment by GeekLee609** [comment]
> 遇到相同问题，去掉 pod 'ZFPlayer/KSYMediaPlayer', '~> 3.0' 就可以

应该是 IJKMediaFramework 和 KSYMediaPlayer 符号重复定义错误导致的，两者只能引入一个
