### ISSUE TITLE
请问：为什么在tableView的cell播放时不显示控制层，参数都是默认的...

### ISSUE THREAD

**Issue by leotenfenrir** [renzifeng/ZFPlayer#966]
private lazy var player: ZFPlayerController = {

        let playerManager = ZFAVPlayerManager()
        let player = ZFPlayerController(scrollView: tableView, playerManager: playerManager, containerViewTag: 990)
        player.controlView = controlView
        player.controlView.bringSubviewToFront(self.view)
        player.shouldAutoPlay = false
        player.playerDisapperaPercent = 1.0
        player.assetURLs = self.urls
        return player
    }()
    
    private lazy var controlView : ZFPlayerControlView = {
        let controlView = ZFPlayerControlView()
        return controlView
    }()

也把缩略图的ImageView设置成可以用户交互了，播放没问题，但是点击不显示控制层。
求助...

**Comment by renzifeng** [comment]
点击不显示控制层的问题，查一下是否会回调控制层的点击方法，不回调的化可能是列表上有其他点击事件拦截了控制层的点击
