### ISSUE TITLE
Swift项目播放列表tableView抖音样式，有声音没画面。OC语言就可以

### ISSUE THREAD

**Issue by Hanrovey** [renzifeng/ZFPlayer#968]

**Comment by Doraemontree** [comment]
swift 怎么解决的

**Comment by Hanrovey** [comment]
延迟一秒播放
        DispatchQueue.main.after(0.1) {
            self.player.playTheIndexPath(indexPath, scrollToTop: scrollToTop)
        }

**Comment by Hanrovey** [comment]
> swift 怎么解决的

延迟播放

**Comment by Doraemontree** [comment]
> > swift 怎么解决的
> 
> 延迟播放

非常感谢
