### ISSUE TITLE
加上tabbar，全屏播放之后，状态栏变透明了

### ISSUE THREAD

**Issue by wulinfeng198810** [renzifeng/ZFPlayer#969]
![3408C4447AB146DF7C387CE1F3C8F9E5](https://user-images.githubusercontent.com/13115659/79090768-53e32300-7d7d-11ea-8837-d9ef02c0d782.jpg)
![D76791562D01DBC7F4C9491857956E4A](https://user-images.githubusercontent.com/13115659/79090778-59d90400-7d7d-11ea-8a1c-7cd671df88fe.jpg)
![E007EE9FBEE6CDBE692FAC1D3BB3CC8B](https://user-images.githubusercontent.com/13115659/79090842-960c6480-7d7d-11ea-84b2-6bc98423b723.png)

**Comment by GSmoke** [comment]
同问,怎么解决呢

**Comment by renzifeng** [comment]
```
    self.player.orientationWillChange = ^(ZFPlayerController * _Nonnull player, BOOL isFullScreen) {
        @strongify(self)
        if (!isFullScreen) {
            /// 解决导航栏上移问题
            self.navigationController.navigationBar.zf_height = KNavBarHeight;
        }
    };
```

建议你把这段代码去掉
