### ISSUE TITLE
抖音样式(Douyin style) 播放闪烁

### ISSUE THREAD

**Issue by Lucifer0103** [renzifeng/ZFPlayer#970]
3.3.1版本Demo, TableView 抖音样式, 滑动播放视频会 闪烁一下, 我有看到#567有人提问这个问题, 但是没有解决方案.  所有请问下如何才能解决这个问题, 或者是什么原因导致的?  . 请望回复, 谢谢

**Comment by chenhengstar** [comment]
是的,闪烁一下,怎么修复

**Comment by Lucifer0103** [comment]
不知道, 有个 ZFPlayerPresentView 颜色为黑色, 就会有个闪烁效果. 如果设置为透明, 就会导致背景图暴露出来.

**Comment by VicDodgson** [comment]
同问, 闪烁一下, 怎么修复.

**Comment by VicDodgson** [comment]
找到个方法临时解决下, 把 ZFPlayerControlView 对象 的属性 effectView 置为空视图

**Comment by fangwei520** [comment]
这个问题了两年了 还没有大佬有解决方案吗....

**Comment by bluerainxty** [comment]
我也遇到这个问题了

**Comment by CoderSXP** [comment]
同问

**Comment by PZXforXcode** [comment]
同问，抖音tableview 闪一下的问题@作者大大

**Comment by PZXforXcode** [comment]
这个问题我今天下午研究出来了 在ZFDouYinControlView.m 里面

**Comment by PZXforXcode** [comment]
这个问题我今天研究出来了，在ZFDouYinControlView.m里
![WeChatc32f206185ea2099cce69b214e792513](https://user-images.githubusercontent.com/17844055/86209303-dfae6380-bba4-11ea-9698-8ce2e335f9cd.png)
作者是在这里判断coverimage显示隐藏的
/// 加载状态改变
- (void)videoPlayer:(ZFPlayerController *)videoPlayer loadStateChanged:(ZFPlayerLoadState)state {
//    if (state == ZFPlayerLoadStatePrepare) {
//        self.coverImageView.hidden = NO;
//    } else if (state == ZFPlayerLoadStatePlaythroughOK || state == ZFPlayerLoadStatePlayable) {
//        self.coverImageView.hidden = YES;
//        self.effectView.hidden = NO;
//    }
    if ((state == ZFPlayerLoadStateStalled || state == ZFPlayerLoadStatePrepare) && videoPlayer.currentPlayerManager.isPlaying) {
        [self.sliderView startAnimating];
    } else {
        [self.sliderView stopAnimating];
    }
}
改到播放状态显示隐藏
//播放状态改变
- (void)videoPlayer:(ZFPlayerController *)videoPlayer playStateChanged:(ZFPlayerPlaybackState)state{
    
    if (state == ZFPlayerLoadStatePrepare) {
        self.coverImageView.hidden = NO;
    } else if (state == ZFPlayerLoadStatePlaythroughOK || state == ZFPlayerLoadStatePlayable) {
        self.coverImageView.hidden = YES;
        self.effectView.hidden = NO;
    }
}

**Comment by qzytcl** [comment]
> 这个问题我今天研究出来了，在ZFDouYinControlView.m里
> ![WeChatc32f206185ea2099cce69b214e792513](https://user-images.githubusercontent.com/17844055/86209303-dfae6380-bba4-11ea-9698-8ce2e335f9cd.png)
> 作者是在这里判断coverimage显示隐藏的
> /// 加载状态改变
> 
> * (void)videoPlayer:(ZFPlayerController *)videoPlayer loadStateChanged:(ZFPlayerLoadState)state {
>   //    if (state == ZFPlayerLoadStatePrepare) {
>   //        self.coverImageView.hidden = NO;
>   //    } else if (state == ZFPlayerLoadStatePlaythroughOK || state == ZFPlayerLoadStatePlayable) {
>   //        self.coverImageView.hidden = YES;
>   //        self.effectView.hidden = NO;
>   //    }
>   if ((state == ZFPlayerLoadStateStalled || state == ZFPlayerLoadStatePrepare) && videoPlayer.currentPlayerManager.isPlaying) {
>   [self.sliderView startAnimating];
>   } else {
>   [self.sliderView stopAnimating];
>   }
>   }
>   改到播放状态显示隐藏
>   //播放状态改变
> * (void)videoPlayer:(ZFPlayerController *)videoPlayer playStateChanged:(ZFPlayerPlaybackState)state{
>   if (state == ZFPlayerLoadStatePrepare) {
>   self.coverImageView.hidden = NO;
>   } else if (state == ZFPlayerLoadStatePlaythroughOK || state == ZFPlayerLoadStatePlayable) {
>   self.coverImageView.hidden = YES;
>   self.effectView.hidden = NO;
>   }
>   }

这个解决方案有效。

**Comment by bluerainxty** [comment]
@PZXforXcode @qzytcl 
(void)videoPlayer:(ZFPlayerController *)videoPlayer playStateChanged:(ZFPlayerPlaybackState)state{
if (state == ZFPlayerLoadStatePrepare) {
self.coverImageView.hidden = NO;
} else if (state == ZFPlayerLoadStatePlaythroughOK || state == ZFPlayerLoadStatePlayable) {
self.coverImageView.hidden = YES;
self.effectView.hidden = NO;
}
}
ZFPlayerPlaybackState不能和ZFPlayerLoadStatePrepare比较啊

**Comment by zuoyou1314** [comment]
@PZXforXcode @qzytcl
(void)videoPlayer:(ZFPlayerController *)videoPlayer playStateChanged:(ZFPlayerPlaybackState)state{
if (state == ZFPlayerLoadStatePrepare) {
self.coverImageView.hidden = NO;
} else if (state == ZFPlayerLoadStatePlaythroughOK || state == ZFPlayerLoadStatePlayable) {
self.coverImageView.hidden = YES;
self.effectView.hidden = NO;
}
}
ZFPlayerPlaybackState不能和ZFPlayerLoadStatePrepare比较啊
按这样写完，又出现更严重的新Bug，背景图会暴露出来

**Comment by qzytcl** [comment]
> @PZXforXcode @qzytcl
> (void)videoPlayer:(ZFPlayerController *)videoPlayer playStateChanged:(ZFPlayerPlaybackState)state{
> if (state == ZFPlayerLoadStatePrepare) {
> self.coverImageView.hidden = NO;
> } else if (state == ZFPlayerLoadStatePlaythroughOK || state == ZFPlayerLoadStatePlayable) {
> self.coverImageView.hidden = YES;
> self.effectView.hidden = NO;
> }
> }
> ZFPlayerPlaybackState不能和ZFPlayerLoadStatePrepare比较啊

<img width="699" alt="image" src="https://user-images.githubusercontent.com/13794139/87896594-496eae80-ca7b-11ea-9162-8d4c6fe071ad.png">
我感觉最主要的原因是这里 蒙版 和 背景图 隐藏的问题， 我只把这里的代码屏蔽了就能解决问题。

**Comment by fangwei520** [comment]
谢谢 大兄弟




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "中文名字"<notifications@github.com&gt;; 
发送时间: 2020年7月20日(星期一) 中午11:23
收件人: "renzifeng/ZFPlayer"<ZFPlayer@noreply.github.com&gt;; 
抄送: "方子龙丶"<490093596@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [renzifeng/ZFPlayer] 抖音样式(Douyin style) 播放闪烁 (#970)



@PZXforXcode @qzytcl
 (void)videoPlayer:(ZFPlayerController *)videoPlayer playStateChanged:(ZFPlayerPlaybackState)state{
 if (state == ZFPlayerLoadStatePrepare) {
 self.coverImageView.hidden = NO;
 } else if (state == ZFPlayerLoadStatePlaythroughOK || state == ZFPlayerLoadStatePlayable) {
 self.coverImageView.hidden = YES;
 self.effectView.hidden = NO;
 }
 }
 ZFPlayerPlaybackState不能和ZFPlayerLoadStatePrepare比较啊
  
 我感觉最主要的原因是这里 蒙版 和 背景图 隐藏的问题， 我只把这里的代码屏蔽了就能解决问题。

**Comment by liubang0909** [comment]
> @PZXforXcode @qzytcl
> (void)videoPlayer:(ZFPlayerController *)videoPlayer playStateChanged:(ZFPlayerPlaybackState)state{
> if (state == ZFPlayerLoadStatePrepare) {
> self.coverImageView.hidden = NO;
> } else if (state == ZFPlayerLoadStatePlaythroughOK || state == ZFPlayerLoadStatePlayable) {
> self.coverImageView.hidden = YES;
> self.effectView.hidden = NO;
> }
> }
> ZFPlayerPlaybackState不能和ZFPlayerLoadStatePrepare比较啊

大哥找到好的解决方法了吗？

**Comment by Weang** [comment]
func videoPlayer(_ videoPlayer: ZFPlayerController, currentTime: TimeInterval, totalTime: TimeInterval) {
        coverImageView.isHidden = currentTime > 0
    }

**Comment by Weang** [comment]
func videoPlayer(_ videoPlayer: ZFPlayerController, currentTime: TimeInterval, totalTime: TimeInterval) {
        coverImageView.isHidden = currentTime > 0
}
这样似乎可以

**Comment by Andy0570** [comment]
Version 4.0.3

我遇到的问题是封面图切换到视频之间会闪烁一下黑屏，目前找到的解决方法：

```objc
ZFAVPlayerManager *playerManager = [[ZFAVPlayerManager alloc] init];
playerManager.view.backgroundColor = [UIColor clearColor];
```

希望能帮助到各位大佬。
