### ISSUE TITLE
ZFSpeedLoadingView一直显示

### ISSUE THREAD

**Issue by tstyllr** [renzifeng/ZFPlayer#971]
正常播放视频，然后把进度条拉到最开始（也就是seek到0）,ZFSpeedLoadingView会一直显示，尽管这时候视频在正常播放。

**Comment by tstyllr** [comment]
该问题100%复现

**Comment by renzifeng** [comment]
提供的控制层并没有复现啊，你是自定义控制层了吧

**Comment by tstyllr** [comment]
> 提供的控制层并没有复现啊，你是自定义控制层了吧

没有自定义控制层哦。不过我更新到最新版后就没有这个问题了。谢谢～
