### ISSUE TITLE
系统12.X旋转的时候报错

### ISSUE THREAD

**Issue by tianfangyege** [renzifeng/ZFPlayer#974]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/9334771/80565790-f230e300-8a23-11ea-8472-dcd2e3f19f96.png">

全屏的时候报错，

**Comment by tianfangyege** [comment]
经测试在Xcode11上创建的应用，在Xcode10上测试12系列版本报错的

**Comment by coderJW** [comment]
[Bugly]  Trapped uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [ZFFullViewController shouldAutorotate] is returning YES' 
(
	0   CoreFoundation                      0x00000001f527b198 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001f44539f8 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001f51853a0 <redacted> + 0
	3   UIKitCore                           0x00000002214db36c <redacted> + 920
	4   UIKitCore                           0x00000002214cb968 <redacted> + 96
	5   UIKitCore                           0x0000000221a9eb20 <redacted> + 120
	6   Â•∂ÁâõÂø´‰º†                        0x0000000101357660 -[ZFOrientationObserver normalOrientation:animated:] + 892
	7   Â•∂ÁâõÂø´‰º†                        0x00000001013587e8 -[ZFOrientationObserver enterLandscapeFullScreen:animated:] + 176
	8   Â•∂ÁâõÂø´‰º†                        0x0000000101361430 -[ZFPlayerController(ZFPlayerOrientationRotation) enterFullScreen:animated:] + 300
	9   Â•∂ÁâõÂø´‰º†                        0x0000000101374ad4 -[ZFPortraitControlView fullScreenButtonClickAction:] + 120
	10  UIKitCore                           0x0000000221a6a300 <redacted> + 96
	11  UIKitCore                           0x0000000221513424 <redacted> + 80
	12  UIKitCore                           0x0000000221513744 <redacted> + 440
	13  UIKitCore                           0x00000002215127b0 <redacted> + 568
	14  UIKitCore                           0x000000022168c2d0 <redacted> + 7900
	15  CoreFoundation                      0x00000001f520c4fc <redacted> + 32
	16  CoreFoundation                      0x00000001f5207224 <redacted> + 412
	17  CoreFoundation                      0x00000001f52077a0 <redacted> + 1228
	18  CoreFoundation                      0x00000001f5206fb4 CFRunLoopRunSpecific + 436
	19  GraphicsServices                    0x00000001f740879c GSEventRunModal + 104
	20  UIKitCore                           0x0000000221a68c38 UIApplicationMain + 212
	21  Â•∂ÁâõÂø´‰º†                        0x0000000100e06f9c main + 76
	22  libdyld.dylib                       0x00000001f4cca8e0 <redacted> + 4
)

**Comment by coderJW** [comment]
真机,iOS12.4.5系统,全屏播放报错

**Comment by coderJW** [comment]
@renzifeng

**Comment by GSmoke** [comment]
Demo解决方案,全局搜索allowOrentitaionRotation,详细如下
AppDeletage
/// 在这里写支持的旋转方向，为了防止横屏方向，应用启动时候界面变为横屏模式
- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
    // 可以这么写
    if (self.allowOrentitaionRotation) {
        return UIInterfaceOrientationMaskAllButUpsideDown;
    }
    return UIInterfaceOrientationMaskPortrait;
}`
播放界面,
`    kAppDel.allowOrentitaionRotation = YES;
    self.view.backgroundColor = [UIColor blackColor];
    @weakify(self)
    self.controlView.backBtnClickCallback = ^{
        @strongify(self)
        [self.player enterFullScreen:NO animated:NO];
        [self.player stop];
        kAppDel.allowOrentitaionRotation = NO;
        [self.navigationController popViewControllerAnimated:NO];

    };`

**Comment by renzifeng** [comment]
这问题很明显啊，工程没有支持横屏啊
