### ISSUE TITLE
加上TabBar,push全屏播放,pop后的界面导航条高度没有恢复

### ISSUE THREAD

**Issue by GSmoke** [renzifeng/ZFPlayer#976]

**Comment by opleonnn** [comment]
我也遇到了相同的问题，有什么解决方案么

**Comment by WIndFate** [comment]
我临时这样解决了
<img width="1304" alt="スクリーンショット 2020-05-27 11 38 27" src="https://user-images.githubusercontent.com/14509638/82971886-c008a600-a00e-11ea-8e4d-eb02cf5c32fb.png">

**Comment by opleonnn** [comment]
@WIndFate 我试了没用啊，能交流下么。qq 565895513

**Comment by WIndFate** [comment]
> @WIndFate 我试了没用啊，能交流下么。qq 565895513

你更新他最新的版本然后再加我这段，我这个是全屏切后台回来显示错乱的bug

**Comment by DLsunset** [comment]
我能想到的办法就是，自定义导航栏。

**Comment by DLsunset** [comment]
> 我能想到的办法就是，自定义导航栏。

但是弊病是，当进入到其他使用系统导航栏的页面，依然会有上移的问题

**Comment by DLsunset** [comment]
目前研究出的最终方案是。
第一步，自定义导航栏。（可解决当前控制器的导航栏上移的问题，但其他使用系统导航栏的控制器依然会上移）
第二部， 在当前控制器下加入下面代码

- (BOOL)prefersStatusBarHidden {
    UIInterfaceOrientation oritentation = [[UIApplication sharedApplication] statusBarOrientation];
    return UIInterfaceOrientationIsLandscape(oritentation);
}

这个可以解决其他使用系统导航栏的控制器中导航栏上移的问题。但是在从全屏返回时，状态栏并不会重新出现，不清楚是什么原因，按说已经返回了No，状态栏应该出现才对。

第三步， 这一步使用了QMUIKit中的一个方法。

player.orientationDidChanged = ^(ZFPlayerController * _Nonnull player, BOOL isFullScreen) {
        self.qmui_prefersStatusBarHiddenBlock = ^BOOL{
            return isFullScreen;
        };
    };

这个是解决从全屏返回后状态栏消失的问题。QMUIKit的那个block是也是用于改变状态栏的隐藏和显示的。
