### ISSUE TITLE
playerPlayStateChanged 播放中状态会连续调用两次

### ISSUE THREAD

**Issue by huangxianyu** [renzifeng/ZFPlayer#980]
播放状态的回调, 播放时调用playTheIndex:方法, 然后ZFPlayerPlayStatePlaying状态会连续调两次, demo也是连续调两次, 有办法解决吗?
[self.player setPlayerPlayStateChanged:^(id<ZFPlayerMediaPlayback>  _Nonnull asset, ZFPlayerPlaybackState playState) {
        
}];

**Comment by renzifeng** [comment]
只要调用playerManager play方法就会修改为ZFPlayerPlayStatePlaying，你断点调试一下，是哪里多次调用play方法了，或者你贴视频链接出来

**Comment by cnzlh** [comment]
![image](https://user-images.githubusercontent.com/5771860/93217203-4c480000-f79b-11ea-960c-b9372983ee2c.png)
![image](https://user-images.githubusercontent.com/5771860/93217241-59fd8580-f79b-11ea-9d10-0d6bf48798e1.png)
确定会有两次状态回调
