### ISSUE TITLE
大哥，你要做IOS13 适配不？比如 SceneDelegate 的 window.

### ISSUE THREAD

**Issue by DreamHuman** [renzifeng/ZFPlayer#986]
+ (UIViewController*)zf_currentViewController; {
    UIWindow *window = [[UIApplication sharedApplication].delegate window];
    UIViewController *topViewController = [window rootViewController];
    while (true) {
        if (topViewController.presentedViewController) {
            topViewController = topViewController.presentedViewController;
        } else if ([topViewController isKindOfClass:[UINavigationController class]] && [(UINavigationController*)topViewController topViewController]) {
            topViewController = [(UINavigationController *)topViewController topViewController];
        } else if ([topViewController isKindOfClass:[UITabBarController class]]) {
            UITabBarController *tab = (UITabBarController *)topViewController;
            topViewController = tab.selectedViewController;
        } else {
            break;
        }
    }
    return topViewController;
}

现在 delegate 里面 没有window (ios 13,强改AppDelegate + UIWindowSceneDelegate 当我没说.)

**Comment by DreamHuman** [comment]
我本地添加下面改动：
+ (UIViewController*)zf_currentViewController; {
    __block UIWindow *window ;
    if (@available(iOS 13, *)) {
        [[UIApplication sharedApplication].connectedScenes enumerateObjectsUsingBlock:^(UIScene * _Nonnull scene, BOOL * _Nonnull scenesStop) {
            if ([scene isKindOfClass: [UIWindowScene class]]) {
                UIWindowScene * windowScene = scene;
                [windowScene.windows enumerateObjectsUsingBlock:^(UIWindow * _Nonnull windowTemp, NSUInteger idx, BOOL * _Nonnull windowStop) {
                    if ([windowTemp isKeyWindow]) {
                        window = windowTemp ;
                        *windowStop = true;
                        *scenesStop = true;
                    }
                }];
            }
        }];
    }else {
        window = [[UIApplication sharedApplication].delegate window];
    }

    UIViewController *topViewController = [window rootViewController];
    while (true) {
        if (topViewController.presentedViewController) {
            topViewController = topViewController.presentedViewController;
        } else if ([topViewController isKindOfClass:[UINavigationController class]] && [(UINavigationController*)topViewController topViewController]) {
            topViewController = [(UINavigationController *)topViewController topViewController];
        } else if ([topViewController isKindOfClass:[UITabBarController class]]) {
            UITabBarController *tab = (UITabBarController *)topViewController;
            topViewController = tab.selectedViewController;
        } else {
            break;
        }
    }
    return topViewController;
}
你要不要添加 进去？

**Comment by renzifeng** [comment]
好的
