### ISSUE TITLE
使用ijkplayer时候第一次加载很慢线程问题

### ISSUE THREAD

**Issue by wangxiusen** [renzifeng/ZFPlayer#987]
xcode提示Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]

**Comment by demoker** [comment]
我这边也存在这个问题

**Comment by Rookie920** [comment]
请问这个解决了吗 @wangxiusen @demoker

**Comment by HouHangLei** [comment]
不连接Xcode时候应该是正常的

**Comment by GeekLee609** [comment]
修复了该方法的调用在主线程，
Duplicate of #998
