### ISSUE TITLE
抖音样式调用collectionView的reloadData后视频只有声音没有画面

### ISSUE THREAD

**Issue by ChengQuanYe** [renzifeng/ZFPlayer#988]
抖音样式调用collectionView的reloadData后只有声音没有画面，再刷新一次又有了，一直往复，看层级应该是刷新一次后播放器控制层不见了，再刷新一次又出来了，collectionView的抖音样式有问题，用tableView的就没问题了

**Comment by Jvaeyhcd** [comment]
遇到相同的问题，视频有时还会卡顿。

**Comment by xiangchangming** [comment]
我是在tableview上局部刷新cell也会遇到这个问题，求解决方法

**Comment by MakeBetterMe** [comment]
读了一下源码，你在reload方法后面，调用下这个方法

self.player.addPlayerViewToCell()

**Comment by zuifeng1776** [comment]
兄弟们，解决了吗？

**Comment by freyzou** [comment]
遇到同样的问题，debug发现ZFPlayerView依然在它该在的地方， frame全对, 但就是不显示，奇怪
