### ISSUE TITLE
KSYMediaPlayer UIWebview

### ISSUE THREAD

**Issue by Lee0820** [renzifeng/ZFPlayer#989]
这个库应该是包含UIWebview，看https://github.com/ksvc/KSYMediaPlayer_iOS已经移除了，不知道作者依赖的这个何时更新下

**Comment by Rookie920** [comment]
KSYMediaPlayer 金山这边已经将 UIWebview 移除，请问作者这边可以适配下吗？谢谢

**Comment by haofanning** [comment]
麻烦作者更新下，目前上线appstore无法通过审核

**Comment by xiaosiZhang** [comment]
作者这边什么时候更新下用到的KSYMediaPlayer库，麻烦早点更新

**Comment by MasterYong** [comment]
作者麻烦更新下，红包大大的
