### ISSUE TITLE
pod 'ZFPlayer/KSYMediaPlayer' 编译错误

### ISSUE THREAD

**Issue by huangjianwengit** [renzifeng/ZFPlayer#993]
pod 'ZFPlayer/KSYMediaPlayer' 编译报错：
截图  https://i.loli.net/2020/06/04/zKWiNuPeHFhMptR.jpg

**Comment by LifeForLove** [comment]
金山云的sdk几年前就不维护了，我之前使用金山云的sdk，与ijk的库冲突了，找他们要一个动态库都没有。

**Comment by huangjianwengit** [comment]
好的，感谢！

**Comment by GeekLee609** [comment]
pod 'ZFPlayer/KSYMediaPlayer' 和pod 'ZFPlayer/ijkplayer' 只引入一个就好
