### ISSUE TITLE
问题：从网络获取数据后无法自动播放

### ISSUE THREAD

**Issue by dong136279559** [renzifeng/ZFPlayer#995]
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        
        [self requestData];
        self.player.assetURLs = self.urls;
        [self.collectionView reloadData];
    });

抖音列表播放demo中，模拟从网络中获取数据，其他方法不变，调用reloadData 后，无法自动播放。

请问是我还需要调用其他方法吗？

建议：能否将demo中的数据获取模拟从网络获取，可能用起来方便一些。谢谢。

**Comment by dong136279559** [comment]
作者能给回复一下吗？网络数据第一个一直播放不了
请问这是框架的问题，还是调用方法的问题啊

**Comment by VolleyZ** [comment]
一样情况。同问

**Comment by VolleyZ** [comment]
必须等reloadData()完成后再播放才行。
`[UIView animateWithDuration:0 animations:^{
        [self.collectionView reloadData];
    } completion:^(BOOL finished) {
        [self playTheIndex:0];
    }];`
或者
`dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self playTheIndex:0];
    });`

**Comment by zhengxuehai** [comment]
我也遇到这个问题了，你解决了吗

**Comment by zhengxuehai** [comment]
> 作者能给回复一下吗？网络数据第一个一直播放不了
> 请问这是框架的问题，还是调用方法的问题啊

我也遇到这个问题了，请问你解决了吗

**Comment by xuanInitial** [comment]
请求完刷新的时候这样搞 

dispatch_async(dispatch_get_main_queue(), ^{
                [self.tableView reloadData];
                /// 找到可以播放的视频并播放
                [self.player zf_filterShouldPlayCellWhileScrolled:^(NSIndexPath *indexPath) {
                    @zf_strongify(self)
                    [self playTheVideoAtIndexPath:indexPath];
                }];

           });
