### ISSUE TITLE
IJK自一次运行卡线程

### ISSUE THREAD

**Issue by Rookie920** [renzifeng/ZFPlayer#998]
控制台提示信息
Main Thread Checker: UI API called on a background thread: -[UIView layer]
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]

**Comment by Rookie920** [comment]
详细信息：

Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 456, TID: 37960, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   TestPlayer                     0x00000001034ad8ec -[IJKSDLGLView isApplicationActive] + 100
5   TestPlayer                     0x00000001034ade84 -[IJKSDLGLView display:] + 64
6   libdispatch.dylib                   0x0000000108afa338 _dispatch_call_block_and_release + 24
7   libdispatch.dylib                   0x0000000108afb730 _dispatch_client_callout + 16
8   libdispatch.dylib                   0x0000000108b0cec8 _dispatch_root_queue_drain + 716
9   libdispatch.dylib                   0x0000000108b0d698 _dispatch_worker_thread2 + 152
10  libsystem_pthread.dylib             0x00000001aa5efb38 _pthread_wqthread + 212
11  libsystem_pthread.dylib             0x00000001aa5f2740 start_wqthread + 8
2020-06-15 11:39:55.979930+0800 TestPlayer[456:37960] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 456, TID: 37960, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   TestPlayer                     0x00000001034ad8ec -[IJKSDLGLView isApplicationActive] + 100
5   TestPlayer                     0x00000001034ade84 -[IJKSDLGLView display:] + 64
6   libdispatch.dylib                   0x0000000108afa338 _dispatch_call_block_and_release + 24
7   libdispatch.dylib                   0x0000000108afb730 _dispatch_client_callout + 16
8   libdispatch.dylib                   0x0000000108b0cec8 _dispatch_root_queue_drain + 716
9   libdispatch.dylib                   0x0000000108b0d698 _dispatch_worker_thread2 + 152
10  libsystem_pthread.dylib             0x00000001aa5efb38 _pthread_wqthread + 212
11  libsystem_pthread.dylib             0x00000001aa5f2740 start_wqthread + 8
2020-06-15 11:40:07.843329+0800 TestPlayer[456:37960] IJKSDLGLView: setupDisplay not ready

**Comment by GeekLee609** [comment]
已经修复了，强制主线程执行
